import { defineElementRule } from "../../../ruleRuntime/formElement/ruleFactory"
import type { PropertyRule } from "@nkdk/runtime/rule-kit"
import { ElementRule } from "../../../ruleRuntime/formElement/types"
import { booleanRule } from "../../../commonObjects/boolean/types"
import {
  dynamicListTableProperties,
  isDirectDynamicListTable,
} from "./dynamicListProperties"
import { settingsComposerTableKinds } from "../../settingsComposer/dataPathModel"
export type { ElementRule, PropertyRule }

export const TableRules = {
  itemType: "Table",
  enterpriseField: "FormTable",
  enterpriseFieldType: "None",
  xmlOrder: [
    "representation",
    "visible",
    "userVisible",
    "titleLocation",
    "titleHeight",
    "commandBarLocation",
    "autofill",
    "enabled",
    "readOnly",
    "skipOnInput",
    "defaultItem",
    "changeRowSet",
    "changeRowOrder",
    "width",
    "autoMaxWidth",
    "maxWidth",
    "height",
    "autoMaxHeight",
    "maxHeight",
    "heightInTableRows",
    "heightControlVariant",
    "autoMaxHeightInTableRows",
    "maxHeightInTableRows",
    "choiceMode",
    "multipleChoice",
    "rowInputMode",
    "selectionMode",
    "rowSelectionMode",
    "header",
    "headerHeight",
    "footer",
    "footerHeight",
    "horizontalScrollBar",
    "verticalScrollBar",
    "horizontalLines",
    "verticalLines",
    "useAlternationRowColor",
    "autoInsertNewRow",
    "autoAddIncomplete",
    "autoMarkIncomplete",
    "searchOnInput",
    "initialListView",
    "initialTreeView",
    "output",
    "horizontalStretch",
    "verticalStretch",
    "enableStartDrag",
    "enableDrag",
    "fileDragMode",
    "dataPath",
    "rowPictureDataPath",
    "rowsPicture",
    "textColor",
    "backColor",
    "borderColor",
    "font",
    "title",
    "titleTextColor",
    "titleFont",
    "shortcut",
    "commandSet",
    "toolTip",
    "toolTipRepresentation",
    "searchStringLocation",
    "viewStatusLocation",
    "searchControlLocation",
    "horizontalAlignInGroup",
    "verticalAlignInGroup",
    "refreshRequest",
    "currentRowUse",
    "viewMode",
    "settingsNamedItemDetailedRepresentation",
    "behaviorOnHorizontalCompression",
    "onMainServerUnavalableBehavior",
    "autoRefresh",
    "autoRefreshPeriod",
    "period",
    "choiceFoldersAndItems",
    "restoreCurrentRow",
    "topLevelParent",
    "showRoot",
    "allowRootChoice",
    "updateOnDataChange",
    "userSettingsGroup",
    "allowGettingCurrentRowURL",
    "rowFilter",
    "contextMenu",
    "autoCommandBar",
    "extendedTooltip",
    "searchStringRepresentation",
    "viewStatusRepresentation",
    "searchControl",
    "events",
    "childItems",
    "name",
    "displayImportance",
  ],
  properties: {
    name: {
      type: "string",
      xml: "_name",
      required: true,
    },
    autoAddIncomplete: { yaml: "АвтоВводНезаполненного", type: "boolean", noImplicitValueYAML: true },
    autoCommandBar: { yaml: "КоманднаяПанель", type: "TableAutoCommandBar", toEnterprise: false },
    autofill: { yaml: "АвтозаполнениеКолонок", type: "boolean", implicitValueYAML: false },
    viewMode: {
      yaml: "РежимОтображения",
      type: "SystemEnumeration",
      typeSE: "DataCompositionSettingsViewMode",
      noImplicitValueYAML: true,
    },
    settingsNamedItemDetailedRepresentation: {
      yaml: "ПодробноеОтображениеИменованныхЭлементовНастройки",
      xml: "SettingsNamedItemDetailedRepresentation",
      type: "boolean",
      noImplicitValueYAML: true,
    },
    autoInsertNewRow: {
      yaml: "АвтоВводНовойСтроки",
      type: "boolean",
      implicitValueYAML: true,
      implicitValueXML: false,
    },
    autoMarkIncomplete: { yaml: "АвтоОтметкаНезаполненного", type: "boolean", noImplicitValueYAML: true },
    autoMaxHeight: { yaml: "АвтоМаксимальнаяВысота", type: "boolean", implicitValueYAML: true },
    autoMaxHeightInTableRows: {
      yaml: "АвтоМаксимальнаяВысотаВСтрокахТаблицы",
      xml: "AutoMaxRowsCount",
      type: "boolean",
      implicitValueYAML: true,
    },
    autoMaxWidth: { yaml: "АвтоМаксимальнаяШирина", type: "boolean", implicitValueYAML: true },
    backColor: {
      yaml: "ЦветФона",
      type: "Color",
      metadataTarget: { kind: "object", roots: ["StyleItem"], filters: [{ kind: "styleItemType", values: ["Color"] }] },
    },
    behaviorOnHorizontalCompression: {
      yaml: "ПоведениеПриСжатииПоГоризонтали",
      type: "SystemEnumeration",
      typeSE: "TableBehaviorOnHorizontalCompression",
      implicitValueYAML: "Auto",
    },
    borderColor: {
      yaml: "ЦветРамки",
      type: "Color",
      metadataTarget: { kind: "object", roots: ["StyleItem"], filters: [{ kind: "styleItemType", values: ["Color"] }] },
    },
    changeRowOrder: { yaml: "ИзменятьПорядокСтрок", type: "boolean", implicitValueYAML: true },
    changeRowSet: { yaml: "ИзменятьСоставСтрок", type: "boolean", implicitValueYAML: true },
    childItems: { yaml: "Элементы", type: "TableChildItems", defaultValue: [] },
    choiceMode: { yaml: "РежимВыбора", type: "boolean", implicitValueYAML: false },
    commandBarLocation: {
      yaml: "ПоложениеКоманднойПанели",
      type: "SystemEnumeration",
      typeSE: "FormItemCommandBarLabelLocation",
      implicitValueYAML: "Auto",
    },
    commandSet: { yaml: "Команда", type: "CommandSet", toEnterprise: false },
    contextMenu: { yaml: "КонтекстноеМеню", type: "ContextMenu", toEnterprise: false },
    currentRowUse: {
      yaml: "ИспользованиеТекущейСтроки",
      type: "SystemEnumeration",
      typeSE: "TableCurrentRowUse",
      implicitValueYAML: "Auto",
    },
    dataPath: {
      yaml: "ПутьКДанным",
      type: "DataPath",
      defaultType: "ValueTable",
      allowedKinds: [
        "DynamicList", "ValueTable", "ValueTree", "ValueListType", "GanttChart",
        "DocumentTabularSection.*", "CatalogTabularSection.*", "DataProcessorTabularSection.*",
        "ReportTabularSection.*", "ExchangePlanTabularSection.*", "BusinessProcessTabularSection.*",
        "TaskTabularSection.*", "ChartOfAccountsTabularSection.*",
        "ChartOfCharacteristicTypesTabularSection.*", "ChartOfCalculationTypesTabularSection.*",
        "ChartOfAccountsExtDimensionTypes.*", "InformationRegisterRecordSet.*",
        "AccumulationRegisterRecordSet.*", "AccountingRegisterRecordSet.*",
        "CalculationRegisterRecordSet.*",
        ...settingsComposerTableKinds,
      ],
      allowComposite: false,
    },
    defaultItem: { yaml: "АктивизироватьПоУмолчанию", type: "boolean", implicitValueYAML: false },
    displayImportance: {
      yaml: "ВажностьПриОтображении",
      xml: "_DisplayImportance",
      type: "SystemEnumeration",
      typeSE: "DisplayImportance",
      implicitValueYAML: "Auto",
    },
    enabled: { yaml: "Доступность", type: "boolean", implicitValueYAML: true },
    enableDrag: booleanRule({
      yaml: "РазрешитьПеретаскивание",
      implicitValueYAML: true,
      implicitValueXML: false,
    }),
    enableStartDrag: booleanRule({
      yaml: "РазрешитьНачалоПеретаскивания",
      implicitValueYAML: true,
      implicitValueXML: false,
    }),
    extendedTooltip: { yaml: "РасширеннаяПодсказка", type: "ExtendedTooltip", toEnterprise: false },
    fileDragMode: {
      yaml: "СпособПеретаскиванияФайлов",
      type: "SystemEnumeration",
      typeSE: "FileDragMode",
      implicitValueYAML: "AsFileRef",
    },
    font: {
      yaml: "Шрифт",
      type: "Font",
      metadataTarget: { kind: "object", roots: ["StyleItem"], filters: [{ kind: "styleItemType", values: ["Font"] }] },
    },
    footer: { yaml: "Подвал", type: "boolean", implicitValueYAML: false },
    footerHeight: { yaml: "ВысотаПодвала", type: "number", implicitValueYAML: 1 },
    header: { yaml: "Шапка", type: "boolean", implicitValueYAML: true },
    headerHeight: { yaml: "ВысотаШапки", type: "number", implicitValueYAML: 1 },
    height: { yaml: "Высота", type: "number", implicitValueYAML: 0 },
    heightControlVariant: {
      yaml: "ВариантУправленияВысотой",
      type: "SystemEnumeration",
      typeSE: "TableHeightControlVariant",
      implicitValueYAML: "Auto",
    },
    heightInTableRows: { yaml: "ВысотаВСтрокахТаблицы", type: "number", implicitValueYAML: 0 },
    horizontalAlignInGroup: {
      yaml: "ГоризонтальноеПоложениеВГруппе",
      xml: "GroupHorizontalAlign",
      type: "SystemEnumeration",
      typeSE: "ItemHorizontalLocation",
      implicitValueYAML: "Auto",
    },
    horizontalLines: { yaml: "ГоризонтальныеЛинии", type: "boolean", implicitValueYAML: true },
    horizontalScrollBar: {
      yaml: "ГоризонтальнаяПолосаПрокрутки",
      type: "SystemEnumeration",
      typeSE: "ScrollBarUse",
      implicitValueYAML: "AutoUse",
    },
    horizontalStretch: { yaml: "РастягиватьПоГоризонтали", type: "boolean", implicitValueYAML: true },
    initialListView: {
      yaml: "НачальноеОтображениеСписка",
      type: "SystemEnumeration",
      typeSE: "InitialListView",
      implicitValueYAML: "Auto",
    },
    initialTreeView: {
      yaml: "НачальноеОтображениеДерева",
      type: "SystemEnumeration",
      typeSE: "InitialTreeView",
      implicitValueYAML: "NoExpand",
    },
    // markIncomplete: { yaml: "ОтметкаНезаполненного", type: "boolean" },
    maxHeight: { yaml: "МаксимальнаяВысота", type: "number", implicitValueYAML: 0 },
    maxHeightInTableRows: {
      yaml: "МаксимальнаяВысотаВСтрокахТаблицы",
      type: "number",
      xml: "MaxRowsCount",
      implicitValueYAML: 0,
    },
    maxWidth: { yaml: "МаксимальнаяШирина", type: "number", implicitValueYAML: 0 },
    multipleChoice: { yaml: "МножественныйВыбор", type: "boolean", implicitValueYAML: false },
    onMainServerUnavalableBehavior: {
      yaml: "ПоведениеПриНедоступностиОсновногоСервера",
      type: "SystemEnumeration",
      typeSE: "OnMainServerUnavalableBehavior",
      implicitValueYAML: "Auto",
    },
    output: {
      yaml: "Вывод",
      type: "SystemEnumeration",
      typeSE: "UseOutput",
      implicitValueYAML: "Auto",
    },
    readOnly: { yaml: "ТолькоПросмотр", type: "boolean", implicitValueYAML: false },
    refreshRequest: {
      yaml: "ЗапросОбновления",
      type: "SystemEnumeration",
      typeSE: "RefreshRequestMethod",
      implicitValueYAML: "None",
    },
    representation: {
      yaml: "Отображение",
      type: "SystemEnumeration",
      typeSE: "TableRepresentation",
      noImplicitValueYAML: true,
    },
    rowInputMode: {
      yaml: "РежимВводаСтрок",
      type: "SystemEnumeration",
      typeSE: "TableRowInputMode",
      implicitValueYAML: "EndOfList",
    },
    rowPictureDataPath: {
      yaml: "ПутьКДаннымКартинкиСтроки",
      type: "DataPath",
      defaultType: "Picture",
    },
    rowSelectionMode: {
      yaml: "РежимВыделенияСтроки",
      type: "SystemEnumeration",
      typeSE: "TableRowSelectionMode",
      implicitValueYAML: "Cell",
    },
    rowsPicture: {
      yaml: "КартинкаСтрок",
      type: "Picture",
      metadataTarget: { kind: "object", roots: ["CommonPicture"] },
    },
    searchControl: {
      yaml: "УправлениеПоиском",
      type: "SingleSearchControlAddition",
      xml: "SearchControlAddition",
      toEnterprise: false,
    },
    searchControlLocation: {
      yaml: "ПоложениеУправленияПоиском",
      type: "SystemEnumeration",
      typeSE: "SearchControlLocation",
      implicitValueYAML: "Auto",
    },
    searchOnInput: {
      yaml: "ПоискПриВводе",
      type: "SystemEnumeration",
      typeSE: "SearchInTableOnInput",
      implicitValueYAML: "Auto",
    },
    searchStringLocation: {
      yaml: "ПоложениеСтрокиПоиска",
      type: "SystemEnumeration",
      typeSE: "SearchStringLocation",
      implicitValueYAML: "Auto",
    },
    searchStringRepresentation: {
      yaml: "ОтображениеСтрокиПоиска",
      type: "SingleSearchStringAddition",
      toEnterprise: false,
      xml: "SearchStringAddition",
    },
    selectionMode: {
      yaml: "РежимВыделения",
      type: "SystemEnumeration",
      typeSE: "TableSelectionMode",
      implicitValueYAML: "MultiRow",
    },
    shortcut: { yaml: "СочетаниеКлавиш", type: "string", toEnterprise: false },
    skipOnInput: { yaml: "ПропускатьПриВводе", type: "boolean", noImplicitValueYAML: true },
    textColor: {
      yaml: "ЦветТекста",
      type: "Color",
      metadataTarget: { kind: "object", roots: ["StyleItem"], filters: [{ kind: "styleItemType", values: ["Color"] }] },
    },
    title: {
      yaml: "Заголовок",
      type: "I8nText",
    },
    titleFont: {
      yaml: "ШрифтЗаголовка",
      type: "Font",
      metadataTarget: { kind: "object", roots: ["StyleItem"], filters: [{ kind: "styleItemType", values: ["Font"] }] },
    },
    titleHeight: { yaml: "ВысотаЗаголовка", type: "number", implicitValueYAML: 0 },
    titleLocation: {
      yaml: "ПоложениеЗаголовка",
      type: "SystemEnumeration",
      typeSE: "FormItemTitleLocation",
      implicitValueYAML: "None",
    },
    titleTextColor: {
      yaml: "ЦветТекстаЗаголовка",
      type: "Color",
      metadataTarget: { kind: "object", roots: ["StyleItem"], filters: [{ kind: "styleItemType", values: ["Color"] }] },
    },
    toolTip: { yaml: "Подсказка", type: "I8nText" },
    toolTipRepresentation: {
      yaml: "ОтображениеПодсказки",
      type: "SystemEnumeration",
      typeSE: "ToolTipRepresentation",
      implicitValueYAML: "Auto",
    },
    useAlternationRowColor: { yaml: "ЧередованиеЦветовСтрок", type: "boolean", implicitValueYAML: false },
    userVisible: {
      yaml: "Использование",
      type: "UserVisible",
      toEnterprise: false,
    },
    verticalAlignInGroup: {
      yaml: "ВертикальноеПоложениеВГруппе",
      xml: "GroupVerticalAlign",
      type: "SystemEnumeration",
      typeSE: "ItemVerticalAlign",
      implicitValueYAML: "Auto",
    },
    verticalLines: { yaml: "ВертикальныеЛинии", type: "boolean", implicitValueYAML: true },
    verticalScrollBar: {
      yaml: "ВертикальнаяПолосаПрокрутки",
      type: "SystemEnumeration",
      typeSE: "ScrollBarUse",
      implicitValueYAML: "AutoUse",
    },
    verticalStretch: { yaml: "РастягиватьПоВертикали", type: "boolean", implicitValueYAML: true },
    viewStatusLocation: {
      yaml: "ПоложениеСостоянияПросмотра",
      type: "SystemEnumeration",
      typeSE: "ViewStatusLocation",
      implicitValueYAML: "Auto",
    },
    viewStatusRepresentation: {
      yaml: "ОтображениеСостоянияПросмотра",
      type: "SingleViewStatusAddition",
      xml: "ViewStatusAddition",
      toEnterprise: false,
    },
    visible: { yaml: "Видимость", type: "boolean", implicitValueYAML: true },
    width: { yaml: "Ширина", type: "number", implicitValueYAML: 0 },
    ...dynamicListTableProperties,
    // additionalCreateParameters: { yaml: "ДополнительныеПараметрыСоздания", type: "boolean" },
    userSettingsGroup: { yaml: "ГруппаПользовательскихНастроек", xml: "UserSettingsGroup", type: "string" },
    // XML-only service fields are computed from the resolved table source.
    period: {
      yaml: "Период",
      type: "boolean",
      fromXML: false,
      toYAML: false,
      fromYAML: false,
      evaluateWhenYAMLMissing: true,
      toXML: isDirectDynamicListTable,
      defaultValueXMLRaw: {
        "v8:variant": { "#text": "Custom", "_xsi:type": "v8:StandardPeriodVariant" },
        "v8:startDate": "0001-01-01T00:00:00",
        "v8:endDate": "0001-01-01T00:00:00",
      },
    },
    topLevelParent: {
      yaml: "РодительВерхнегоУровня",
      type: "boolean",
      fromXML: false,
      toYAML: false,
      fromYAML: false,
      evaluateWhenYAMLMissing: true,
      toXML: isDirectDynamicListTable,
      defaultValueXMLRaw: { "_xsi:nil": "true" },
    },
    rowFilter: {
      yaml: "ОтборСтрок",
      type: "boolean",
      fromXML: false,
      toYAML: false,
      fromYAML: false,
      preserveUnknownReferenceXML: false,
    },
    events: {
      type: "Events",
      yaml: "События",
      toEnterprise: false,
      items: {
        selection: "Выбор",
        valueChoice: "ВыборЗначения",
        dragStart: "НачалоПеретаскивания",
        choiceProcessing: "ОбработкаВыбора",
        newWriteProcessing: "ОбработкаЗаписиНового",
        refreshRequestProcessing: "ОбработкаЗапросаОбновления",
        dragEnd: "ОкончаниеПеретаскивания",
        onLoadUserSettingsAtServer: "ПриЗагрузкеПользовательскихНастроекНаСервере",
        uRLListGetProcessing: "ОбработкаПолученияСпискаНавигационныхСсылок",
        uRLGetProcessing: "ОбработкаПолученияНавигационнойСсылки",
        onGetDataAtServer: "ПриПолученииДанныхНаСервере",
        onSaveUserSettingsAtServer: "ПриСохраненииПользовательскихНастроекНаСервере",
        onUpdateUserSettingSetAtServer: "ПриОбновленииСоставаПользовательскихНастроекНаСервере",
        beforeLoadUserSettingsAtServer: "ПередЗагрузкойПользовательскихНастроекНаСервере",
        beforeAddRow: "ПередНачаломДобавления",
        beforeRowChange: "ПередНачаломИзменения",
        beforeEditEnd: "ПередОкончаниемРедактирования",
        beforeExpand: "ПередРазворачиванием",
        beforeCollapse: "ПередСворачиванием",
        beforeDeleteRow: "ПередУдалением",
        drag: "Перетаскивание",
        afterDeleteRow: "ПослеУдаления",
        onActivateField: "ПриАктивизацииПоля",
        onActivateRow: "ПриАктивизацииСтроки",
        onActivateCell: "ПриАктивизацииЯчейки",
        onChange: "ПриИзменении",
        onStartEdit: "ПриНачалеРедактирования",
        onEditEnd: "ПриОкончанииРедактирования",
        onCurrentParentChange: "ПриСменеТекущегоРодителя",
        dragCheck: "ПроверкаПеретаскивания",
      },
    },
  } as const,
} as const satisfies ElementRule

export const metadataRuleLayer000 = defineElementRule("Table", TableRules)
