import { registerExport } from "~/lib/xml/export/exporterFactory"
import { FormElementType } from "../types"

export const exportMetadataDocumentToXML = (data: MetadataDocument | undefined): MetadataDocumentXML | undefined => {
  if (!data) return undefined

  return {
    ActionsWritingOnPost: data.actionsWritingOnPost,
    AdditionalIndexes: data.additionalIndexes,
    Attributes: data.attributes,
    Autonumbering: data.autonumbering,
    AuxiliaryChoiceForm: data.auxiliaryChoiceForm,
    AuxiliaryListForm: data.auxiliaryListForm,
    AuxiliaryObjectForm: data.auxiliaryObjectForm,
    BasedOn: data.basedOn,
    Characteristics: data.characteristics,
    CheckUnique: data.checkUnique,
    ChoiceDataGetModeOnInputByString: data.choiceDataGetModeOnInputByString,
    ChoiceHistoryOnInput: data.choiceHistoryOnInput,
    Commands: data.commands,
    Comment: data.comment,
    CreateOnInput: data.createOnInput,
    DataHistory: data.dataHistory,
    DataLockControlMode: data.dataLockControlMode,
    DataLockFields: data.dataLockFields,
    DefaultChoiceForm: data.defaultChoiceForm,
    DefaultListForm: data.defaultListForm,
    DefaultObjectForm: data.defaultObjectForm,
    ExecuteAfterWriteDataHistoryVersionProcessing: data.executeAfterWriteDataHistoryVersionProcessing,
    Explanation: data.explanation,
    ExtendedConfigurationObject: data.extendedConfigurationObject,
    ExtendedListPresentation: data.extendedListPresentation,
    ExtendedObjectPresentation: data.extendedObjectPresentation,
    Forms: data.forms,
    FullTextSearch: data.fullTextSearch,
    FullTextSearchOnInputByString: data.fullTextSearchOnInputByString,
    Help: data.help,
    IncludeHelpInContents: data.includeHelpInContents,
    InputByString: data.inputByString,
    ListPresentation: data.listPresentation,
    ManagerModule: data.managerModule,
    NumberAllowedLength: data.numberAllowedLength,
    NumberLength: data.numberLength,
    NumberPeriodicity: data.numberPeriodicity,
    NumberType: data.numberType,
    Numerator: data.numerator,
    ObjectBelonging: data.objectBelonging,
    ObjectModule: data.objectModule,
    ObjectPresentation: data.objectPresentation,
    Posting: data.posting,
    PrivilegedPostingMode: data.privilegedPostingMode,
    PrivilegedUnpostingMode: data.privilegedUnpostingMode,
    RealTimePosting: data.realTimePosting,
    RegisterRecords: data.registerRecords,
    RegisterRecordsDeletion: data.registerRecordsDeletion,
    SearchStringModeOnInputByString: data.searchStringModeOnInputByString,
    SequenceFilling: data.sequenceFilling,
    StandardAttributes: data.standardAttributes,
    Synonym: data.synonym,
    TabularSections: data.tabularSections,
    Templates: data.templates,
    UpdateDataHistoryImmediatelyAfterWrite: data.updateDataHistoryImmediatelyAfterWrite,
    UseStandardCommands: data.useStandardCommands,
  }
}

registerExport(FormElementType.MetadataDocument, exportMetadataDocumentToXML)
