import { registerImport } from "~/lib/xml/import/importerFactory"
import { FormElementType } from "../types"

export const importMetadataDocumentFromXML = (xml: MetadataDocumentXML | undefined): MetadataDocument | undefined => {
  if (!xml) return undefined

  return {
    elementType: FormElementType.MetadataDocument,

    actionsWritingOnPost: xml.ActionsWritingOnPost,
    additionalIndexes: xml.AdditionalIndexes,
    attributes: xml.Attributes,
    autonumbering: xml.Autonumbering,
    auxiliaryChoiceForm: xml.AuxiliaryChoiceForm,
    auxiliaryListForm: xml.AuxiliaryListForm,
    auxiliaryObjectForm: xml.AuxiliaryObjectForm,
    basedOn: xml.BasedOn,
    characteristics: xml.Characteristics,
    checkUnique: xml.CheckUnique,
    choiceDataGetModeOnInputByString: xml.ChoiceDataGetModeOnInputByString,
    choiceHistoryOnInput: xml.ChoiceHistoryOnInput,
    commands: xml.Commands,
    comment: xml.Comment,
    createOnInput: xml.CreateOnInput,
    dataHistory: xml.DataHistory,
    dataLockControlMode: xml.DataLockControlMode,
    dataLockFields: xml.DataLockFields,
    defaultChoiceForm: xml.DefaultChoiceForm,
    defaultListForm: xml.DefaultListForm,
    defaultObjectForm: xml.DefaultObjectForm,
    executeAfterWriteDataHistoryVersionProcessing: xml.ExecuteAfterWriteDataHistoryVersionProcessing,
    explanation: xml.Explanation,
    extendedConfigurationObject: xml.ExtendedConfigurationObject,
    extendedListPresentation: xml.ExtendedListPresentation,
    extendedObjectPresentation: xml.ExtendedObjectPresentation,
    forms: xml.Forms,
    fullTextSearch: xml.FullTextSearch,
    fullTextSearchOnInputByString: xml.FullTextSearchOnInputByString,
    help: xml.Help,
    includeHelpInContents: xml.IncludeHelpInContents,
    inputByString: xml.InputByString,
    listPresentation: xml.ListPresentation,
    managerModule: xml.ManagerModule,
    numberAllowedLength: xml.NumberAllowedLength,
    numberLength: xml.NumberLength,
    numberPeriodicity: xml.NumberPeriodicity,
    numberType: xml.NumberType,
    numerator: xml.Numerator,
    objectBelonging: xml.ObjectBelonging,
    objectModule: xml.ObjectModule,
    objectPresentation: xml.ObjectPresentation,
    posting: xml.Posting,
    privilegedPostingMode: xml.PrivilegedPostingMode,
    privilegedUnpostingMode: xml.PrivilegedUnpostingMode,
    realTimePosting: xml.RealTimePosting,
    registerRecords: xml.RegisterRecords,
    registerRecordsDeletion: xml.RegisterRecordsDeletion,
    searchStringModeOnInputByString: xml.SearchStringModeOnInputByString,
    sequenceFilling: xml.SequenceFilling,
    standardAttributes: xml.StandardAttributes,
    synonym: xml.Synonym,
    tabularSections: xml.TabularSections,
    templates: xml.Templates,
    updateDataHistoryImmediatelyAfterWrite: xml.UpdateDataHistoryImmediatelyAfterWrite,
    useStandardCommands: xml.UseStandardCommands,
  }
}

registerImport(FormElementType.MetadataDocument, importMetadataDocumentFromXML)
