import { Color, ColorEnterprise, ColorXML } from "~/lib/metadata/commonObjects/color/types";
import { Font, FontEnterprise, FontXML } from "~/lib/metadata/commonObjects/font/types";
import { I8nText, I8nTextEnterprise, I8nTextXML } from "~/lib/metadata/commonObjects/i8nText/types";
import { Picture, PictureEnterprise, PictureXML } from "~/lib/metadata/commonObjects/pictures/types";
import { TypeDescription, TypeDescriptionEnterprise, TypeDescriptionXML } from "~/lib/metadata/commonObjects/typeDescription/types";
import { UserVisible, UserVisibleEnterprise, UserVisibleXML } from "~/lib/metadata/commonObjects/userVisible/types";
import { EventsXML } from "~/lib/metadata/forms/events/types";
import * as SE from "~/lib/metadata/systemEnumerations/types";
import { BaseElement, BaseElementEnterprise, BaseElementXML } from "../baseElement/types";
import { CommandBar, CommandBarEnterprise, CommandBarXML } from "../commandBar/types";
import { FormDecoration, FormDecorationEnterprise, FormDecorationXML } from "../formDecoration/types";
import { Table, TableEnterprise, TableXML } from "../table/types";


export interface FormField extends BaseElement {

  autoCellHeight?: boolean,
  cellHyperlink?: boolean,
  contextMenu?: CommandBar,
  dataPath?: string,
  defaultItem?: boolean,
  displayImportance?: SE.DisplayImportance,
  editMode?: SE.ColumnEditMode,
  enabled?: boolean,
  extendedTooltip?: FormDecoration,
  fixingInTable?: SE.FixingInTable,
  footerBackColor?: Color,
  footerDataPath?: string,
  footerFont?: Font,
  footerHorizontalAlign?: SE.ItemHorizontalLocation,
  footerPicture?: Picture,
  footerText?: I8nText,
  footerTextColor?: Color,
  headerHorizontalAlign?: SE.ItemHorizontalLocation,
  headerPicture?: Picture,
  horizontalAlign?: SE.ItemHorizontalLocation,
  horizontalAlignInGroup?: SE.ItemHorizontalLocation,
  readOnly?: boolean,
  shortcut?: string,
  showInFooter?: boolean,
  showInHeader?: boolean,
  skipOnInput?: boolean,
  table?: Table,
  title?: I8nText,
  titleBackColor?: Color,
  titleFont?: Font,
  titleHeight?: number,
  titleLocation?: SE.FormItemTitleLocation,
  titleTextColor?: Color,
  toolTip?: I8nText,
  toolTipRepresentation?: SE.ToolTipRepresentation,
  type?: SE.FormFieldType,
  typeRestriction?: TypeDescription,
  userVisible?: UserVisible,
  verticalAlign?: SE.ItemVerticalAlign,
  verticalAlignInGroup?: SE.ItemVerticalAlign,
  visible?: boolean,
  warningOnEdit?: I8nText,
  warningOnEditRepresentation?: SE.WarningOnEditRepresentation,
  events?: {
    onChange?: string,
  },
}

export interface FormFieldXML extends BaseElementXML {
  
  AutoCellHeight?: boolean,
  CellHyperlink?: boolean,
  ContextMenu?: CommandBarXML,
  DataPath?: string,
  DefaultItem?: boolean,
  _DisplayImportance?: SE.DisplayImportance,
  EditMode?: SE.ColumnEditMode,
  Enabled?: boolean,
  ExtendedTooltip?: FormDecorationXML,
  FixingInTable?: SE.FixingInTable,
  FooterBackColor?: ColorXML,
  FooterDataPath?: string,
  FooterFont?: FontXML,
  FooterHorizontalAlign?: SE.ItemHorizontalLocation,
  FooterPicture?: PictureXML,
  FooterText?: I8nTextXML,
  FooterTextColor?: ColorXML,
  HeaderHorizontalAlign?: SE.ItemHorizontalLocation,
  HeaderPicture?: PictureXML,
  HorizontalAlign?: SE.ItemHorizontalLocation,
  HorizontalAlignInGroup?: SE.ItemHorizontalLocation,
  ReadOnly?: boolean,
  Shortcut?: string,
  ShowInFooter?: boolean,
  ShowInHeader?: boolean,
  SkipOnInput?: boolean,
  Table?: TableXML,
  Title?: I8nTextXML,
  TitleBackColor?: ColorXML,
  TitleFont?: FontXML,
  TitleHeight?: number,
  TitleLocation?: SE.FormItemTitleLocation,
  TitleTextColor?: ColorXML,
  ToolTip?: I8nTextXML,
  ToolTipRepresentation?: SE.ToolTipRepresentation,
  Type?: SE.FormFieldType,
  TypeRestriction?: TypeDescriptionXML,
  UserVisible?: UserVisibleXML,
  VerticalAlign?: SE.ItemVerticalAlign,
  VerticalAlignInGroup?: SE.ItemVerticalAlign,
  Visible?: boolean,
  WarningOnEdit?: I8nTextXML,
  WarningOnEditRepresentation?: SE.WarningOnEditRepresentation,
  Events?: EventsXML,
}

export interface FormFieldEnterprise extends BaseElementEnterprise {
  АвтоВысотаЯчейки?: boolean,
  ГиперссылкаЯчейки?: boolean,
  КонтекстноеМеню?: CommandBarEnterprise,
  ПутьКДанным?: string,
  АктивизироватьПоУмолчанию?: boolean,
  ВажностьПриОтображении?: SE.DisplayImportanceEnterprise,
  РежимРедактирования?: SE.ColumnEditModeEnterprise,
  Доступность?: boolean,
  РасширеннаяПодсказка?: FormDecorationEnterprise,
  ФиксацияВТаблице?: SE.FixingInTableEnterprise,
  ЦветФонаПодвала?: ColorEnterprise,
  ПутьКДаннымПодвала?: string,
  ШрифтПодвала?: FontEnterprise,
  ГоризонтальноеПоложениеВПодвале?: SE.ItemHorizontalLocationEnterprise,
  КартинкаПодвала?: PictureEnterprise,
  ТекстПодвала?: I8nTextEnterprise,
  ЦветТекстаПодвала?: ColorEnterprise,
  ГоризонтальноеПоложениеВШапке?: SE.ItemHorizontalLocationEnterprise,
  КартинкаШапки?: PictureEnterprise,
  ГоризонтальноеПоложение?: SE.ItemHorizontalLocationEnterprise,
  ГоризонтальноеПоложениеВГруппе?: SE.ItemHorizontalLocationEnterprise,
  ТолькоПросмотр?: boolean,
  СочетаниеКлавиш?: string,
  ОтображатьВПодвале?: boolean,
  ОтображатьВШапке?: boolean,
  ПропускатьПриВводе?: boolean,
  Таблица?: TableEnterprise,
  Заголовок?: I8nTextEnterprise,
  ЦветФонаЗаголовка?: ColorEnterprise,
  ШрифтЗаголовка?: FontEnterprise,
  ВысотаЗаголовка?: number,
  ПоложениеЗаголовка?: SE.FormItemTitleLocationEnterprise,
  ЦветТекстаЗаголовка?: ColorEnterprise,
  Подсказка?: I8nTextEnterprise,
  ОтображениеПодсказки?: SE.ToolTipRepresentationEnterprise,
  Вид?: SE.FormFieldTypeEnterprise,
  ОграничениеТипа?: TypeDescriptionEnterprise,
  ПользовательскаяВидимость?: UserVisibleEnterprise,
  ВертикальноеПоложение?: SE.ItemVerticalAlignEnterprise,
  ВертикальноеПоложениеВГруппе?: SE.ItemVerticalAlignEnterprise,
  Видимость?: boolean,
  ПредупреждениеПриРедактировании?: I8nTextEnterprise,
  ОтображениеПредупрежденияПриРедактировании?: SE.WarningOnEditRepresentationEnterprise,
  События?: {
    ПриИзменении?: string,
  },
}