import { MetadataConstant, MetadataConstantYAML } from "../types"

export const full: MetadataConstant = {
  itemType: "MetadataConstant",
  name: "КонстантаВсеСвойства",
  synonym: { items: { ru: "Синоним" } },
  comment: "Комментарий",
  type: { type: ["string"], stringQualifiers: { length: 10, allowedLength: "Variable" } },
  useStandardCommands: false,
  defaultForm: "CommonForm.КонстантаВсеСвойства",
  extendedPresentation: { items: { ru: "Расширенное представление" } },
  explanation: { items: { ru: "Пояснение" } },
  passwordMode: true,
  format: { items: { ru: "ЧЦ=15; ЧДЦ=2" } },
  editFormat: { items: { ru: "ЧЦ=15; ЧДЦ=2" } },
  toolTip: { items: { ru: "Подсказка" } },
  markNegatives: true,
  mask: "Маска",
  multiLine: true,
  extendedEdit: true,
  minValue: 5,
  maxValue: 90,
  fillChecking: "ShowError",
  linkByType: {
    dataPath: "Constant.КонстантаБулево",
    linkItem: 0,
  },
  choiceHistoryOnInput: "DontUse",
  dataLockControlMode: "Automatic",
  dataHistory: "Use",
  updateDataHistoryImmediatelyAfterWrite: true,
  executeAfterWriteDataHistoryVersionProcessing: true,
}

export const fullYAML: MetadataConstantYAML = {
  Синоним: "Синоним",
  Комментарий: "Комментарий",
  Тип: "Строка(10)",
  ИспользоватьСтандартныеКоманды: "Ложь",
  ОсновнаяФорма: "CommonForm.КонстантаВсеСвойства",
  РасширенноеПредставление: "Расширенное представление",
  Пояснение: "Пояснение",
  РежимПароля: "Истина",
  Формат: "ЧЦ=15; ЧДЦ=2",
  ФорматРедактирования: "ЧЦ=15; ЧДЦ=2",
  Подсказка: "Подсказка",
  ВыделятьОтрицательные: "Истина",
  Маска: "Маска",
  МногострочныйРежим: "Истина",
  РасширенноеРедактирование: "Истина",
  МинимальноеЗначение: 5,
  МаксимальноеЗначение: 90,
  ПроверкаЗаполнения: "ВыдаватьОшибку",
  СвязьПоТипу: "Константа.КонстантаБулево",
  ИсторияВыбораПриВводе: "НеИспользовать",
  РежимУправленияБлокировкойДанных: "Автоматический",
  ИсторияДанных: "Использовать",
  ОбновлятьИсториюДанныхСразуПослеЗаписи: "Истина",
  ВыполнятьОбработкуПослеЗаписиВерсииИсторииДанных: "Истина",
}
