import { MetadataItemRule } from "~/metadata/orchestration/property/types"
import type { ReferenceScope } from "../../relations/referenceScope"
import { MetadataCatalogStandardAttributeNames } from "./types"

const catalogBaseProperties = ["Catalog"]

const catalogProperties = ["Catalog", "Properties"]
const catalogChildObjects = ["Catalog", "ChildObjects"]

export const MetadataCatalogRules = {
  itemType: "MetadataCatalog",
  itemTypePrefix: "Справочник",
  properties: {
    internalInfo: {
      type: "InternalInfo",
      xmlParents: catalogBaseProperties,
      forReferenceOnly: true,
      items: [
        { name: "CatalogObject", category: "Object" },
        { name: "CatalogRef", category: "Ref" },
        { name: "CatalogSelection", category: "Selection" },
        { name: "CatalogList", category: "List" },
        { name: "CatalogManager", category: "Manager" },
      ],
    },
    uuid: {
      type: "string",
      xml: "_uuid",
      forReferenceOnly: true,
      xmlParents: catalogBaseProperties,
    },
    additionalIndexes: {
      yaml: "ДополнительныеИндексы",
      type: "AdditionalIndex",
      xmlParents: catalogProperties,
    },
    attributes: {
      yaml: "Реквизиты",
      type: "MetadataAttributes",
      xmlParents: catalogChildObjects,
      xml: "Attribute",
    },
    autonumbering: {
      yaml: "Автонумерация",
      type: "boolean",
      defaultValueXML: true,
      xmlParents: catalogProperties,
      order: 18,
    },
    auxiliaryChoiceForm: {
      yaml: "ДополнительнаяФормаДляВыбора",
      type: "string",
      xmlParents: catalogProperties,
      referenceScope: { target: "this", kind: "Form" },
      defaultValueXMLRaw: "",
      order: 38,
    },
    auxiliaryFolderChoiceForm: {
      yaml: "ДополнительнаяФормаДляВыбораГруппы",
      type: "string",
      xmlParents: catalogProperties,
      referenceScope: { target: "this", kind: "Form" },
      defaultValueXMLRaw: "",
      order: 39,
    },
    auxiliaryFolderForm: {
      yaml: "ДополнительнаяФормаГруппы",
      type: "string",
      xmlParents: catalogProperties,
      referenceScope: { target: "this", kind: "Form" },
      defaultValueXMLRaw: "",
      order: 36,
    },
    auxiliaryListForm: {
      yaml: "ДополнительнаяФормаСписка",
      type: "string",
      xmlParents: catalogProperties,
      referenceScope: { target: "this", kind: "Form" },
      defaultValueXMLRaw: "",
      order: 37,
    },
    auxiliaryObjectForm: {
      yaml: "ДополнительнаяФормаОбъекта",
      type: "string",
      xmlParents: catalogProperties,
      referenceScope: { target: "this", kind: "Form" },
      defaultValueXMLRaw: "",
      order: 35,
    },
    basedOn: {
      yaml: "ВводитсяНаОсновании",
      type: "MetadataValueCollection",
      xmlParents: catalogProperties,
      referenceScope: { target: "topLevel", allowedTypes: ["Справочник", "Документ"] },
      defaultValueXMLRaw: {},
      order: 41,
    },
    characteristics: {
      yaml: "Характеристики",
      type: "CharacteristicsDescriptions",
      xmlParents: catalogProperties,
      defaultValueXMLRaw: {},
      order: 21,
    },
    checkUnique: {
      yaml: "КонтрольУникальности",
      type: "boolean",
      defaultValueXML: true,
      xmlParents: catalogProperties,
      order: 17,
    },
    choiceDataGetModeOnInputByString: {
      yaml: "РежимПолученияДанныхВыбораПриВводеПоСтроке",
      type: "SystemEnumeration",
      typeSE: "ChoiceDataGetModeOnInputByString",
      defaultValueXML: "Directly",
      xmlParents: catalogProperties,
      defaultValueYAML: "Directly",
      order: 29,
    },
    choiceHistoryOnInput: {
      yaml: "ИсторияВыбораПриВводе",
      type: "SystemEnumeration",
      typeSE: "ChoiceHistoryOnInput",
      defaultValueXML: "Auto",
      xmlParents: catalogProperties,
      defaultValueYAML: "Auto",
      order: 51,
    },
    choiceMode: {
      yaml: "СпособВыбора",
      type: "SystemEnumeration",
      typeSE: "ChoiceMode",
      defaultValueXML: "BothWays",
      xmlParents: catalogProperties,
      defaultValueYAML: "BothWays",
      order: 25,
    },
    codeAllowedLength: {
      yaml: "ДопустимаяДлинаКода",
      type: "SystemEnumeration",
      typeSE: "AllowedLength",
      defaultValueXML: "Variable",
      xmlParents: catalogProperties,
      defaultValueYAML: "Variable",
      order: 15,
    },
    codeLength: {
      yaml: "ДлинаКода",
      type: "number",
      defaultValueXML: 9,
      xmlParents: catalogProperties,
      order: 12,
    },
    codeSeries: {
      yaml: "СерииКодов",
      type: "SystemEnumeration",
      typeSE: "CatalogCodesSeries",
      defaultValueXML: "WholeCatalog",
      xmlParents: catalogProperties,
      defaultValueYAML: "WholeCatalog",
      order: 16,
    },
    codeType: {
      yaml: "ТипКода",
      type: "SystemEnumeration",
      typeSE: "CatalogCodeType",
      defaultValueXML: "String",
      xmlParents: catalogProperties,
      defaultValueYAML: "String",
      order: 14,
    },
    comment: {
      yaml: "Комментарий",
      type: "string",
      xmlParents: catalogProperties,
      defaultValueXMLRaw: "",
      order: 3,
    },
    createOnInput: {
      yaml: "СозданиеПриВводе",
      type: "SystemEnumeration",
      typeSE: "CreateOnInput",
      defaultValueXML: "Use",
      xmlParents: catalogProperties,
      defaultValueYAML: "Use",
      order: 50,
    },
    dataHistory: {
      yaml: "ИсторияДанных",
      type: "SystemEnumeration",
      typeSE: "DataHistoryUse",
      defaultValueXML: "DontUse",
      xmlParents: catalogProperties,
      defaultValueYAML: "DontUse",
      order: 52,
    },
    dataLockControlMode: {
      yaml: "РежимУправленияБлокировкойДанных",
      type: "SystemEnumeration",
      typeSE: "DefaultDataLockControlMode",
      defaultValueXML: "Managed",
      xmlParents: catalogProperties,
      defaultValueYAML: "Managed",
      order: 43,
    },
    dataLockFields: {
      yaml: "ПоляБлокировкиДанных",
      type: "MetadataFields",
      xmlParents: catalogProperties,
      defaultValueXMLRaw: {},
      order: 42,
    },
    defaultChoiceForm: {
      yaml: "ОсновнаяФормаДляВыбора",
      type: "string",
      xmlParents: catalogProperties,
      referenceScope: { target: "this", kind: "Form" },
      defaultValueXMLRaw: "",
      order: 33,
    },
    defaultFolderChoiceForm: {
      yaml: "ОсновнаяФормаДляВыбораГруппы",
      type: "string",
      xmlParents: catalogProperties,
      referenceScope: { target: "this", kind: "Form" },
      defaultValueXMLRaw: "",
      order: 34,
    },
    defaultFolderForm: {
      yaml: "ОсновнаяФормаГруппы",
      type: "string",
      xmlParents: catalogProperties,
      referenceScope: { target: "this", kind: "Form" },
      defaultValueXMLRaw: "",
      order: 31,
    },
    defaultListForm: {
      yaml: "ОсновнаяФормаСписка",
      type: "string",
      xmlParents: catalogProperties,
      referenceScope: { target: "this", kind: "Form" },
      defaultValueXMLRaw: "",
      order: 32,
    },
    defaultObjectForm: {
      yaml: "ОсновнаяФормаОбъекта",
      type: "string",
      xmlParents: catalogProperties,
      referenceScope: { target: "this", kind: "Form" },
      defaultValueXMLRaw: "",
      order: 30,
    },
    defaultPresentation: {
      yaml: "ОсновноеПредставление",
      type: "SystemEnumeration",
      typeSE: "CatalogMainPresentation",
      defaultValueXML: "AsDescription",
      xmlParents: catalogProperties,
      defaultValueYAML: "AsDescription",
      order: 19,
    },
    descriptionLength: {
      yaml: "ДлинаНаименования",
      type: "number",
      defaultValueXML: 25,
      xmlParents: catalogProperties,
      order: 13,
    },
    editType: {
      yaml: "СпособРедактирования",
      type: "SystemEnumeration",
      typeSE: "EditType",
      defaultValueXML: "InDialog",
      xmlParents: catalogProperties,
      defaultValueYAML: "InDialog",
      order: 23,
    },
    executeAfterWriteDataHistoryVersionProcessing: {
      yaml: "ВыполнятьОбработкуПослеЗаписиВерсииИсторииДанных",
      type: "boolean",
      defaultValueXML: false,
      xmlParents: catalogProperties,
      order: 54,
    },
    explanation: {
      yaml: "Пояснение",
      type: "I8nText",
      xmlParents: catalogProperties,
      defaultValueXMLRaw: {},
      order: 49,
    },
    extendedListPresentation: {
      yaml: "РасширенноеПредставлениеСписка",
      type: "I8nText",
      xmlParents: catalogProperties,
      defaultValueXMLRaw: {},
      order: 48,
    },
    extendedObjectPresentation: {
      yaml: "РасширенноеПредставлениеОбъекта",
      type: "I8nText",
      xmlParents: catalogProperties,
      defaultValueXMLRaw: {},
      order: 46,
    },
    foldersOnTop: {
      yaml: "ГруппыСверху",
      type: "boolean",
      defaultValueXML: true,
      xmlParents: catalogProperties,
      order: 8,
    },
    fullTextSearch: {
      yaml: "ПолнотекстовыйПоиск",
      type: "SystemEnumeration",
      typeSE: "UseFullTextSearch",
      defaultValueXML: "Use",
      xmlParents: catalogProperties,
      defaultValueYAML: "Use",
      order: 44,
    },
    fullTextSearchOnInputByString: {
      yaml: "ПолнотекстовыйПоискПриВводеПоСтроке",
      type: "SystemEnumeration",
      typeSE: "FullTextSearchOnInputByString",
      defaultValueXML: "DontUse",
      xmlParents: catalogProperties,
      defaultValueYAML: "DontUse",
      order: 28,
    },
    hierarchical: {
      yaml: "Иерархический",
      type: "boolean",
      defaultValueXML: false,
      xmlParents: catalogProperties,
      order: 4,
    },
    hierarchyType: {
      yaml: "ВидИерархии",
      type: "SystemEnumeration",
      typeSE: "HierarchyType",
      defaultValueXML: "HierarchyFoldersAndItems",
      xmlParents: catalogProperties,
      defaultValueYAML: "HierarchyFoldersAndItems",
      order: 5,
    },
    includeHelpInContents: {
      yaml: "ВключатьСправкуВСодержание",
      type: "boolean",
      defaultValueXML: false,
      xmlParents: catalogProperties,
      order: 40,
    },
    inputByString: {
      yaml: "ВводПоСтроке",
      type: "MetadataFields",
      xmlParents: catalogProperties,
      referenceScope: { target: "this", kind: "Attribute", filter: "stringIndexedAttribute" },
      order: 26,
    },
    levelCount: {
      yaml: "КоличествоУровней",
      type: "number",
      defaultValueXML: 2,
      xmlParents: catalogProperties,
      order: 7,
    },
    limitLevelCount: {
      yaml: "ОграничиватьКоличествоУровней",
      type: "boolean",
      defaultValueXML: false,
      xmlParents: catalogProperties,
      order: 6,
    },
    listPresentation: {
      yaml: "ПредставлениеСписка",
      type: "I8nText",
      xmlParents: catalogProperties,
      defaultValueXMLRaw: {},
      order: 47,
    },
    name: {
      type: "string",
      xmlParents: catalogProperties,
      required: true,
      order: 1,
    },
    objectBelonging: {
      yaml: "ПринадлежностьОбъекта",
      type: "SystemEnumeration",
      typeSE: "ObjectBelonging",
      xmlParents: catalogProperties,
      toYAML: false,
      fromYAML: false,
      defaultValueYAML: "Native",
    },
    objectPresentation: {
      yaml: "ПредставлениеОбъекта",
      type: "I8nText",
      xmlParents: catalogProperties,
      defaultValueXMLRaw: {},
      order: 45,
    },
    owners: {
      yaml: "Владельцы",
      type: "MetadataValueCollection",
      xmlParents: catalogProperties,
      referenceScope: { target: "topLevel", allowedTypes: ["Справочник", "Документ"] },
      defaultValueXMLRaw: {},
      order: 10,
    },
    predefined: {
      yaml: "Предопределенные",
      type: "Predefined",
      xmlParents: catalogProperties,
    },
    predefinedDataUpdate: {
      yaml: "ОбновлениеПредопределенныхДанных",
      type: "SystemEnumeration",
      typeSE: "PredefinedDataUpdate",
      defaultValueXML: "Auto",
      xmlParents: catalogProperties,
      defaultValueYAML: "Auto",
      order: 22,
    },
    quickChoice: {
      yaml: "БыстрыйВыбор",
      type: "boolean",
      defaultValueXML: false,
      xmlParents: catalogProperties,
      order: 24,
    },
    searchStringModeOnInputByString: {
      yaml: "СпособПоискаСтрокиПриВводеПоСтроке",
      type: "SystemEnumeration",
      typeSE: "SearchStringModeOnInputByString",
      defaultValueXML: "Begin",
      xmlParents: catalogProperties,
      defaultValueYAML: "Begin",
      order: 27,
    },
    subordinationUse: {
      yaml: "ИспользованиеПодчинения",
      type: "SystemEnumeration",
      typeSE: "SubordinationUse",
      defaultValueXML: "ToItems",
      xmlParents: catalogProperties,
      defaultValueYAML: "ToItems",
      order: 11,
    },
    synonym: {
      yaml: "Синоним",
      type: "I8nText",
      xmlParents: catalogProperties,
      order: 2,
    },
    tabularSections: {
      yaml: "ТабличныеЧасти",
      type: "MetadataTabularSections",
      xmlParents: catalogChildObjects,
      xml: "TabularSection",
    },
    standardAttributes: {
      yaml: "СтандартныеРеквизиты",
      type: "StandardAttributeDescriptions",
      standartAttributeNames: MetadataCatalogStandardAttributeNames,
      xmlParents: catalogProperties,
      order: 20,
    },
    commands: {
      yaml: "Команды",
      type: "MetadataCommands",
      xmlParents: catalogChildObjects,
      xml: "Command",
    },
    updateDataHistoryImmediatelyAfterWrite: {
      yaml: "ОбновлятьИсториюДанныхСразуПослеЗаписи",
      type: "boolean",
      defaultValueXML: false,
      xmlParents: catalogProperties,
      order: 53,
    },
    useStandardCommands: {
      yaml: "ИспользоватьСтандартныеКоманды",
      type: "boolean",
      defaultValueXML: true,
      xmlParents: catalogProperties,
      order: 9,
    },
  },
} as const satisfies MetadataItemRule

/**
 * Возвращает referenceScope для свойства справочника по его YAML-ключу.
 * Используется VSCode-провайдерами для фильтрации автодополнения.
 */
export function getCatalogPropertyReferenceScope(yamlKey: string): ReferenceScope | undefined {
  for (const rule of Object.values(MetadataCatalogRules.properties)) {
    const r = rule as { yaml?: string; referenceScope?: ReferenceScope }
    if (r.yaml === yamlKey && r.referenceScope != null) {
      return r.referenceScope
    }
  }
  return undefined
}
