import { MetadataItemRule } from "~/metadata/orchestration/property/types"
import { MetadataCatalogStandardAttributeNames } from "./types"

const catalogBaseProperties = ["Catalog"]

const catalogProperties = ["Catalog", "Properties"]
const catalogChildObjects = ["Catalog", "ChildObjects"]

export const MetadataCatalogRules = {
  itemType: "MetadataCatalog",
  itemTypePrefix: "Справочник",
  properties: {
    internalInfo: {
      type: "InternalInfo",
      xmlParents: catalogBaseProperties,
      forReferenceOnly: true,
      items: [
        { name: "CatalogObject", category: "Object" },
        { name: "CatalogRef", category: "Ref" },
        { name: "CatalogSelection", category: "Selection" },
        { name: "CatalogList", category: "List" },
        { name: "CatalogManager", category: "Manager" },
      ],
    },
    uuid: {
      type: "string",
      xml: "_uuid",
      forReferenceOnly: true,
      xmlParents: catalogBaseProperties,
    },
    additionalIndexes: {
      yaml: "ДополнительныеИндексы",
      type: "AdditionalIndex",
      xmlParents: catalogProperties,
    },
    attributes: {
      yaml: "Реквизиты",
      type: "MetadataAttributes",
      xmlParents: catalogChildObjects,
      xml: "Attribute",
    },
    autonumbering: {
      yaml: "Автонумерация",
      type: "boolean",
      defaultValueXML: true,
      xmlParents: catalogProperties,
    },
    auxiliaryChoiceForm: {
      yaml: "ДополнительнаяФормаДляВыбора",
      type: "string",
      xmlParents: catalogProperties,
      // dependencies: ["this", "Form"],
    },
    auxiliaryFolderChoiceForm: {
      yaml: "ДополнительнаяФормаДляВыбораГруппы",
      type: "string",
      xmlParents: catalogProperties,
    },
    auxiliaryFolderForm: {
      yaml: "ДополнительнаяФормаГруппы",
      type: "string",
      xmlParents: catalogProperties,
    },
    auxiliaryListForm: {
      yaml: "ДополнительнаяФормаСписка",
      type: "string",
      xmlParents: catalogProperties,
    },
    auxiliaryObjectForm: {
      yaml: "ДополнительнаяФормаОбъекта",
      type: "string",
      xmlParents: catalogProperties,
    },
    basedOn: {
      yaml: "ВводитсяНаОсновании",
      type: "MetadataValueCollection",
      xmlParents: catalogProperties,
    },
    characteristics: {
      yaml: "Характеристики",
      type: "CharacteristicsDescriptions",
      xmlParents: catalogProperties,
    },
    checkUnique: {
      yaml: "КонтрольУникальности",
      type: "boolean",
      defaultValueXML: true,
      xmlParents: catalogProperties,
    },
    choiceDataGetModeOnInputByString: {
      yaml: "РежимПолученияДанныхВыбораПриВводеПоСтроке",
      type: "SystemEnumeration",
      typeSE: "ChoiceDataGetModeOnInputByString",
      defaultValueXML: "Directly",
      xmlParents: catalogProperties,
    },
    choiceHistoryOnInput: {
      yaml: "ИсторияВыбораПриВводе",
      type: "SystemEnumeration",
      typeSE: "ChoiceHistoryOnInput",
      defaultValueXML: "Auto",
      xmlParents: catalogProperties,
    },
    choiceMode: {
      yaml: "СпособВыбора",
      type: "SystemEnumeration",
      typeSE: "ChoiceMode",
      defaultValueXML: "BothWays",
      xmlParents: catalogProperties,
    },
    codeAllowedLength: {
      yaml: "ДопустимаяДлинаКода",
      type: "SystemEnumeration",
      typeSE: "AllowedLength",
      defaultValueXML: "Variable",
      xmlParents: catalogProperties,
    },
    codeLength: {
      yaml: "ДлинаКода",
      type: "number",
      defaultValueXML: 9,
      xmlParents: catalogProperties,
    },
    codeSeries: {
      yaml: "СерииКодов",
      type: "SystemEnumeration",
      typeSE: "CatalogCodesSeries",
      defaultValueXML: "WholeCatalog",
      xmlParents: catalogProperties,
    },
    codeType: {
      yaml: "ТипКода",
      type: "SystemEnumeration",
      typeSE: "CatalogCodeType",
      defaultValueXML: "String",
      xmlParents: catalogProperties,
    },
    comment: {
      yaml: "Комментарий",
      type: "string",
      xmlParents: catalogProperties,
    },
    createOnInput: {
      yaml: "СозданиеПриВводе",
      type: "SystemEnumeration",
      typeSE: "CreateOnInput",
      defaultValueXML: "Use",
      xmlParents: catalogProperties,
    },
    dataHistory: {
      yaml: "ИсторияДанных",
      type: "SystemEnumeration",
      typeSE: "DataHistoryUse",
      defaultValueXML: "DontUse",
      xmlParents: catalogProperties,
    },
    dataLockControlMode: {
      yaml: "РежимУправленияБлокировкойДанных",
      type: "SystemEnumeration",
      typeSE: "DefaultDataLockControlMode",
      defaultValueXML: "Managed",
      xmlParents: catalogProperties,
    },
    dataLockFields: {
      yaml: "ПоляБлокировкиДанных",
      type: "MetadataFields",
      xmlParents: catalogProperties,
    },
    defaultChoiceForm: {
      yaml: "ОсновнаяФормаДляВыбора",
      type: "string",
      xmlParents: catalogProperties,
    },
    defaultFolderChoiceForm: {
      yaml: "ОсновнаяФормаДляВыбораГруппы",
      type: "string",
      xmlParents: catalogProperties,
    },
    defaultFolderForm: {
      yaml: "ОсновнаяФормаГруппы",
      type: "string",
      xmlParents: catalogProperties,
    },
    defaultListForm: {
      yaml: "ОсновнаяФормаСписка",
      type: "string",
      xmlParents: catalogProperties,
    },
    defaultObjectForm: {
      yaml: "ОсновнаяФормаОбъекта",
      type: "string",
      xmlParents: catalogProperties,
    },
    defaultPresentation: {
      yaml: "ОсновноеПредставление",
      type: "SystemEnumeration",
      typeSE: "CatalogMainPresentation",
      defaultValueXML: "AsDescription",
      xmlParents: catalogProperties,
    },
    descriptionLength: {
      yaml: "ДлинаНаименования",
      type: "number",
      defaultValueXML: 25,
      xmlParents: catalogProperties,
    },
    editType: {
      yaml: "СпособРедактирования",
      type: "SystemEnumeration",
      typeSE: "EditType",
      defaultValueXML: "InDialog",
      xmlParents: catalogProperties,
    },
    executeAfterWriteDataHistoryVersionProcessing: {
      yaml: "ВыполнятьОбработкуПослеЗаписиВерсииИсторииДанных",
      type: "boolean",
      defaultValueXML: false,
      xmlParents: catalogProperties,
    },
    explanation: {
      yaml: "Пояснение",
      type: "I8nText",
      xmlParents: catalogProperties,
    },
    extendedListPresentation: {
      yaml: "РасширенноеПредставлениеСписка",
      type: "I8nText",
      xmlParents: catalogProperties,
    },
    extendedObjectPresentation: {
      yaml: "РасширенноеПредставлениеОбъекта",
      type: "I8nText",
      xmlParents: catalogProperties,
    },
    foldersOnTop: {
      yaml: "ГруппыСверху",
      type: "boolean",
      defaultValueXML: true,
      xmlParents: catalogProperties,
    },
    fullTextSearch: {
      yaml: "ПолнотекстовыйПоиск",
      type: "SystemEnumeration",
      typeSE: "UseFullTextSearch",
      defaultValueXML: "Use",
      xmlParents: catalogProperties,
    },
    fullTextSearchOnInputByString: {
      yaml: "ПолнотекстовыйПоискПриВводеПоСтроке",
      type: "SystemEnumeration",
      typeSE: "FullTextSearchOnInputByString",
      defaultValueXML: "DontUse",
      xmlParents: catalogProperties,
    },
    hierarchical: {
      yaml: "Иерархический",
      type: "boolean",
      defaultValueXML: false,
      xmlParents: catalogProperties,
    },
    hierarchyType: {
      yaml: "ВидИерархии",
      type: "SystemEnumeration",
      typeSE: "HierarchyType",
      defaultValueXML: "HierarchyFoldersAndItems",
      xmlParents: catalogProperties,
    },
    includeHelpInContents: {
      yaml: "ВключатьСправкуВСодержание",
      type: "boolean",
      defaultValueXML: false,
      xmlParents: catalogProperties,
    },
    inputByString: {
      yaml: "ВводПоСтроке",
      type: "MetadataFields",
      xmlParents: catalogProperties,
    },
    levelCount: {
      yaml: "КоличествоУровней",
      type: "number",
      defaultValueXML: 2,
      xmlParents: catalogProperties,
    },
    limitLevelCount: {
      yaml: "ОграничиватьКоличествоУровней",
      type: "boolean",
      defaultValueXML: false,
      xmlParents: catalogProperties,
    },
    listPresentation: {
      yaml: "ПредставлениеСписка",
      type: "I8nText",
      xmlParents: catalogProperties,
    },
    name: {
      type: "string",
      xmlParents: catalogProperties,
      required: true,
    },
    objectBelonging: {
      yaml: "ПринадлежностьОбъекта",
      type: "SystemEnumeration",
      typeSE: "ObjectBelonging",
      xmlParents: catalogProperties,
    },
    objectPresentation: {
      yaml: "ПредставлениеОбъекта",
      type: "I8nText",
      xmlParents: catalogProperties,
    },
    owners: {
      yaml: "Владельцы",
      type: "MetadataValueCollection",
      xmlParents: catalogProperties,
    },
    predefined: {
      yaml: "Предопределенные",
      type: "Predefined",
      xmlParents: catalogProperties,
    },
    predefinedDataUpdate: {
      yaml: "ОбновлениеПредопределенныхДанных",
      type: "SystemEnumeration",
      typeSE: "PredefinedDataUpdate",
      defaultValueXML: "Auto",
      xmlParents: catalogProperties,
    },
    quickChoice: {
      yaml: "БыстрыйВыбор",
      type: "boolean",
      defaultValueXML: false,
      xmlParents: catalogProperties,
    },
    searchStringModeOnInputByString: {
      yaml: "СпособПоискаСтрокиПриВводеПоСтроке",
      type: "SystemEnumeration",
      typeSE: "SearchStringModeOnInputByString",
      defaultValueXML: "Begin",
      xmlParents: catalogProperties,
    },
    subordinationUse: {
      yaml: "ИспользованиеПодчинения",
      type: "SystemEnumeration",
      typeSE: "SubordinationUse",
      defaultValueXML: "ToItems",
      xmlParents: catalogProperties,
    },
    synonym: {
      yaml: "Синоним",
      type: "I8nText",
      xmlParents: catalogProperties,
    },
    tabularSections: {
      yaml: "ТабличныеЧасти",
      type: "MetadataTabularSections",
      xmlParents: catalogChildObjects,
      xml: "TabularSection",
    },
    standardAttributes: {
      yaml: "СтандартныеРеквизиты",
      type: "StandardAttributeDescriptions",
      standartAttributeNames: MetadataCatalogStandardAttributeNames,
      xmlParents: catalogProperties,
    },
    commands: {
      yaml: "Команды",
      type: "MetadataCommands",
      xmlParents: catalogChildObjects,
      xml: "Command",
    },
    updateDataHistoryImmediatelyAfterWrite: {
      yaml: "ОбновлятьИсториюДанныхСразуПослеЗаписи",
      type: "boolean",
      defaultValueXML: false,
      xmlParents: catalogProperties,
    },
    useStandardCommands: {
      yaml: "ИспользоватьСтандартныеКоманды",
      type: "boolean",
      defaultValueXML: true,
      xmlParents: catalogProperties,
    },
  },
} as const satisfies MetadataItemRule
