import { stringRule } from "../string/types"
import { MetadataTabularSectionAttributeWithFillRules } from "../metadataAttribute/rules"
import type { MetadataItemRule } from "../../orchestration/property/types"
export const MetadataTaskAddressingAttributeRules = {
  itemType: "MetadataAttribute",
  externalMetadata: { segment: "AddressingAttribute", placement: "ownerChild" },
  xmlOrder: [
    "objectBelonging",
    "name",
    "synonym",
    "comment",
    "type",
    "passwordMode",
    "format",
    "editFormat",
    "toolTip",
    "markNegatives",
    "mask",
    "multiLine",
    "extendedEdit",
    "minValue",
    "maxValue",
    "fillFromFillingValue",
    "fillValue",
    "fillChecking",
    "choiceFoldersAndItems",
    "choiceParameterLinks",
    "choiceParameters",
    "quickChoice",
    "createOnInput",
    "choiceForm",
    "linkByType",
    "choiceHistoryOnInput",
    "indexing",
    "addressingDimension",
    "fullTextSearch",
    "dataHistory",
    "uuid",
  ],
  properties: {
    ...MetadataTabularSectionAttributeWithFillRules.properties,
    addressingDimension: stringRule({
      yaml: "ИзмерениеАдресации",
      xml: "AddressingDimension",
      xmlParents: ["Properties"],
      defaultValueXMLRaw: "",
    }),
  },
} as const satisfies MetadataItemRule
