import { addDefaultLanguageNameToSynonym } from "~/metadata/helpers/synonymHelpers"
import { ConfigurationContext } from "~/metadata/context/types"
import { MetadataItemRule, PropertyRule } from "~/metadata/orchestration/property/types"
import { uuidPropertyRule } from "~/metadata/commonObjects/uuid/rule"

const commonAttributeProperties = {
  uuid: uuidPropertyRule,
  name: {
    xml: "Name",
    type: "string",
    required: true,
    xmlParents: ["Properties"],
    order: 1,
  },
  synonym: {
    yaml: "Синоним",
    xml: "Synonym",
    type: "I8nText",
    excludeIfEqualNameYAML: true,
    defaultValue: ({ context, name, operation }: { context: ConfigurationContext; name?: string; operation?: string }) =>
      operation === "importFromYAML" && name
        ? addDefaultLanguageNameToSynonym(context, undefined, name)
        : { items: { [context.defaultLanguage]: "" } },
    xmlParents: ["Properties"],
    order: 2,
    defaultValueXMLRaw: "",
  },
  comment: {
    yaml: "Комментарий",
    xml: "Comment",
    type: "string",
    xmlParents: ["Properties"],
    order: 3,
    defaultValueXMLRaw: "",
  },
  type: {
    yaml: "Тип",
    type: "TypeDescription",
    xml: "Type",
    useAsShortValueYAML: true,
    xmlParents: ["Properties"],
    order: 4,
  },
  passwordMode: {
    yaml: "РежимПароля",
    xml: "PasswordMode",
    type: "boolean",
    defaultValueXML: false,
    xmlParents: ["Properties"],
    order: 5,
  },
  format: {
    yaml: "Формат",
    xml: "Format",
    type: "I8nText",
    xmlParents: ["Properties"],
    order: 6,
    defaultValueXMLRaw: "",
  },
  editFormat: {
    yaml: "ФорматРедактирования",
    xml: "EditFormat",
    type: "I8nText",
    xmlParents: ["Properties"],
    order: 7,
    defaultValueXMLRaw: "",
  },
  toolTip: {
    yaml: "Подсказка",
    xml: "ToolTip",
    type: "I8nText",
    xmlParents: ["Properties"],
    order: 8,
    defaultValueXMLRaw: "",
  },
  markNegatives: {
    yaml: "ВыделятьОтрицательные",
    xml: "MarkNegatives",
    type: "boolean",
    defaultValueXML: false,
    xmlParents: ["Properties"],
    order: 9,
  },
  mask: {
    yaml: "Маска",
    xml: "Mask",
    type: "string",
    xmlParents: ["Properties"],
    order: 10,
    defaultValueXMLRaw: "",
  },
  multiLine: {
    yaml: "МногострочныйРежим",
    xml: "MultiLine",
    type: "boolean",
    defaultValueXML: false,
    xmlParents: ["Properties"],
    order: 11,
  },
  extendedEdit: {
    yaml: "РасширенноеРедактирование",
    xml: "ExtendedEdit",
    type: "boolean",
    defaultValueXML: false,
    xmlParents: ["Properties"],
    order: 12,
  },
  minValue: {
    yaml: "МинимальноеЗначение",
    xml: "MinValue",
    type: "number",
    xmlParents: ["Properties"],
    order: 13,
    defaultValueXMLRaw: { "_xsi:nil": true },
  },
  maxValue: {
    yaml: "МаксимальноеЗначение",
    xml: "MaxValue",
    type: "number",
    xmlParents: ["Properties"],
    order: 14,
    defaultValueXMLRaw: { "_xsi:nil": true },
  },
  fillChecking: {
    yaml: "ПроверкаЗаполнения",
    xml: "FillChecking",
    type: "SystemEnumeration",
    typeSE: "FillChecking",
    defaultValueXML: "DontCheck",
    defaultValueYAML: "DontCheck",
    xmlParents: ["Properties"],
    order: 17,
  },
  choiceFoldersAndItems: {
    yaml: "ВыборГруппИЭлементов",
    xml: "ChoiceFoldersAndItems",
    type: "SystemEnumeration",
    typeSE: "FoldersAndItemsUse",
    defaultValueXML: "Items",
    defaultValueYAML: "Items",
    xmlParents: ["Properties"],
    order: 18,
  },
  choiceParameterLinks: {
    yaml: "СвязиПараметровВыбора",
    xml: "ChoiceParameterLinks",
    type: "ChoiceParameterLinks",
    xmlParents: ["Properties"],
    order: 19,
    defaultValueXMLRaw: "",
  },
  choiceParameters: {
    yaml: "ПараметрыВыбора",
    xml: "ChoiceParameters",
    type: "ChoiceParameters",
    xmlParents: ["Properties"],
    order: 20,
    defaultValueXMLRaw: "",
  },
  quickChoice: {
    yaml: "БыстрыйВыбор",
    xml: "QuickChoice",
    type: "SystemEnumeration",
    typeSE: "UseQuickChoice",
    defaultValueXML: "Auto",
    defaultValueYAML: "Auto",
    xmlParents: ["Properties"],
    order: 21,
  },
  createOnInput: {
    yaml: "СозданиеПриВводе",
    xml: "CreateOnInput",
    type: "SystemEnumeration",
    typeSE: "CreateOnInput",
    defaultValueXML: "Auto",
    defaultValueYAML: "Auto",
    xmlParents: ["Properties"],
    order: 22,
  },
  choiceForm: {
    yaml: "ФормаВыбора",
    xml: "ChoiceForm",
    type: "string",
    xmlParents: ["Properties"],
    order: 23,
    defaultValueXMLRaw: "",
  },
  linkByType: {
    yaml: "СвязьПоТипу",
    xml: "LinkByType",
    type: "TypeLink",
    xmlParents: ["Properties"],
    order: 24,
    defaultValueXMLRaw: "",
  },
  choiceHistoryOnInput: {
    yaml: "ИсторияВыбораПриВводе",
    xml: "ChoiceHistoryOnInput",
    type: "SystemEnumeration",
    typeSE: "ChoiceHistoryOnInput",
    defaultValueXML: "Auto",
    defaultValueYAML: "Auto",
    xmlParents: ["Properties"],
    order: 25,
  },
  indexing: {
    yaml: "Индексирование",
    xml: "Indexing",
    type: "SystemEnumeration",
    typeSE: "Indexing",
    defaultValueXML: "DontIndex",
    defaultValueYAML: "DontIndex",
    xmlParents: ["Properties"],
    order: 27,
  },
  fullTextSearch: {
    yaml: "ПолнотекстовыйПоиск",
    xml: "FullTextSearch",
    type: "SystemEnumeration",
    typeSE: "UseFullTextSearch",
    defaultValueXML: "Use",
    defaultValueYAML: "Use",
    xmlParents: ["Properties"],
    order: 28,
  },
  dataHistory: {
    yaml: "ИсторияДанных",
    xml: "DataHistory",
    type: "SystemEnumeration",
    typeSE: "DataHistoryUse",
    defaultValueXML: "Use",
    defaultValueYAML: "Use",
    xmlParents: ["Properties"],
    order: 29,
  },
  objectBelonging: {
    yaml: "ПринадлежностьОбъекта",
    xml: "ObjectBelonging",
    type: "SystemEnumeration",
    typeSE: "ObjectBelonging",
    defaultValueYAML: "Native",
    toYAML: false,
    fromYAML: false,
    xmlParents: ["Properties"],
  },
} as const satisfies Record<string, PropertyRule>

const fillProperties = {
  fillFromFillingValue: {
    yaml: "ЗаполнятьИзДанныхЗаполнения",
    xml: "FillFromFillingValue",
    type: "boolean",
    defaultValueXML: false,
    xmlParents: ["Properties"],
    order: 15,
  },
  fillValue: {
    yaml: "ЗначениеЗаполнения",
    xml: "FillValue",
    type: "MetadataValue",
    xmlParents: ["Properties"],
    order: 16,
    defaultValueXMLRaw: { "_xsi:nil": true },
  },
} as const satisfies Record<string, PropertyRule>

const binaryDataStorageLocationUseFieldProperty = {
  binaryDataStorageLocationUseField: {
    yaml: "ПолеИспользованияХраненияВХранилищеДвоичныхДанных",
    xml: "BinaryDataStorageLocationUseField",
    type: "boolean",
    xmlParents: ["Properties"],
    order: 31,
  },
} as const satisfies Record<string, PropertyRule>

export const MetadataAttributeRules = {
  itemType: "MetadataAttribute",
  properties: {
    ...commonAttributeProperties,
    ...fillProperties,
    use: {
      yaml: "Использование",
      xml: "Use",
      type: "SystemEnumeration",
      typeSE: "AttributeUse",
      defaultValueXML: "ForItem",
      defaultValueYAML: "ForItem",
      xmlParents: ["Properties"],
      order: 26,
    },
    binaryDataStorageLocationUse: {
      yaml: "ИспользованиеХраненияВХранилищеДвоичныхДанных",
      xml: "BinaryDataStorageLocationUse",
      type: "SystemEnumeration",
      typeSE: "BinaryDataStorageLocationUse",
      xmlParents: ["Properties"],
      order: 30,
    },
    ...binaryDataStorageLocationUseFieldProperty,
  },
} as const satisfies MetadataItemRule

export const MetadataDocumentAttributeRules = {
  itemType: "MetadataAttribute",
  properties: {
    ...commonAttributeProperties,
    ...fillProperties,
    ...binaryDataStorageLocationUseFieldProperty,
  },
} as const satisfies MetadataItemRule

export const MetadataTabularSectionAttributeRules = {
  itemType: "MetadataAttribute",
  properties: commonAttributeProperties,
} as const satisfies MetadataItemRule
