import { systemEnumerationRule } from "../../systemEnumerations/types"
import { addDefaultLanguageNameToSynonym } from "../../helpers/synonymHelpers"
import { ConfigurationContext } from "../../context/types"
import type { MetadataItemRule, PropertyRule } from "../../orchestration/property/types"
import { uuidPropertyRule } from "../uuid/rule"
const commonAttributeProperties = {
  uuid: uuidPropertyRule,
  name: {
    xml: "Name",
    type: "string",
    required: true,
    xmlParents: ["Properties"],
  },
  synonym: {
    yaml: "Синоним",
    xml: "Synonym",
    type: "I8nText",
    excludeIfEqualNameYAML: true,
    defaultValue: ({
      context,
      name,
      operation,
    }: {
      context: ConfigurationContext
      name?: string
      operation?: string
    }) =>
      operation === "importFromYAML" && name
        ? addDefaultLanguageNameToSynonym(context, undefined, name)
        : { items: { [context.defaultLanguage]: "" } },
    xmlParents: ["Properties"],
    defaultValueXMLEmpty: { items: {} },
    defaultValueXMLRaw: "",
    preserveEmptyXML: true,
  },
  comment: {
    yaml: "Комментарий",
    xml: "Comment",
    type: "string",
    xmlParents: ["Properties"],
    defaultValueXMLRaw: "",
  },
  type: {
    yaml: "Тип",
    type: "TypeDescription",
    xml: "Type",
    xmlParents: ["Properties"],
    defaultValueXMLRaw: "",
  },
  passwordMode: {
    yaml: "РежимПароля",
    xml: "PasswordMode",
    type: "boolean",
    defaultValueXML: false,
    implicitValueYAML: false,
    xmlParents: ["Properties"],
  },
  format: {
    yaml: "Формат",
    xml: "Format",
    type: "I8nText",
    xmlParents: ["Properties"],
    defaultValueXMLRaw: "",
  },
  editFormat: {
    yaml: "ФорматРедактирования",
    xml: "EditFormat",
    type: "I8nText",
    xmlParents: ["Properties"],
    defaultValueXMLRaw: "",
  },
  toolTip: {
    yaml: "Подсказка",
    xml: "ToolTip",
    type: "I8nText",
    xmlParents: ["Properties"],
    defaultValueXMLRaw: "",
  },
  markNegatives: {
    yaml: "ВыделятьОтрицательные",
    xml: "MarkNegatives",
    type: "boolean",
    defaultValueXML: false,
    implicitValueYAML: false,
    xmlParents: ["Properties"],
  },
  mask: {
    yaml: "Маска",
    xml: "Mask",
    type: "string",
    xmlParents: ["Properties"],
    defaultValueXMLRaw: "",
  },
  multiLine: {
    yaml: "МногострочныйРежим",
    xml: "MultiLine",
    type: "boolean",
    defaultValueXML: false,
    implicitValueYAML: false,
    xmlParents: ["Properties"],
  },
  extendedEdit: {
    yaml: "РасширенноеРедактирование",
    xml: "ExtendedEdit",
    type: "boolean",
    defaultValueXML: false,
    implicitValueYAML: false,
    xmlParents: ["Properties"],
  },
  minValue: {
    yaml: "МинимальноеЗначение",
    xml: "MinValue",
    type: "MinMaxValue",
    xmlParents: ["Properties"],
    typedXML: "xs:string",
    defaultValueXMLRaw: { "_xsi:nil": true },
  },
  maxValue: {
    yaml: "МаксимальноеЗначение",
    xml: "MaxValue",
    type: "MinMaxValue",
    xmlParents: ["Properties"],
    typedXML: "xs:string",
    defaultValueXMLRaw: { "_xsi:nil": true },
  },
  fillChecking: {
    yaml: "ПроверкаЗаполнения",
    xml: "FillChecking",
    type: "SystemEnumeration",
    typeSE: "FillChecking",
    defaultValueXML: "DontCheck",
    implicitValueYAML: "DontCheck",
    xmlParents: ["Properties"],
  },
  choiceFoldersAndItems: {
    yaml: "ВыборГруппИЭлементов",
    xml: "ChoiceFoldersAndItems",
    type: "SystemEnumeration",
    typeSE: "FoldersAndItemsUse",
    defaultValueXML: "Items",
    implicitValueYAML: "Items",
    xmlParents: ["Properties"],
  },
  choiceParameterLinks: {
    yaml: "СвязиПараметровВыбора",
    xml: "ChoiceParameterLinks",
    type: "ChoiceParameterLinks",
    xmlParents: ["Properties"],
    defaultValueXMLRaw: "",
  },
  choiceParameters: {
    yaml: "ПараметрыВыбора",
    xml: "ChoiceParameters",
    type: "ChoiceParameters",
    xmlParents: ["Properties"],
    defaultValueXMLRaw: "",
  },
  quickChoice: {
    yaml: "БыстрыйВыбор",
    xml: "QuickChoice",
    type: "SystemEnumeration",
    typeSE: "UseQuickChoice",
    defaultValueXML: "Auto",
    implicitValueYAML: "Auto",
    xmlParents: ["Properties"],
  },
  createOnInput: {
    yaml: "СозданиеПриВводе",
    xml: "CreateOnInput",
    type: "SystemEnumeration",
    typeSE: "CreateOnInput",
    defaultValueXML: "Auto",
    implicitValueYAML: "Auto",
    xmlParents: ["Properties"],
  },
  choiceForm: {
    yaml: "ФормаВыбора",
    xml: "ChoiceForm",
    type: "string",
    xmlParents: ["Properties"],
    defaultValueXMLRaw: "",
  },
  linkByType: {
    yaml: "СвязьПоТипу",
    xml: "LinkByType",
    type: "TypeLink",
    xmlParents: ["Properties"],
    defaultValueXMLRaw: "",
  },
  choiceHistoryOnInput: {
    yaml: "ИсторияВыбораПриВводе",
    xml: "ChoiceHistoryOnInput",
    type: "SystemEnumeration",
    typeSE: "ChoiceHistoryOnInput",
    defaultValueXML: "Auto",
    implicitValueYAML: "Auto",
    xmlParents: ["Properties"],
  },
  indexing: {
    yaml: "Индексирование",
    xml: "Indexing",
    type: "SystemEnumeration",
    typeSE: "Indexing",
    defaultValueXML: "DontIndex",
    implicitValueYAML: "DontIndex",
    xmlParents: ["Properties"],
  },
  fullTextSearch: {
    yaml: "ПолнотекстовыйПоиск",
    xml: "FullTextSearch",
    type: "SystemEnumeration",
    typeSE: "UseFullTextSearch",
    defaultValueXML: "Use",
    implicitValueYAML: "Use",
    xmlParents: ["Properties"],
  },
  dataHistory: {
    yaml: "ИсторияДанных",
    xml: "DataHistory",
    type: "SystemEnumeration",
    typeSE: "DataHistoryUse",
    defaultValueXML: "Use",
    implicitValueYAML: "Use",
    xmlParents: ["Properties"],
  },
  objectBelonging: {
    yaml: "ПринадлежностьОбъекта",
    xml: "ObjectBelonging",
    type: "SystemEnumeration",
    typeSE: "ObjectBelonging",
    implicitValueYAML: "Native",
    toYAML: false,
    fromYAML: false,
    xmlParents: ["Properties"],
  },
} as const satisfies Record<string, PropertyRule>
const fillProperties = {
  fillFromFillingValue: {
    yaml: "ЗаполнятьИзДанныхЗаполнения",
    xml: "FillFromFillingValue",
    type: "boolean",
    defaultValueXML: false,
    implicitValueYAML: false,
    xmlParents: ["Properties"],
  },
  fillValue: {
    yaml: "ЗначениеЗаполнения",
    xml: "FillValue",
    type: "MetadataValue",
    xmlParents: ["Properties"],
    defaultValueXMLRaw: { "_xsi:nil": true },
  },
} as const satisfies Record<string, PropertyRule>
const binaryDataStorageLocationUseFieldProperty = {
  binaryDataStorageLocationUseField: {
    yaml: "ПолеИспользованияХраненияВХранилищеДвоичныхДанных",
    xml: "BinaryDataStorageLocationUseField",
    type: "string",
    xmlParents: ["Properties"],
    metadataTarget: {
      kind: "member",
      owner: "this",
      memberKinds: ["Attribute"],
      filters: [{ kind: "directMember" }, { kind: "hasType", type: "boolean" }],
    },
  },
} as const satisfies Record<string, PropertyRule>
export const METADATA_ATTRIBUTE_ALLOWED_TYPES = [
  "string",
  "decimal",
  "date",
  "boolean",
  "ValueStorage",
  "UUID",
  "CatalogRef",
  "CatalogRef.*",
  "DocumentRef",
  "DocumentRef.*",
  "EnumRef",
  "EnumRef.*",
  "ChartOfCharacteristicTypesRef",
  "ChartOfCharacteristicTypesRef.*",
  "ChartOfAccountsRef",
  "ChartOfAccountsRef.*",
  "ChartOfCalculationTypesRef",
  "ChartOfCalculationTypesRef.*",
  "BusinessProcessRef",
  "BusinessProcessRef.*",
  "BusinessProcessRoutePointRef",
  "BusinessProcessRoutePointRef.*",
  "TaskRef",
  "TaskRef.*",
  "ExchangePlanRef",
  "ExchangePlanRef.*",
  "AnyIBRef",
  "DefinedType.*",
  "Characteristic.*",
  "ExternalDataSourceTableRef.*",
  "ExternalDataSourceCubeDimensionTableRef.*",
] as const
const attributeExternalMetadata = { segment: "Attribute", placement: "ownerChild" } as const
export const MetadataAttributeRules = {
  itemType: "MetadataAttribute",
  metadataTargetOwner: { kind: "inherit" },
  externalMetadata: attributeExternalMetadata,
  xmlOrder: [
    "objectBelonging",
    "name",
    "synonym",
    "comment",
    "type",
    "passwordMode",
    "format",
    "editFormat",
    "toolTip",
    "markNegatives",
    "mask",
    "multiLine",
    "extendedEdit",
    "minValue",
    "maxValue",
    "fillFromFillingValue",
    "fillValue",
    "fillChecking",
    "choiceFoldersAndItems",
    "choiceParameterLinks",
    "choiceParameters",
    "quickChoice",
    "createOnInput",
    "choiceForm",
    "linkByType",
    "choiceHistoryOnInput",
    "indexing",
    "fullTextSearch",
    "dataHistory",
    "binaryDataStorageLocationUseField",
    "uuid",
  ],
  properties: {
    ...commonAttributeProperties,
    ...fillProperties,
    use: systemEnumerationRule({
      yaml: "Использование",
      xml: "Use",
      typeSE: "AttributeUse",
      implicitValueYAML: "ForItem",
      xmlParents: ["Properties"],
    }),
    binaryDataStorageLocationUse: systemEnumerationRule({
      yaml: "ИспользованиеХраненияВХранилищеДвоичныхДанных",
      xml: "BinaryDataStorageLocationUse",
      typeSE: "BinaryDataStorageLocationUse",
      implicitValueYAML: "Use",
      xmlParents: ["Properties"],
    }),
    ...binaryDataStorageLocationUseFieldProperty,
  },
} as const satisfies MetadataItemRule
export const MetadataAttributesWithAllowedTypesRules = {
  ...MetadataAttributeRules,
  xmlOrder: [
    "objectBelonging",
    "name",
    "synonym",
    "comment",
    "type",
    "passwordMode",
    "format",
    "editFormat",
    "toolTip",
    "markNegatives",
    "mask",
    "multiLine",
    "extendedEdit",
    "minValue",
    "maxValue",
    "fillFromFillingValue",
    "fillValue",
    "fillChecking",
    "choiceFoldersAndItems",
    "choiceParameterLinks",
    "choiceParameters",
    "quickChoice",
    "createOnInput",
    "choiceForm",
    "linkByType",
    "choiceHistoryOnInput",
    "indexing",
    "use",
    "fullTextSearch",
    "dataHistory",
    "uuid",
  ],
  properties: {
    ...MetadataAttributeRules.properties,
    type: {
      ...commonAttributeProperties.type,
      allowedTypes: METADATA_ATTRIBUTE_ALLOWED_TYPES,
    },
    use: systemEnumerationRule({
      yaml: "Использование",
      xml: "Use",
      typeSE: "AttributeUse",
      defaultValueXML: "ForItem",
      implicitValueYAML: "ForItem",
      xmlParents: ["Properties"],
    }),
  },
} as const satisfies MetadataItemRule
export const MetadataCatalogAttributeRules = {
  itemType: "MetadataAttribute",
  metadataTargetOwner: { kind: "inherit" },
  externalMetadata: attributeExternalMetadata,
  xmlOrder: [
    "objectBelonging",
    "name",
    "synonym",
    "comment",
    "type",
    "passwordMode",
    "format",
    "editFormat",
    "toolTip",
    "markNegatives",
    "mask",
    "multiLine",
    "extendedEdit",
    "minValue",
    "maxValue",
    "fillFromFillingValue",
    "fillValue",
    "fillChecking",
    "choiceFoldersAndItems",
    "choiceParameterLinks",
    "choiceParameters",
    "quickChoice",
    "createOnInput",
    "choiceForm",
    "linkByType",
    "choiceHistoryOnInput",
    "use",
    "indexing",
    "fullTextSearch",
    "dataHistory",
    "binaryDataStorageLocationUse",
    "binaryDataStorageLocationUseField",
    "uuid",
  ],
  properties: {
    ...commonAttributeProperties,
    type: {
      ...commonAttributeProperties.type,
      allowedTypes: METADATA_ATTRIBUTE_ALLOWED_TYPES,
    },
    ...fillProperties,
    use: systemEnumerationRule({
      yaml: "Использование",
      xml: "Use",
      typeSE: "AttributeUse",
      defaultValueXML: "ForItem",
      implicitValueYAML: "ForItem",
      xmlParents: ["Properties"],
    }),
    binaryDataStorageLocationUse: systemEnumerationRule({
      yaml: "ИспользованиеХраненияВХранилищеДвоичныхДанных",
      xml: "BinaryDataStorageLocationUse",
      typeSE: "BinaryDataStorageLocationUse",
      implicitValueYAML: "Use",
      xmlParents: ["Properties"],
    }),
    ...binaryDataStorageLocationUseFieldProperty,
  },
} as const satisfies MetadataItemRule
export const MetadataDocumentAttributeRules = {
  itemType: "MetadataAttribute",
  metadataTargetOwner: { kind: "inherit" },
  externalMetadata: attributeExternalMetadata,
  xmlOrder: [
    "objectBelonging",
    "name",
    "synonym",
    "comment",
    "type",
    "passwordMode",
    "format",
    "editFormat",
    "toolTip",
    "markNegatives",
    "mask",
    "multiLine",
    "extendedEdit",
    "minValue",
    "maxValue",
    "fillFromFillingValue",
    "fillValue",
    "fillChecking",
    "choiceFoldersAndItems",
    "choiceParameterLinks",
    "choiceParameters",
    "quickChoice",
    "createOnInput",
    "choiceForm",
    "linkByType",
    "choiceHistoryOnInput",
    "indexing",
    "fullTextSearch",
    "dataHistory",
    "binaryDataStorageLocationUseField",
    "uuid",
  ],
  properties: {
    ...commonAttributeProperties,
    type: {
      ...commonAttributeProperties.type,
      allowedTypes: METADATA_ATTRIBUTE_ALLOWED_TYPES,
    },
    ...fillProperties,
    ...binaryDataStorageLocationUseFieldProperty,
  },
} as const satisfies MetadataItemRule
export const MetadataTabularSectionAttributeRules = {
  itemType: "MetadataAttribute",
  metadataTargetOwner: { kind: "inherit" },
  externalMetadata: attributeExternalMetadata,
  xmlOrder: [
    "objectBelonging",
    "name",
    "synonym",
    "comment",
    "type",
    "passwordMode",
    "format",
    "editFormat",
    "toolTip",
    "markNegatives",
    "mask",
    "multiLine",
    "extendedEdit",
    "minValue",
    "maxValue",
    "fillFromFillingValue",
    "fillValue",
    "fillChecking",
    "choiceFoldersAndItems",
    "choiceParameterLinks",
    "choiceParameters",
    "quickChoice",
    "createOnInput",
    "choiceForm",
    "linkByType",
    "choiceHistoryOnInput",
    "indexing",
    "fullTextSearch",
    "dataHistory",
    "uuid",
  ],
  properties: {
    ...commonAttributeProperties,
    type: {
      ...commonAttributeProperties.type,
      allowedTypes: METADATA_ATTRIBUTE_ALLOWED_TYPES,
    },
    ...fillProperties,
  },
} as const satisfies MetadataItemRule
