import { borderRule } from "../../../commonObjects/border/types"
import { colorRule } from "../../../commonObjects/color/types"
import { fontRule } from "../../../commonObjects/font/types"
import { dataPathRule } from "../../../commonObjects/metadataPath/types"
import { eventsRule } from "../../commonObjects/event/types"
import { booleanRule } from "../../../commonObjects/boolean/types"
import { i8nTextRule } from "../../../commonObjects/i8nText/types"
import { numberRule } from "../../../commonObjects/number/types"
import { registerElementRule } from "../../../ruleRuntime/formElement/ruleFactory"
import type { DataPathAllowedKind, PropertyRule } from "../../../ruleRuntime/property/types"
import { ElementRule } from "../../../ruleRuntime/formElement/types"
import { formFieldCommonProperties, formFieldTableRelatedProperties } from "../formField/rules"
import { registerExplicitHeaderHorizontalAlign } from "../formField/explicitHeaderHorizontalAlign"
export type { ElementRule, PropertyRule }
const labelFieldDataPathKinds = [
  "string", "decimal", "boolean", "dateTime", "UUID", "Null", "<any>",
  "Picture", "FormattedString", "ValueStorage", "TypeDescription",
  "ValueTable", "ValueTree", "ValueListType", "StandardPeriod",
  "DocumentRef.*", "CatalogRef.*", "EnumRef.*", "TaskRef.*",
  "BusinessProcessRef.*", "ExchangePlanRef.*", "ChartOfAccountsRef.*",
  "ChartOfCharacteristicTypesRef.*", "ChartOfCalculationTypesRef.*",
  "AccumulationRegisterRef.*", "AccountingRegisterRef.*", "InformationRegisterRef.*",
  "CalculationRegisterRef.*", "Characteristic.*", "DefinedType.*",
  "DocumentRef", "CatalogRef", "EnumRef", "TaskRef", "BusinessProcessRef",
  "ExchangePlanRef", "ChartOfAccountsRef", "ChartOfCharacteristicTypesRef",
  "ChartOfCalculationTypesRef", "BusinessProcessRoutePointRef", "AnyIBRef",
  "<standard-enum>", "DataCompositionSortDirection",
] as const satisfies readonly DataPathAllowedKind[]
export const LabelFieldRules = {
  itemType: "LabelField",
  enterpriseField: "FormField",
  enterpriseFieldType: "FormFieldType.LabelField",
  xmlOrder: [
    "dataPath",
    "visible",
    "userVisible",
    "defaultItem",
    "enabled",
    "readOnly",
    "skipOnInput",
    "title",
    "titleTextColor",
    "titleBackColor",
    "titleFont",
    "titleLocation",
    "titleHeight",
    "toolTip",
    "toolTipRepresentation",
    "warningOnEditRepresentation",
    "warningOnEdit",
    "shortcut",
    "horizontalAlign",
    "verticalAlign",
    "horizontalAlignInGroup",
    "verticalAlignInGroup",
    "editMode",
    "cellHyperlink",
    "showInHeader",
    "headerPicture",
    "showInFooter",
    "footerDataPath",
    "footerText",
    "footerTextColor",
    "footerBackColor",
    "footerFont",
    "footerPicture",
    "footerHorizontalAlign",
    "onMainServerUnavalableBehavior",
    "width",
    "autoMaxWidth",
    "maxWidth",
    "height",
    "autoMaxHeight",
    "maxHeight",
    "horizontalStretch",
    "verticalStretch",
    "markNegatives",
    "format",
    "hyperlink",
    "passwordMode",
    "border",
    "borderColor",
    "textColor",
    "backColor",
    "font",
    "contextMenu",
    "extendedTooltip",
    "events",
    "name",
    "displayImportance",
  ],
  properties: {
    autoMaxHeight: booleanRule({ yaml: "АвтоМаксимальнаяВысота", implicitValueYAML: true }),
    autoMaxWidth: booleanRule({ yaml: "АвтоМаксимальнаяШирина", implicitValueYAML: true }),
    backColor: colorRule({
      yaml: "ЦветФона",
      metadataTarget: { kind: "object", roots: ["StyleItem"], filters: [{ kind: "styleItemType", values: ["Color"] }] },
    }),
    border: borderRule({
      yaml: "Рамка",
      implicitValueYAML: "WithoutBorder",
      metadataTarget: {
        kind: "object",
        roots: ["StyleItem"],
        filters: [{ kind: "styleItemType", values: ["Border"] }],
      },
    }),
    borderColor: colorRule({
      yaml: "ЦветРамки",
      metadataTarget: { kind: "object", roots: ["StyleItem"], filters: [{ kind: "styleItemType", values: ["Color"] }] },
    }),
    font: fontRule({
      yaml: "Шрифт",
      metadataTarget: { kind: "object", roots: ["StyleItem"], filters: [{ kind: "styleItemType", values: ["Font"] }] },
    }),
    format: i8nTextRule({ yaml: "Формат" }),
    height: numberRule({ yaml: "Высота", implicitValueYAML: 0 }),
    horizontalStretch: booleanRule({ yaml: "РастягиватьПоГоризонтали", noImplicitValueYAML: true }),
    hyperlink: booleanRule({ yaml: "Гиперссылка", xml: "Hiperlink", implicitValueYAML: false }),
    markNegatives: booleanRule({ yaml: "ВыделятьОтрицательные", noImplicitValueYAML: true }),
    maxHeight: numberRule({ yaml: "МаксимальнаяВысота", implicitValueYAML: 0 }),
    maxWidth: numberRule({ yaml: "МаксимальнаяШирина", implicitValueYAML: 0 }),
    passwordMode: booleanRule({ yaml: "РежимПароля", noImplicitValueYAML: true }),
    textColor: colorRule({
      yaml: "ЦветТекста",
      metadataTarget: { kind: "object", roots: ["StyleItem"], filters: [{ kind: "styleItemType", values: ["Color"] }] },
    }),
    verticalStretch: booleanRule({ yaml: "РастягиватьПоВертикали", noImplicitValueYAML: true }),
    width: numberRule({ yaml: "Ширина", implicitValueYAML: 0 }),
    events: eventsRule({
      yaml: "События",
      toEnterprise: false,
      items: {
        onChange: "ПриИзменении",
        click: "Нажатие",
        uRLProcessing: "ОбработкаНавигационнойСсылки",
      },
    }),
    dataPath: dataPathRule({
      yaml: "ПутьКДанным",
      defaultType: "string",
      allowedKinds: labelFieldDataPathKinds,
      allowComposite: true,
    }),
    ...formFieldCommonProperties,
    titleHeight: numberRule({ yaml: "ВысотаЗаголовка", implicitValueYAML: 0 }),
  },
} as const satisfies ElementRule
export const TableLabelFieldRules = {
  itemType: "TableLabelField",
  xmlTag: "LabelField",
  enterpriseField: "FormField",
  enterpriseFieldType: "FormFieldType.LabelField",
  xmlOrder: [
    "dataPath",
    "visible",
    "userVisible",
    "defaultItem",
    "enabled",
    "readOnly",
    "skipOnInput",
    "title",
    "titleTextColor",
    "titleBackColor",
    "titleFont",
    "titleLocation",
    "titleHeight",
    "toolTip",
    "toolTipRepresentation",
    "warningOnEditRepresentation",
    "warningOnEdit",
    "shortcut",
    "horizontalAlign",
    "verticalAlign",
    "editMode",
    "fixingInTable",
    "cellHyperlink",
    "autoCellHeight",
    "showInHeader",
    "headerPicture",
    "headerHorizontalAlign",
    "showInFooter",
    "footerDataPath",
    "footerText",
    "footerTextColor",
    "footerBackColor",
    "footerFont",
    "footerPicture",
    "footerHorizontalAlign",
    "width",
    "onMainServerUnavalableBehavior",
    "autoMaxWidth",
    "maxWidth",
    "height",
    "autoMaxHeight",
    "maxHeight",
    "horizontalStretch",
    "markNegatives",
    "verticalStretch",
    "format",
    "hyperlink",
    "passwordMode",
    "border",
    "borderColor",
    "textColor",
    "backColor",
    "font",
    "contextMenu",
    "extendedTooltip",
    "events",
    "name",
    "displayImportance",
  ],
  properties: {
    ...LabelFieldRules.properties,
    ...formFieldTableRelatedProperties,
  },
} as const satisfies ElementRule
registerExplicitHeaderHorizontalAlign(TableLabelFieldRules.itemType)
registerElementRule("LabelField", LabelFieldRules)
registerElementRule("TableLabelField", TableLabelFieldRules)
