import { uuidPropertyRule } from "~/metadata/commonObjects/uuid/rule"
import { MetadataItemRule, PropertyRule } from "~/metadata/orchestration/property/types"

const propertiesParents = ["Properties"]

export const externalDataSourceFieldBaseProperties = {
  uuid: uuidPropertyRule,
  name: {
    xml: "Name",
    type: "string",
    required: true,
    xmlParents: propertiesParents,
  },
  synonym: {
    yaml: "Синоним",
    xml: "Synonym",
    type: "I8nText",
    xmlParents: propertiesParents,
    defaultValueXMLRaw: "",
  },
  comment: {
    yaml: "Комментарий",
    xml: "Comment",
    type: "string",
    xmlParents: propertiesParents,
    defaultValueXMLRaw: "",
  },
  type: {
    yaml: "Тип",
    xml: "Type",
    type: "TypeDescription",
    required: true,
    xmlParents: propertiesParents,
  },
  passwordMode: {
    yaml: "РежимПароля",
    xml: "PasswordMode",
    type: "boolean",
    xmlParents: propertiesParents,
    defaultValueXML: false,
    implicitValueYAML: false,
  },
  format: {
    yaml: "Формат",
    xml: "Format",
    type: "I8nText",
    xmlParents: propertiesParents,
    defaultValueXMLRaw: "",
  },
  editFormat: {
    yaml: "ФорматРедактирования",
    xml: "EditFormat",
    type: "I8nText",
    xmlParents: propertiesParents,
    defaultValueXMLRaw: "",
  },
  toolTip: {
    yaml: "Подсказка",
    xml: "ToolTip",
    type: "I8nText",
    xmlParents: propertiesParents,
    defaultValueXMLRaw: "",
  },
  markNegatives: {
    yaml: "ВыделятьОтрицательные",
    xml: "MarkNegatives",
    type: "boolean",
    xmlParents: propertiesParents,
    defaultValueXML: false,
    implicitValueYAML: false,
  },
  mask: {
    yaml: "Маска",
    xml: "Mask",
    type: "string",
    xmlParents: propertiesParents,
    defaultValueXMLRaw: "",
  },
  multiLine: {
    yaml: "МногострочныйРежим",
    xml: "MultiLine",
    type: "boolean",
    xmlParents: propertiesParents,
    defaultValueXML: false,
    implicitValueYAML: false,
  },
  extendedEdit: {
    yaml: "РасширенноеРедактирование",
    xml: "ExtendedEdit",
    type: "boolean",
    xmlParents: propertiesParents,
    defaultValueXML: false,
    implicitValueYAML: false,
  },
  minValue: {
    yaml: "МинимальноеЗначение",
    xml: "MinValue",
    type: "MinMaxValue",
    xmlParents: propertiesParents,
    typedXML: "xs:string",
    defaultValueXMLRaw: { "_xsi:nil": true },
  },
  maxValue: {
    yaml: "МаксимальноеЗначение",
    xml: "MaxValue",
    type: "MinMaxValue",
    xmlParents: propertiesParents,
    typedXML: "xs:string",
    defaultValueXMLRaw: { "_xsi:nil": true },
  },
  fillFromFillingValue: {
    yaml: "ЗаполнятьИзДанныхЗаполнения",
    xml: "FillFromFillingValue",
    type: "boolean",
    xmlParents: propertiesParents,
    defaultValueXML: false,
    implicitValueYAML: false,
  },
  fillValue: {
    yaml: "ЗначениеЗаполнения",
    xml: "FillValue",
    type: "MetadataValue",
    xmlParents: propertiesParents,
    defaultValueXMLRaw: { "_xsi:nil": true },
  },
  fillChecking: {
    yaml: "ПроверкаЗаполнения",
    xml: "FillChecking",
    type: "SystemEnumeration",
    typeSE: "FillChecking",
    xmlParents: propertiesParents,
    defaultValueXML: "DontCheck",
    implicitValueYAML: "DontCheck",
  },
  choiceParameterLinks: {
    yaml: "СвязиПараметровВыбора",
    xml: "ChoiceParameterLinks",
    type: "ChoiceParameterLinks",
    xmlParents: propertiesParents,
    defaultValueXMLRaw: "",
  },
  choiceParameters: {
    yaml: "ПараметрыВыбора",
    xml: "ChoiceParameters",
    type: "ChoiceParameters",
    xmlParents: propertiesParents,
    defaultValueXMLRaw: "",
  },
  quickChoice: {
    yaml: "БыстрыйВыбор",
    xml: "QuickChoice",
    type: "SystemEnumeration",
    typeSE: "UseQuickChoice",
    xmlParents: propertiesParents,
    defaultValueXML: "Auto",
    implicitValueYAML: "Auto",
  },
  createOnInput: {
    yaml: "СозданиеПриВводе",
    xml: "CreateOnInput",
    type: "SystemEnumeration",
    typeSE: "CreateOnInput",
    xmlParents: propertiesParents,
    defaultValueXML: "Auto",
    implicitValueYAML: "Auto",
  },
  choiceHistoryOnInput: {
    yaml: "ИсторияВыбораПриВводе",
    xml: "ChoiceHistoryOnInput",
    type: "SystemEnumeration",
    typeSE: "ChoiceHistoryOnInput",
    xmlParents: propertiesParents,
    defaultValueXML: "Auto",
    implicitValueYAML: "Auto",
  },
  choiceForm: {
    yaml: "ФормаВыбора",
    xml: "ChoiceForm",
    type: "string",
    xmlParents: propertiesParents,
    defaultValueXMLRaw: "",
  },
} as const satisfies Record<string, PropertyRule>

const externalDataSourceServiceProperties = {
  objectBelonging: {
    yaml: "ПринадлежностьОбъекта",
    xml: "ObjectBelonging",
    type: "SystemEnumeration",
    typeSE: "ObjectBelonging",
    xmlParents: propertiesParents,
    implicitValueYAML: "Native",
    toYAML: false,
    fromYAML: false,
  },
  extendedConfigurationObject: {
    xml: "ExtendedConfigurationObject",
    type: "string",
    xmlParents: propertiesParents,
    runtimeOnly: true,
  },
} as const satisfies Record<string, PropertyRule>

export const externalDataSourceObjectServiceProperties = externalDataSourceServiceProperties

export const MetadataExternalDataSourceFieldRules = {
  itemType: "MetadataExternalDataSourceField",
  properties: {
    ...externalDataSourceFieldBaseProperties,
    nameInDataSource: {
      yaml: "ИмяВИсточникеДанных",
      xml: "NameInDataSource",
      type: "string",
      xmlParents: propertiesParents,
    },
    readOnly: {
      yaml: "ТолькоЧтение",
      xml: "ReadOnly",
      type: "boolean",
      xmlParents: propertiesParents,
      defaultValueXML: false,
      implicitValueYAML: false,
    },
    allowNull: {
      yaml: "РазрешитьNull",
      xml: "AllowNull",
      type: "boolean",
      xmlParents: propertiesParents,
      defaultValueXML: true,
      implicitValueYAML: true,
    },
    ...externalDataSourceServiceProperties,
  },
} as const satisfies MetadataItemRule
