import { stringRule } from "../string/types"
import {
  METADATA_ATTRIBUTE_ALLOWED_TYPES,
  attributeChoiceFragment,
  attributeFillFragment,
  attributeIdentityFragment,
  attributePresentationFragment,
  attributeSearchAndHistoryFragment,
  attributeUuidFragment,
} from "../metadataAttribute/fragments"
import type { MetadataItemRule } from "@nkdk/runtime/rule-kit"
export const MetadataTaskAddressingAttributeRules = {
  itemType: "MetadataAttribute",
  externalMetadata: { segment: "AddressingAttribute", placement: "ownerChild" },
  xmlOrder: [
    "objectBelonging",
    "name",
    "synonym",
    "comment",
    "type",
    "passwordMode",
    "format",
    "editFormat",
    "toolTip",
    "markNegatives",
    "mask",
    "multiLine",
    "extendedEdit",
    "minValue",
    "maxValue",
    "fillFromFillingValue",
    "fillValue",
    "fillChecking",
    "choiceFoldersAndItems",
    "choiceParameterLinks",
    "choiceParameters",
    "quickChoice",
    "createOnInput",
    "choiceForm",
    "linkByType",
    "choiceHistoryOnInput",
    "indexing",
    "addressingDimension",
    "fullTextSearch",
    "dataHistory",
    "uuid",
  ],
  properties: {
    ...attributeIdentityFragment.properties,
    ...attributePresentationFragment({ allowedTypes: METADATA_ATTRIBUTE_ALLOWED_TYPES }).properties,
    ...attributeFillFragment.properties,
    ...attributeChoiceFragment.properties,
    ...attributeSearchAndHistoryFragment.properties,
    ...attributeUuidFragment.properties,
    addressingDimension: stringRule({
      yaml: "ИзмерениеАдресации",
      xml: "AddressingDimension",
      xmlParents: ["Properties"],
      defaultValueXMLRaw: "",
    }),
  },
} as const satisfies MetadataItemRule
