import { MetadataItemRule, PropertyRule } from "~/metadata/orchestration"
import { ElementRule } from "../../orchestration/formElement/types"
import { FormRulesTags } from "./types"
export type { ElementRule, PropertyRule }

export const ClientApplicationFormRules = {
  itemType: "ClientApplicationForm",
  properties: {
    // #region Form

    itemPictures: {
      type: "ExternalFormItemFile",
      xml: "Picture",
      yaml: "Картинки",
      syncExternalOnly: true,
    },
    itemHeaderPictures: {
      type: "ExternalFormItemFile",
      xml: "HeaderPicture",
      yaml: "КартинкиШапки",
      syncExternalOnly: true,
    },
    itemValuesPictures: {
      type: "ExternalFormItemFile",
      xml: "ValuesPicture",
      yaml: "КартинкиЗначений",
      syncExternalOnly: true,
    },
    itemRowsPictures: {
      type: "ExternalFormItemFile",
      xml: "RowsPicture",
      yaml: "КартинкиСтрок",
      syncExternalOnly: true,
    },
    autoCommandBar: {
      yaml: "КоманднаяПанель",
      type: "AutoCommandBar",
      tag: FormRulesTags.Form,
      order: 1,
    },
    autoFillCheck: {
      yaml: "ПроверятьЗаполнениеАвтоматически",
      type: "boolean",
      tag: FormRulesTags.Form,
      implicitValueYAML: true,
    },
    autoSaveDataInSettings: {
      yaml: "АвтоматическоеСохранениеДанныхВНастройках",
      type: "SystemEnumeration",
      typeSE: "AutoSaveFormDataInSettings",
      tag: FormRulesTags.Form,
      implicitValueYAML: "DontUse",
    },
    autoTitle: {
      yaml: "АвтоЗаголовок",
      type: "boolean",
      tag: FormRulesTags.Form,
      implicitValueYAML: true,
    },
    autoURL: {
      yaml: "АвтоНавигационнаяСсылка",
      type: "boolean",
      tag: FormRulesTags.Form,
      implicitValueYAML: true,
    },
    childItems: {
      yaml: "Элементы",
      type: "GroupChildItems",
      tag: FormRulesTags.Form,
      defaultValue: [],
      order: 2,
    },
    attributes: {
      yaml: "Реквизиты",
      type: "FormAttributes",
      tag: FormRulesTags.Form,
      defaultValueXMLEmpty: [],
      order: 3,
    },
    attributesConditionalAppearance: {
      yaml: "УсловноеОформлениеРеквизитов",
      type: "ConditionalAppearance",
      xml: "ConditionalAppearance",
      xmlParents: ["Attributes"],
      tag: FormRulesTags.Form,
    },
    childItemsHorizontalAlign: {
      yaml: "ГоризонтальноеПоложениеПодчиненных",
      xml: "HorizontalAlign",
      xmlAliases: ["ChildItemsHorizontalAlign"],
      type: "SystemEnumeration",
      typeSE: "ItemHorizontalLocation",
      tag: FormRulesTags.Form,
      implicitValueYAML: "Auto",
    },
    childItemsVerticalAlign: {
      yaml: "ВертикальноеПоложениеПодчиненных",
      xml: "VerticalAlign",
      xmlAliases: ["ChildItemsVerticalAlign"],
      type: "SystemEnumeration",
      typeSE: "ItemVerticalAlign",
      tag: FormRulesTags.Form,
      implicitValueYAML: "Auto",
    },
    closeOnChoice: {
      yaml: "ЗакрыватьПриВыборе",
      type: "boolean",
      tag: FormRulesTags.Form,
      noImplicitValueYAML: true,
    },
    closeOnOwnerClose: {
      yaml: "ЗакрыватьПриЗакрытииВладельца",
      type: "boolean",
      tag: FormRulesTags.Form,
      noImplicitValueYAML: true,
    },
    collapseItemsByImportance: {
      yaml: "СворачиваниеЭлементовПоВажности",
      xml: "CollapseItemsByImportanceVariant",
      xmlAliases: ["CollapseItemsByImportance"],
      type: "SystemEnumeration",
      typeSE: "CollapseFormItemsByImportance",
      tag: FormRulesTags.Form,
      implicitValueYAML: "Auto",
    },
    commandBarLocation: {
      yaml: "ПоложениеКоманднойПанели",
      type: "SystemEnumeration",
      typeSE: "FormCommandBarLabelLocation",
      tag: FormRulesTags.Form,
      implicitValueYAML: "Auto",
    },
    commandInterface: {
      yaml: "ИнтерфейсКоманды",
      type: "CommandInterface",
      tag: FormRulesTags.Form,
    },
    commandSet: {
      yaml: "СоставКоманд",
      type: "CommandSet",
      tag: FormRulesTags.Form,
    },
    reportResult: {
      yaml: "РезультатОтчета",
      xml: "ReportResult",
      type: "StringOrNumber",
      tag: FormRulesTags.Form,
    },
    detailsData: {
      yaml: "ДанныеРасшифровки",
      xml: "DetailsData",
      type: "StringOrNumber",
      tag: FormRulesTags.Form,
    },
    reportFormType: {
      yaml: "ТипФормыОтчета",
      xml: "ReportFormType",
      type: "SystemEnumeration",
      typeSE: "ReportFormType",
      tag: FormRulesTags.Form,
      noImplicitValueYAML: true,
    },
    variantAppearance: {
      yaml: "ПредставлениеВарианта",
      xml: "VariantAppearance",
      type: "string",
      tag: FormRulesTags.Form,
    },
    autoShowState: {
      yaml: "АвтоОтображениеСостояния",
      xml: "AutoShowState",
      type: "SystemEnumeration",
      typeSE: "AutoShowStateMode",
      tag: FormRulesTags.Form,
      implicitValueYAML: "Auto",
      omitImplicitValueYAMLBySource: true,
    },
    customSettingsFolder: {
      yaml: "ГруппаПользовательскихНастроек",
      xml: "CustomSettingsFolder",
      type: "string",
      tag: FormRulesTags.Form,
    },
    reportResultViewMode: {
      yaml: "РежимОтображенияРезультатаОтчета",
      xml: "ReportResultViewMode",
      type: "SystemEnumeration",
      typeSE: "ReportResultViewMode",
      tag: FormRulesTags.Form,
      implicitValueYAML: "Auto",
      omitImplicitValueYAMLBySource: true,
    },
    viewModeApplicationOnSetReportResult: {
      yaml: "ПрименениеРежимаОтображенияПриУстановкеРезультатаОтчета",
      xml: "ViewModeApplicationOnSetReportResult",
      type: "SystemEnumeration",
      typeSE: "ViewModeApplicationOnSetReportResult",
      tag: FormRulesTags.Form,
      implicitValueYAML: "Auto",
      omitImplicitValueYAMLBySource: true,
    },
    mobileDeviceCommandBarContent: {
      yaml: "СоставКоманднойПанелиНаМобильномУстройстве",
      type: "MobileDeviceCommandBarContent",
      tag: FormRulesTags.Form,
    },
    commands: {
      yaml: "Команды",
      type: "FormCommands",
      tag: FormRulesTags.Form,
      defaultValue: [],
    },
    conversationsRepresentation: {
      yaml: "ОтображениеОбсуждений",
      type: "SystemEnumeration",
      typeSE: "FormConversationsRepresentation",
      tag: FormRulesTags.Form,
      implicitValueYAML: "Auto",
    },
    customizable: {
      yaml: "РазрешитьИзменятьФорму",
      type: "boolean",
      tag: FormRulesTags.Form,
      implicitValueYAML: true,
    },
    enabled: {
      yaml: "Доступность",
      type: "boolean",
      tag: FormRulesTags.Form,
      implicitValueYAML: true,
    },
    enterKeyBehavior: {
      yaml: "ПоведениеКлавишиEnter",
      type: "SystemEnumeration",
      typeSE: "EnterKeyBehaviorType",
      tag: FormRulesTags.Form,
      implicitValueYAML: "ControlNavigation",
    },
    formWindowOpeningMode: {
      yaml: "РежимОткрытияОкнаФормы",
      type: "SystemEnumeration",
      typeSE: "FormWindowOpeningMode",
      xml: "WindowOpeningMode",
      tag: FormRulesTags.Form,
      implicitValueYAML: "DontBlock",
    },
    group: {
      yaml: "Группировка",
      type: "SystemEnumeration",
      typeSE: "ChildFormItemsGroup",
      tag: FormRulesTags.Form,
      implicitValueYAML: "Vertical",
    },
    groupList: {
      yaml: "СписокГрупп",
      xml: "GroupList",
      type: "string",
      tag: FormRulesTags.Form,
    },
    height: {
      yaml: "Высота",
      type: "number",
      tag: FormRulesTags.Form,
      implicitValueYAML: 0,
    },
    horizontalSpacing: {
      yaml: "ГоризонтальныйИнтервал",
      type: "SystemEnumeration",
      typeSE: "FormItemSpacing",
      tag: FormRulesTags.Form,
      implicitValueYAML: "Auto",
    },
    itemsAndTitlesAlign: {
      yaml: "ВыравниваниеЭлементовИЗаголовков",
      xml: "ChildrenAlign",
      xmlAliases: ["ItemsAndTitlesAlign"],
      type: "SystemEnumeration",
      typeSE: "ItemsAndTitlesAlignVariant",
      tag: FormRulesTags.Form,
      implicitValueYAML: "Auto",
    },
    modalMode: {
      yaml: "МодальныйРежим",
      type: "boolean",
      tag: FormRulesTags.Form,
      noImplicitValueYAML: true,
    },
    modified: {
      yaml: "Модифицированность",
      type: "boolean",
      tag: FormRulesTags.Form,
      noImplicitValueYAML: true,
    },
    parameters: {
      yaml: "Параметры",
      type: "FormParameters",
      tag: FormRulesTags.Form,
    },
    purposeUseKey: {
      yaml: "КлючНазначенияИспользования",
      type: "string",
      tag: FormRulesTags.Form,
    },
    readOnly: {
      yaml: "ТолькоПросмотр",
      type: "boolean",
      tag: FormRulesTags.Form,
      noImplicitValueYAML: true,
    },
    saveDataInSettings: {
      yaml: "СохранениеДанныхВНастройках",
      type: "SystemEnumeration",
      typeSE: "SaveFormDataInSettings",
      tag: FormRulesTags.Form,
      implicitValueYAML: "DontUse",
    },
    savedInSettingsDataModified: {
      yaml: "СохраняемыеВНастройкахДанныеМодифицированы",
      type: "boolean",
      tag: FormRulesTags.Form,
      noImplicitValueYAML: true,
    },
    scale: {
      yaml: "Масштаб",
      type: "number",
      tag: FormRulesTags.Form,
      implicitValueYAML: 100,
    },
    saveWindowSettings: {
      yaml: "СохранятьНастройкиОкна",
      type: "boolean",
      tag: FormRulesTags.Form,
      implicitValueYAML: true,
    },
    settingsStorage: {
      yaml: "ХранилищеНастроек",
      type: "MetadataItemLink",
      metadataTarget: {
        kind: "member",
        owner: "this",
        memberKinds: ["Form"],
        objectRoots: ["SettingsStorage"],
        allowedMemberPaths: [["Report", "Form"]],
      },
      tag: FormRulesTags.Form,
    },
    showCloseButton: {
      yaml: "ОтображатьКнопкуЗакрытия",
      type: "boolean",
      tag: FormRulesTags.Form,
      implicitValueYAML: true,
    },
    showTitle: {
      yaml: "ОтображатьЗаголовок",
      type: "boolean",
      tag: FormRulesTags.Form,
      implicitValueYAML: true,
    },
    slaveItemsWidth: {
      yaml: "ШиринаПодчиненныхЭлементов",
      xml: "ChildItemsWidth",
      xmlAliases: ["SlaveItemsWidth"],
      type: "SystemEnumeration",
      typeSE: "ChildFormItemsWidth",
      tag: FormRulesTags.Form,
      implicitValueYAML: "Auto",
    },
    title: {
      yaml: "Заголовок",
      type: "I8nText",
      tag: FormRulesTags.Form,
    },
    usedFormServer: {
      yaml: "ИспользуемыйСерверФормы",
      type: "SystemEnumeration",
      typeSE: "UsedServer",
      tag: FormRulesTags.Form,
      implicitValueYAML: "Main",
    },
    verticalScroll: {
      yaml: "ВертикальнаяПрокрутка",
      type: "SystemEnumeration",
      typeSE: "VerticalFormScroll",
      tag: FormRulesTags.Form,
      implicitValueYAML: "auto",
    },
    scalingMode: {
      yaml: "ВариантМасштаба",
      xml: "ScalingMode",
      type: "SystemEnumeration",
      typeSE: "ClientApplicationFormScaleVariant",
      tag: FormRulesTags.Form,
      implicitValueYAML: "Auto",
    },
    verticalSpacing: {
      yaml: "ВертикальныйИнтервал",
      type: "SystemEnumeration",
      typeSE: "FormItemSpacing",
      tag: FormRulesTags.Form,
      implicitValueYAML: "Auto",
    },
    width: {
      yaml: "Ширина",
      type: "number",
      tag: FormRulesTags.Form,
      implicitValueYAML: 0,
    },
    windowOptionsKey: {
      yaml: "КлючСохраненияПоложенияОкна",
      type: "string",
      tag: FormRulesTags.Form,
    },
    // #endregion
    // #region Metadata
    uuid: {
      type: "string",
      xml: "_uuid",
      forReferenceOnly: true,
      tag: FormRulesTags.Metadata,
      xmlParents: ["Form"],
    },
    name: {
      type: "string",
      tag: FormRulesTags.Metadata,
      fromXML: false,
      xmlParents: ["Form", "Properties"],
    },
    formType: {
      type: "SystemEnumeration",
      typeSE: "FormType",
      tag: FormRulesTags.Metadata,
      defaultValueXML: "Managed",
      xml: "FormType",
      xmlParents: ["Form", "Properties"],
      implicitValueYAML: "Managed",
    },
    synonym: {
      yaml: "Синоним",
      type: "I8nText",
      tag: FormRulesTags.Metadata,
      xmlParents: ["Form", "Properties"],
      defaultValueXMLEmpty: { items: {} },
    },
    comment: {
      yaml: "Комментарий",
      type: "string",
      tag: FormRulesTags.Metadata,
      xmlParents: ["Form", "Properties"],
      defaultValueXMLEmpty: "",
      implicitValueYAML: "",
    },
    includeHelpInContents: {
      yaml: "ВключатьСправкуВСодержание",
      type: "boolean",
      tag: FormRulesTags.Metadata,
      xmlParents: ["Form", "Properties"],
      defaultValueXMLEmpty: false,
      implicitValueYAML: "Ложь",
    },
    usePurposes: {
      yaml: "НазначенияИспользования",
      type: "UsePurposes",
      tag: FormRulesTags.Metadata,
      xmlParents: ["Form", "Properties"],
    },
    extendedPresentation: {
      yaml: "РасширенноеПредставление",
      type: "I8nText",
      tag: FormRulesTags.Metadata,
      xml: "ExtendedPresentation",
      xmlParents: ["Form", "Properties"],
      defaultValueXMLEmpty: { items: {} },
      defaultValueXMLRaw: "",
      preserveFromReferenceXML: true,
    },
    // #endregion

    // #region Catalog

    choiceAvailable: {
      yaml: "ВыборДоступен",
      type: "boolean",
      tag: FormRulesTags.Form,
      noImplicitValueYAML: true,
    },
    useForFoldersAndItems: {
      yaml: "ИспользованиеДляГруппИЭлементов",
      type: "SystemEnumeration",
      typeSE: "FoldersAndItemsUse",
      tag: FormRulesTags.Form,
      implicitValueYAML: "Items",
    },
    choiceParameters: {
      yaml: "ПараметрыВыбора",
      type: "ChoiceParameters",
      tag: FormRulesTags.Form,
    },
    choiceMode: {
      yaml: "РежимВыбора",
      type: "SystemEnumeration",
      typeSE: "ChoiceMode",
      tag: FormRulesTags.Form,
      noImplicitValueYAML: true,
    },
    // #endregion

    // #region Document
    autoTime: {
      yaml: "АвтоВремя",
      type: "SystemEnumeration",
      typeSE: "AutoTimeMode",
      tag: FormRulesTags.Form,
      implicitValueYAML: "CurrentOrLast",
    },
    usePostingMode: {
      yaml: "РежимПроведения",
      xml: "UsePostingMode",
      type: "SystemEnumeration",
      typeSE: "DocumentPostingMode",
      tag: FormRulesTags.Form,
      implicitValueYAML: "Auto",
    },
    repostOnWrite: {
      yaml: "ПерепроводитьПриЗаписи",
      type: "boolean",
      tag: FormRulesTags.Form,
      implicitValueYAML: true,
    },
    // #endregion

    events: {
      type: "Events",
      yaml: "События",
      tag: FormRulesTags.Form,
      items: {
        collaborationSystemUsersAutoComplete: "АвтоПодборПользователейСистемыВзаимодействия",
        externalEvent: "ВнешнееСобытие",
        activationProcessing: "ОбработкаАктивизации",
        choiceProcessing: "ОбработкаВыбора",
        newWriteProcessing: "ОбработкаЗаписиНового",
        uRLProcessing: "ОбработкаНавигационнойСсылки",
        notificationProcessing: "ОбработкаОповещения",
        navigationProcessing: "ОбработкаПерехода",
        uRLGetProcessing: "ОбработкаПолученияНавигационнойСсылки",
        uRLListGetProcessing: "ОбработкаПолученияСпискаНавигационныхСсылок",
        collaborationSystemUsersChoiceFormGetProcessing:
          "ОбработкаПолученияФормыВыбораПользователейСистемыВзаимодействия",
        fillCheckProcessingAtServer: "ОбработкаПроверкиЗаполненияНаСервере",
        addInDetachmentOnError: "ОтключениеВнешнейКомпонентыПриОшибке",
        beforeLoadDataFromSettingsAtServer: "ПередЗагрузкойДанныхИзНастроекНаСервере",
        beforeExecute: "ПередВыполнением",
        beforeLoadUserSettingsAtServer: "ПередЗагрузкойПользовательскихНастроекНаСервере",
        beforeLoadVariantAtServer: "ПередЗагрузкойВариантаНаСервере",
        beforeClose: "ПередЗакрытием",
        beforeReopenFromOtherServer: "ПередПереоткрытиемСДругогоСервера",
        onPasteFromClipboard: "ПриВставкеИзБуфераОбмена",
        onLoadDataFromSettingsAtServer: "ПриЗагрузкеДанныхИзНастроекНаСервере",
        onClose: "ПриЗакрытии",
        onMainServerAvailabilityChange: "ПриИзмененииДоступностиОсновногоСервера",
        onChangeDisplaySettings: "ПриИзмененииПараметровЭкрана",
        onOpen: "ПриОткрытии",
        onReopenFromOtherServer: "ПриПереоткрытииСДругогоСервера",
        onReopen: "ПриПовторномОткрытии",
        onCreateAtServer: "ПриСозданииНаСервере",
        onLoadUserSettingsAtServer: "ПриЗагрузкеПользовательскихНастроекНаСервере",
        onLoadVariantAtServer: "ПриЗагрузкеВариантаНаСервере",
        onSaveDataInSettingsAtServer: "ПриСохраненииДанныхВНастройкахНаСервере",
        onSaveUserSettingsAtServer: "ПриСохраненииПользовательскихНастроекНаСервере",
        onSaveVariantAtServer: "ПриСохраненииВариантаНаСервере",
        onUpdateUserSettingSetAtServer: "ПриОбновленииСоставаПользовательскихНастроекНаСервере",
        onClientApplicationSuspend: "ПриЗасыпанииКлиентскогоПриложения",
        onClientApplicationResume: "ПриПробужденииКлиентскогоПриложения",

        // #region Catalog
        valueChoice: "ВыборЗначения",
        beforeWrite: "ПередЗаписью",
        beforeWriteAtServer: "ПередЗаписьюНаСервере",
        afterWrite: "ПослеЗаписи",
        afterWriteAtServer: "ПослеЗаписиНаСервере",
        onWriteAtServer: "ПриЗаписиНаСервере",
        onReadAtServer: "ПриЧтенииНаСервере",
        // #endregion
      },
    },
  },
  eventsTag: FormRulesTags.Form,
} as const satisfies MetadataItemRule
