import { V8_MDCLASSES_ROOT } from "~/metadata/orchestration/appliedObject/presets"
import { MetadataItemRule } from "~/metadata/orchestration/property/types"

const properties = ["Properties"]

const contentObjectRoots = [
  "InformationRegister",
  "Document",
  "Catalog",
  "Report",
  "Enum",
  "CommonCommand",
  "DataProcessor",
  "AccumulationRegister",
  "Constant",
  "CommonForm",
  "Subsystem",
  "DocumentJournal",
  "ChartOfCharacteristicTypes",
  "BusinessProcess",
  "CommonAttribute",
  "ExchangePlan",
  "Task",
  "AccountingRegister",
  "FilterCriterion",
  "ChartOfCalculationTypes",
  "ChartOfAccounts",
  "CalculationRegister",
] as const

const contentMemberRoots = [
  "Document",
  "Catalog",
  "InformationRegister",
  "AccumulationRegister",
  "DataProcessor",
  "Report",
  "ChartOfCharacteristicTypes",
  "AccountingRegister",
  "ChartOfCalculationTypes",
  "BusinessProcess",
  "ChartOfAccounts",
  "ExchangePlan",
  "Task",
  "DocumentJournal",
] as const

export const MetadataFunctionalOptionRules = {
  itemType: "MetadataFunctionalOption",
  itemTypePrefix: "ФункциональнаяОпция",
  xmlDir: "FunctionalOptions",
  properties: {
    xmlRoot: {
      type: "XMLRoot",
      container: "FunctionalOption",
      rootAttributes: V8_MDCLASSES_ROOT,
      forReferenceOnly: true,
      toYAML: false,
      fromYAML: false,
    },
    uuid: {
      type: "uuid",
      xml: "_uuid",
      forReferenceOnly: true,
      xmlParents: [],
    },
    name: {
      type: "string",
      xmlParents: properties,
      required: true,
    },
    synonym: {
      yaml: "Синоним",
      type: "I8nText",
      xmlParents: properties,
      defaultValueXMLRaw: "",
    },
    comment: {
      yaml: "Комментарий",
      type: "string",
      xmlParents: properties,
      defaultValueXMLRaw: "",
    },
    location: {
      yaml: "Размещение",
      xml: "Location",
      type: "string",
      xmlParents: properties,
    },
    privilegedGetMode: {
      yaml: "ПривилегированныйРежимПриПолучении",
      xml: "PrivilegedGetMode",
      type: "boolean",
      xmlParents: properties,
      defaultValueXML: true,
      implicitValueYAML: true,
    },
    content: {
      yaml: "СоставФункциональнойОпции",
      xml: "Content",
      type: "MetadataItemLinks",
      metadataTarget: {
        kind: "member",
        owner: "explicit",
        roots: contentMemberRoots,
        objectRoots: contentObjectRoots,
        nestedObjectRoots: ["Subsystem"],
        memberKinds: ["Attribute", "TabularSection", "Resource", "Dimension", "Command", "AccountingFlag"],
      },
      xmlParents: properties,
      metadataItemLinksXMLItem: "xr:Object",
      defaultValueXMLRaw: "",
    },
    objectBelonging: {
      yaml: "ПринадлежностьОбъекта",
      xml: "ObjectBelonging",
      type: "SystemEnumeration",
      typeSE: "ObjectBelonging",
      xmlParents: properties,
      toYAML: false,
      fromYAML: false,
      implicitValueYAML: "Native",
    },
    extendedConfigurationObject: {
      xml: "ExtendedConfigurationObject",
      type: "string",
      xmlParents: properties,
      runtimeOnly: true,
    },
  },
} as const satisfies MetadataItemRule
