import { V8_MDCLASSES_ROOT } from "~/metadata/orchestration/appliedObject/presets"
import { MetadataItemRule } from "~/metadata/orchestration/property/types"

const properties = ["Properties"]

const contentObjectPaths = [
  ["Constant"],
  ["Catalog"],
  ["Subsystem"],
  ["CommonAttribute"],
  ["ExchangePlan"],
  ["FilterCriterion"],
  ["CommonForm"],
  ["CommonCommand"],
  ["Document"],
  ["DocumentJournal"],
  ["Enum"],
  ["DataProcessor"],
  ["Report"],
  ["ChartOfCharacteristicTypes"],
  ["ChartOfAccounts"],
  ["ChartOfCalculationTypes"],
  ["InformationRegister"],
  ["AccumulationRegister"],
  ["AccountingRegister"],
  ["CalculationRegister"],
  ["BusinessProcess"],
  ["Task"],
  ["ExternalDataSource", "Cube"],
  ["ExternalDataSource", "Table"],
  ["ExternalDataSource", "Cube", "DimensionTable"],
  ["ExternalDataSource", "Function"],
] as const

const contentMemberPaths = [
  ["Catalog", "Attribute"],
  ["Catalog", "TabularSection"],
  ["Catalog", "TabularSection", "Attribute"],
  ["Catalog", "Command"],
  ["ExchangePlan", "Attribute"],
  ["ExchangePlan", "Command"],
  ["ExchangePlan", "TabularSection"],
  ["ExchangePlan", "TabularSection", "Attribute"],
  ["FilterCriterion", "Command"],
  ["Document", "Attribute"],
  ["Document", "TabularSection"],
  ["Document", "TabularSection", "Attribute"],
  ["Document", "Command"],
  ["DocumentJournal", "Command"],
  ["Enum", "Command"],
  ["DataProcessor", "Attribute"],
  ["DataProcessor", "TabularSection"],
  ["DataProcessor", "TabularSection", "Attribute"],
  ["DataProcessor", "Command"],
  ["Report", "Attribute"],
  ["Report", "Command"],
  ["ChartOfCharacteristicTypes", "Attribute"],
  ["ChartOfCharacteristicTypes", "TabularSection"],
  ["ChartOfCharacteristicTypes", "TabularSection", "Attribute"],
  ["ChartOfCharacteristicTypes", "Command"],
  ["ChartOfAccounts", "Attribute"],
  ["ChartOfAccounts", "AccountingFlag"],
  ["ChartOfAccounts", "ExtDimensionAccountingFlag"],
  ["ChartOfAccounts", "TabularSection"],
  ["ChartOfAccounts", "TabularSection", "Attribute"],
  ["ChartOfAccounts", "Command"],
  ["ChartOfCalculationTypes", "Attribute"],
  ["ChartOfCalculationTypes", "TabularSection"],
  ["ChartOfCalculationTypes", "TabularSection", "Attribute"],
  ["ChartOfCalculationTypes", "Command"],
  ["InformationRegister", "Dimension"],
  ["InformationRegister", "Resource"],
  ["InformationRegister", "Attribute"],
  ["InformationRegister", "Command"],
  ["AccumulationRegister", "Dimension"],
  ["AccumulationRegister", "Resource"],
  ["AccumulationRegister", "Attribute"],
  ["AccumulationRegister", "Command"],
  ["AccountingRegister", "Dimension"],
  ["AccountingRegister", "Resource"],
  ["AccountingRegister", "Attribute"],
  ["AccountingRegister", "Command"],
  ["CalculationRegister", "Dimension"],
  ["CalculationRegister", "Resource"],
  ["CalculationRegister", "Attribute"],
  ["CalculationRegister", "Command"],
  ["BusinessProcess", "Attribute"],
  ["BusinessProcess", "TabularSection"],
  ["BusinessProcess", "TabularSection", "Attribute"],
  ["BusinessProcess", "Command"],
  ["Task", "AddressingAttribute"],
  ["Task", "Attribute"],
  ["Task", "TabularSection"],
  ["Task", "TabularSection", "Attribute"],
  ["Task", "Command"],
  ["ExternalDataSource", "Table", "Field"],
  ["ExternalDataSource", "Table", "Command"],
  ["ExternalDataSource", "Cube", "DimensionTable", "Field"],
  ["ExternalDataSource", "Cube", "Dimension"],
  ["ExternalDataSource", "Cube", "Resource"],
  ["ExternalDataSource", "Cube", "Command"],
] as const

export const MetadataFunctionalOptionRules = {
  itemType: "MetadataFunctionalOption",
  metadataTargetOwner: { kind: "self", root: "FunctionalOption" },
  itemTypePrefix: "ФункциональнаяОпция",
  xmlDir: "FunctionalOptions",
  properties: {
    xmlRoot: {
      type: "XMLRoot",
      container: "FunctionalOption",
      rootAttributes: V8_MDCLASSES_ROOT,
      forReferenceOnly: true,
      toYAML: false,
      fromYAML: false,
    },
    uuid: {
      type: "uuid",
      xml: "_uuid",
      forReferenceOnly: true,
      xmlParents: [],
    },
    name: {
      type: "string",
      xmlParents: properties,
      required: true,
    },
    synonym: {
      yaml: "Синоним",
      type: "I8nText",
      xmlParents: properties,
      defaultValueXMLRaw: "",
    },
    comment: {
      yaml: "Комментарий",
      type: "string",
      xmlParents: properties,
      defaultValueXMLRaw: "",
    },
    location: {
      yaml: "Размещение",
      xml: "Location",
      type: "string",
      xmlParents: properties,
    },
    privilegedGetMode: {
      yaml: "ПривилегированныйРежимПриПолучении",
      xml: "PrivilegedGetMode",
      type: "boolean",
      xmlParents: properties,
      defaultValueXML: true,
      implicitValueYAML: true,
    },
    content: {
      yaml: "СоставФункциональнойОпции",
      xml: "Content",
      type: "MetadataItemLinks",
      metadataTarget: {
        kind: "member",
        owner: "explicit",
        allowedObjectPaths: contentObjectPaths,
        allowedMemberPaths: contentMemberPaths,
        nestedObjectRoots: ["Subsystem"],
      },
      xmlParents: properties,
      metadataItemLinksXMLItem: "xr:Object",
      defaultValueXMLRaw: "",
    },
    objectBelonging: {
      yaml: "ПринадлежностьОбъекта",
      xml: "ObjectBelonging",
      type: "SystemEnumeration",
      typeSE: "ObjectBelonging",
      xmlParents: properties,
      toYAML: false,
      fromYAML: false,
      implicitValueYAML: "Native",
    },
    extendedConfigurationObject: {
      xml: "ExtendedConfigurationObject",
      type: "string",
      xmlParents: properties,
      runtimeOnly: true,
    },
  },
} as const satisfies MetadataItemRule
