import { metadataItemLinksRule } from "~/metadata/commonObjects/metadataPath/types"
import { booleanRule } from "~/metadata/commonObjects/boolean/types"
import { i8nTextRule } from "~/metadata/commonObjects/i8nText/types"
import { stringRule } from "~/metadata/commonObjects/string/types"
import { uuidRule } from "~/metadata/commonObjects/uuid/types"
import { xmlRootRule } from "~/metadata/commonObjects/xmlRoot/types"
import { systemEnumerationRule } from "~/metadata/systemEnumerations/types"
import { V8_MDCLASSES_ROOT } from "~/metadata/orchestration/appliedObject/presets"
import { MetadataItemRule } from "~/metadata/orchestration/property/types"
const properties = ["Properties"]
const contentObjectPaths = [
  ["Constant"],
  ["Catalog"],
  ["Subsystem"],
  ["CommonAttribute"],
  ["ExchangePlan"],
  ["FilterCriterion"],
  ["CommonForm"],
  ["CommonCommand"],
  ["Document"],
  ["DocumentJournal"],
  ["Enum"],
  ["DataProcessor"],
  ["Report"],
  ["ChartOfCharacteristicTypes"],
  ["ChartOfAccounts"],
  ["ChartOfCalculationTypes"],
  ["InformationRegister"],
  ["AccumulationRegister"],
  ["AccountingRegister"],
  ["CalculationRegister"],
  ["BusinessProcess"],
  ["Task"],
  ["ExternalDataSource", "Cube"],
  ["ExternalDataSource", "Table"],
  ["ExternalDataSource", "Cube", "DimensionTable"],
  ["ExternalDataSource", "Function"],
] as const
const contentMemberPaths = [
  ["Catalog", "Attribute"],
  ["Catalog", "TabularSection"],
  ["Catalog", "TabularSection", "Attribute"],
  ["Catalog", "Command"],
  ["ExchangePlan", "Attribute"],
  ["ExchangePlan", "Command"],
  ["ExchangePlan", "TabularSection"],
  ["ExchangePlan", "TabularSection", "Attribute"],
  ["FilterCriterion", "Command"],
  ["Document", "Attribute"],
  ["Document", "TabularSection"],
  ["Document", "TabularSection", "Attribute"],
  ["Document", "Command"],
  ["DocumentJournal", "Command"],
  ["Enum", "Command"],
  ["DataProcessor", "Attribute"],
  ["DataProcessor", "TabularSection"],
  ["DataProcessor", "TabularSection", "Attribute"],
  ["DataProcessor", "Command"],
  ["Report", "Attribute"],
  ["Report", "Command"],
  ["ChartOfCharacteristicTypes", "Attribute"],
  ["ChartOfCharacteristicTypes", "TabularSection"],
  ["ChartOfCharacteristicTypes", "TabularSection", "Attribute"],
  ["ChartOfCharacteristicTypes", "Command"],
  ["ChartOfAccounts", "Attribute"],
  ["ChartOfAccounts", "AccountingFlag"],
  ["ChartOfAccounts", "ExtDimensionAccountingFlag"],
  ["ChartOfAccounts", "TabularSection"],
  ["ChartOfAccounts", "TabularSection", "Attribute"],
  ["ChartOfAccounts", "Command"],
  ["ChartOfCalculationTypes", "Attribute"],
  ["ChartOfCalculationTypes", "TabularSection"],
  ["ChartOfCalculationTypes", "TabularSection", "Attribute"],
  ["ChartOfCalculationTypes", "Command"],
  ["InformationRegister", "Dimension"],
  ["InformationRegister", "Resource"],
  ["InformationRegister", "Attribute"],
  ["InformationRegister", "Command"],
  ["AccumulationRegister", "Dimension"],
  ["AccumulationRegister", "Resource"],
  ["AccumulationRegister", "Attribute"],
  ["AccumulationRegister", "Command"],
  ["AccountingRegister", "Dimension"],
  ["AccountingRegister", "Resource"],
  ["AccountingRegister", "Attribute"],
  ["AccountingRegister", "Command"],
  ["CalculationRegister", "Dimension"],
  ["CalculationRegister", "Resource"],
  ["CalculationRegister", "Attribute"],
  ["CalculationRegister", "Command"],
  ["BusinessProcess", "Attribute"],
  ["BusinessProcess", "TabularSection"],
  ["BusinessProcess", "TabularSection", "Attribute"],
  ["BusinessProcess", "Command"],
  ["Task", "AddressingAttribute"],
  ["Task", "Attribute"],
  ["Task", "TabularSection"],
  ["Task", "TabularSection", "Attribute"],
  ["Task", "Command"],
  ["ExternalDataSource", "Table", "Field"],
  ["ExternalDataSource", "Table", "Command"],
  ["ExternalDataSource", "Cube", "DimensionTable", "Field"],
  ["ExternalDataSource", "Cube", "Dimension"],
  ["ExternalDataSource", "Cube", "Resource"],
  ["ExternalDataSource", "Cube", "Command"],
] as const
export const MetadataFunctionalOptionRules = {
  itemType: "MetadataFunctionalOption",
  metadataTargetOwner: { kind: "self", root: "FunctionalOption" },
  itemTypePrefix: "ФункциональнаяОпция",
  xmlDir: "FunctionalOptions",
  properties: {
    xmlRoot: xmlRootRule({
      container: "FunctionalOption",
      rootAttributes: V8_MDCLASSES_ROOT,
      forReferenceOnly: true,
      toYAML: false,
      fromYAML: false,
    }),
    uuid: uuidRule({
      xml: "_uuid",
      forReferenceOnly: true,
      xmlParents: [],
    }),
    name: stringRule({
      xmlParents: properties,
      required: true,
    }),
    synonym: i8nTextRule({
      yaml: "Синоним",
      xmlParents: properties,
      defaultValueXMLRaw: "",
      excludeIfEqualNameYAML: true,
    }),
    comment: stringRule({
      yaml: "Комментарий",
      xmlParents: properties,
      defaultValueXMLRaw: "",
    }),
    location: stringRule({
      yaml: "Размещение",
      xml: "Location",
      xmlParents: properties,
    }),
    privilegedGetMode: booleanRule({
      yaml: "ПривилегированныйРежимПриПолучении",
      xml: "PrivilegedGetMode",
      xmlParents: properties,
      defaultValueXML: true,
      implicitValueYAML: true,
    }),
    content: metadataItemLinksRule({
      yaml: "СоставФункциональнойОпции",
      xml: "Content",
      metadataTarget: {
        kind: "member",
        owner: "explicit",
        allowedObjectPaths: contentObjectPaths,
        allowedMemberPaths: contentMemberPaths,
        nestedObjectRoots: ["Subsystem"],
      },
      xmlParents: properties,
      metadataItemLinksXMLItem: "xr:Object",
      defaultValueXMLRaw: "",
    }),
    objectBelonging: systemEnumerationRule({
      yaml: "ПринадлежностьОбъекта",
      xml: "ObjectBelonging",
      typeSE: "ObjectBelonging",
      xmlParents: properties,
      toYAML: false,
      fromYAML: false,
      implicitValueYAML: "Native",
    }),
    extendedConfigurationObject: stringRule({
      xml: "ExtendedConfigurationObject",
      xmlParents: properties,
      runtimeOnly: true,
    }),
  },
} as const satisfies MetadataItemRule
