import { booleanRule } from "../../../commonObjects/boolean/types"
import { defineElementRule } from "../../../ruleRuntime/formElement/ruleFactory"
import type { MetadataItemRule, PropertyRule } from "@nkdk/runtime/rule-kit"
import { ElementRule } from "../../../ruleRuntime/formElement/types"
import { formFieldCommonProperties, formFieldTableRelatedProperties } from "../formField/rules"
export type { ElementRule, PropertyRule }
const CheckBoxFieldCommonRulesProperties = {
  backColor: {
    yaml: "ЦветФона",
    type: "Color",
    metadataTarget: { kind: "object", roots: ["StyleItem"], filters: [{ kind: "styleItemType", values: ["Color"] }] },
  },
  borderColor: {
    yaml: "ЦветРамки",
    type: "Color",
    metadataTarget: { kind: "object", roots: ["StyleItem"], filters: [{ kind: "styleItemType", values: ["Color"] }] },
  },
  checkBoxType: {
    yaml: "ВидФлажка",
    type: "SystemEnumeration",
    typeSE: "CheckBoxType",
    implicitValueYAML: "Auto",
    defaultValueXML: "Auto",
    toXML: (source) => source.has("checkBoxType") || !source.has("threeState"),
  },
  editFormat: { yaml: "ФорматРедактирования", type: "I8nText" },
  equalItemsWidth: { yaml: "ОдинаковаяШиринаЭлементов", type: "boolean", noImplicitValueYAML: true },
  font: {
    yaml: "Шрифт",
    type: "Font",
    metadataTarget: { kind: "object", roots: ["StyleItem"], filters: [{ kind: "styleItemType", values: ["Font"] }] },
  },
  itemHeight: { yaml: "ВысотаЭлемента", type: "number", implicitValueYAML: 0 },
  itemTitleHeight: { yaml: "ВысотаЗаголовкаЭлемента", type: "number", implicitValueYAML: 0 },
  itemWidth: { yaml: "ШиринаЭлемента", type: "number", implicitValueYAML: 0 },
  textColor: {
    yaml: "ЦветТекста",
    type: "Color",
    metadataTarget: { kind: "object", roots: ["StyleItem"], filters: [{ kind: "styleItemType", values: ["Color"] }] },
  },
  threeState: { yaml: "ТриСостояния", type: "boolean", implicitValueYAML: false },
  events: {
    type: "Events",
    yaml: "События",
    toEnterprise: false,
    items: {
      onChange: "ПриИзменении",
    },
  },
  dataPath: {
    yaml: "ПутьКДанным",
    type: "DataPath",
    defaultType: "boolean",
    allowedKinds: ["boolean", "decimal"],
    allowComposite: false,
  },
  ...formFieldCommonProperties,
} as const satisfies MetadataItemRule["properties"]
export const CheckBoxFieldRules = {
  itemType: "CheckBoxField",
  enterpriseField: "FormField",
  enterpriseFieldType: "FormFieldType.CheckBoxField",
  xmlOrder: [
    "dataPath",
    "defaultItem",
    "visible",
    "userVisible",
    "enabled",
    "readOnly",
    "skipOnInput",
    "title",
    "titleTextColor",
    "titleFont",
    "titleLocation",
    "titleHeight",
    "toolTip",
    "horizontalAlign",
    "footerHorizontalAlign",
    "toolTipRepresentation",
    "verticalAlign",
    "threeState",
    "warningOnEditRepresentation",
    "warningOnEdit",
    "shortcut",
    "horizontalAlignInGroup",
    "verticalAlignInGroup",
    "editMode",
    "showInHeader",
    "checkBoxType",
    "editFormat",
    "itemHeight",
    "itemTitleHeight",
    "itemWidth",
    "equalItemsWidth",
    "contextMenu",
    "extendedTooltip",
    "events",
    "name",
    "displayImportance",
  ],
  properties: {
    ...CheckBoxFieldCommonRulesProperties,
    skipOnInput: booleanRule({ yaml: "ПропускатьПриВводе", noImplicitValueYAML: true }),
    titleHeight: { ...formFieldCommonProperties.titleHeight, implicitValueYAML: 0 },
  },
} as const satisfies ElementRule
export const TableCheckBoxFieldRules = {
  itemType: "TableCheckBoxField",
  xmlTag: "CheckBoxField",
  enterpriseField: "FormField",
  enterpriseFieldType: "FormFieldType.CheckBoxField",
  xmlOrder: [
    "dataPath",
    "visible",
    "userVisible",
    "defaultItem",
    "enabled",
    "readOnly",
    "skipOnInput",
    "title",
    "titleTextColor",
    "titleBackColor",
    "titleFont",
    "titleLocation",
    "titleHeight",
    "toolTip",
    "toolTipRepresentation",
    "warningOnEditRepresentation",
    "warningOnEdit",
    "shortcut",
    "horizontalAlign",
    "verticalAlign",
    "editMode",
    "fixingInTable",
    "cellHyperlink",
    "autoCellHeight",
    "showInHeader",
    "headerPicture",
    "headerHorizontalAlign",
    "showInFooter",
    "threeState",
    "footerDataPath",
    "footerText",
    "footerTextColor",
    "footerBackColor",
    "footerFont",
    "footerPicture",
    "footerHorizontalAlign",
    "onMainServerUnavalableBehavior",
    "checkBoxType",
    "borderColor",
    "backColor",
    "editFormat",
    "contextMenu",
    "extendedTooltip",
    "events",
    "name",
    "displayImportance",
  ],
  properties: {
    ...CheckBoxFieldCommonRulesProperties,
    skipOnInput: booleanRule({ yaml: "ПропускатьПриВводе", noImplicitValueYAML: true }),
    titleHeight: { ...formFieldCommonProperties.titleHeight, implicitValueYAML: 0 },
    ...formFieldTableRelatedProperties,
  },
} as const satisfies ElementRule
export const metadataRuleLayer001 = defineElementRule("CheckBoxField", CheckBoxFieldRules)
export const metadataRuleLayer002 = defineElementRule("TableCheckBoxField", TableCheckBoxFieldRules)
