import * as z from "zod"
import { ZFormField, ZFormFieldXML } from "../formField/types"

export const ZPlannerField = ZFormField.extend({
  autoMaxHeight: z.boolean().optional(),
  autoMaxWidth: z.boolean().optional(),
  dimensionItemHyperlink: z.boolean().optional(),
  enableDrag: z.boolean().optional(),
  enableStartDrag: z.boolean().optional(),
  height: z.number().optional(),
  horizontalStretch: z.boolean().optional(),
  maxHeight: z.number().optional(),
  maxWidth: z.number().optional(),
  timeScaleItemHyperlink: z.boolean().optional(),
  verticalStretch: z.boolean().optional(),
  width: z.number().optional(),
  wrappedTimeScaleHeaderHyperlink: z.boolean().optional(),
  events: z.object({
    selection: z.string().optional(),
    plannerActionClick: z.string().optional(),
    uRLClick: z.string().optional(),
    wrappedTimeScaleHeaderClick: z.string().optional(),
    dimensionItemClick: z.string().optional(),
    timeScaleItemClick: z.string().optional(),
    dragStart: z.string().optional(),
    commandGenerateProcessing: z.string().optional(),
    dragEnd: z.string().optional(),
    beforeStartQuickEdit: z.string().optional(),
    beforeStartEdit: z.string().optional(),
    beforePrint: z.string().optional(),
    beforeExpandDimensionItem: z.string().optional(),
    beforeCollapseDimensionItem: z.string().optional(),
    beforeCreate: z.string().optional(),
    beforeDelete: z.string().optional(),
    drag: z.string().optional(),
    onActivate: z.string().optional(),
    onEditEnd: z.string().optional(),
    onCurrentRepresentationPeriodChange: z.string().optional(),
    dragCheck: z.string().optional(),
    insideDragCheck: z.string().optional(),
  }).optional(),
})

export const ZPlannerFieldXML = ZFormFieldXML.extend({
  AutoMaxHeight: z.boolean().optional(),
  AutoMaxWidth: z.boolean().optional(),
  DimensionItemHyperlink: z.boolean().optional(),
  EnableDrag: z.boolean().optional(),
  EnableStartDrag: z.boolean().optional(),
  Height: z.number().optional(),
  HorizontalStretch: z.boolean().optional(),
  MaxHeight: z.number().optional(),
  MaxWidth: z.number().optional(),
  TimeScaleItemHyperlink: z.boolean().optional(),
  VerticalStretch: z.boolean().optional(),
  Width: z.number().optional(),
  WrappedTimeScaleHeaderHyperlink: z.boolean().optional(),
  Events: z.object({
    Selection: z.string().optional(),
    PlannerActionClick: z.string().optional(),
    URLClick: z.string().optional(),
    WrappedTimeScaleHeaderClick: z.string().optional(),
    DimensionItemClick: z.string().optional(),
    TimeScaleItemClick: z.string().optional(),
    DragStart: z.string().optional(),
    CommandGenerateProcessing: z.string().optional(),
    DragEnd: z.string().optional(),
    BeforeStartQuickEdit: z.string().optional(),
    BeforeStartEdit: z.string().optional(),
    BeforePrint: z.string().optional(),
    BeforeExpandDimensionItem: z.string().optional(),
    BeforeCollapseDimensionItem: z.string().optional(),
    BeforeCreate: z.string().optional(),
    BeforeDelete: z.string().optional(),
    Drag: z.string().optional(),
    OnActivate: z.string().optional(),
    OnEditEnd: z.string().optional(),
    OnCurrentRepresentationPeriodChange: z.string().optional(),
    DragCheck: z.string().optional(),
    InsideDragCheck: z.string().optional(),
  }).optional(),
})

export type TPlannerField = z.infer<typeof ZPlannerField>

export type TPlannerFieldXML = z.infer<typeof ZPlannerFieldXML>