import { importColorFromXML } from "~/lib/metadata/commonObjects/color/importFromXML"
import { importFontFromXML } from "~/lib/metadata/commonObjects/font/importFromXML"
import { importI8nTextFromXML } from "~/lib/metadata/commonObjects/i8nText/importI8nTextFromXML"
import { importFormDecorationFromXML } from "../formDecoration/importFromXML"
import { importFormGroupFromXML } from "../formGroup/importFromXML"
import { importChildItemsFromXML } from "../childItems/importFromXML"
import { importFormItemAdditionFromXML } from "../formItemAddition/importFromXML"
import { importBaseElementFromXML } from "../baseElement/importFromXML"
import { TTableXML, TTable } from "./types"
import { ZElementType } from "../types"
import { registerImport } from "~/lib/xml/import/importerFactory"

export const importTableFromXML = (xml: TTableXML | undefined): TTable | undefined => {
  if (!xml) return undefined

   
  return {
    id: xml._id,
    name: xml._name,
    elementType: ZElementType.enum.Table,
    autoAddIncomplete: xml.AutoAddIncomplete,
    autoInsertNewRow: xml.AutoInsertNewRow,
    autoMarkIncomplete: xml.AutoMarkIncomplete,
    autoMaxHeight: xml.AutoMaxHeight,
    autoMaxHeightInTableRows: xml.AutoMaxHeightInTableRows,
    autoMaxWidth: xml.AutoMaxWidth,
    backColor: importColorFromXML(xml.BackColor),
    behaviorOnHorizontalCompression: xml.BehaviorOnHorizontalCompression,
    borderColor: importColorFromXML(xml.BorderColor),
    changeRowOrder: xml.ChangeRowOrder,
    changeRowSet: xml.ChangeRowSet,
    choiceMode: xml.ChoiceMode,
    commandBar: importFormGroupFromXML(xml.CommandBar),
    commandBarLocation: xml.CommandBarLocation,
    contextMenu: importFormGroupFromXML(xml.ContextMenu),
    currentRowUse: xml.CurrentRowUse,
    dataPath: xml.DataPath,
    defaultItem: xml.DefaultItem,
    displayImportance: xml._DisplayImportance,
    enabled: xml.Enabled,
    enableDrag: xml.EnableDrag,
    enableStartDrag: xml.EnableStartDrag,
    extendedTooltip: importFormDecorationFromXML(xml.ExtendedTooltip),
    fileDragMode: xml.FileDragMode,
    font: importFontFromXML(xml.Font),
    footer: xml.Footer,
    footerHeight: xml.FooterHeight,
    header: xml.Header,
    headerHeight: xml.HeaderHeight,
    height: xml.Height,
    heightControlVariant: xml.HeightControlVariant,
    heightInTableRows: xml.HeightInTableRows,
    horizontalAlignInGroup: xml.HorizontalAlignInGroup,
    horizontalLines: xml.HorizontalLines,
    horizontalScrollBar: xml.HorizontalScrollBar,
    horizontalStretch: xml.HorizontalStretch,
    initialListView: xml.InitialListView,
    initialTreeView: xml.InitialTreeView,
    markIncomplete: xml.MarkIncomplete,
    maxHeight: xml.MaxHeight,
    maxHeightInTableRows: xml.MaxHeightInTableRows,
    maxWidth: xml.MaxWidth,
    multipleChoice: xml.MultipleChoice,
    output: xml.Output,
    readOnly: xml.ReadOnly,
    refreshRequest: xml.RefreshRequest,
    representation: xml.Representation,
    rowInputMode: xml.RowInputMode,
    rowPictureDataPath: xml.RowPictureDataPath,
    rowSelectionMode: xml.RowSelectionMode,
    rowsPicture: xml.RowsPicture,
    searchControl: importFormItemAdditionFromXML(xml.SearchControl),
    searchControlLocation: xml.SearchControlLocation,
    searchOnInput: xml.SearchOnInput,
    searchStringLocation: xml.SearchStringLocation,
    searchStringRepresentation: importFormItemAdditionFromXML(xml.SearchStringRepresentation),
    selectionMode: xml.SelectionMode,
    shortcut: xml.Shortcut,
    skipOnInput: xml.SkipOnInput,
    textColor: importColorFromXML(xml.TextColor),
    title: importI8nTextFromXML(xml.Title),
    titleFont: importFontFromXML(xml.TitleFont),
    titleHeight: xml.TitleHeight,
    titleLocation: xml.TitleLocation,
    titleTextColor: importColorFromXML(xml.TitleTextColor),
    toolTip: importI8nTextFromXML(xml.ToolTip),
    toolTipRepresentation: xml.ToolTipRepresentation,
    useAlternationRowColor: xml.UseAlternationRowColor,
    verticalAlignInGroup: xml.VerticalAlignInGroup,
    verticalLines: xml.VerticalLines,
    verticalScrollBar: xml.VerticalScrollBar,
    verticalStretch: xml.VerticalStretch,
    viewStatusLocation: xml.ViewStatusLocation,
    viewStatusRepresentation: importFormItemAdditionFromXML(xml.ViewStatusRepresentation),
    visible: xml.Visible,
    width: xml.Width,
    childItems: importChildItemsFromXML(xml.ChildItems),
    events: xml.Events ? {
       selection: xml.Events.Selection,
       valueChoice: xml.Events.ValueChoice,
       dragStart: xml.Events.DragStart,
       choiceProcessing: xml.Events.ChoiceProcessing,
       newWriteProcessing: xml.Events.NewWriteProcessing,
       refreshRequestProcessing: xml.Events.RefreshRequestProcessing,
       dragEnd: xml.Events.DragEnd,
       beforeAddRow: xml.Events.BeforeAddRow,
       beforeRowChange: xml.Events.BeforeRowChange,
       beforeEditEnd: xml.Events.BeforeEditEnd,
       beforeExpand: xml.Events.BeforeExpand,
       beforeCollapse: xml.Events.BeforeCollapse,
       beforeDeleteRow: xml.Events.BeforeDeleteRow,
       drag: xml.Events.Drag,
       afterDeleteRow: xml.Events.AfterDeleteRow,
       onActivateField: xml.Events.OnActivateField,
       onActivateRow: xml.Events.OnActivateRow,
       onActivateCell: xml.Events.OnActivateCell,
       onChange: xml.Events.OnChange,
       onStartEdit: xml.Events.OnStartEdit,
       onEditEnd: xml.Events.OnEditEnd,
       onCurrentParentChange: xml.Events.OnCurrentParentChange,
       dragCheck: xml.Events.DragCheck,
    } : undefined,
  }
}

registerImport(ZElementType.enum.Table, importTableFromXML)