import * as z from "zod"
import { TElementRules } from "../types"
import * as SE from "~/lib/metadata/systemEnumerations/types"
import { ZI8nText, ZI8nTextXML } from "~/lib/metadata/commonObjects/i8nText/types"
import { ZColor, ZColorXML } from "~/lib/metadata/commonObjects/color/types"
import { ZFont, ZFontXML } from "~/lib/metadata/commonObjects/font/types"
import { ZFormDecoration, ZFormDecorationXML } from "../formDecoration/types"
import { ZCommandBar, ZCommandBarXML } from "../commandBar/types"
import { ZChildItems, ZChildItemsXML } from "../childItems/types"
import { ZFormItemAddition, ZFormItemAdditionXML } from "../formItemAddition/types"
import { ZUserVisible, ZUserVisibleXML } from "~/lib/metadata/commonObjects/userVisible/types"
import { ZCommandSet, ZCommandSetXML } from "~/lib/metadata/forms/commandSet/types"
import { ZSearchStringAddition, ZSearchStringAdditionXML } from "~/lib/metadata/forms/elements/searchStringAddition/types"
import { ZViewStatusAddition, ZViewStatusAdditionXML } from "~/lib/metadata/forms/elements/viewStatusAddition/types"
import { ZSearchControlAddition, ZSearchControlAdditionXML } from "~/lib/metadata/forms/elements/searchControlAddition/types"
import { exportColorToXML } from "~/lib/metadata/commonObjects/color/exportToXML"
import { importColorFromXML } from "~/lib/metadata/commonObjects/color/importFromXML"
import { exportFontToXML } from "~/lib/metadata/commonObjects/font/exportToXML"
import { importFontFromXML } from "~/lib/metadata/commonObjects/font/importFromXML"
import { exportI8nTextToXML } from "~/lib/metadata/commonObjects/i8nText/exportI8nTextToXML"
import { importI8nTextFromXML } from "~/lib/metadata/commonObjects/i8nText/importI8nTextFromXML"
import { exportFormDecorationToXML } from "../formDecoration/exportToXML"
import { importFormDecorationFromXML } from "../formDecoration/importFromXML"
import { exportCommandBarToXML } from "../commandBar/exportToXML"
import { importCommandBarFromXML } from "../commandBar/importFromXML"
import { exportChildItemsToXML } from "../childItems/exportToXML"
import { importChildItemsFromXML } from "../childItems/importFromXML"
import { exportFormItemAdditionToXML } from "../formItemAddition/exportToXML"
import { importFormItemAdditionFromXML } from "../formItemAddition/importFromXML"
import { exportUserVisibleToXML } from "~/lib/metadata/commonObjects/userVisible/exportToXML"
import { importUserVisibleFromXML } from "~/lib/metadata/commonObjects/userVisible/importFromXML"
import { exportCommandSetToXML } from "~/lib/metadata/forms/commandSet/exportToXML"
import { importCommandSetFromXML } from "~/lib/metadata/forms/commandSet/importFromXML"
import { exportSearchStringAdditionToXML } from "~/lib/metadata/forms/elements/searchStringAddition/exportToXML"
import { importSearchStringAdditionFromXML } from "~/lib/metadata/forms/elements/searchStringAddition/importFromXML"
import { exportViewStatusAdditionToXML } from "~/lib/metadata/forms/elements/viewStatusAddition/exportToXML"
import { importViewStatusAdditionFromXML } from "~/lib/metadata/forms/elements/viewStatusAddition/importFromXML"
import { exportSearchControlAdditionToXML } from "~/lib/metadata/forms/elements/searchControlAddition/exportToXML"
import { importSearchControlAdditionFromXML } from "~/lib/metadata/forms/elements/searchControlAddition/importFromXML"


export const ZTableRules: TElementRules = {
  "autoAddIncomplete": {
    get type() { return z.boolean() },
    nameXML: "AutoAddIncomplete",
    get typeXML() { return z.boolean() },
    nameEnterprise: "АвтоВводНезаполненного",
    format: undefined,
    isProperties: ()=> true,
  },
  "autoCommandBar": {
    get type() { return ZCommandBar },
    nameXML: "AutoCommandBar",
    get typeXML() { return ZCommandBarXML },
    nameEnterprise: "АвтоКоманднаяПанель",
    format: undefined,
    isProperties: ()=> true,
  },
  "autoInsertNewRow": {
    get type() { return z.boolean() },
    nameXML: "AutoInsertNewRow",
    get typeXML() { return z.boolean() },
    nameEnterprise: "АвтоВводНовойСтроки",
    format: undefined,
    isProperties: ()=> true,
  },
  "autoMarkIncomplete": {
    get type() { return z.boolean() },
    nameXML: "AutoMarkIncomplete",
    get typeXML() { return z.boolean() },
    nameEnterprise: "АвтоОтметкаНезаполненного",
    format: undefined,
    isProperties: ()=> true,
  },
  "autoMaxHeight": {
    get type() { return z.boolean() },
    nameXML: "AutoMaxHeight",
    get typeXML() { return z.boolean() },
    nameEnterprise: "АвтоМаксимальнаяВысота",
    format: undefined,
    isProperties: ()=> true,
  },
  "autoMaxHeightInTableRows": {
    get type() { return z.boolean() },
    nameXML: "AutoMaxHeightInTableRows",
    get typeXML() { return z.boolean() },
    nameEnterprise: "АвтоМаксимальнаяВысотаВСтрокахТаблицы",
    format: undefined,
    isProperties: ()=> true,
  },
  "autoMaxWidth": {
    get type() { return z.boolean() },
    nameXML: "AutoMaxWidth",
    get typeXML() { return z.boolean() },
    nameEnterprise: "АвтоМаксимальнаяШирина",
    format: undefined,
    isProperties: ()=> true,
  },
  "backColor": {
    get type() { return ZColor },
    nameXML: "BackColor",
    get typeXML() { return ZColorXML },
    nameEnterprise: "ЦветФона",
    format: undefined,
    isProperties: ()=> true,
  },
  "behaviorOnHorizontalCompression": {
    get type() { return SE.ZTableBehaviorOnHorizontalCompression },
    nameXML: "BehaviorOnHorizontalCompression",
    get typeXML() { return SE.ZTableBehaviorOnHorizontalCompression },
    nameEnterprise: "ПоведениеПриСжатииПоГоризонтали",
    format: undefined,
    isProperties: ()=> true,
  },
  "borderColor": {
    get type() { return ZColor },
    nameXML: "BorderColor",
    get typeXML() { return ZColorXML },
    nameEnterprise: "ЦветРамки",
    format: undefined,
    isProperties: ()=> true,
  },
  "changeRowOrder": {
    get type() { return z.boolean() },
    nameXML: "ChangeRowOrder",
    get typeXML() { return z.boolean() },
    nameEnterprise: "ИзменятьПорядокСтрок",
    format: undefined,
    isProperties: ()=> true,
  },
  "changeRowSet": {
    get type() { return z.boolean() },
    nameXML: "ChangeRowSet",
    get typeXML() { return z.boolean() },
    nameEnterprise: "ИзменятьСоставСтрок",
    format: undefined,
    isProperties: ()=> true,
  },
  "choiceMode": {
    get type() { return z.boolean() },
    nameXML: "ChoiceMode",
    get typeXML() { return z.boolean() },
    nameEnterprise: "РежимВыбора",
    format: undefined,
    isProperties: ()=> true,
  },
  "commandBar": {
    get type() { return ZCommandBar },
    nameXML: "CommandBar",
    get typeXML() { return ZCommandBarXML },
    nameEnterprise: "КоманднаяПанель",
    format: undefined,
    isProperties: ()=> true,
  },
  "commandBarLocation": {
    get type() { return SE.ZFormItemCommandBarLabelLocation },
    nameXML: "CommandBarLocation",
    get typeXML() { return SE.ZFormItemCommandBarLabelLocation },
    nameEnterprise: "ПоложениеКоманднойПанели",
    format: undefined,
    isProperties: ()=> true,
  },
  "commandSet": {
    get type() { return ZCommandSet },
    nameXML: "CommandSet",
    get typeXML() { return ZCommandSetXML },
    nameEnterprise: "Команда",
    format: undefined,
    isProperties: ()=> true,
  },
  "contextMenu": {
    get type() { return ZCommandBar },
    nameXML: "ContextMenu",
    get typeXML() { return ZCommandBarXML },
    nameEnterprise: "КонтекстноеМеню",
    format: undefined,
    isProperties: ()=> true,
  },
  "currentRowUse": {
    get type() { return SE.ZTableCurrentRowUse },
    nameXML: "CurrentRowUse",
    get typeXML() { return SE.ZTableCurrentRowUse },
    nameEnterprise: "ИспользованиеТекущейСтроки",
    format: undefined,
    isProperties: ()=> true,
  },
  "dataPath": {
    get type() { return z.string() },
    nameXML: "DataPath",
    get typeXML() { return z.string() },
    nameEnterprise: "ПутьКДанным",
    format: undefined,
    isProperties: ()=> true,
  },
  "defaultItem": {
    get type() { return z.boolean() },
    nameXML: "DefaultItem",
    get typeXML() { return z.boolean() },
    nameEnterprise: "АктивизироватьПоУмолчанию",
    format: undefined,
    isProperties: ()=> true,
  },
  "displayImportance": {
    get type() { return SE.ZDisplayImportance },
    nameXML: "_DisplayImportance",
    get typeXML() { return SE.ZDisplayImportance },
    nameEnterprise: "ВажностьПриОтображении",
    format: undefined,
    isProperties: ()=> true,
  },
  "enabled": {
    get type() { return z.boolean() },
    nameXML: "Enabled",
    get typeXML() { return z.boolean() },
    nameEnterprise: "Доступность",
    format: undefined,
    isProperties: ()=> true,
  },
  "enableDrag": {
    get type() { return z.boolean() },
    nameXML: "EnableDrag",
    get typeXML() { return z.boolean() },
    nameEnterprise: "РазрешитьПеретаскивание",
    format: undefined,
    isProperties: ()=> true,
  },
  "enableStartDrag": {
    get type() { return z.boolean() },
    nameXML: "EnableStartDrag",
    get typeXML() { return z.boolean() },
    nameEnterprise: "РазрешитьНачалоПеретаскивания",
    format: undefined,
    isProperties: ()=> true,
  },
  "extendedTooltip": {
    get type() { return ZFormDecoration },
    nameXML: "ExtendedTooltip",
    get typeXML() { return ZFormDecorationXML },
    nameEnterprise: "РасширеннаяПодсказка",
    format: undefined,
    isProperties: ()=> true,
  },
  "fileDragMode": {
    get type() { return SE.ZFileDragMode },
    nameXML: "FileDragMode",
    get typeXML() { return SE.ZFileDragMode },
    nameEnterprise: "СпособПеретаскиванияФайлов",
    format: undefined,
    isProperties: ()=> true,
  },
  "font": {
    get type() { return ZFont },
    nameXML: "Font",
    get typeXML() { return ZFontXML },
    nameEnterprise: "Шрифт",
    format: undefined,
    isProperties: ()=> true,
  },
  "footer": {
    get type() { return z.boolean() },
    nameXML: "Footer",
    get typeXML() { return z.boolean() },
    nameEnterprise: "Подвал",
    format: undefined,
    isProperties: ()=> true,
  },
  "footerHeight": {
    get type() { return z.number() },
    nameXML: "FooterHeight",
    get typeXML() { return z.number() },
    nameEnterprise: "ВысотаПодвала",
    format: undefined,
    isProperties: ()=> true,
  },
  "header": {
    get type() { return z.boolean() },
    nameXML: "Header",
    get typeXML() { return z.boolean() },
    nameEnterprise: "Шапка",
    format: undefined,
    isProperties: ()=> true,
  },
  "headerHeight": {
    get type() { return z.number() },
    nameXML: "HeaderHeight",
    get typeXML() { return z.number() },
    nameEnterprise: "ВысотаШапки",
    format: undefined,
    isProperties: ()=> true,
  },
  "height": {
    get type() { return z.number() },
    nameXML: "Height",
    get typeXML() { return z.number() },
    nameEnterprise: "Высота",
    format: undefined,
    isProperties: ()=> true,
  },
  "heightControlVariant": {
    get type() { return SE.ZTableHeightControlVariant },
    nameXML: "HeightControlVariant",
    get typeXML() { return SE.ZTableHeightControlVariant },
    nameEnterprise: "ВариантУправленияВысотой",
    format: undefined,
    isProperties: ()=> true,
  },
  "heightInTableRows": {
    get type() { return z.number() },
    nameXML: "HeightInTableRows",
    get typeXML() { return z.number() },
    nameEnterprise: "ВысотаВСтрокахТаблицы",
    format: undefined,
    isProperties: ()=> true,
  },
  "horizontalAlignInGroup": {
    get type() { return SE.ZItemHorizontalLocation },
    nameXML: "HorizontalAlignInGroup",
    get typeXML() { return SE.ZItemHorizontalLocation },
    nameEnterprise: "ГоризонтальноеПоложениеВГруппе",
    format: undefined,
    isProperties: ()=> true,
  },
  "horizontalLines": {
    get type() { return z.boolean() },
    nameXML: "HorizontalLines",
    get typeXML() { return z.boolean() },
    nameEnterprise: "ГоризонтальныеЛинии",
    format: undefined,
    isProperties: ()=> true,
  },
  "horizontalScrollBar": {
    get type() { return SE.ZScrollBarUse },
    nameXML: "HorizontalScrollBar",
    get typeXML() { return SE.ZScrollBarUse },
    nameEnterprise: "ГоризонтальнаяПолосаПрокрутки",
    format: undefined,
    isProperties: ()=> true,
  },
  "horizontalStretch": {
    get type() { return z.boolean() },
    nameXML: "HorizontalStretch",
    get typeXML() { return z.boolean() },
    nameEnterprise: "РастягиватьПоГоризонтали",
    format: undefined,
    isProperties: ()=> true,
  },
  "initialListView": {
    get type() { return SE.ZInitialListView },
    nameXML: "InitialListView",
    get typeXML() { return SE.ZInitialListView },
    nameEnterprise: "НачальноеОтображениеСписка",
    format: undefined,
    isProperties: ()=> true,
  },
  "initialTreeView": {
    get type() { return SE.ZInitialTreeView },
    nameXML: "InitialTreeView",
    get typeXML() { return SE.ZInitialTreeView },
    nameEnterprise: "НачальноеОтображениеДерева",
    format: undefined,
    isProperties: ()=> true,
  },
  "markIncomplete": {
    get type() { return z.boolean() },
    nameXML: "MarkIncomplete",
    get typeXML() { return z.boolean() },
    nameEnterprise: "ОтметкаНезаполненного",
    format: undefined,
    isProperties: ()=> true,
  },
  "maxHeight": {
    get type() { return z.number() },
    nameXML: "MaxHeight",
    get typeXML() { return z.number() },
    nameEnterprise: "МаксимальнаяВысота",
    format: undefined,
    isProperties: ()=> true,
  },
  "maxHeightInTableRows": {
    get type() { return z.number() },
    nameXML: "MaxHeightInTableRows",
    get typeXML() { return z.number() },
    nameEnterprise: "МаксимальнаяВысотаВСтрокахТаблицы",
    format: undefined,
    isProperties: ()=> true,
  },
  "maxWidth": {
    get type() { return z.number() },
    nameXML: "MaxWidth",
    get typeXML() { return z.number() },
    nameEnterprise: "МаксимальнаяШирина",
    format: undefined,
    isProperties: ()=> true,
  },
  "multipleChoice": {
    get type() { return z.boolean() },
    nameXML: "MultipleChoice",
    get typeXML() { return z.boolean() },
    nameEnterprise: "МножественныйВыбор",
    format: undefined,
    isProperties: ()=> true,
  },
  "output": {
    get type() { return SE.ZUseOutput },
    nameXML: "Output",
    get typeXML() { return SE.ZUseOutput },
    nameEnterprise: "Вывод",
    format: undefined,
    isProperties: ()=> true,
  },
  "readOnly": {
    get type() { return z.boolean() },
    nameXML: "ReadOnly",
    get typeXML() { return z.boolean() },
    nameEnterprise: "ТолькоПросмотр",
    format: undefined,
    isProperties: ()=> true,
  },
  "refreshRequest": {
    get type() { return SE.ZRefreshRequestMethod },
    nameXML: "RefreshRequest",
    get typeXML() { return SE.ZRefreshRequestMethod },
    nameEnterprise: "ЗапросОбновления",
    format: undefined,
    isProperties: ()=> true,
  },
  "representation": {
    get type() { return SE.ZTableRepresentation },
    nameXML: "Representation",
    get typeXML() { return SE.ZTableRepresentation },
    nameEnterprise: "Отображение",
    format: undefined,
    isProperties: ()=> true,
  },
  "rowInputMode": {
    get type() { return SE.ZTableRowInputMode },
    nameXML: "RowInputMode",
    get typeXML() { return SE.ZTableRowInputMode },
    nameEnterprise: "РежимВводаСтрок",
    format: undefined,
    isProperties: ()=> true,
  },
  "rowPictureDataPath": {
    get type() { return z.string() },
    nameXML: "RowPictureDataPath",
    get typeXML() { return z.string() },
    nameEnterprise: "ПутьКДаннымКартинкиСтроки",
    format: undefined,
    isProperties: ()=> true,
  },
  "rowSelectionMode": {
    get type() { return SE.ZTableRowSelectionMode },
    nameXML: "RowSelectionMode",
    get typeXML() { return SE.ZTableRowSelectionMode },
    nameEnterprise: "РежимВыделенияСтроки",
    format: undefined,
    isProperties: ()=> true,
  },
  "rowsPicture": {
    get type() { return z.boolean() },
    nameXML: "RowsPicture",
    get typeXML() { return z.boolean() },
    nameEnterprise: "КартинкаСтрок",
    format: undefined,
    isProperties: ()=> true,
  },
  "searchControl": {
    get type() { return ZFormItemAddition },
    nameXML: "SearchControl",
    get typeXML() { return ZFormItemAdditionXML },
    nameEnterprise: "УправлениеПоиском",
    format: undefined,
    isProperties: ()=> true,
  },
  "searchControlAddition": {
    get type() { return ZSearchControlAddition },
    nameXML: "SearchControlAddition",
    get typeXML() { return ZSearchControlAdditionXML },
    nameEnterprise: "УправлениеПоиском",
    format: undefined,
    isProperties: ()=> true,
  },
  "searchControlLocation": {
    get type() { return SE.ZSearchControlLocation },
    nameXML: "SearchControlLocation",
    get typeXML() { return SE.ZSearchControlLocation },
    nameEnterprise: "ПоложениеУправленияПоиском",
    format: undefined,
    isProperties: ()=> true,
  },
  "searchOnInput": {
    get type() { return SE.ZSearchInTableOnInput },
    nameXML: "SearchOnInput",
    get typeXML() { return SE.ZSearchInTableOnInput },
    nameEnterprise: "ПоискПриВводе",
    format: undefined,
    isProperties: ()=> true,
  },
  "searchStringAddition": {
    get type() { return ZSearchStringAddition },
    nameXML: "SearchStringAddition",
    get typeXML() { return ZSearchStringAdditionXML },
    nameEnterprise: "ПоложениеПоисковогоСтроки",
    format: undefined,
    isProperties: ()=> true,
  },
  "searchStringLocation": {
    get type() { return SE.ZSearchStringLocation },
    nameXML: "SearchStringLocation",
    get typeXML() { return SE.ZSearchStringLocation },
    nameEnterprise: "ПоложениеСтрокиПоиска",
    format: undefined,
    isProperties: ()=> true,
  },
  "searchStringRepresentation": {
    get type() { return ZFormItemAddition },
    nameXML: "SearchStringRepresentation",
    get typeXML() { return ZFormItemAdditionXML },
    nameEnterprise: "ОтображениеСтрокиПоиска",
    format: undefined,
    isProperties: ()=> true,
  },
  "selectionMode": {
    get type() { return SE.ZTableSelectionMode },
    nameXML: "SelectionMode",
    get typeXML() { return SE.ZTableSelectionMode },
    nameEnterprise: "РежимВыделения",
    format: undefined,
    isProperties: ()=> true,
  },
  "shortcut": {
    get type() { return z.string() },
    nameXML: "Shortcut",
    get typeXML() { return z.string() },
    nameEnterprise: "СочетаниеКлавиш",
    format: undefined,
    isProperties: ()=> true,
  },
  "skipOnInput": {
    get type() { return z.boolean() },
    nameXML: "SkipOnInput",
    get typeXML() { return z.boolean() },
    nameEnterprise: "ПропускатьПриВводе",
    format: undefined,
    isProperties: ()=> true,
  },
  "textColor": {
    get type() { return ZColor },
    nameXML: "TextColor",
    get typeXML() { return ZColorXML },
    nameEnterprise: "ЦветТекста",
    format: undefined,
    isProperties: ()=> true,
  },
  "title": {
    get type() { return ZI8nText },
    nameXML: "Title",
    get typeXML() { return ZI8nTextXML },
    nameEnterprise: "Заголовок",
    format: undefined,
    isProperties: ()=> true,
  },
  "titleFont": {
    get type() { return ZFont },
    nameXML: "TitleFont",
    get typeXML() { return ZFontXML },
    nameEnterprise: "ШрифтЗаголовка",
    format: undefined,
    isProperties: ()=> true,
  },
  "titleHeight": {
    get type() { return z.number() },
    nameXML: "TitleHeight",
    get typeXML() { return z.number() },
    nameEnterprise: "ВысотаЗаголовка",
    format: undefined,
    isProperties: ()=> true,
  },
  "titleLocation": {
    get type() { return SE.ZFormItemTitleLocation },
    nameXML: "TitleLocation",
    get typeXML() { return SE.ZFormItemTitleLocation },
    nameEnterprise: "ПоложениеЗаголовка",
    format: undefined,
    isProperties: ()=> true,
  },
  "titleTextColor": {
    get type() { return ZColor },
    nameXML: "TitleTextColor",
    get typeXML() { return ZColorXML },
    nameEnterprise: "ЦветТекстаЗаголовка",
    format: undefined,
    isProperties: ()=> true,
  },
  "toolTip": {
    get type() { return ZI8nText },
    nameXML: "ToolTip",
    get typeXML() { return ZI8nTextXML },
    nameEnterprise: "Подсказка",
    format: undefined,
    isProperties: ()=> true,
  },
  "toolTipRepresentation": {
    get type() { return SE.ZToolTipRepresentation },
    nameXML: "ToolTipRepresentation",
    get typeXML() { return SE.ZToolTipRepresentation },
    nameEnterprise: "ОтображениеПодсказки",
    format: undefined,
    isProperties: ()=> true,
  },
  "useAlternationRowColor": {
    get type() { return z.boolean() },
    nameXML: "UseAlternationRowColor",
    get typeXML() { return z.boolean() },
    nameEnterprise: "ЧередованиеЦветовСтрок",
    format: undefined,
    isProperties: ()=> true,
  },
  "userVisible": {
    get type() { return ZUserVisible },
    nameXML: "UserVisible",
    get typeXML() { return ZUserVisibleXML },
    nameEnterprise: "ПользовательскаяВидимость",
    format: undefined,
    isProperties: ()=> true,
  },
  "verticalAlignInGroup": {
    get type() { return SE.ZItemVerticalAlign },
    nameXML: "VerticalAlignInGroup",
    get typeXML() { return SE.ZItemVerticalAlign },
    nameEnterprise: "ВертикальноеПоложениеВГруппе",
    format: undefined,
    isProperties: ()=> true,
  },
  "verticalLines": {
    get type() { return z.boolean() },
    nameXML: "VerticalLines",
    get typeXML() { return z.boolean() },
    nameEnterprise: "ВертикальныеЛинии",
    format: undefined,
    isProperties: ()=> true,
  },
  "verticalScrollBar": {
    get type() { return SE.ZScrollBarUse },
    nameXML: "VerticalScrollBar",
    get typeXML() { return SE.ZScrollBarUse },
    nameEnterprise: "ВертикальнаяПолосаПрокрутки",
    format: undefined,
    isProperties: ()=> true,
  },
  "verticalStretch": {
    get type() { return z.boolean() },
    nameXML: "VerticalStretch",
    get typeXML() { return z.boolean() },
    nameEnterprise: "РастягиватьПоВертикали",
    format: undefined,
    isProperties: ()=> true,
  },
  "viewStatusAddition": {
    get type() { return ZViewStatusAddition },
    nameXML: "ViewStatusAddition",
    get typeXML() { return ZViewStatusAdditionXML },
    nameEnterprise: "ПоложениеСостоянияПросмотра",
    format: undefined,
    isProperties: ()=> true,
  },
  "viewStatusLocation": {
    get type() { return SE.ZViewStatusLocation },
    nameXML: "ViewStatusLocation",
    get typeXML() { return SE.ZViewStatusLocation },
    nameEnterprise: "ПоложениеСостоянияПросмотра",
    format: undefined,
    isProperties: ()=> true,
  },
  "viewStatusRepresentation": {
    get type() { return ZFormItemAddition },
    nameXML: "ViewStatusRepresentation",
    get typeXML() { return ZFormItemAdditionXML },
    nameEnterprise: "ОтображениеСостоянияПросмотра",
    format: undefined,
    isProperties: ()=> true,
  },
  "visible": {
    get type() { return z.boolean() },
    nameXML: "Visible",
    get typeXML() { return z.boolean() },
    nameEnterprise: "Видимость",
    format: undefined,
    isProperties: ()=> true,
  },
  "width": {
    get type() { return z.number() },
    nameXML: "Width",
    get typeXML() { return z.number() },
    nameEnterprise: "Ширина",
    format: undefined,
    isProperties: ()=> true,
  },
  "childItems": {
    get type() { return ZЭлементыФормы },
    nameXML: "ChildItems",
    get typeXML() { return ZЭлементыФормыXML },
    nameEnterprise: "ПодчиненныеЭлементы",
    format: undefined,
    isProperties: ()=> true,
  },
}
