import * as z from "zod"
import * as SE from "~/lib/metadata/systemEnumerations/types"
import { ZI8nText, ZI8nTextXML } from "~/lib/metadata/commonObjects/i8nText/types"
import { ZColor, ZColorXML } from "~/lib/metadata/commonObjects/color/types"
import { ZFont, ZFontXML } from "~/lib/metadata/commonObjects/font/types"
import { ZBaseElement, ZBaseElementXML } from "../baseElement/types"
import { ZFormDecoration, ZFormDecorationXML } from "../formDecoration/types"
import { ZFormGroup, ZFormGroupXML } from "../formGroup/types"
import { ZChildItems, ZChildItemsXML } from "../childItems/types"
import { ZFormItemAddition, ZFormItemAdditionXML } from "../formItemAddition/types"

export const ZTable = ZBaseElement.extend({
  autoAddIncomplete: z.boolean().optional(),
  autoInsertNewRow: z.boolean().optional(),
  autoMarkIncomplete: z.boolean().optional(),
  autoMaxHeight: z.boolean().optional(),
  autoMaxHeightInTableRows: z.boolean().optional(),
  autoMaxWidth: z.boolean().optional(),
  backColor: ZColor.optional(),
  behaviorOnHorizontalCompression: SE.ZTableBehaviorOnHorizontalCompression.optional(),
  borderColor: ZColor.optional(),
  changeRowOrder: z.boolean().optional(),
  changeRowSet: z.boolean().optional(),
  choiceMode: z.boolean().optional(),
  commandBar: ZFormGroup.optional(),
  commandBarLocation: SE.ZFormItemCommandBarLabelLocation.optional(),
  get contextMenu() {
    return ZFormGroup.optional()
  },
  currentRowUse: SE.ZTableCurrentRowUse.optional(),
  dataPath: z.string().optional(),
  defaultItem: z.boolean().optional(),
  displayImportance: SE.ZDisplayImportance.optional(),
  enabled: z.boolean().optional(),
  enableDrag: z.boolean().optional(),
  enableStartDrag: z.boolean().optional(),
  get extendedTooltip() {
    return ZFormDecoration.optional()
  },
  fileDragMode: SE.ZFileDragMode.optional(),
  font: ZFont.optional(),
  footer: z.boolean().optional(),
  footerHeight: z.number().optional(),
  header: z.boolean().optional(),
  headerHeight: z.number().optional(),
  height: z.number().optional(),
  heightControlVariant: SE.ZTableHeightControlVariant.optional(),
  heightInTableRows: z.number().optional(),
  horizontalAlignInGroup: SE.ZItemHorizontalLocation.optional(),
  horizontalLines: z.boolean().optional(),
  horizontalScrollBar: SE.ZScrollBarUse.optional(),
  horizontalStretch: z.boolean().optional(),
  initialListView: SE.ZInitialListView.optional(),
  initialTreeView: SE.ZInitialTreeView.optional(),
  markIncomplete: z.boolean().optional(),
  maxHeight: z.number().optional(),
  maxHeightInTableRows: z.number().optional(),
  maxWidth: z.number().optional(),
  multipleChoice: z.boolean().optional(),
  output: SE.ZUseOutput.optional(),
  readOnly: z.boolean().optional(),
  refreshRequest: SE.ZRefreshRequestMethod.optional(),
  representation: SE.ZTableRepresentation.optional(),
  rowInputMode: SE.ZTableRowInputMode.optional(),
  rowPictureDataPath: z.string().optional(),
  rowSelectionMode: SE.ZTableRowSelectionMode.optional(),
  rowsPicture: z.boolean().optional(),
  searchControl: ZFormItemAddition.optional(),
  searchControlLocation: SE.ZSearchControlLocation.optional(),
  searchOnInput: SE.ZSearchInTableOnInput.optional(),
  searchStringLocation: SE.ZSearchStringLocation.optional(),
  searchStringRepresentation: ZFormItemAddition.optional(),
  selectionMode: SE.ZTableSelectionMode.optional(),
  shortcut: z.string().optional(),
  skipOnInput: z.boolean().optional(),
  textColor: ZColor.optional(),
  title: ZI8nText.optional(),
  titleFont: ZFont.optional(),
  titleHeight: z.number().optional(),
  titleLocation: SE.ZFormItemTitleLocation.optional(),
  titleTextColor: ZColor.optional(),
  toolTip: ZI8nText.optional(),
  toolTipRepresentation: SE.ZToolTipRepresentation.optional(),
  useAlternationRowColor: z.boolean().optional(),
  verticalAlignInGroup: SE.ZItemVerticalAlign.optional(),
  verticalLines: z.boolean().optional(),
  verticalScrollBar: SE.ZScrollBarUse.optional(),
  verticalStretch: z.boolean().optional(),
  viewStatusLocation: SE.ZViewStatusLocation.optional(),
  viewStatusRepresentation: ZFormItemAddition.optional(),
  visible: z.boolean().optional(),
  width: z.number().optional(),
  get childItems() {
    return ZChildItems
  },
})

export const ZTableXML = ZBaseElementXML.extend({
  AutoAddIncomplete: z.boolean().optional(),
  AutoInsertNewRow: z.boolean().optional(),
  AutoMarkIncomplete: z.boolean().optional(),
  AutoMaxHeight: z.boolean().optional(),
  AutoMaxHeightInTableRows: z.boolean().optional(),
  AutoMaxWidth: z.boolean().optional(),
  BackColor: ZColorXML.optional(),
  BehaviorOnHorizontalCompression: SE.ZTableBehaviorOnHorizontalCompression.optional(),
  BorderColor: ZColorXML.optional(),
  ChangeRowOrder: z.boolean().optional(),
  ChangeRowSet: z.boolean().optional(),
  ChoiceMode: z.boolean().optional(),
  CommandBar: ZFormGroupXML.optional(),
  CommandBarLocation: SE.ZFormItemCommandBarLabelLocation.optional(),
  get ContextMenu() {
    return ZFormGroupXML.optional()
  },
  CurrentRowUse: SE.ZTableCurrentRowUse.optional(),
  DataPath: z.string().optional(),
  DefaultItem: z.boolean().optional(),
  DisplayImportance: SE.ZDisplayImportance.optional(),
  Enabled: z.boolean().optional(),
  EnableDrag: z.boolean().optional(),
  EnableStartDrag: z.boolean().optional(),
  get ExtendedTooltip() {
    return ZFormDecorationXML.optional()
  },
  FileDragMode: SE.ZFileDragMode.optional(),
  Font: ZFontXML.optional(),
  Footer: z.boolean().optional(),
  FooterHeight: z.number().optional(),
  Header: z.boolean().optional(),
  HeaderHeight: z.number().optional(),
  Height: z.number().optional(),
  HeightControlVariant: SE.ZTableHeightControlVariant.optional(),
  HeightInTableRows: z.number().optional(),
  HorizontalAlignInGroup: SE.ZItemHorizontalLocation.optional(),
  HorizontalLines: z.boolean().optional(),
  HorizontalScrollBar: SE.ZScrollBarUse.optional(),
  HorizontalStretch: z.boolean().optional(),
  InitialListView: SE.ZInitialListView.optional(),
  InitialTreeView: SE.ZInitialTreeView.optional(),
  MarkIncomplete: z.boolean().optional(),
  MaxHeight: z.number().optional(),
  MaxHeightInTableRows: z.number().optional(),
  MaxWidth: z.number().optional(),
  MultipleChoice: z.boolean().optional(),
  Output: SE.ZUseOutput.optional(),
  ReadOnly: z.boolean().optional(),
  RefreshRequest: SE.ZRefreshRequestMethod.optional(),
  Representation: SE.ZTableRepresentation.optional(),
  RowInputMode: SE.ZTableRowInputMode.optional(),
  RowPictureDataPath: z.string().optional(),
  RowSelectionMode: SE.ZTableRowSelectionMode.optional(),
  RowsPicture: z.boolean().optional(),
  SearchControl: ZFormItemAdditionXML.optional(),
  SearchControlLocation: SE.ZSearchControlLocation.optional(),
  SearchOnInput: SE.ZSearchInTableOnInput.optional(),
  SearchStringLocation: SE.ZSearchStringLocation.optional(),
  SearchStringRepresentation: ZFormItemAdditionXML.optional(),
  SelectionMode: SE.ZTableSelectionMode.optional(),
  Shortcut: z.string().optional(),
  SkipOnInput: z.boolean().optional(),
  TextColor: ZColorXML.optional(),
  Title: ZI8nTextXML.optional(),
  TitleFont: ZFontXML.optional(),
  TitleHeight: z.number().optional(),
  TitleLocation: SE.ZFormItemTitleLocation.optional(),
  TitleTextColor: ZColorXML.optional(),
  ToolTip: ZI8nTextXML.optional(),
  ToolTipRepresentation: SE.ZToolTipRepresentation.optional(),
  UseAlternationRowColor: z.boolean().optional(),
  VerticalAlignInGroup: SE.ZItemVerticalAlign.optional(),
  VerticalLines: z.boolean().optional(),
  VerticalScrollBar: SE.ZScrollBarUse.optional(),
  VerticalStretch: z.boolean().optional(),
  ViewStatusLocation: SE.ZViewStatusLocation.optional(),
  ViewStatusRepresentation: ZFormItemAdditionXML.optional(),
  Visible: z.boolean().optional(),
  Width: z.number().optional(),
  get ChildItems() {
    return ZChildItemsXML.optional()
  },
})

export type TTable = z.infer<typeof ZTable>

export type TTableXML = z.infer<typeof ZTableXML>