import * as SE from "~/lib/metadata/systemEnumerations/types"
import { ZI8nText, ZI8nTextXML } from "~/lib/metadata/commonObjects/i8nText/types"
import { ZColor, ZColorXML } from "~/lib/metadata/commonObjects/color/types"
import { ZFont, ZFontXML } from "~/lib/metadata/commonObjects/font/types"
import { ZBaseElement, ZBaseElementXML } from "../baseElement/types"
import { ZFormDecoration, ZFormDecorationXML } from "../formDecoration/types"
import { ZCommandBar, ZCommandBarXML } from "../commandBar/types"
import { ZChildItems, ZChildItemsXML, TChildItems } from "../childItems/types"
import { ZFormItemAddition, ZFormItemAdditionXML } from "../formItemAddition/types"
import { ZUserVisible, ZUserVisibleXML } from "~/lib/metadata/commonObjects/userVisible/types"
import { ZCommandSet, ZCommandSetXML } from "~/lib/metadata/forms/commandSet/types"
import { ZSearchStringAddition, ZSearchStringAdditionXML } from "~/lib/metadata/forms/elements/searchStringAddition/types"
import { ZViewStatusAddition, ZViewStatusAdditionXML } from "~/lib/metadata/forms/elements/viewStatusAddition/types"
import { ZSearchControlAddition, ZSearchControlAdditionXML } from "~/lib/metadata/forms/elements/searchControlAddition/types"
import { ZEventsXML } from "~/lib/metadata/forms/events/types"
import { ZElementType } from "~/lib/metadata/forms/elements/types"
import { ZodChildItemsType } from "../childItems/typesExt"

export interface Table {
  elementType: ElementType
  name: string
  id?: string
  autoAddIncomplete?: boolean,
  autoCommandBar?: CommandBar,
  autoInsertNewRow?: boolean,
  autoMarkIncomplete?: boolean,
  autoMaxHeight?: boolean,
  autoMaxHeightInTableRows?: boolean,
  autoMaxWidth?: boolean,
  backColor?: Color,
  behaviorOnHorizontalCompression?: SE.TableBehaviorOnHorizontalCompression,
  borderColor?: Color,
  changeRowOrder?: boolean,
  changeRowSet?: boolean,
  choiceMode?: boolean,
  commandBar?: CommandBar,
  commandBarLocation?: SE.FormItemCommandBarLabelLocation,
  commandSet?: CommandSet,
  contextMenu?: CommandBar,
  currentRowUse?: SE.TableCurrentRowUse,
  dataPath?: string,
  defaultItem?: boolean,
  displayImportance?: SE.DisplayImportance,
  enabled?: boolean,
  enableDrag?: boolean,
  enableStartDrag?: boolean,
  extendedTooltip?: FormDecoration,
  fileDragMode?: SE.FileDragMode,
  font?: Font,
  footer?: boolean,
  footerHeight?: number,
  header?: boolean,
  headerHeight?: number,
  height?: number,
  heightControlVariant?: SE.TableHeightControlVariant,
  heightInTableRows?: number,
  horizontalAlignInGroup?: SE.ItemHorizontalLocation,
  horizontalLines?: boolean,
  horizontalScrollBar?: SE.ScrollBarUse,
  horizontalStretch?: boolean,
  initialListView?: SE.InitialListView,
  initialTreeView?: SE.InitialTreeView,
  markIncomplete?: boolean,
  maxHeight?: number,
  maxHeightInTableRows?: number,
  maxWidth?: number,
  multipleChoice?: boolean,
  output?: SE.UseOutput,
  readOnly?: boolean,
  refreshRequest?: SE.RefreshRequestMethod,
  representation?: SE.TableRepresentation,
  rowInputMode?: SE.TableRowInputMode,
  rowPictureDataPath?: string,
  rowSelectionMode?: SE.TableRowSelectionMode,
  rowsPicture?: boolean,
  searchControl?: FormItemAddition,
  searchControlAddition?: SearchControlAddition,
  searchControlLocation?: SE.SearchControlLocation,
  searchOnInput?: SE.SearchInTableOnInput,
  searchStringAddition?: SearchStringAddition,
  searchStringLocation?: SE.SearchStringLocation,
  searchStringRepresentation?: FormItemAddition,
  selectionMode?: SE.TableSelectionMode,
  shortcut?: string,
  skipOnInput?: boolean,
  textColor?: Color,
  title?: I8nText,
  titleFont?: Font,
  titleHeight?: number,
  titleLocation?: SE.FormItemTitleLocation,
  titleTextColor?: Color,
  toolTip?: I8nText,
  toolTipRepresentation?: SE.ToolTipRepresentation,
  useAlternationRowColor?: boolean,
  userVisible?: UserVisible,
  verticalAlignInGroup?: SE.ItemVerticalAlign,
  verticalLines?: boolean,
  verticalScrollBar?: SE.ScrollBarUse,
  verticalStretch?: boolean,
  viewStatusAddition?: ViewStatusAddition,
  viewStatusLocation?: SE.ViewStatusLocation,
  viewStatusRepresentation?: FormItemAddition,
  visible?: boolean,
  width?: number,
  childItems?: ChildItems,
  events?: {
    selection?: string,
    valueChoice?: string,
    dragStart?: string,
    choiceProcessing?: string,
    newWriteProcessing?: string,
    refreshRequestProcessing?: string,
    dragEnd?: string,
    beforeAddRow?: string,
    beforeRowChange?: string,
    beforeEditEnd?: string,
    beforeExpand?: string,
    beforeCollapse?: string,
    beforeDeleteRow?: string,
    drag?: string,
    afterDeleteRow?: string,
    onActivateField?: string,
    onActivateRow?: string,
    onActivateCell?: string,
    onChange?: string,
    onStartEdit?: string,
    onEditEnd?: string,
    onCurrentParentChange?: string,
    dragCheck?: string,
  },
}

export interface TableXML {
  _name: z.string(),
  _id: z.string(),
  _DisplayImportance: SE.DisplayImportance,
  UserVisible: UserVisible,
  TitleLocation: SE.FormItemTitleLocation,
  TitleHeight: number,
  Representation: SE.TableRepresentation,
  CommandBarLocation: SE.FormItemCommandBarLabelLocation,
  Enabled: boolean,
  ReadOnly: boolean,
  SkipOnInput: boolean,
  DefaultItem: boolean,
  ChangeRowSet: boolean,
  ChangeRowOrder: boolean,
  Width: number,
  AutoMaxWidth: boolean,
  MaxWidth: number,
  Height: number,
  AutoMaxHeight: boolean,
  MaxHeight: number,
  HeightInTableRows: number,
  HeightControlVariant: SE.TableHeightControlVariant,
  ChoiceMode: boolean,
  MultipleChoice: boolean,
  RowInputMode: SE.TableRowInputMode,
  SelectionMode: SE.TableSelectionMode,
  RowSelectionMode: SE.TableRowSelectionMode,
  EnableStartDrag: boolean,
  EnableDrag: boolean,
  Header: boolean,
  HeaderHeight: number,
  Footer: boolean,
  FooterHeight: number,
  HorizontalScrollBar: SE.ScrollBarUse,
  VerticalScrollBar: SE.ScrollBarUse,
  HorizontalLines: boolean,
  VerticalLines: boolean,
  AutoInsertNewRow: boolean,
  UseAlternationRowColor: boolean,
  AutoAddIncomplete: boolean,
  AutoMarkIncomplete: boolean,
  SearchOnInput: SE.SearchInTableOnInput,
  InitialListView: SE.InitialListView,
  InitialTreeView: SE.InitialTreeView,
  Output: SE.UseOutput,
  HorizontalStretch: boolean,
  VerticalStretch: boolean,
  FileDragMode: SE.FileDragMode,
  DataPath: string,
  CommandSet: CommandSet,
  RowPictureDataPath: string,
  RowsPicture: boolean,
  TextColor: Color,
  BackColor: Color,
  BorderColor: Color,
  Font: Font,
  Title: I8nText,
  TitleTextColor: Color,
  TitleFont: Font,
  Shortcut: string,
  ToolTip: I8nText,
  ToolTipRepresentation: SE.ToolTipRepresentation,
  SearchStringLocation: SE.SearchStringLocation,
  ViewStatusLocation: SE.ViewStatusLocation,
  SearchControlLocation: SE.SearchControlLocation,
  RefreshRequest: SE.RefreshRequestMethod,
  CurrentRowUse: SE.TableCurrentRowUse,
  BehaviorOnHorizontalCompression: SE.TableBehaviorOnHorizontalCompression,
  ContextMenu: CommandBar,
  AutoCommandBar: CommandBar,
  ExtendedTooltip: FormDecoration,
  SearchStringAddition: SearchStringAddition,
  ViewStatusAddition: ViewStatusAddition,
  SearchControlAddition: SearchControlAddition,
  AutoMaxHeightInTableRows: boolean,
  CommandBar: CommandBar,
  HorizontalAlignInGroup: SE.ItemHorizontalLocation,
  MarkIncomplete: boolean,
  MaxHeightInTableRows: number,
  SearchControl: FormItemAddition,
  SearchStringRepresentation: FormItemAddition,
  VerticalAlignInGroup: SE.ItemVerticalAlign,
  ViewStatusRepresentation: FormItemAddition,
  Visible: boolean,
  ChildItems: ChildItems,
}