import { uuidPropertyRule } from "~/metadata/commonObjects/uuid/rule"
import { MetadataItemRule } from "~/metadata/orchestration/property/types"

export const MetadataCommandRules = {
  itemType: "MetadataCommand",
  properties: {
    uuid: uuidPropertyRule,
    name: {
      xml: "Name",
      type: "string",
      required: true,
      xmlParents: ["Properties"],
      order: 1,
    },
    synonym: {
      yaml: "Синоним",
      xml: "Synonym",
      type: "I8nText",
      excludeIfEqualNameYAML: true,
      xmlParents: ["Properties"],
      order: 2,
      defaultValueXMLRaw: "",
    },
    comment: {
      yaml: "Комментарий",
      xml: "Comment",
      type: "string",
      xmlParents: ["Properties"],
      order: 3,
      defaultValueXMLRaw: "",
    },
    group: {
      yaml: "Группа",
      xml: "Group",
      type: "MetadataCommandGroup",
      xmlParents: ["Properties"],
      order: 4,
    },
    commandParameterType: {
      yaml: "ТипПараметраКоманды",
      xml: "CommandParameterType",
      type: "TypeDescription",
      xmlParents: ["Properties"],
      order: 5,
      defaultValueXMLRaw: "",
    },
    parameterUseMode: {
      yaml: "РежимИспользованияПараметра",
      xml: "ParameterUseMode",
      type: "SystemEnumeration",
      typeSE: "CommandParameterUseMode",
      xmlParents: ["Properties"],
      order: 6,
      defaultValueXML: "Single",
    },
    modifiesData: {
      yaml: "ИзменяетДанные",
      xml: "ModifiesData",
      type: "boolean",
      xmlParents: ["Properties"],
      order: 7,
      defaultValueXML: false,
    },
    representation: {
      yaml: "Отображение",
      xml: "Representation",
      type: "SystemEnumeration",
      typeSE: "ButtonRepresentation",
      implicitValueYAML: "Auto",
      defaultValueXML: "Auto",
      xmlParents: ["Properties"],
      order: 8,
    },
    toolTip: {
      yaml: "Подсказка",
      xml: "ToolTip",
      type: "I8nText",
      xmlParents: ["Properties"],
      order: 9,
      defaultValueXMLRaw: "",
    },
    picture: {
      yaml: "Картинка",
      xml: "Picture",
      type: "Picture",
      xmlParents: ["Properties"],
      order: 10,
      defaultValueXMLRaw: "",
    },
    shortcut: {
      yaml: "СочетаниеКлавиш",
      xml: "Shortcut",
      type: "string",
      xmlParents: ["Properties"],
      order: 11,
      defaultValueXMLRaw: "",
    },
    onMainServerUnavalableBehavior: {
      yaml: "ПоведениеПриНедоступностиОсновногоСервера",
      xml: "OnMainServerUnavalableBehavior",
      type: "SystemEnumeration",
      typeSE: "OnMainServerUnavalableBehavior",
      implicitValueYAML: "Auto",
      defaultValueXML: "Auto",
      xmlParents: ["Properties"],
      order: 12,
    },
    objectBelonging: {
      yaml: "ПринадлежностьОбъекта",
      xml: "ObjectBelonging",
      type: "SystemEnumeration",
      typeSE: "ObjectBelonging",
      implicitValueYAML: "Native",
      toYAML: false,
      fromYAML: false,
      xmlParents: ["Properties"],
    },
    commandModule: {
      type: "Module",
      nkdkPath: ({ name }: { name: string }) => "Команды/" + name + ".bsl",
      xmlPath: ({ name }: { name: string }) => "Commands/" + name + "/Ext/CommandModule.bsl",
      toXML: false,
      fromXML: false,
    },
  },
} as const satisfies MetadataItemRule
