import { V8_MDCLASSES_ROOT } from "~/metadata/orchestration/appliedObject/presets"
import { MetadataItemRule } from "~/metadata/orchestration/property/types"

const properties = ["Properties"]

export const MetadataCommonModuleRules = {
  itemType: "MetadataCommonModule",
  metadataTargetOwner: { kind: "self", root: "CommonModule" },
  itemTypePrefix: "ОбщийМодуль",
  xmlDir: "CommonModules",
  properties: {
    xmlRoot: {
      type: "XMLRoot",
      container: "CommonModule",
      rootAttributes: V8_MDCLASSES_ROOT,
      forReferenceOnly: true,
      toYAML: false,
      fromYAML: false,
    },
    uuid: {
      type: "uuid",
      xml: "_uuid",
      forReferenceOnly: true,
      xmlParents: [],
    },
    name: {
      type: "string",
      xmlParents: properties,
      required: true,
    },
    synonym: {
      yaml: "Синоним",
      type: "I8nText",
      xmlParents: properties,
      defaultValueXMLRaw: "",
    },
    comment: {
      yaml: "Комментарий",
      type: "string",
      xmlParents: properties,
      defaultValueXMLRaw: "",
    },
    global: {
      yaml: "Глобальный",
      xml: "Global",
      type: "boolean",
      xmlParents: properties,
      defaultValueXML: false,
      implicitValueYAML: false,
    },
    clientManagedApplication: {
      yaml: "Клиент",
      xml: "ClientManagedApplication",
      type: "boolean",
      xmlParents: properties,
      defaultValueXML: false,
      implicitValueYAML: false,
    },
    server: {
      yaml: "Сервер",
      xml: "Server",
      type: "boolean",
      xmlParents: properties,
      defaultValueXML: true,
      implicitValueYAML: true,
    },
    externalConnection: {
      yaml: "ВнешнееСоединение",
      xml: "ExternalConnection",
      type: "boolean",
      xmlParents: properties,
      defaultValueXML: false,
      implicitValueYAML: false,
    },
    clientOrdinaryApplication: {
      yaml: "КлиентОбычноеПриложение",
      xml: "ClientOrdinaryApplication",
      type: "boolean",
      xmlParents: properties,
      defaultValueXML: false,
      implicitValueYAML: false,
    },
    serverCall: {
      yaml: "ВызовСервера",
      xml: "ServerCall",
      type: "boolean",
      xmlParents: properties,
      defaultValueXML: false,
      implicitValueYAML: false,
    },
    privileged: {
      yaml: "Привилегированный",
      xml: "Privileged",
      type: "boolean",
      xmlParents: properties,
      defaultValueXML: false,
      implicitValueYAML: false,
    },
    returnValuesReuse: {
      yaml: "ПовторноеИспользованиеВозвращаемыхЗначений",
      xml: "ReturnValuesReuse",
      type: "SystemEnumeration",
      typeSE: "ReturnValuesReuse",
      xmlParents: properties,
      defaultValueXML: "DontUse",
      implicitValueYAML: "DontUse",
    },
    module: {
      type: "Module",
      nkdkPath: "Модуль.bsl",
      xmlPath: "Ext/Module.bsl",
    },
    objectBelonging: {
      yaml: "ПринадлежностьОбъекта",
      xml: "ObjectBelonging",
      type: "SystemEnumeration",
      typeSE: "ObjectBelonging",
      xmlParents: properties,
      implicitValueYAML: "Native",
      toYAML: false,
      fromYAML: false,
    },
    extendedConfigurationObject: {
      xml: "ExtendedConfigurationObject",
      type: "string",
      xmlParents: properties,
      runtimeOnly: true,
    },
  },
} as const satisfies MetadataItemRule
