import { registerElementRule } from "~/metadata/metadataFactory/elements/ruleFactory"
import { PropertyRule } from "~/metadata/orchestration/property/types"
import { ElementRule } from "../../../metadataFactory/elements/types"
export type { ElementRule, PropertyRule }

export const SpreadSheetDocumentFieldRules = {
  itemType: "SpreadSheetDocumentField",
  enterpriseFieldType: "FormFieldType.SpreadsheetDocumentField",
  enterpriseField: "FormField",
  properties: {
    autoCellHeight: { yaml: "АвтоВысотаЯчейки", type: "boolean" },
    cellHyperlink: { yaml: "ГиперссылкаЯчейки", type: "boolean" },
    contextMenu: { yaml: "КонтекстноеМеню", type: "ContextMenu", toEnterprise: false },
    dataPath: { yaml: "ПутьКДанным", type: "DataPath", defaultType: "string" },

    defaultItem: { yaml: "АктивизироватьПоУмолчанию", type: "boolean" },
    displayImportance: {
      yaml: "ВажностьПриОтображении",
      xml: "_DisplayImportance",
      type: "SystemEnumeration",
      typeSE: "DisplayImportance",
    },
    editMode: {
      yaml: "РежимРедактирования",
      type: "SystemEnumeration",
      typeSE: "ColumnEditMode",
    },
    enabled: { yaml: "Доступность", type: "boolean" },
    extendedTooltip: { yaml: "РасширеннаяПодсказка", type: "ExtendedTooltip", toEnterprise: false },
    fixingInTable: {
      yaml: "ФиксацияВТаблице",
      type: "SystemEnumeration",
      typeSE: "FixingInTable",
    },
    footerBackColor: { yaml: "ЦветФонаПодвала", type: "Color" },
    footerDataPath: { yaml: "ПутьКДаннымПодвала", type: "DataPath", defaultType: "string" },
    footerFont: { yaml: "ШрифтПодвала", type: "Font" },
    footerHorizontalAlign: {
      yaml: "ГоризонтальноеПоложениеВПодвале",
      type: "SystemEnumeration",
      typeSE: "ItemHorizontalLocation",
    },
    footerPicture: { yaml: "КартинкаПодвала", type: "Picture" },
    footerText: { yaml: "ТекстПодвала", type: "I8nText" },
    footerTextColor: { yaml: "ЦветТекстаПодвала", type: "Color" },
    headerHorizontalAlign: {
      yaml: "ГоризонтальноеПоложениеВШапке",
      type: "SystemEnumeration",
      typeSE: "ItemHorizontalLocation",
    },
    headerPicture: { yaml: "КартинкаШапки", type: "Picture" },
    horizontalAlign: {
      yaml: "ГоризонтальноеПоложение",
      type: "SystemEnumeration",
      typeSE: "ItemHorizontalLocation",
    },
    horizontalAlignInGroup: {
      yaml: "ГоризонтальноеПоложениеВГруппе",
      xml: "GroupHorizontalAlign",
      type: "SystemEnumeration",
      typeSE: "ItemHorizontalLocation",
    },
    readOnly: { yaml: "ТолькоПросмотр", type: "boolean" },
    shortcut: { yaml: "СочетаниеКлавиш", type: "string", toEnterprise: false },
    showInFooter: { yaml: "ОтображатьВПодвале", type: "boolean" },
    showInHeader: { yaml: "ОтображатьВШапке", type: "boolean" },
    skipOnInput: { yaml: "ПропускатьПриВводе", type: "boolean" },
    title: {
      yaml: "Заголовок",
      type: "I8nText",
      yamlPartialOthers: true,
    },
    titleBackColor: { yaml: "ЦветФонаЗаголовка", type: "Color" },
    titleFont: { yaml: "ШрифтЗаголовка", type: "Font" },
    titleHeight: { yaml: "ВысотаЗаголовка", type: "number" },
    titleLocation: {
      yaml: "ПоложениеЗаголовка",
      type: "SystemEnumeration",
      typeSE: "FormItemTitleLocation",
    },
    titleTextColor: { yaml: "ЦветТекстаЗаголовка", type: "Color" },
    toolTip: { yaml: "Подсказка", type: "I8nText" },
    toolTipRepresentation: {
      yaml: "ОтображениеПодсказки",
      type: "SystemEnumeration",
      typeSE: "ToolTipRepresentation",
    },
    type: {
      yaml: "Вид",
      type: "SystemEnumeration",
      typeSE: "FormFieldType",
    },
    typeRestriction: { yaml: "ОграничениеТипа", type: "TypeDescription", toEnterprise: false },
    verticalAlign: {
      yaml: "ВертикальноеПоложение",
      type: "SystemEnumeration",
      typeSE: "ItemVerticalAlign",
    },
    verticalAlignInGroup: {
      yaml: "ВертикальноеПоложениеВГруппе",
      xml: "GroupVerticalAlign",
      type: "SystemEnumeration",
      typeSE: "ItemVerticalAlign",
    },
    visible: { yaml: "Видимость", type: "boolean" },
    warningOnEdit: { yaml: "ПредупреждениеПриРедактировании", type: "I8nText" },
    warningOnEditRepresentation: {
      yaml: "ОтображениеПредупрежденияПриРедактировании",
      type: "SystemEnumeration",
      typeSE: "WarningOnEditRepresentation",
    },
    autoMaxHeight: { yaml: "АвтоМаксимальнаяВысота", type: "boolean" },
    autoMaxWidth: { yaml: "АвтоМаксимальнаяШирина", type: "boolean" },
    blackAndWhiteView: { yaml: "ЧерноБелыйПросмотр", type: "boolean" },
    borderColor: { yaml: "ЦветРамки", type: "Color" },
    drawingSelectionShowMode: {
      yaml: "РежимОтображенияВыделенияРисунков",
      type: "SystemEnumeration",
      typeSE: "DrawingSelectionShowMode",
    },
    table: { yaml: "Таблица", xml: "AssociatedTableElementId", type: "AssociatedTable", toEnterprise: false },
    edit: { yaml: "Редактирование", type: "boolean" },
    enableDrag: { yaml: "РазрешитьПеретаскивание", type: "boolean" },
    enableStartDrag: { yaml: "РазрешитьНачалоПеретаскивания", type: "boolean" },
    height: { yaml: "Высота", type: "number" },
    horizontalScrollBar: {
      yaml: "ГоризонтальнаяПолосаПрокрутки",
      type: "SystemEnumeration",
      typeSE: "ScrollBarUse",
    },
    horizontalStretch: { yaml: "РастягиватьПоГоризонтали", type: "boolean" },
    maxHeight: { yaml: "МаксимальнаяВысота", type: "number" },
    maxWidth: { yaml: "МаксимальнаяШирина", type: "number" },
    output: {
      yaml: "Вывод",
      type: "SystemEnumeration",
      typeSE: "UseOutput",
    },
    pointerType: {
      yaml: "ТипКурсоров",
      type: "SystemEnumeration",
      typeSE: "SpreadsheetDocumentPointerType",
    },
    protection: { yaml: "Защита", type: "boolean" },
    selectionShowMode: {
      yaml: "РежимОтображенияВыделения",
      type: "SystemEnumeration",
      typeSE: "SelectionShowMode",
    },
    showCellNames: { yaml: "ОтображатьИменаЯчеек", type: "boolean" },
    showGrid: { yaml: "ОтображатьСетку", type: "boolean" },
    showGroups: { yaml: "ОтображатьГруппировки", type: "boolean" },
    showHeaders: { yaml: "ОтображатьЗаголовки", type: "boolean" },
    showRowAndColumnNames: { yaml: "ОтображатьИменаСтрокИКолонок", type: "boolean" },
    statePresentation: {
      yaml: "ОтображениеСостояния",
      type: "SystemEnumeration",
      typeSE: "StatePresentation",
    },
    usedFileName: { yaml: "ИспользуемоеИмяФайла", type: "string" },
    verticalScrollBar: {
      yaml: "ВертикальнаяПолосаПрокрутки",
      type: "SystemEnumeration",
      typeSE: "ScrollBarUse",
    },
    verticalStretch: { yaml: "РастягиватьПоВертикали", type: "boolean" },
    viewScalingMode: {
      yaml: "РежимМасштабированияПросмотра",
      type: "SystemEnumeration",
      typeSE: "ViewScalingMode",
    },
    width: { yaml: "Ширина", type: "number" },
    userVisible: {
      yaml: "РазрешитьИспользование",
      yamlDeny: "ЗапретитьИспользование",
      type: "UserVisible",
      toEnterprise: false,
    },
  },
  events: {
    onChange: "ПриИзменении",
    selection: "Выбор",
    dragStart: "НачалоПеретаскивания",
    additionalDetailProcessing: "ОбработкаДополнительнойРасшифровки",
    uRLProcessing: "ОбработкаНавигационнойСсылки",
    detailProcessing: "ОбработкаРасшифровки",
    dragEnd: "ОкончаниеПеретаскивания",
    beforeWrite: "ПередЗаписью",
    beforePrint: "ПередПечатью",
    drag: "Перетаскивание",
    afterWrite: "ПослеЗаписи",
    onActivate: "ПриАктивизации",
    onChangeAreaContentEvent: "ПриИзмененииСодержимогоОбласти",
    dragCheck: "ПроверкаПеретаскивания",
  },
} as const satisfies ElementRule

registerElementRule("SpreadSheetDocumentField", SpreadSheetDocumentFieldRules)
