import * as z from "zod"
import { TElementRules } from "../types"
import * as SE from "~/lib/metadata/systemEnumerations/types"
import { ZI8nText, ZI8nTextXML } from "~/lib/metadata/commonObjects/i8nText/types"
import { ZColor, ZColorXML } from "~/lib/metadata/commonObjects/color/types"
import { ZTypeDescription, ZTypeDescriptionXML } from "~/lib/metadata/commonObjects/typeDescription/types"
import { ZPicture, ZPictureXML } from "~/lib/metadata/commonObjects/pictures/types"
import { ZFont, ZFontXML } from "~/lib/metadata/commonObjects/font/types"
import { ZFormDecoration, ZFormDecorationXML } from "../formDecoration/types"
import { ZTable, ZTableXML } from "../table/types"
import { ZCommandBar, ZCommandBarXML } from "../commandBar/types"
import { ZUserVisible, ZUserVisibleXML } from "~/lib/metadata/commonObjects/userVisible/types"
import { exportColorToXML } from "~/lib/metadata/commonObjects/color/exportToXML"
import { importColorFromXML } from "~/lib/metadata/commonObjects/color/importFromXML"
import { exportFontToXML } from "~/lib/metadata/commonObjects/font/exportToXML"
import { importFontFromXML } from "~/lib/metadata/commonObjects/font/importFromXML"
import { exportI8nTextToXML } from "~/lib/metadata/commonObjects/i8nText/exportI8nTextToXML"
import { importI8nTextFromXML } from "~/lib/metadata/commonObjects/i8nText/importI8nTextFromXML"
import { exportTypeDescriptionToXML } from "~/lib/metadata/commonObjects/typeDescription/exportToXML"
import { importTypeDescriptionFromXML } from "~/lib/metadata/commonObjects/typeDescription/importFromXML"
import { exportPictureToXML } from "~/lib/metadata/commonObjects/pictures/exportToXML"
import { importPictureFromXML } from "~/lib/metadata/commonObjects/pictures/importFromXML"
import { exportTableToXML } from "../table/exportToXML"
import { importTableFromXML } from "../table/importFromXML"
import { exportFormDecorationToXML } from "../formDecoration/exportToXML"
import { importFormDecorationFromXML } from "../formDecoration/importFromXML"
import { exportCommandBarToXML } from "../commandBar/exportToXML"
import { importCommandBarFromXML } from "../commandBar/importFromXML"
import { exportUserVisibleToXML } from "~/lib/metadata/commonObjects/userVisible/exportToXML"
import { importUserVisibleFromXML } from "~/lib/metadata/commonObjects/userVisible/importFromXML"


export const ZChartFieldRules: TElementRules = {
  "autoCellHeight": {
    get type() { return z.boolean() },
    nameXML: "AutoCellHeight",
    get typeXML() { return z.boolean() },
    nameEnterprise: "АвтоВысотаЯчейки",
    format: undefined,
    isProperties: ()=> true,
  },
  "cellHyperlink": {
    get type() { return z.boolean() },
    nameXML: "CellHyperlink",
    get typeXML() { return z.boolean() },
    nameEnterprise: "ГиперссылкаЯчейки",
    format: undefined,
    isProperties: ()=> true,
  },
  "contextMenu": {
    get type() { return ZCommandBar },
    nameXML: "ContextMenu",
    get typeXML() { return ZCommandBarXML },
    nameEnterprise: "КонтекстноеМеню",
    format: undefined,
    isProperties: ()=> true,
  },
  "dataPath": {
    get type() { return z.string() },
    nameXML: "DataPath",
    get typeXML() { return z.string() },
    nameEnterprise: "ПутьКДанным",
    format: undefined,
    isProperties: ()=> true,
  },
  "defaultItem": {
    get type() { return z.boolean() },
    nameXML: "DefaultItem",
    get typeXML() { return z.boolean() },
    nameEnterprise: "АктивизироватьПоУмолчанию",
    format: undefined,
    isProperties: ()=> true,
  },
  "displayImportance": {
    get type() { return SE.ZDisplayImportance },
    nameXML: "_DisplayImportance",
    get typeXML() { return SE.ZDisplayImportance },
    nameEnterprise: "ВажностьПриОтображении",
    format: undefined,
    isProperties: ()=> true,
  },
  "editMode": {
    get type() { return SE.ZColumnEditMode },
    nameXML: "EditMode",
    get typeXML() { return SE.ZColumnEditMode },
    nameEnterprise: "РежимРедактирования",
    format: undefined,
    isProperties: ()=> true,
  },
  "enabled": {
    get type() { return z.boolean() },
    nameXML: "Enabled",
    get typeXML() { return z.boolean() },
    nameEnterprise: "Доступность",
    format: undefined,
    isProperties: ()=> true,
  },
  "extendedTooltip": {
    get type() { return ZFormDecoration },
    nameXML: "ExtendedTooltip",
    get typeXML() { return ZFormDecorationXML },
    nameEnterprise: "РасширеннаяПодсказка",
    format: undefined,
    isProperties: ()=> true,
  },
  "fixingInTable": {
    get type() { return SE.ZFixingInTable },
    nameXML: "FixingInTable",
    get typeXML() { return SE.ZFixingInTable },
    nameEnterprise: "ФиксацияВТаблице",
    format: undefined,
    isProperties: ()=> true,
  },
  "footerBackColor": {
    get type() { return ZColor },
    nameXML: "FooterBackColor",
    get typeXML() { return ZColorXML },
    nameEnterprise: "ЦветФонаПодвала",
    format: undefined,
    isProperties: ()=> true,
  },
  "footerDataPath": {
    get type() { return z.string() },
    nameXML: "FooterDataPath",
    get typeXML() { return z.string() },
    nameEnterprise: "ПутьКДаннымПодвала",
    format: undefined,
    isProperties: ()=> true,
  },
  "footerFont": {
    get type() { return ZFont },
    nameXML: "FooterFont",
    get typeXML() { return ZFontXML },
    nameEnterprise: "ШрифтПодвала",
    format: undefined,
    isProperties: ()=> true,
  },
  "footerHorizontalAlign": {
    get type() { return SE.ZItemHorizontalLocation },
    nameXML: "FooterHorizontalAlign",
    get typeXML() { return SE.ZItemHorizontalLocation },
    nameEnterprise: "ГоризонтальноеПоложениеВПодвале",
    format: undefined,
    isProperties: ()=> true,
  },
  "footerPicture": {
    get type() { return ZPicture },
    nameXML: "FooterPicture",
    get typeXML() { return ZPictureXML },
    nameEnterprise: "КартинкаПодвала",
    format: undefined,
    isProperties: ()=> true,
  },
  "footerText": {
    get type() { return ZI8nText },
    nameXML: "FooterText",
    get typeXML() { return ZI8nTextXML },
    nameEnterprise: "ТекстПодвала",
    format: undefined,
    isProperties: ()=> true,
  },
  "footerTextColor": {
    get type() { return ZColor },
    nameXML: "FooterTextColor",
    get typeXML() { return ZColorXML },
    nameEnterprise: "ЦветТекстаПодвала",
    format: undefined,
    isProperties: ()=> true,
  },
  "headerHorizontalAlign": {
    get type() { return SE.ZItemHorizontalLocation },
    nameXML: "HeaderHorizontalAlign",
    get typeXML() { return SE.ZItemHorizontalLocation },
    nameEnterprise: "ГоризонтальноеПоложениеВШапке",
    format: undefined,
    isProperties: ()=> true,
  },
  "headerPicture": {
    get type() { return ZPicture },
    nameXML: "HeaderPicture",
    get typeXML() { return ZPictureXML },
    nameEnterprise: "КартинкаШапки",
    format: undefined,
    isProperties: ()=> true,
  },
  "horizontalAlign": {
    get type() { return SE.ZItemHorizontalLocation },
    nameXML: "HorizontalAlign",
    get typeXML() { return SE.ZItemHorizontalLocation },
    nameEnterprise: "ГоризонтальноеПоложение",
    format: undefined,
    isProperties: ()=> true,
  },
  "horizontalAlignInGroup": {
    get type() { return SE.ZItemHorizontalLocation },
    nameXML: "HorizontalAlignInGroup",
    get typeXML() { return SE.ZItemHorizontalLocation },
    nameEnterprise: "ГоризонтальноеПоложениеВГруппе",
    format: undefined,
    isProperties: ()=> true,
  },
  "readOnly": {
    get type() { return z.boolean() },
    nameXML: "ReadOnly",
    get typeXML() { return z.boolean() },
    nameEnterprise: "ТолькоПросмотр",
    format: undefined,
    isProperties: ()=> true,
  },
  "shortcut": {
    get type() { return z.string() },
    nameXML: "Shortcut",
    get typeXML() { return z.string() },
    nameEnterprise: "СочетаниеКлавиш",
    format: undefined,
    isProperties: ()=> true,
  },
  "showInFooter": {
    get type() { return z.boolean() },
    nameXML: "ShowInFooter",
    get typeXML() { return z.boolean() },
    nameEnterprise: "ОтображатьВПодвале",
    format: undefined,
    isProperties: ()=> true,
  },
  "showInHeader": {
    get type() { return z.boolean() },
    nameXML: "ShowInHeader",
    get typeXML() { return z.boolean() },
    nameEnterprise: "ОтображатьВШапке",
    format: undefined,
    isProperties: ()=> true,
  },
  "skipOnInput": {
    get type() { return z.boolean() },
    nameXML: "SkipOnInput",
    get typeXML() { return z.boolean() },
    nameEnterprise: "ПропускатьПриВводе",
    format: undefined,
    isProperties: ()=> true,
  },
  "table": {
    get type() { return ZTable },
    nameXML: "Table",
    get typeXML() { return ZTableXML },
    nameEnterprise: "Таблица",
    format: undefined,
    isProperties: ()=> true,
  },
  "title": {
    get type() { return ZI8nText },
    nameXML: "Title",
    get typeXML() { return ZI8nTextXML },
    nameEnterprise: "Заголовок",
    format: undefined,
    isProperties: ()=> true,
  },
  "titleBackColor": {
    get type() { return ZColor },
    nameXML: "TitleBackColor",
    get typeXML() { return ZColorXML },
    nameEnterprise: "ЦветФонаЗаголовка",
    format: undefined,
    isProperties: ()=> true,
  },
  "titleFont": {
    get type() { return ZFont },
    nameXML: "TitleFont",
    get typeXML() { return ZFontXML },
    nameEnterprise: "ШрифтЗаголовка",
    format: undefined,
    isProperties: ()=> true,
  },
  "titleHeight": {
    get type() { return z.number() },
    nameXML: "TitleHeight",
    get typeXML() { return z.number() },
    nameEnterprise: "ВысотаЗаголовка",
    format: undefined,
    isProperties: ()=> true,
  },
  "titleLocation": {
    get type() { return SE.ZFormItemTitleLocation },
    nameXML: "TitleLocation",
    get typeXML() { return SE.ZFormItemTitleLocation },
    nameEnterprise: "ПоложениеЗаголовка",
    format: undefined,
    isProperties: ()=> true,
  },
  "titleTextColor": {
    get type() { return ZColor },
    nameXML: "TitleTextColor",
    get typeXML() { return ZColorXML },
    nameEnterprise: "ЦветТекстаЗаголовка",
    format: undefined,
    isProperties: ()=> true,
  },
  "toolTip": {
    get type() { return ZI8nText },
    nameXML: "ToolTip",
    get typeXML() { return ZI8nTextXML },
    nameEnterprise: "Подсказка",
    format: undefined,
    isProperties: ()=> true,
  },
  "toolTipRepresentation": {
    get type() { return SE.ZToolTipRepresentation },
    nameXML: "ToolTipRepresentation",
    get typeXML() { return SE.ZToolTipRepresentation },
    nameEnterprise: "ОтображениеПодсказки",
    format: undefined,
    isProperties: ()=> true,
  },
  "type": {
    get type() { return SE.ZFormFieldType },
    nameXML: "Type",
    get typeXML() { return SE.ZFormFieldType },
    nameEnterprise: "Вид",
    format: undefined,
    isProperties: ()=> true,
  },
  "typeRestriction": {
    get type() { return ZTypeDescription },
    nameXML: "TypeRestriction",
    get typeXML() { return ZTypeDescriptionXML },
    nameEnterprise: "ОграничениеТипа",
    format: undefined,
    isProperties: ()=> true,
  },
  "userVisible": {
    get type() { return ZUserVisible },
    nameXML: "UserVisible",
    get typeXML() { return ZUserVisibleXML },
    nameEnterprise: "ПользовательскаяВидимость",
    format: undefined,
    isProperties: ()=> true,
  },
  "verticalAlign": {
    get type() { return SE.ZItemVerticalAlign },
    nameXML: "VerticalAlign",
    get typeXML() { return SE.ZItemVerticalAlign },
    nameEnterprise: "ВертикальноеПоложение",
    format: undefined,
    isProperties: ()=> true,
  },
  "verticalAlignInGroup": {
    get type() { return SE.ZItemVerticalAlign },
    nameXML: "VerticalAlignInGroup",
    get typeXML() { return SE.ZItemVerticalAlign },
    nameEnterprise: "ВертикальноеПоложениеВГруппе",
    format: undefined,
    isProperties: ()=> true,
  },
  "visible": {
    get type() { return z.boolean() },
    nameXML: "Visible",
    get typeXML() { return z.boolean() },
    nameEnterprise: "Видимость",
    format: undefined,
    isProperties: ()=> true,
  },
  "warningOnEdit": {
    get type() { return ZI8nText },
    nameXML: "WarningOnEdit",
    get typeXML() { return ZI8nTextXML },
    nameEnterprise: "ПредупреждениеПриРедактировании",
    format: undefined,
    isProperties: ()=> true,
  },
  "warningOnEditRepresentation": {
    get type() { return SE.ZWarningOnEditRepresentation },
    nameXML: "WarningOnEditRepresentation",
    get typeXML() { return SE.ZWarningOnEditRepresentation },
    nameEnterprise: "ОтображениеПредупрежденияПриРедактировании",
    format: undefined,
    isProperties: ()=> true,
  },
  "autoMaxHeight": {
    get type() { return z.boolean() },
    nameXML: "AutoMaxHeight",
    get typeXML() { return z.boolean() },
    nameEnterprise: "АвтоМаксимальнаяВысота",
    format: undefined,
    isProperties: ()=> true,
  },
  "autoMaxWidth": {
    get type() { return z.boolean() },
    nameXML: "AutoMaxWidth",
    get typeXML() { return z.boolean() },
    nameEnterprise: "АвтоМаксимальнаяШирина",
    format: undefined,
    isProperties: ()=> true,
  },
  "height": {
    get type() { return z.number() },
    nameXML: "Height",
    get typeXML() { return z.number() },
    nameEnterprise: "Высота",
    format: undefined,
    isProperties: ()=> true,
  },
  "horizontalStretch": {
    get type() { return z.boolean() },
    nameXML: "HorizontalStretch",
    get typeXML() { return z.boolean() },
    nameEnterprise: "РастягиватьПоГоризонтали",
    format: undefined,
    isProperties: ()=> true,
  },
  "maxHeight": {
    get type() { return z.number() },
    nameXML: "MaxHeight",
    get typeXML() { return z.number() },
    nameEnterprise: "МаксимальнаяВысота",
    format: undefined,
    isProperties: ()=> true,
  },
  "maxWidth": {
    get type() { return z.number() },
    nameXML: "MaxWidth",
    get typeXML() { return z.number() },
    nameEnterprise: "МаксимальнаяШирина",
    format: undefined,
    isProperties: ()=> true,
  },
  "verticalStretch": {
    get type() { return z.boolean() },
    nameXML: "VerticalStretch",
    get typeXML() { return z.boolean() },
    nameEnterprise: "РастягиватьПоВертикали",
    format: undefined,
    isProperties: ()=> true,
  },
  "width": {
    get type() { return z.number() },
    nameXML: "Width",
    get typeXML() { return z.number() },
    nameEnterprise: "Ширина",
    format: undefined,
    isProperties: ()=> true,
  },
}
