import { registerElementRule } from "~/metadata/orchestration/formElement/ruleFactory"
import { PropertyRule } from "~/metadata/orchestration/property/types"
import { ElementRule } from "../../../orchestration/formElement/types"
import { formFieldCommonProperties, formFieldTableRelatedProperties } from "../formField/rules"
export type { ElementRule, PropertyRule }

export const InputFieldRules = {
  itemType: "InputField",
  enterpriseField: "FormField",
  enterpriseFieldType: "FormFieldType.InputField",
  properties: {
    allowInputEmptyMultipleValues: {
      yaml: "РазрешитьВводПустыхМножественныхЗначений",
      type: "boolean",
    },
    allowMultipleValuesDuplicates: { yaml: "РазрешитьДублированиеМножественныхЗначений", type: "boolean" },
    autoCapitalizationOnTextInput: {
      yaml: "АвтоИзменениеРегистраПриВводеТекста",
      type: "SystemEnumeration",
      typeSE: "AutoCapitalizationOnTextInput",
      implicitValueYAML: "Auto",
    },
    autoChoiceIncomplete: { yaml: "АвтоВыборНезаполненного", type: "boolean" },
    autoCorrectionOnTextInput: {
      yaml: "АвтоИсправлениеПриВводеТекста",
      type: "SystemEnumeration",
      typeSE: "AutoCorrectionOnTextInput",
      implicitValueYAML: "Auto",
    },
    autoFillHint: {
      yaml: "ПодсказкаАвтозаполнения",
      type: "SystemEnumeration",
      typeSE: "InputFieldAutofillHint",
      xml: "AutofillHint",
      implicitValueYAML: "DontUse",
    },
    autoMarkIncomplete: {
      yaml: "АвтоОтметкаНезаполненного",
      type: "boolean",
    },
    autoMaxHeight: { yaml: "АвтоМаксимальнаяВысота", type: "boolean" },
    autoMaxWidth: { yaml: "АвтоМаксимальнаяШирина", type: "boolean" },
    autoShowClearButton: {
      yaml: "АвтоОтображениеКнопкиОчистки",
      type: "SystemEnumeration",
      typeSE: "AutoShowClearButtonMode",
      xml: "AutoShowClearButtonMode",
      implicitValueYAML: "Auto",
    },
    autoShowOpenButton: {
      yaml: "АвтоОтображениеКнопкиОткрытия",
      type: "SystemEnumeration",
      typeSE: "AutoShowOpenButtonMode",
      xml: "AutoShowOpenButtonMode",
      implicitValueYAML: "Auto",
    },
    availableTypes: {
      yaml: "ДоступныеТипы",
      type: "TypeDescription",
      toEnterprise: false,
    },
    backColor: { yaml: "ЦветФона", type: "Color", metadataTarget: { kind: "object", roots: ["StyleItem"], filters: [{ kind: "styleItemType", values: ["Color"] }] } },
    borderColor: { yaml: "ЦветРамки", type: "Color", metadataTarget: { kind: "object", roots: ["StyleItem"], filters: [{ kind: "styleItemType", values: ["Color"] }] } },
    choiceButton: { yaml: "КнопкаВыбора", type: "boolean" },
    choiceButtonPicture: { yaml: "КартинкаКнопкиВыбора", type: "Picture", metadataTarget: { kind: "object", roots: ["CommonPicture"] } },
    choiceButtonRepresentation: {
      yaml: "ОтображениеКнопкиВыбора",
      type: "SystemEnumeration",
      typeSE: "ChoiceButtonRepresentation",
      implicitValueYAML: "Auto",
    },
    choiceFoldersAndItems: {
      yaml: "ВыборГруппИЭлементов",
      type: "SystemEnumeration",
      typeSE: "FoldersAndItems",
      implicitValueYAML: "Auto",
    },
    choiceForm: {
      yaml: "ФормаВыбора",
      type: "string",
      toEnterprise: false,
    },
    choiceHistoryOnInput: {
      yaml: "ИсторияВыбораПриВводе",
      type: "SystemEnumeration",
      typeSE: "ChoiceHistoryOnInput",
      implicitValueYAML: "Auto",
    },
    choiceList: { yaml: "СписокВыбора", type: "ChoiceList", toEnterprise: false },
    choiceListButton: { yaml: "КнопкаСпискаВыбора", type: "boolean" },
    choiceListHeight: { yaml: "ВысотаСпискаВыбора", type: "number" },
    choiceParameterLinks: { yaml: "СвязиПараметровВыбора", type: "ChoiceParameterLinks", toEnterprise: false },
    choiceParameters: { yaml: "ПараметрыВыбора", type: "ChoiceParameters", toEnterprise: false },
    chooseType: { yaml: "ВыбиратьТип", type: "boolean" },
    clearButton: { yaml: "КнопкаОчистки", type: "boolean" },
    createButton: { yaml: "КнопкаСоздания", type: "boolean" },
    dropListButton: { yaml: "КнопкаВыпадающегоСписка", type: "boolean" },
    dropListWidth: { yaml: "ШиринаВыпадающегоСписка", type: "number" },
    editFormat: { yaml: "ФорматРедактирования", type: "I8nText" },
    // editText: { yaml: "ТекстРедактирования", type: "string" },
    editTextUpdate: {
      yaml: "ОбновлениеТекстаРедактирования",
      type: "SystemEnumeration",
      typeSE: "EditTextUpdate",
      implicitValueYAML: "Auto",
    },
    extendedEdit: {
      yaml: "РасширенноеРедактирование",
      type: "boolean",
    },
    font: { yaml: "Шрифт", type: "Font", metadataTarget: { kind: "object", roots: ["StyleItem"], filters: [{ kind: "styleItemType", values: ["Font"] }] } },
    format: { yaml: "Формат", type: "I8nText" },
    height: { yaml: "Высота", type: "number" },
    heightControlVariant: {
      yaml: "ВариантУправленияВысотой",
      type: "SystemEnumeration",
      typeSE: "ItemHeightControlVariant",
      implicitValueYAML: "Auto",
    },
    horizontalStretch: { yaml: "РастягиватьПоГоризонтали", type: "boolean" },
    incompleteChoiceMode: {
      yaml: "РежимВыбораНезаполненного",
      type: "SystemEnumeration",
      typeSE: "IncompleteChoiceMode",
      implicitValueYAML: "OnEnterPressed",
    },
    inputHint: { yaml: "ПодсказкаВвода", type: "I8nText" },
    listChoiceMode: { yaml: "РежимВыбораИзСписка", type: "boolean" },
    typeDomainEnabled: {
      yaml: "РазрешитьСоставнойТип",
      type: "boolean",
      implicitValueYAML: true,
    },
    // markIncomplete: { yaml: "ОтметкаНезаполненного", type: "boolean" },
    markNegatives: { yaml: "ВыделятьОтрицательные", type: "boolean" },
    mask: { yaml: "Маска", type: "string" },
    maxHeight: { yaml: "МаксимальнаяВысота", type: "number" },
    maxValue: { yaml: "МаксимальноеЗначение", type: "MinMaxValue", xml: "MaxValue" },
    maxWidth: { yaml: "МаксимальнаяШирина", type: "number" },
    minValue: { yaml: "МинимальноеЗначение", type: "MinMaxValue", xml: "MinValue" },
    multiLine: { yaml: "МногострочныйРежим", type: "boolean" },
    multipleValuePictureDataPath: {
      yaml: "ПутьКДаннымКартинкиМножественногоЗначения",
      type: "DataPath",
      defaultType: "string",
      xml: "MultipleValuePictureDataPath",
    },
    multipleValuePictureShape: {
      yaml: "ФигураКартинкиМножественногоЗначения",
      type: "SystemEnumeration",
      typeSE: "InputFieldMultipleValuePictureShape",
      implicitValueYAML: "Auto",
    },
    multipleValuePictureSize: {
      yaml: "РазмерКартинкиМножественногоЗначения",
      type: "SystemEnumeration",
      typeSE: "InputFieldMultipleValuePictureSize",
      implicitValueYAML: "Auto",
    },
    multipleValuePresentationDataPath: {
      yaml: "ПутьКДаннымПредставленияМножественногоЗначения",
      type: "DataPath",
      defaultType: "string",
      xml: "MultipleValuePresentDataPath",
    },
    multipleValuesBackColor: { yaml: "ЦветФонаМножественныхЗначений", type: "Color", metadataTarget: { kind: "object", roots: ["StyleItem"], filters: [{ kind: "styleItemType", values: ["Color"] }] } },
    multipleValuesExtendedEdit: {
      yaml: "РасширенноеРедактированиеМножественныхЗначений",
      type: "boolean",
      xml: "ExtendedEditMultipleValues",
    },
    multipleValuesFont: { yaml: "ШрифтМножественныхЗначений", type: "Font", metadataTarget: { kind: "object", roots: ["StyleItem"], filters: [{ kind: "styleItemType", values: ["Font"] }] } },
    multipleValuesHyperlink: { yaml: "ГиперссылкаМножественныхЗначений", type: "boolean" },
    multipleValuesPicture: {
      yaml: "КартинкаМножественныхЗначений",
      type: "Picture", metadataTarget: { kind: "object", roots: ["CommonPicture"] },
    },
    multipleValuesTextColor: { yaml: "ЦветТекстаМножественныхЗначений", type: "Color", metadataTarget: { kind: "object", roots: ["StyleItem"], filters: [{ kind: "styleItemType", values: ["Color"] }] } },
    multipleValueValueDataPath: {
      yaml: "ПутьКДаннымЗначенияМножественногоЗначения",
      type: "DataPath",
      defaultType: "string",
      xml: "MultipleValueDataPath",
    },
    onScreenKeyboardReturnKeyText: {
      yaml: "ТекстКнопкиВводаЭкраннойКлавиатуры",
      type: "SystemEnumeration",
      typeSE: "OnScreenKeyboardReturnKeyText",
      implicitValueYAML: "Auto",
    },
    openButton: { yaml: "КнопкаОткрытия", type: "boolean" },
    passwordMode: { yaml: "РежимПароля", type: "boolean" },
    quickChoice: { yaml: "БыстрыйВыбор", type: "boolean" },
    showCheckBoxesInDropListWhenInputMultipleValues: {
      yaml: "ОтображатьФлажкиВВыпадающемСпискеПриВводеМножественныхЗначений",
      type: "boolean",
      xml: "ShowCheckBoxesInDropList",
    },
    specialTextInputMode: {
      yaml: "СпециальныйРежимВводаТекста",
      type: "SystemEnumeration",
      typeSE: "SpecialTextInputMode",
      implicitValueYAML: "Auto",
    },
    spellCheckingOnTextInput: {
      yaml: "ПроверкаПравописанияПриВводеТекста",
      type: "SystemEnumeration",
      typeSE: "SpellCheckingOnTextInput",
      implicitValueYAML: "Auto",
    },
    spinButton: { yaml: "КнопкаРегулирования", type: "boolean" },
    textColor: { yaml: "ЦветТекста", type: "Color", metadataTarget: { kind: "object", roots: ["StyleItem"], filters: [{ kind: "styleItemType", values: ["Color"] }] } },
    textEdit: { yaml: "РедактированиеТекста", type: "boolean" },
    typeLink: { yaml: "СвязьПоТипу", type: "TypeLink", toEnterprise: false },
    verticalStretch: { yaml: "РастягиватьПоВертикали", type: "boolean" },
    width: { yaml: "Ширина", type: "number" },
    wrap: { yaml: "АвтоПереносСтрок", type: "boolean" },
    events: {
      type: "Events",
      yaml: "События",
      toEnterprise: false,
      items: {
        onChange: "ПриИзменении",
        autoComplete: "АвтоПодбор",
        multipleValuesAdd: "ДобавлениеМножественныхЗначений",
        editTextChange: "ИзменениеТекстаРедактирования",
        startChoice: "НачалоВыбора",
        startListChoice: "НачалоВыбораИзСписка",
        choiceProcessing: "ОбработкаВыбора",
        multipleValueURLProcessing: "ОбработкаНавигационнойСсылкиМножественногоЗначения",
        commandGenerateProcessing: "ОбработкаФормированияКоманд",
        textEditEnd: "ОкончаниеВводаТекста",
        opening: "Открытие",
        multipleValueOpening: "ОткрытиеМножественногоЗначения",
        clearing: "Очистка",
        tuning: "Регулирование",
        creating: "Создание",
        multipleValuesDelete: "УдалениеМножественныхЗначений",
      },
    },
    dataPath: {
      yaml: "ПутьКДанным",
      type: "DataPath",
      // fromYAML: false,
      defaultType: "string",
      allowOpaqueMultipleValue: true,
    },
    ...formFieldCommonProperties,
  },
} as const satisfies ElementRule

export const TableInputFieldRules = {
  itemType: "TableInputField",
  xmlTag: "InputField",
  enterpriseField: "FormField",
  enterpriseFieldType: "FormFieldType.InputField",
  properties: {
    ...InputFieldRules.properties,
    ...formFieldTableRelatedProperties,
    dataPath: {
      yaml: "ПутьКДанным",
      type: "DataPath",
      defaultType: "string",
    },
    minValue: { yaml: "МинимальноеЗначение", type: "MinMaxValue", xml: "MinValue" },
    maxValue: { yaml: "МаксимальноеЗначение", type: "MinMaxValue", xml: "MaxValue" },
  },
} as const satisfies ElementRule

registerElementRule("InputField", InputFieldRules)
registerElementRule("TableInputField", TableInputFieldRules)
