import { V8_MDCLASSES_ROOT } from "~/metadata/orchestration/appliedObject/presets"
import { MetadataItemRule } from "~/metadata/orchestration/property/types"

const properties = ["Properties"]

export const MetadataCommonAttributeRules = {
  itemType: "MetadataCommonAttribute",
  metadataTargetOwner: { kind: "self", root: "CommonAttribute" },
  itemTypePrefix: "ОбщийРеквизит",
  xmlDir: "CommonAttributes",
  properties: {
    xmlRoot: {
      type: "XMLRoot",
      container: "CommonAttribute",
      rootAttributes: V8_MDCLASSES_ROOT,
      forReferenceOnly: true,
      toYAML: false,
      fromYAML: false,
    },
    uuid: {
      type: "uuid",
      xml: "_uuid",
      forReferenceOnly: true,
      xmlParents: [],
    },
    name: {
      type: "string",
      xmlParents: properties,
      required: true,
    },
    synonym: {
      yaml: "Синоним",
      type: "I8nText",
      xmlParents: properties,
      defaultValueXMLRaw: "",
    },
    comment: {
      yaml: "Комментарий",
      type: "string",
      xmlParents: properties,
      defaultValueXMLRaw: "",
    },
    type: {
      yaml: "Тип",
      type: "TypeDescription",
      xmlParents: properties,
    },
    passwordMode: {
      yaml: "РежимПароля",
      type: "boolean",
      defaultValueXML: false,
      implicitValueYAML: false,
      xmlParents: properties,
    },
    format: {
      yaml: "Формат",
      type: "I8nText",
      xmlParents: properties,
      defaultValueXMLRaw: "",
    },
    editFormat: {
      yaml: "ФорматРедактирования",
      type: "I8nText",
      xmlParents: properties,
      defaultValueXMLRaw: "",
    },
    toolTip: {
      yaml: "Подсказка",
      type: "I8nText",
      xmlParents: properties,
      defaultValueXMLRaw: "",
    },
    markNegatives: {
      yaml: "ВыделятьОтрицательные",
      type: "boolean",
      defaultValueXML: false,
      implicitValueYAML: false,
      xmlParents: properties,
    },
    mask: {
      yaml: "Маска",
      type: "string",
      xmlParents: properties,
      defaultValueXMLRaw: "",
    },
    multiLine: {
      yaml: "МногострочныйРежим",
      type: "boolean",
      defaultValueXML: false,
      implicitValueYAML: false,
      xmlParents: properties,
    },
    extendedEdit: {
      yaml: "РасширенноеРедактирование",
      type: "boolean",
      defaultValueXML: false,
      implicitValueYAML: false,
      xmlParents: properties,
    },
    minValue: {
      yaml: "МинимальноеЗначение",
      type: "MinMaxValue",
      typedXML: "xs:string",
      xmlParents: properties,
      defaultValueXMLRaw: { "_xsi:nil": true },
    },
    maxValue: {
      yaml: "МаксимальноеЗначение",
      type: "MinMaxValue",
      typedXML: "xs:string",
      xmlParents: properties,
      defaultValueXMLRaw: { "_xsi:nil": true },
    },
    fillFromFillingValue: {
      yaml: "ЗаполнятьИзДанныхЗаполнения",
      type: "boolean",
      defaultValueXML: false,
      implicitValueYAML: false,
      xmlParents: properties,
    },
    fillValue: {
      yaml: "ЗначениеЗаполнения",
      type: "MetadataValue",
      xml: "FillValue",
      xmlParents: properties,
      defaultValueXMLRaw: { "_xsi:type": "xs:string" },
    },
    fillChecking: {
      yaml: "ПроверкаЗаполнения",
      type: "SystemEnumeration",
      typeSE: "FillChecking",
      defaultValueXML: "DontCheck",
      implicitValueYAML: "DontCheck",
      xmlParents: properties,
    },
    choiceFoldersAndItems: {
      yaml: "ВыборГруппИЭлементов",
      type: "SystemEnumeration",
      typeSE: "FoldersAndItemsUse",
      defaultValueXML: "Items",
      implicitValueYAML: "Items",
      xmlParents: properties,
    },
    choiceParameterLinks: {
      yaml: "СвязиПараметровВыбора",
      type: "ChoiceParameterLinks",
      xmlParents: properties,
      defaultValueXMLRaw: "",
    },
    choiceParameters: {
      yaml: "ПараметрыВыбора",
      type: "ChoiceParameters",
      xmlParents: properties,
      defaultValueXMLRaw: "",
    },
    quickChoice: {
      yaml: "БыстрыйВыбор",
      type: "SystemEnumeration",
      typeSE: "UseQuickChoice",
      defaultValueXML: "Auto",
      implicitValueYAML: "Auto",
      xmlParents: properties,
    },
    createOnInput: {
      yaml: "СозданиеПриВводе",
      type: "SystemEnumeration",
      typeSE: "CreateOnInput",
      defaultValueXML: "Auto",
      implicitValueYAML: "Auto",
      xmlParents: properties,
    },
    choiceForm: {
      yaml: "ФормаВыбора",
      type: "string",
      xmlParents: properties,
      defaultValueXMLRaw: "",
    },
    linkByType: {
      yaml: "СвязьПоТипу",
      type: "TypeLink",
      xmlParents: properties,
      defaultValueXMLRaw: "",
    },
    choiceHistoryOnInput: {
      yaml: "ИсторияВыбораПриВводе",
      type: "SystemEnumeration",
      typeSE: "ChoiceHistoryOnInput",
      defaultValueXML: "Auto",
      implicitValueYAML: "Auto",
      xmlParents: properties,
    },
    content: {
      yaml: "Состав",
      type: "CommonAttributeContent",
      xml: "Content",
      xmlParents: properties,
      defaultValueXMLRaw: "",
    },
    autoUse: {
      yaml: "АвтоИспользование",
      type: "SystemEnumeration",
      typeSE: "CommonAttributeAutoUse",
      defaultValueXML: "DontUse",
      implicitValueYAML: "DontUse",
      xmlParents: properties,
    },
    dataSeparation: {
      yaml: "РазделениеДанных",
      type: "SystemEnumeration",
      typeSE: "CommonAttributeDataSeparation",
      defaultValueXML: "DontUse",
      implicitValueYAML: "DontUse",
      xmlParents: properties,
    },
    separatedDataUse: {
      yaml: "ИспользованиеРазделенныхДанных",
      type: "SystemEnumeration",
      typeSE: "CommonAttributeSeparatedDataUse",
      defaultValueXML: "Independently",
      implicitValueYAML: "Independently",
      xmlParents: properties,
    },
    dataSeparationValue: {
      yaml: "ЗначениеРазделенияДанных",
      type: "string",
      xmlParents: properties,
      defaultValueXMLRaw: "",
    },
    dataSeparationUse: {
      yaml: "ИспользованиеРазделенияДанных",
      type: "string",
      xmlParents: properties,
      defaultValueXMLRaw: "",
    },
    conditionalSeparation: {
      yaml: "УсловноеРазделение",
      type: "string",
      xmlParents: properties,
      defaultValueXMLRaw: "",
    },
    usersSeparation: {
      yaml: "РазделениеПользователей",
      type: "SystemEnumeration",
      typeSE: "CommonAttributeUsersSeparation",
      defaultValueXML: "DontUse",
      implicitValueYAML: "DontUse",
      xmlParents: properties,
    },
    authenticationSeparation: {
      yaml: "РазделениеАутентификации",
      type: "SystemEnumeration",
      typeSE: "CommonAttributeAuthenticationSeparation",
      defaultValueXML: "DontUse",
      implicitValueYAML: "DontUse",
      xmlParents: properties,
    },
    configurationExtensionsSeparation: {
      yaml: "РазделениеРасширенийКонфигурации",
      type: "SystemEnumeration",
      typeSE: "CommonAttributeConfigurationExtensionsSeparation",
      defaultValueXML: "DontUse",
      implicitValueYAML: "DontUse",
      xmlParents: properties,
    },
    indexing: {
      yaml: "Индексирование",
      type: "SystemEnumeration",
      typeSE: "Indexing",
      defaultValueXML: "DontIndex",
      implicitValueYAML: "DontIndex",
      xmlParents: properties,
    },
    fullTextSearch: {
      yaml: "ПолнотекстовыйПоиск",
      type: "SystemEnumeration",
      typeSE: "UseFullTextSearch",
      defaultValueXML: "Use",
      implicitValueYAML: "Use",
      xmlParents: properties,
    },
    dataHistory: {
      yaml: "ИсторияДанных",
      type: "SystemEnumeration",
      typeSE: "DataHistoryUse",
      defaultValueXML: "Use",
      implicitValueYAML: "Use",
      xmlParents: properties,
    },
    objectBelonging: {
      yaml: "ПринадлежностьОбъекта",
      type: "SystemEnumeration",
      typeSE: "ObjectBelonging",
      implicitValueYAML: "Native",
      toYAML: false,
      fromYAML: false,
      xmlParents: properties,
    },
    extendedConfigurationObject: {
      yaml: "ОбъектРасширяемойКонфигурации",
      type: "string",
      runtimeOnly: true,
    },
  },
} as const satisfies MetadataItemRule
