import { V8_MDCLASSES_ROOT } from "~/metadata/orchestration/appliedObject/presets"
import { MetadataItemRule } from "~/metadata/orchestration/property/types"

const constantProperties = ["Properties"]

export const MetadataConstantRules = {
  itemType: "MetadataConstant",
  itemTypePrefix: "Константа",
  xmlDir: "Constants",
  properties: {
    xmlRoot: {
      type: "XMLRoot",
      container: "Constant",
      rootAttributes: V8_MDCLASSES_ROOT,
      forReferenceOnly: true,
      toYAML: false,
      fromYAML: false,
    },
    internalInfo: {
      type: "InternalInfo",
      xmlParents: [],
      forReferenceOnly: true,
      items: [
        { name: "ConstantManager", category: "Manager" },
        { name: "ConstantValueManager", category: "ValueManager" },
        { name: "ConstantValueKey", category: "ValueKey" },
      ],
    },
    uuid: {
      type: "uuid",
      xml: "_uuid",
      forReferenceOnly: true,
      xmlParents: [],
    },
    name: {
      type: "string",
      xmlParents: constantProperties,
      required: true,
    },
    synonym: {
      yaml: "Синоним",
      type: "I8nText",
      xmlParents: constantProperties,
      defaultValueXMLRaw: "",
    },
    comment: {
      yaml: "Комментарий",
      type: "string",
      xmlParents: constantProperties,
      defaultValueXMLRaw: "",
    },
    type: {
      yaml: "Тип",
      type: "TypeDescription",
      xmlParents: constantProperties,
    },
    useStandardCommands: {
      yaml: "ИспользоватьСтандартныеКоманды",
      type: "boolean",
      defaultValueXML: true,
      defaultValueYAML: true,
      xmlParents: constantProperties,
    },
    defaultForm: {
      yaml: "ОсновнаяФорма",
      type: "string",
      xmlParents: constantProperties,
      referenceScope: { target: "this", kind: "Form" },
      defaultValueXMLRaw: "",
    },
    extendedPresentation: {
      yaml: "РасширенноеПредставление",
      type: "I8nText",
      xmlParents: constantProperties,
      defaultValueXMLRaw: "",
    },
    explanation: {
      yaml: "Пояснение",
      type: "I8nText",
      xmlParents: constantProperties,
      defaultValueXMLRaw: "",
    },
    passwordMode: {
      yaml: "РежимПароля",
      type: "boolean",
      defaultValueXML: false,
      defaultValueYAML: false,
      xmlParents: constantProperties,
    },
    format: {
      yaml: "Формат",
      type: "I8nText",
      xmlParents: constantProperties,
      defaultValueXMLRaw: "",
    },
    editFormat: {
      yaml: "ФорматРедактирования",
      type: "I8nText",
      xmlParents: constantProperties,
      defaultValueXMLRaw: "",
    },
    toolTip: {
      yaml: "Подсказка",
      type: "I8nText",
      xmlParents: constantProperties,
      defaultValueXMLRaw: "",
    },
    markNegatives: {
      yaml: "ВыделятьОтрицательные",
      type: "boolean",
      defaultValueXML: false,
      defaultValueYAML: false,
      xmlParents: constantProperties,
    },
    mask: {
      yaml: "Маска",
      type: "string",
      xmlParents: constantProperties,
      defaultValueXMLRaw: "",
    },
    multiLine: {
      yaml: "МногострочныйРежим",
      type: "boolean",
      defaultValueXML: false,
      defaultValueYAML: false,
      xmlParents: constantProperties,
    },
    extendedEdit: {
      yaml: "РасширенноеРедактирование",
      type: "boolean",
      defaultValueXML: false,
      defaultValueYAML: false,
      xmlParents: constantProperties,
    },
    minValue: {
      yaml: "МинимальноеЗначение",
      type: "MinMaxValue",
      typedXML: "xs:string",
      xmlParents: constantProperties,
      defaultValueXMLRaw: { "_xsi:nil": true },
    },
    maxValue: {
      yaml: "МаксимальноеЗначение",
      type: "MinMaxValue",
      typedXML: "xs:string",
      xmlParents: constantProperties,
      defaultValueXMLRaw: { "_xsi:nil": true },
    },
    fillChecking: {
      yaml: "ПроверкаЗаполнения",
      type: "SystemEnumeration",
      typeSE: "FillChecking",
      defaultValueXML: "DontCheck",
      defaultValueYAML: "DontCheck",
      xmlParents: constantProperties,
    },
    choiceFoldersAndItems: {
      yaml: "ВыборГруппИЭлементов",
      type: "SystemEnumeration",
      typeSE: "FoldersAndItemsUse",
      defaultValueXML: "Items",
      defaultValueYAML: "Items",
      xmlParents: constantProperties,
    },
    choiceParameterLinks: {
      yaml: "СвязиПараметровВыбора",
      type: "ChoiceParameterLinks",
      xmlParents: constantProperties,
      defaultValueXMLRaw: "",
    },
    choiceParameters: {
      yaml: "ПараметрыВыбора",
      type: "ChoiceParameters",
      xmlParents: constantProperties,
      defaultValueXMLRaw: "",
    },
    quickChoice: {
      yaml: "БыстрыйВыбор",
      type: "SystemEnumeration",
      typeSE: "UseQuickChoice",
      defaultValueXML: "Auto",
      defaultValueYAML: "Auto",
      xmlParents: constantProperties,
    },
    choiceForm: {
      yaml: "ФормаВыбора",
      type: "string",
      xmlParents: constantProperties,
      referenceScope: { target: "this", kind: "Form" },
      defaultValueXMLRaw: "",
    },
    linkByType: {
      yaml: "СвязьПоТипу",
      type: "TypeLink",
      xmlParents: constantProperties,
      defaultValueXMLRaw: "",
    },
    choiceHistoryOnInput: {
      yaml: "ИсторияВыбораПриВводе",
      type: "SystemEnumeration",
      typeSE: "ChoiceHistoryOnInput",
      defaultValueXML: "Auto",
      defaultValueYAML: "Auto",
      xmlParents: constantProperties,
    },
    dataLockControlMode: {
      yaml: "РежимУправленияБлокировкойДанных",
      type: "SystemEnumeration",
      typeSE: "DefaultDataLockControlMode",
      defaultValueXML: "Managed",
      defaultValueYAML: "Managed",
      xmlParents: constantProperties,
    },
    dataHistory: {
      yaml: "ИсторияДанных",
      type: "SystemEnumeration",
      typeSE: "DataHistoryUse",
      defaultValueXML: "DontUse",
      defaultValueYAML: "DontUse",
      xmlParents: constantProperties,
    },
    updateDataHistoryImmediatelyAfterWrite: {
      yaml: "ОбновлятьИсториюДанныхСразуПослеЗаписи",
      type: "boolean",
      defaultValueXML: false,
      defaultValueYAML: false,
      xmlParents: constantProperties,
    },
    executeAfterWriteDataHistoryVersionProcessing: {
      yaml: "ВыполнятьОбработкуПослеЗаписиВерсииИсторииДанных",
      type: "boolean",
      defaultValueXML: false,
      defaultValueYAML: false,
      xmlParents: constantProperties,
    },
    objectBelonging: {
      yaml: "ПринадлежностьОбъекта",
      type: "SystemEnumeration",
      typeSE: "ObjectBelonging",
      defaultValueYAML: "Native",
      toYAML: false,
      fromYAML: false,
      xmlParents: constantProperties,
    },
    extendedConfigurationObject: {
      yaml: "ОбъектРасширяемойКонфигурации",
      type: "string",
      runtimeOnly: true,
    },
    managerModule: {
      type: "Module",
      nkdkPath: "МодульМенеджера.bsl",
      xmlPath: "Ext/ManagerModule.bsl",
    },
    valueManagerModule: {
      type: "Module",
      nkdkPath: "МодульМенеджераЗначения.bsl",
      xmlPath: "Ext/ValueManagerModule.bsl",
    },
  },
} as const satisfies MetadataItemRule
