import * as z from "zod"
import { TElementRules } from "../types"
import * as SE from "~/lib/metadata/systemEnumerations/types"
import { ZI8nText, ZI8nTextXML } from "~/lib/metadata/commonObjects/i8nText/types"
import { ZColor, ZColorXML } from "~/lib/metadata/commonObjects/color/types"
import { ZTypeDescription, ZTypeDescriptionXML } from "~/lib/metadata/commonObjects/typeDescription/types"
import { ZPicture, ZPictureXML } from "~/lib/metadata/commonObjects/pictures/types"
import { ZFont, ZFontXML } from "~/lib/metadata/commonObjects/font/types"
import { ZFormDecoration, ZFormDecorationXML } from "../formDecoration/types"
import { ZTable, ZTableXML } from "../table/types"
import { ZCommandBar, ZCommandBarXML } from "../commandBar/types"
import { ZChoiceList, ZChoiceListXML } from "~/lib/metadata/commonObjects/choiceList/types"
import { ZTypeLink, ZTypeLinkXML } from "~/lib/metadata/commonObjects/typeLink/types"
import { ZChoiceParameterLinks, ZChoiceParameterLinksXML } from "~/lib/metadata/commonObjects/сhoiceParameterLinks/types"
import { ZUserVisible, ZUserVisibleXML } from "~/lib/metadata/commonObjects/userVisible/types"
import { exportColorToXML } from "~/lib/metadata/commonObjects/color/exportToXML"
import { importColorFromXML } from "~/lib/metadata/commonObjects/color/importFromXML"
import { exportFontToXML } from "~/lib/metadata/commonObjects/font/exportToXML"
import { importFontFromXML } from "~/lib/metadata/commonObjects/font/importFromXML"
import { exportI8nTextToXML } from "~/lib/metadata/commonObjects/i8nText/exportI8nTextToXML"
import { importI8nTextFromXML } from "~/lib/metadata/commonObjects/i8nText/importI8nTextFromXML"
import { exportTypeDescriptionToXML } from "~/lib/metadata/commonObjects/typeDescription/exportToXML"
import { importTypeDescriptionFromXML } from "~/lib/metadata/commonObjects/typeDescription/importFromXML"
import { exportPictureToXML } from "~/lib/metadata/commonObjects/pictures/exportToXML"
import { importPictureFromXML } from "~/lib/metadata/commonObjects/pictures/importFromXML"
import { exportTableToXML } from "../table/exportToXML"
import { importTableFromXML } from "../table/importFromXML"
import { exportFormDecorationToXML } from "../formDecoration/exportToXML"
import { importFormDecorationFromXML } from "../formDecoration/importFromXML"
import { exportCommandBarToXML } from "../commandBar/exportToXML"
import { importCommandBarFromXML } from "../commandBar/importFromXML"
import { exportChoiceListToXML } from "~/lib/metadata/commonObjects/choiceList/exportToXML"
import { importChoiceListFromXML } from "~/lib/metadata/commonObjects/choiceList/importFromXML"
import { exportTypeLinkToXML } from "~/lib/metadata/commonObjects/typeLink/exportToXML"
import { importTypeLinkFromXML } from "~/lib/metadata/commonObjects/typeLink/importFromXML"
import { exportChoiceParameterLinksToXML } from "~/lib/metadata/commonObjects/сhoiceParameterLinks/exportToXML"
import { importChoiceParameterLinksFromXML } from "~/lib/metadata/commonObjects/сhoiceParameterLinks/importFromXML"
import { exportUserVisibleToXML } from "~/lib/metadata/commonObjects/userVisible/exportToXML"
import { importUserVisibleFromXML } from "~/lib/metadata/commonObjects/userVisible/importFromXML"


export const ZInputFieldRules: TElementRules = {
  "autoCellHeight": {
    get type() { return z.boolean() },
    nameXML: "AutoCellHeight",
    get typeXML() { return z.boolean() },
    nameEnterprise: "АвтоВысотаЯчейки",
    format: undefined,
    isProperties: ()=> true,
  },
  "cellHyperlink": {
    get type() { return z.boolean() },
    nameXML: "CellHyperlink",
    get typeXML() { return z.boolean() },
    nameEnterprise: "ГиперссылкаЯчейки",
    format: undefined,
    isProperties: ()=> true,
  },
  "contextMenu": {
    get type() { return ZCommandBar },
    nameXML: "ContextMenu",
    get typeXML() { return ZCommandBarXML },
    nameEnterprise: "КонтекстноеМеню",
    format: undefined,
    isProperties: ()=> true,
  },
  "dataPath": {
    get type() { return z.string() },
    nameXML: "DataPath",
    get typeXML() { return z.string() },
    nameEnterprise: "ПутьКДанным",
    format: undefined,
    isProperties: ()=> true,
  },
  "defaultItem": {
    get type() { return z.boolean() },
    nameXML: "DefaultItem",
    get typeXML() { return z.boolean() },
    nameEnterprise: "АктивизироватьПоУмолчанию",
    format: undefined,
    isProperties: ()=> true,
  },
  "displayImportance": {
    get type() { return SE.ZDisplayImportance },
    nameXML: "_DisplayImportance",
    get typeXML() { return SE.ZDisplayImportance },
    nameEnterprise: "ВажностьПриОтображении",
    format: undefined,
    isProperties: ()=> true,
  },
  "editMode": {
    get type() { return SE.ZColumnEditMode },
    nameXML: "EditMode",
    get typeXML() { return SE.ZColumnEditMode },
    nameEnterprise: "РежимРедактирования",
    format: undefined,
    isProperties: ()=> true,
  },
  "enabled": {
    get type() { return z.boolean() },
    nameXML: "Enabled",
    get typeXML() { return z.boolean() },
    nameEnterprise: "Доступность",
    format: undefined,
    isProperties: ()=> true,
  },
  "extendedTooltip": {
    get type() { return ZFormDecoration },
    nameXML: "ExtendedTooltip",
    get typeXML() { return ZFormDecorationXML },
    nameEnterprise: "РасширеннаяПодсказка",
    format: undefined,
    isProperties: ()=> true,
  },
  "fixingInTable": {
    get type() { return SE.ZFixingInTable },
    nameXML: "FixingInTable",
    get typeXML() { return SE.ZFixingInTable },
    nameEnterprise: "ФиксацияВТаблице",
    format: undefined,
    isProperties: ()=> true,
  },
  "footerBackColor": {
    get type() { return ZColor },
    nameXML: "FooterBackColor",
    get typeXML() { return ZColorXML },
    nameEnterprise: "ЦветФонаПодвала",
    format: undefined,
    isProperties: ()=> true,
  },
  "footerDataPath": {
    get type() { return z.string() },
    nameXML: "FooterDataPath",
    get typeXML() { return z.string() },
    nameEnterprise: "ПутьКДаннымПодвала",
    format: undefined,
    isProperties: ()=> true,
  },
  "footerFont": {
    get type() { return ZFont },
    nameXML: "FooterFont",
    get typeXML() { return ZFontXML },
    nameEnterprise: "ШрифтПодвала",
    format: undefined,
    isProperties: ()=> true,
  },
  "footerHorizontalAlign": {
    get type() { return SE.ZItemHorizontalLocation },
    nameXML: "FooterHorizontalAlign",
    get typeXML() { return SE.ZItemHorizontalLocation },
    nameEnterprise: "ГоризонтальноеПоложениеВПодвале",
    format: undefined,
    isProperties: ()=> true,
  },
  "footerPicture": {
    get type() { return ZPicture },
    nameXML: "FooterPicture",
    get typeXML() { return ZPictureXML },
    nameEnterprise: "КартинкаПодвала",
    format: undefined,
    isProperties: ()=> true,
  },
  "footerText": {
    get type() { return ZI8nText },
    nameXML: "FooterText",
    get typeXML() { return ZI8nTextXML },
    nameEnterprise: "ТекстПодвала",
    format: undefined,
    isProperties: ()=> true,
  },
  "footerTextColor": {
    get type() { return ZColor },
    nameXML: "FooterTextColor",
    get typeXML() { return ZColorXML },
    nameEnterprise: "ЦветТекстаПодвала",
    format: undefined,
    isProperties: ()=> true,
  },
  "headerHorizontalAlign": {
    get type() { return SE.ZItemHorizontalLocation },
    nameXML: "HeaderHorizontalAlign",
    get typeXML() { return SE.ZItemHorizontalLocation },
    nameEnterprise: "ГоризонтальноеПоложениеВШапке",
    format: undefined,
    isProperties: ()=> true,
  },
  "headerPicture": {
    get type() { return ZPicture },
    nameXML: "HeaderPicture",
    get typeXML() { return ZPictureXML },
    nameEnterprise: "КартинкаШапки",
    format: undefined,
    isProperties: ()=> true,
  },
  "horizontalAlign": {
    get type() { return SE.ZItemHorizontalLocation },
    nameXML: "HorizontalAlign",
    get typeXML() { return SE.ZItemHorizontalLocation },
    nameEnterprise: "ГоризонтальноеПоложение",
    format: undefined,
    isProperties: ()=> true,
  },
  "horizontalAlignInGroup": {
    get type() { return SE.ZItemHorizontalLocation },
    nameXML: "HorizontalAlignInGroup",
    get typeXML() { return SE.ZItemHorizontalLocation },
    nameEnterprise: "ГоризонтальноеПоложениеВГруппе",
    format: undefined,
    isProperties: ()=> true,
  },
  "readOnly": {
    get type() { return z.boolean() },
    nameXML: "ReadOnly",
    get typeXML() { return z.boolean() },
    nameEnterprise: "ТолькоПросмотр",
    format: undefined,
    isProperties: ()=> true,
  },
  "shortcut": {
    get type() { return z.string() },
    nameXML: "Shortcut",
    get typeXML() { return z.string() },
    nameEnterprise: "СочетаниеКлавиш",
    format: undefined,
    isProperties: ()=> true,
  },
  "showInFooter": {
    get type() { return z.boolean() },
    nameXML: "ShowInFooter",
    get typeXML() { return z.boolean() },
    nameEnterprise: "ОтображатьВПодвале",
    format: undefined,
    isProperties: ()=> true,
  },
  "showInHeader": {
    get type() { return z.boolean() },
    nameXML: "ShowInHeader",
    get typeXML() { return z.boolean() },
    nameEnterprise: "ОтображатьВШапке",
    format: undefined,
    isProperties: ()=> true,
  },
  "skipOnInput": {
    get type() { return z.boolean() },
    nameXML: "SkipOnInput",
    get typeXML() { return z.boolean() },
    nameEnterprise: "ПропускатьПриВводе",
    format: undefined,
    isProperties: ()=> true,
  },
  "table": {
    get type() { return ZTable },
    nameXML: "Table",
    get typeXML() { return ZTableXML },
    nameEnterprise: "Таблица",
    format: undefined,
    isProperties: ()=> true,
  },
  "title": {
    get type() { return ZI8nText },
    nameXML: "Title",
    get typeXML() { return ZI8nTextXML },
    nameEnterprise: "Заголовок",
    format: undefined,
    isProperties: ()=> true,
  },
  "titleBackColor": {
    get type() { return ZColor },
    nameXML: "TitleBackColor",
    get typeXML() { return ZColorXML },
    nameEnterprise: "ЦветФонаЗаголовка",
    format: undefined,
    isProperties: ()=> true,
  },
  "titleFont": {
    get type() { return ZFont },
    nameXML: "TitleFont",
    get typeXML() { return ZFontXML },
    nameEnterprise: "ШрифтЗаголовка",
    format: undefined,
    isProperties: ()=> true,
  },
  "titleHeight": {
    get type() { return z.number() },
    nameXML: "TitleHeight",
    get typeXML() { return z.number() },
    nameEnterprise: "ВысотаЗаголовка",
    format: undefined,
    isProperties: ()=> true,
  },
  "titleLocation": {
    get type() { return SE.ZFormItemTitleLocation },
    nameXML: "TitleLocation",
    get typeXML() { return SE.ZFormItemTitleLocation },
    nameEnterprise: "ПоложениеЗаголовка",
    format: undefined,
    isProperties: ()=> true,
  },
  "titleTextColor": {
    get type() { return ZColor },
    nameXML: "TitleTextColor",
    get typeXML() { return ZColorXML },
    nameEnterprise: "ЦветТекстаЗаголовка",
    format: undefined,
    isProperties: ()=> true,
  },
  "toolTip": {
    get type() { return ZI8nText },
    nameXML: "ToolTip",
    get typeXML() { return ZI8nTextXML },
    nameEnterprise: "Подсказка",
    format: undefined,
    isProperties: ()=> true,
  },
  "toolTipRepresentation": {
    get type() { return SE.ZToolTipRepresentation },
    nameXML: "ToolTipRepresentation",
    get typeXML() { return SE.ZToolTipRepresentation },
    nameEnterprise: "ОтображениеПодсказки",
    format: undefined,
    isProperties: ()=> true,
  },
  "type": {
    get type() { return SE.ZFormFieldType },
    nameXML: "Type",
    get typeXML() { return SE.ZFormFieldType },
    nameEnterprise: "Вид",
    format: undefined,
    isProperties: ()=> true,
  },
  "typeRestriction": {
    get type() { return ZTypeDescription },
    nameXML: "TypeRestriction",
    get typeXML() { return ZTypeDescriptionXML },
    nameEnterprise: "ОграничениеТипа",
    format: undefined,
    isProperties: ()=> true,
  },
  "userVisible": {
    get type() { return ZUserVisible },
    nameXML: "UserVisible",
    get typeXML() { return ZUserVisibleXML },
    nameEnterprise: "ПользовательскаяВидимость",
    format: undefined,
    isProperties: ()=> true,
  },
  "verticalAlign": {
    get type() { return SE.ZItemVerticalAlign },
    nameXML: "VerticalAlign",
    get typeXML() { return SE.ZItemVerticalAlign },
    nameEnterprise: "ВертикальноеПоложение",
    format: undefined,
    isProperties: ()=> true,
  },
  "verticalAlignInGroup": {
    get type() { return SE.ZItemVerticalAlign },
    nameXML: "VerticalAlignInGroup",
    get typeXML() { return SE.ZItemVerticalAlign },
    nameEnterprise: "ВертикальноеПоложениеВГруппе",
    format: undefined,
    isProperties: ()=> true,
  },
  "visible": {
    get type() { return z.boolean() },
    nameXML: "Visible",
    get typeXML() { return z.boolean() },
    nameEnterprise: "Видимость",
    format: undefined,
    isProperties: ()=> true,
  },
  "warningOnEdit": {
    get type() { return ZI8nText },
    nameXML: "WarningOnEdit",
    get typeXML() { return ZI8nTextXML },
    nameEnterprise: "ПредупреждениеПриРедактировании",
    format: undefined,
    isProperties: ()=> true,
  },
  "warningOnEditRepresentation": {
    get type() { return SE.ZWarningOnEditRepresentation },
    nameXML: "WarningOnEditRepresentation",
    get typeXML() { return SE.ZWarningOnEditRepresentation },
    nameEnterprise: "ОтображениеПредупрежденияПриРедактировании",
    format: undefined,
    isProperties: ()=> true,
  },
  "allowInputEmptyMultipleValues": {
    get type() { return z.boolean() },
    nameXML: "AllowInputEmptyMultipleValues",
    get typeXML() { return z.boolean() },
    nameEnterprise: "РазрешитьВводПустыхМножественныхЗначений",
    format: undefined,
    isProperties: ()=> true,
  },
  "allowMultipleValuesDuplicates": {
    get type() { return z.boolean() },
    nameXML: "AllowMultipleValuesDuplicates",
    get typeXML() { return z.boolean() },
    nameEnterprise: "РазрешитьДублированиеМножественныхЗначений",
    format: undefined,
    isProperties: ()=> true,
  },
  "autoCapitalizationOnTextInput": {
    get type() { return SE.ZAutoCapitalizationOnTextInput },
    nameXML: "AutoCapitalizationOnTextInput",
    get typeXML() { return SE.ZAutoCapitalizationOnTextInput },
    nameEnterprise: "АвтоИзменениеРегистраПриВводеТекста",
    format: undefined,
    isProperties: ()=> true,
  },
  "autoChoiceIncomplete": {
    get type() { return z.boolean() },
    nameXML: "AutoChoiceIncomplete",
    get typeXML() { return z.boolean() },
    nameEnterprise: "АвтоВыборНезаполненного",
    format: undefined,
    isProperties: ()=> true,
  },
  "autoCorrectionOnTextInput": {
    get type() { return SE.ZAutoCorrectionOnTextInput },
    nameXML: "AutoCorrectionOnTextInput",
    get typeXML() { return SE.ZAutoCorrectionOnTextInput },
    nameEnterprise: "АвтоИсправлениеПриВводеТекста",
    format: undefined,
    isProperties: ()=> true,
  },
  "autoFillHint": {
    get type() { return SE.ZInputFieldAutofillHint },
    nameXML: "AutoFillHint",
    get typeXML() { return SE.ZInputFieldAutofillHint },
    nameEnterprise: "ПодсказкаАвтозаполнения",
    format: undefined,
    isProperties: ()=> true,
  },
  "autoMarkIncomplete": {
    get type() { return z.boolean() },
    nameXML: "AutoMarkIncomplete",
    get typeXML() { return z.boolean() },
    nameEnterprise: "АвтоОтметкаНезаполненного",
    format: undefined,
    isProperties: ()=> true,
  },
  "autoMaxHeight": {
    get type() { return z.boolean() },
    nameXML: "AutoMaxHeight",
    get typeXML() { return z.boolean() },
    nameEnterprise: "АвтоМаксимальнаяВысота",
    format: undefined,
    isProperties: ()=> true,
  },
  "autoMaxWidth": {
    get type() { return z.boolean() },
    nameXML: "AutoMaxWidth",
    get typeXML() { return z.boolean() },
    nameEnterprise: "АвтоМаксимальнаяШирина",
    format: undefined,
    isProperties: ()=> true,
  },
  "autoShowClearButton": {
    get type() { return SE.ZAutoShowClearButtonMode },
    nameXML: "AutoShowClearButton",
    get typeXML() { return SE.ZAutoShowClearButtonMode },
    nameEnterprise: "АвтоОтображениеКнопкиОчистки",
    format: undefined,
    isProperties: ()=> true,
  },
  "autoShowOpenButton": {
    get type() { return SE.ZAutoShowOpenButtonMode },
    nameXML: "AutoShowOpenButton",
    get typeXML() { return SE.ZAutoShowOpenButtonMode },
    nameEnterprise: "АвтоОтображениеКнопкиОткрытия",
    format: undefined,
    isProperties: ()=> true,
  },
  "availableTypes": {
    get type() { return ZTypeDescription },
    nameXML: "AvailableTypes",
    get typeXML() { return ZTypeDescriptionXML },
    nameEnterprise: "ДоступныеТипы",
    format: undefined,
    isProperties: ()=> true,
  },
  "backColor": {
    get type() { return ZColor },
    nameXML: "BackColor",
    get typeXML() { return ZColorXML },
    nameEnterprise: "ЦветФона",
    format: undefined,
    isProperties: ()=> true,
  },
  "borderColor": {
    get type() { return ZColor },
    nameXML: "BorderColor",
    get typeXML() { return ZColorXML },
    nameEnterprise: "ЦветРамки",
    format: undefined,
    isProperties: ()=> true,
  },
  "choiceButton": {
    get type() { return z.boolean() },
    nameXML: "ChoiceButton",
    get typeXML() { return z.boolean() },
    nameEnterprise: "КнопкаВыбора",
    format: undefined,
    isProperties: ()=> true,
  },
  "choiceButtonPicture": {
    get type() { return ZPicture },
    nameXML: "ChoiceButtonPicture",
    get typeXML() { return ZPictureXML },
    nameEnterprise: "КартинкаКнопкиВыбора",
    format: undefined,
    isProperties: ()=> true,
  },
  "choiceButtonRepresentation": {
    get type() { return SE.ZChoiceButtonRepresentation },
    nameXML: "ChoiceButtonRepresentation",
    get typeXML() { return SE.ZChoiceButtonRepresentation },
    nameEnterprise: "ОтображениеКнопкиВыбора",
    format: undefined,
    isProperties: ()=> true,
  },
  "choiceFoldersAndItems": {
    get type() { return SE.ZFoldersAndItems },
    nameXML: "ChoiceFoldersAndItems",
    get typeXML() { return SE.ZFoldersAndItems },
    nameEnterprise: "ВыборГруппИЭлементов",
    format: undefined,
    isProperties: ()=> true,
  },
  "choiceForm": {
    get type() { return z.string() },
    nameXML: "ChoiceForm",
    get typeXML() { return z.string() },
    nameEnterprise: "ФормаВыбора",
    format: undefined,
    isProperties: ()=> true,
  },
  "choiceHistoryOnInput": {
    get type() { return SE.ZChoiceHistoryOnInput },
    nameXML: "ChoiceHistoryOnInput",
    get typeXML() { return SE.ZChoiceHistoryOnInput },
    nameEnterprise: "ИсторияВыбораПриВводе",
    format: undefined,
    isProperties: ()=> true,
  },
  "choiceList": {
    get type() { return ZChoiceList },
    nameXML: "ChoiceList",
    get typeXML() { return ZChoiceListXML },
    nameEnterprise: "СписокВыбора",
    format: undefined,
    isProperties: ()=> true,
  },
  "choiceListButton": {
    get type() { return z.boolean() },
    nameXML: "ChoiceListButton",
    get typeXML() { return z.boolean() },
    nameEnterprise: "КнопкаСпискаВыбора",
    format: undefined,
    isProperties: ()=> true,
  },
  "choiceListHeight": {
    get type() { return z.number() },
    nameXML: "ChoiceListHeight",
    get typeXML() { return z.number() },
    nameEnterprise: "ВысотаСпискаВыбора",
    format: undefined,
    isProperties: ()=> true,
  },
  "choiceParameterLinks": {
    get type() { return ZChoiceParameterLinks },
    nameXML: "ChoiceParameterLinks",
    get typeXML() { return ZChoiceParameterLinksXML },
    nameEnterprise: "СвязиПараметровВыбора",
    format: undefined,
    isProperties: ()=> true,
  },
  "choiceParameters": {
    get type() { return ZChoiceParameterLinks },
    nameXML: "ChoiceParameters",
    get typeXML() { return ZChoiceParameterLinksXML },
    nameEnterprise: "ПараметрыВыбора",
    format: undefined,
    isProperties: ()=> true,
  },
  "chooseType": {
    get type() { return z.boolean() },
    nameXML: "ChooseType",
    get typeXML() { return z.boolean() },
    nameEnterprise: "ВыбиратьТип",
    format: undefined,
    isProperties: ()=> true,
  },
  "clearButton": {
    get type() { return z.boolean() },
    nameXML: "ClearButton",
    get typeXML() { return z.boolean() },
    nameEnterprise: "КнопкаОчистки",
    format: undefined,
    isProperties: ()=> true,
  },
  "createButton": {
    get type() { return z.boolean() },
    nameXML: "CreateButton",
    get typeXML() { return z.boolean() },
    nameEnterprise: "КнопкаСоздания",
    format: undefined,
    isProperties: ()=> true,
  },
  "dropListButton": {
    get type() { return z.boolean() },
    nameXML: "DropListButton",
    get typeXML() { return z.boolean() },
    nameEnterprise: "КнопкаВыпадающегоСписка",
    format: undefined,
    isProperties: ()=> true,
  },
  "dropListWidth": {
    get type() { return z.number() },
    nameXML: "DropListWidth",
    get typeXML() { return z.number() },
    nameEnterprise: "ШиринаВыпадающегоСписка",
    format: undefined,
    isProperties: ()=> true,
  },
  "editFormat": {
    get type() { return ZI8nText },
    nameXML: "EditFormat",
    get typeXML() { return ZI8nTextXML },
    nameEnterprise: "ФорматРедактирования",
    format: undefined,
    isProperties: ()=> true,
  },
  "editText": {
    get type() { return z.string() },
    nameXML: "EditText",
    get typeXML() { return z.string() },
    nameEnterprise: "ТекстРедактирования",
    format: undefined,
    isProperties: ()=> true,
  },
  "editTextUpdate": {
    get type() { return SE.ZEditTextUpdate },
    nameXML: "EditTextUpdate",
    get typeXML() { return SE.ZEditTextUpdate },
    nameEnterprise: "ОбновлениеТекстаРедактирования",
    format: undefined,
    isProperties: ()=> true,
  },
  "extendedEdit": {
    get type() { return z.boolean() },
    nameXML: "ExtendedEdit",
    get typeXML() { return z.boolean() },
    nameEnterprise: "РасширенноеРедактирование",
    format: undefined,
    isProperties: ()=> true,
  },
  "font": {
    get type() { return ZFont },
    nameXML: "Font",
    get typeXML() { return ZFontXML },
    nameEnterprise: "Шрифт",
    format: undefined,
    isProperties: ()=> true,
  },
  "format": {
    get type() { return ZI8nText },
    nameXML: "Format",
    get typeXML() { return ZI8nTextXML },
    nameEnterprise: "Формат",
    format: undefined,
    isProperties: ()=> true,
  },
  "height": {
    get type() { return z.number() },
    nameXML: "Height",
    get typeXML() { return z.number() },
    nameEnterprise: "Высота",
    format: undefined,
    isProperties: ()=> true,
  },
  "heightControlVariant": {
    get type() { return SE.ZItemHeightControlVariant },
    nameXML: "HeightControlVariant",
    get typeXML() { return SE.ZItemHeightControlVariant },
    nameEnterprise: "ВариантУправленияВысотой",
    format: undefined,
    isProperties: ()=> true,
  },
  "horizontalStretch": {
    get type() { return z.boolean() },
    nameXML: "HorizontalStretch",
    get typeXML() { return z.boolean() },
    nameEnterprise: "РастягиватьПоГоризонтали",
    format: undefined,
    isProperties: ()=> true,
  },
  "incompleteChoiceMode": {
    get type() { return SE.ZIncompleteChoiceMode },
    nameXML: "IncompleteChoiceMode",
    get typeXML() { return SE.ZIncompleteChoiceMode },
    nameEnterprise: "РежимВыбораНезаполненного",
    format: undefined,
    isProperties: ()=> true,
  },
  "inputHint": {
    get type() { return ZI8nText },
    nameXML: "InputHint",
    get typeXML() { return ZI8nTextXML },
    nameEnterprise: "ПодсказкаВвода",
    format: undefined,
    isProperties: ()=> true,
  },
  "listChoiceMode": {
    get type() { return z.boolean() },
    nameXML: "ListChoiceMode",
    get typeXML() { return z.boolean() },
    nameEnterprise: "РежимВыбораИзСписка",
    format: undefined,
    isProperties: ()=> true,
  },
  "markIncomplete": {
    get type() { return z.boolean() },
    nameXML: "MarkIncomplete",
    get typeXML() { return z.boolean() },
    nameEnterprise: "ОтметкаНезаполненного",
    format: undefined,
    isProperties: ()=> true,
  },
  "markNegatives": {
    get type() { return z.boolean() },
    nameXML: "MarkNegatives",
    get typeXML() { return z.boolean() },
    nameEnterprise: "ВыделятьОтрицательные",
    format: undefined,
    isProperties: ()=> true,
  },
  "mask": {
    get type() { return z.string() },
    nameXML: "Mask",
    get typeXML() { return z.string() },
    nameEnterprise: "Маска",
    format: undefined,
    isProperties: ()=> true,
  },
  "maxHeight": {
    get type() { return z.number() },
    nameXML: "MaxHeight",
    get typeXML() { return z.number() },
    nameEnterprise: "МаксимальнаяВысота",
    format: undefined,
    isProperties: ()=> true,
  },
  "maxValue": {
    get type() { return z.number() },
    nameXML: "MaxValue",
    get typeXML() { return z.number() },
    nameEnterprise: "МаксимальноеЗначение",
    format: undefined,
    isProperties: ()=> true,
  },
  "maxWidth": {
    get type() { return z.number() },
    nameXML: "MaxWidth",
    get typeXML() { return z.number() },
    nameEnterprise: "МаксимальнаяШирина",
    format: undefined,
    isProperties: ()=> true,
  },
  "minValue": {
    get type() { return z.number() },
    nameXML: "MinValue",
    get typeXML() { return z.number() },
    nameEnterprise: "МинимальноеЗначение",
    format: undefined,
    isProperties: ()=> true,
  },
  "multiLine": {
    get type() { return z.boolean() },
    nameXML: "MultiLine",
    get typeXML() { return z.boolean() },
    nameEnterprise: "МногострочныйРежим",
    format: undefined,
    isProperties: ()=> true,
  },
  "multipleValuePictureDataPath": {
    get type() { return z.string() },
    nameXML: "MultipleValuePictureDataPath",
    get typeXML() { return z.string() },
    nameEnterprise: "ПутьКДаннымКартинкиМножественногоЗначения",
    format: undefined,
    isProperties: ()=> true,
  },
  "multipleValuePictureShape": {
    get type() { return SE.ZInputFieldMultipleValuePictureShape },
    nameXML: "MultipleValuePictureShape",
    get typeXML() { return SE.ZInputFieldMultipleValuePictureShape },
    nameEnterprise: "ФигураКартинкиМножественногоЗначения",
    format: undefined,
    isProperties: ()=> true,
  },
  "multipleValuePictureSize": {
    get type() { return SE.ZInputFieldMultipleValuePictureSize },
    nameXML: "MultipleValuePictureSize",
    get typeXML() { return SE.ZInputFieldMultipleValuePictureSize },
    nameEnterprise: "РазмерКартинкиМножественногоЗначения",
    format: undefined,
    isProperties: ()=> true,
  },
  "multipleValuePresentationDataPath": {
    get type() { return z.string() },
    nameXML: "MultipleValuePresentationDataPath",
    get typeXML() { return z.string() },
    nameEnterprise: "ПутьКДаннымПредставленияМножественногоЗначения",
    format: undefined,
    isProperties: ()=> true,
  },
  "multipleValuesBackColor": {
    get type() { return ZColor },
    nameXML: "MultipleValuesBackColor",
    get typeXML() { return ZColorXML },
    nameEnterprise: "ЦветФонаМножественныхЗначений",
    format: undefined,
    isProperties: ()=> true,
  },
  "multipleValuesExtendedEdit": {
    get type() { return z.boolean() },
    nameXML: "MultipleValuesExtendedEdit",
    get typeXML() { return z.boolean() },
    nameEnterprise: "РасширенноеРедактированиеМножественныхЗначений",
    format: undefined,
    isProperties: ()=> true,
  },
  "multipleValuesFont": {
    get type() { return ZFont },
    nameXML: "MultipleValuesFont",
    get typeXML() { return ZFontXML },
    nameEnterprise: "ШрифтМножественныхЗначений",
    format: undefined,
    isProperties: ()=> true,
  },
  "multipleValuesHyperlink": {
    get type() { return z.boolean() },
    nameXML: "MultipleValuesHyperlink",
    get typeXML() { return z.boolean() },
    nameEnterprise: "ГиперссылкаМножественныхЗначений",
    format: undefined,
    isProperties: ()=> true,
  },
  "multipleValuesPicture": {
    get type() { return ZPicture },
    nameXML: "MultipleValuesPicture",
    get typeXML() { return ZPictureXML },
    nameEnterprise: "КартинкаМножественныхЗначений",
    format: undefined,
    isProperties: ()=> true,
  },
  "multipleValuesTextColor": {
    get type() { return ZColor },
    nameXML: "MultipleValuesTextColor",
    get typeXML() { return ZColorXML },
    nameEnterprise: "ЦветТекстаМножественныхЗначений",
    format: undefined,
    isProperties: ()=> true,
  },
  "multipleValueValueDataPath": {
    get type() { return z.string() },
    nameXML: "MultipleValueValueDataPath",
    get typeXML() { return z.string() },
    nameEnterprise: "ПутьКДаннымЗначенияМножественногоЗначения",
    format: undefined,
    isProperties: ()=> true,
  },
  "onScreenKeyboardReturnKeyText": {
    get type() { return SE.ZOnScreenKeyboardReturnKeyText },
    nameXML: "OnScreenKeyboardReturnKeyText",
    get typeXML() { return SE.ZOnScreenKeyboardReturnKeyText },
    nameEnterprise: "ТекстКнопкиВводаЭкраннойКлавиатуры",
    format: undefined,
    isProperties: ()=> true,
  },
  "openButton": {
    get type() { return z.boolean() },
    nameXML: "OpenButton",
    get typeXML() { return z.boolean() },
    nameEnterprise: "КнопкаОткрытия",
    format: undefined,
    isProperties: ()=> true,
  },
  "passwordMode": {
    get type() { return z.boolean() },
    nameXML: "PasswordMode",
    get typeXML() { return z.boolean() },
    nameEnterprise: "РежимПароля",
    format: undefined,
    isProperties: ()=> true,
  },
  "quickChoice": {
    get type() { return z.boolean() },
    nameXML: "QuickChoice",
    get typeXML() { return z.boolean() },
    nameEnterprise: "БыстрыйВыбор",
    format: undefined,
    isProperties: ()=> true,
  },
  "selectedText": {
    get type() { return z.string() },
    nameXML: "SelectedText",
    get typeXML() { return z.string() },
    nameEnterprise: "ВыделенныйТекст",
    format: undefined,
    isProperties: ()=> true,
  },
  "showCheckBoxesInDropListWhenInputMultipleValues": {
    get type() { return z.boolean() },
    nameXML: "ShowCheckBoxesInDropListWhenInputMultipleValues",
    get typeXML() { return z.boolean() },
    nameEnterprise: "ОтображатьФлажкиВВыпадающемСпискеПриВводеМножественныхЗначений",
    format: undefined,
    isProperties: ()=> true,
  },
  "specialTextInputMode": {
    get type() { return SE.ZSpecialTextInputMode },
    nameXML: "SpecialTextInputMode",
    get typeXML() { return SE.ZSpecialTextInputMode },
    nameEnterprise: "СпециальныйРежимВводаТекста",
    format: undefined,
    isProperties: ()=> true,
  },
  "spellCheckingOnTextInput": {
    get type() { return SE.ZSpellCheckingOnTextInput },
    nameXML: "SpellCheckingOnTextInput",
    get typeXML() { return SE.ZSpellCheckingOnTextInput },
    nameEnterprise: "ПроверкаПравописанияПриВводеТекста",
    format: undefined,
    isProperties: ()=> true,
  },
  "spinButton": {
    get type() { return z.boolean() },
    nameXML: "SpinButton",
    get typeXML() { return z.boolean() },
    nameEnterprise: "КнопкаРегулирования",
    format: undefined,
    isProperties: ()=> true,
  },
  "textColor": {
    get type() { return ZColor },
    nameXML: "TextColor",
    get typeXML() { return ZColorXML },
    nameEnterprise: "ЦветТекста",
    format: undefined,
    isProperties: ()=> true,
  },
  "textEdit": {
    get type() { return z.boolean() },
    nameXML: "TextEdit",
    get typeXML() { return z.boolean() },
    nameEnterprise: "РедактированиеТекста",
    format: undefined,
    isProperties: ()=> true,
  },
  "typeDomainEnabled": {
    get type() { return z.boolean() },
    nameXML: "TypeDomainEnabled",
    get typeXML() { return z.boolean() },
    nameEnterprise: "РазрешитьСоставнойТип",
    format: undefined,
    isProperties: ()=> true,
  },
  "typeLink": {
    get type() { return ZTypeLink },
    nameXML: "TypeLink",
    get typeXML() { return ZTypeLinkXML },
    nameEnterprise: "СвязьПоТипу",
    format: undefined,
    isProperties: ()=> true,
  },
  "verticalStretch": {
    get type() { return z.boolean() },
    nameXML: "VerticalStretch",
    get typeXML() { return z.boolean() },
    nameEnterprise: "РастягиватьПоВертикали",
    format: undefined,
    isProperties: ()=> true,
  },
  "width": {
    get type() { return z.number() },
    nameXML: "Width",
    get typeXML() { return z.number() },
    nameEnterprise: "Ширина",
    format: undefined,
    isProperties: ()=> true,
  },
  "wrap": {
    get type() { return z.boolean() },
    nameXML: "Wrap",
    get typeXML() { return z.boolean() },
    nameEnterprise: "АвтоПереносСтрок",
    format: undefined,
    isProperties: ()=> true,
  },
}
