import * as z from "zod"
import * as SE from "~/lib/metadata/systemEnumerations/types"
import { ZI8nText, ZI8nTextXML } from "~/lib/metadata/i8nText/types"
import { ZColor, ZColorXML } from "~/lib/metadata/color/types"
import { ZTypeDescription, ZTypeDescriptionXML } from "~/lib/metadata/typeDescription/types"
import { ZPicture, ZPictureXML } from "../../pictures/types"
import { ZFont, ZFontXML } from "~/lib/metadata/font/types"
import { ZBaseElement, ZBaseElementXML } from "../baseElement/types"

export const ZInputField = ZFormField.extend({
  autoChoiceIncomplete: z.boolean().optional(),
  autoCapitalizationOnTextInput: SE.ZAutoCapitalizationOnTextInput.optional(),
  autoCorrectionOnTextInput: SE.ZAutoCorrectionOnTextInput.optional(),
  autoMaxHeight: z.boolean().optional(),
  autoMaxWidth: z.boolean().optional(),
  autoMarkIncomplete: z.boolean().optional(),
  autoShowOpenButton: SE.ZAutoShowOpenButtonMode.optional(),
  autoShowClearButton: SE.ZAutoShowClearButtonMode.optional(),
  wrap: z.boolean().optional(),
  quickChoice: z.boolean().optional(),
  heightControlVariant: SE.ZItemHeightControlVariant.optional(),
  chooseType: z.boolean().optional(),
  choiceFoldersAndItems: SE.ZFoldersAndItems.optional(),
  selectedText: z.string().optional(),
  markNegatives: z.boolean().optional(),
  height: z.number().optional(),
  choiceListHeight: z.number().optional(),
  multipleValuesHyperlink: z.boolean().optional(),
  availableTypes: ZTypeDescription.optional(),
  choiceHistoryOnInput: SE.ZChoiceHistoryOnInput.optional(),
  choiceButtonPicture: ZPicture.optional(),
  multipleValuesPicture: ZPicture.optional(),
  choiceButton: z.boolean().optional(),
  dropListButton: z.boolean().optional(),
  openButton: z.boolean().optional(),
  clearButton: z.boolean().optional(),
  spinButton: z.boolean().optional(),
  createButton: z.boolean().optional(),
  choiceListButton: z.boolean().optional(),
  maxHeight: z.number().optional(),
  maxWidth: z.number().optional(),
  maxValue: z.number().optional(),
  mask: z.string().optional(),
  minValue: z.number().optional(),
  multiLine: z.boolean().optional(),
  editTextUpdate: SE.ZEditTextUpdate.optional(),
  markIncomplete: z.boolean().optional(),
  showCheckBoxesInDropListWhenInputMultipleValues: z.boolean().optional(),
  choiceButtonRepresentation: SE.ZChoiceButtonRepresentation.optional(),
  choiceParameters: ZFixedArray.optional(),
  autoFillHint: SE.ZInputFieldAutofillHint.optional(),
  inputHint: z.string().optional(),
  spellCheckingOnTextInput: SE.ZSpellCheckingOnTextInput.optional(),
  multipleValueValueDataPath: z.string().optional(),
  multipleValuePictureDataPath: z.string().optional(),
  multipleValuePresentationDataPath: z.string().optional(),
  multipleValuePictureSize: SE.ZInputFieldMultipleValuePictureSize.optional(),
  allowInputEmptyMultipleValues: z.boolean().optional(),
  allowMultipleValuesDuplicates: z.boolean().optional(),
  typeDomainEnabled: z.boolean().optional(),
  verticalStretch: z.boolean().optional(),
  horizontalStretch: z.boolean().optional(),
  extendedEdit: z.boolean().optional(),
  multipleValuesExtendedEdit: z.boolean().optional(),
  textEdit: z.boolean().optional(),
  listChoiceMode: z.boolean().optional(),
  incompleteChoiceMode: SE.ZIncompleteChoiceMode.optional(),
  passwordMode: z.boolean().optional(),
  choiceParameterLinks: ZFixedArray.optional(),
  typeLink: ZTypeLink.optional(),
  specialTextInputMode: SE.ZSpecialTextInputMode.optional(),
  choiceList: ZChoiceList.optional(),
  onScreenKeyboardReturnKeyText: SE.ZOnScreenKeyboardReturnKeyText.optional(),
  editText: z.string().optional(),
  multipleValuePictureShape: SE.ZInputFieldMultipleValuePictureShape.optional(),
  choiceForm: z.string().optional(),
  format: z.string().optional(),
  editFormat: z.string().optional(),
  borderColor: ZColor.optional(),
  textColor: ZColor.optional(),
  multipleValuesTextColor: ZColor.optional(),
  backColor: ZColor.optional(),
  multipleValuesBackColor: ZColor.optional(),
  width: z.number().optional(),
  dropListWidth: z.number().optional(),
  font: ZFont.optional(),
  multipleValuesFont: ZFont.optional(),
  value: z.string().optional(),
})

export const ZInputFieldXML = ZFormFieldXML.extend({
  AutoChoiceIncomplete: z.boolean().optional(),
  AutoCapitalizationOnTextInput: SE.ZAutoCapitalizationOnTextInput.optional(),
  AutoCorrectionOnTextInput: SE.ZAutoCorrectionOnTextInput.optional(),
  AutoMaxHeight: z.boolean().optional(),
  AutoMaxWidth: z.boolean().optional(),
  AutoMarkIncomplete: z.boolean().optional(),
  AutoShowOpenButton: SE.ZAutoShowOpenButtonMode.optional(),
  AutoShowClearButton: SE.ZAutoShowClearButtonMode.optional(),
  Wrap: z.boolean().optional(),
  QuickChoice: z.boolean().optional(),
  HeightControlVariant: SE.ZItemHeightControlVariant.optional(),
  ChooseType: z.boolean().optional(),
  ChoiceFoldersAndItems: SE.ZFoldersAndItems.optional(),
  SelectedText: z.string().optional(),
  MarkNegatives: z.boolean().optional(),
  Height: z.number().optional(),
  ChoiceListHeight: z.number().optional(),
  MultipleValuesHyperlink: z.boolean().optional(),
  AvailableTypes: ZTypeDescriptionXML.optional(),
  ChoiceHistoryOnInput: SE.ZChoiceHistoryOnInput.optional(),
  ChoiceButtonPicture: ZPictureXML.optional(),
  MultipleValuesPicture: ZPictureXML.optional(),
  ChoiceButton: z.boolean().optional(),
  DropListButton: z.boolean().optional(),
  OpenButton: z.boolean().optional(),
  ClearButton: z.boolean().optional(),
  SpinButton: z.boolean().optional(),
  CreateButton: z.boolean().optional(),
  ChoiceListButton: z.boolean().optional(),
  MaxHeight: z.number().optional(),
  MaxWidth: z.number().optional(),
  MaxValue: z.number().optional(),
  Mask: z.string().optional(),
  MinValue: z.number().optional(),
  MultiLine: z.boolean().optional(),
  EditTextUpdate: SE.ZEditTextUpdate.optional(),
  MarkIncomplete: z.boolean().optional(),
  ShowCheckBoxesInDropListWhenInputMultipleValues: z.boolean().optional(),
  ChoiceButtonRepresentation: SE.ZChoiceButtonRepresentation.optional(),
  ChoiceParameters: ZFixedArrayXML.optional(),
  AutoFillHint: SE.ZInputFieldAutofillHint.optional(),
  InputHint: z.string().optional(),
  SpellCheckingOnTextInput: SE.ZSpellCheckingOnTextInput.optional(),
  MultipleValueValueDataPath: z.string().optional(),
  MultipleValuePictureDataPath: z.string().optional(),
  MultipleValuePresentationDataPath: z.string().optional(),
  MultipleValuePictureSize: SE.ZInputFieldMultipleValuePictureSize.optional(),
  AllowInputEmptyMultipleValues: z.boolean().optional(),
  AllowMultipleValuesDuplicates: z.boolean().optional(),
  TypeDomainEnabled: z.boolean().optional(),
  VerticalStretch: z.boolean().optional(),
  HorizontalStretch: z.boolean().optional(),
  ExtendedEdit: z.boolean().optional(),
  MultipleValuesExtendedEdit: z.boolean().optional(),
  TextEdit: z.boolean().optional(),
  ListChoiceMode: z.boolean().optional(),
  IncompleteChoiceMode: SE.ZIncompleteChoiceMode.optional(),
  PasswordMode: z.boolean().optional(),
  ChoiceParameterLinks: ZFixedArrayXML.optional(),
  TypeLink: ZTypeLinkXML.optional(),
  SpecialTextInputMode: SE.ZSpecialTextInputMode.optional(),
  ChoiceList: ZChoiceListXML.optional(),
  OnScreenKeyboardReturnKeyText: SE.ZOnScreenKeyboardReturnKeyText.optional(),
  EditText: z.string().optional(),
  MultipleValuePictureShape: SE.ZInputFieldMultipleValuePictureShape.optional(),
  ChoiceForm: z.string().optional(),
  Format: z.string().optional(),
  EditFormat: z.string().optional(),
  BorderColor: ZColorXML.optional(),
  TextColor: ZColorXML.optional(),
  MultipleValuesTextColor: ZColorXML.optional(),
  BackColor: ZColorXML.optional(),
  MultipleValuesBackColor: ZColorXML.optional(),
  Width: z.number().optional(),
  DropListWidth: z.number().optional(),
  Font: ZFontXML.optional(),
  MultipleValuesFont: ZFontXML.optional(),
})

export type TInputField = z.infer<typeof ZInputField>

export type TInputFieldXML = z.infer<typeof ZInputFieldXML>