import { commands } from "vscode";
import { string } from "yaml/dist/schema/common/string";
import * as SE from "~/lib/metadata/systemEnumerations/types";


export interface Document  {

  actionsWritingOnPost?: SE.RegisterRecordsWritingOnPost,
  additionalIndexes?: ДополнительныеИндексы,
  attributes?: КоллекцияОбъектовМетаданных,
  autonumbering?: boolean,
  auxiliaryChoiceForm?: ОбъектМетаданных: Форма,
  auxiliaryListForm?: ERROR: No type found for property ДополнительнаяФормаСписка,
  auxiliaryObjectForm?: ERROR: No type found for property ДополнительнаяФормаОбъекта,
  basedOn?: КоллекцияЗначенийСвойстваОбъектаМетаданных,
  characteristics?: ОписанияХарактеристик,
  checkUnique?: boolean,
  choiceDataGetModeOnInputByString?: SE.ChoiceDataGetModeOnInputByString,
  choiceHistoryOnInput?: SE.ChoiceHistoryOnInput,
  commands?: КоллекцияОбъектовМетаданных,
  comment?: string,
  createOnInput?: SE.CreateOnInput,
  dataHistory?: SE.DataHistoryUse,
  dataLockControlMode?: SE.DefaultDataLockControlMode,
  dataLockFields?: СписокПолей,
  defaultChoiceForm?: Неопределено,
  defaultListForm?: Неопределено,
  defaultObjectForm?: Неопределено,
  executeAfterWriteDataHistoryVersionProcessing?: boolean,
  explanation?: string,
  extendedListPresentation?: string,
  extendedObjectPresentation?: string,
  forms?: КоллекцияОбъектовМетаданных,
  fullTextSearch?: SE.UseFullTextSearch,
  fullTextSearchOnInputByString?: SE.FullTextSearchOnInputByString,
  help?: Неопределено,
  includeHelpInContents?: boolean,
  inputByString?: СписокПолей,
  listPresentation?: string,
  managerModule?: Неопределено,
  numberAllowedLength?: SE.AllowedLength,
  numberLength?: number,
  numberPeriodicity?: SE.BusinessProcessNumberPeriodicity,
  numberType?: SE.DocumentNumberType,
  numerator?: ОбъектМетаданных: Нумератор,
  objectBelonging?: SE.ObjectBelonging,
  objectModule?: Неопределено,
  objectPresentation?: string,
  posting?: SE.Posting,
  privilegedPostingMode?: boolean,
  privilegedUnpostingMode?: boolean,
  realTimePosting?: SE.RealTimePosting,
  registerRecords?: КоллекцияЗначенийСвойстваОбъектаМетаданных,
  registerRecordsDeletion?: SE.RegisterRecordsDeletion,
  searchStringModeOnInputByString?: SE.SearchStringModeOnInputByString,
  sequenceFilling?: SE.SequenceFilling,
  standardAttributes?: ОписанияСтандартныхРеквизитов,
  synonym?: string,
  tabularSections?: КоллекцияОбъектовМетаданных,
  templates?: КоллекцияОбъектовМетаданных,
  updateDataHistoryImmediatelyAfterWrite?: boolean,
  userVisible?: UserVisible,
  useStandardCommands?: boolean,
}

export interface DocumentXML  {
  
  ActionsWritingOnPost?: SE.RegisterRecordsWritingOnPost,
  AdditionalIndexes?: ДополнительныеИндексыXML,
  Attributes?: КоллекцияОбъектовМетаданныхXML,
  Autonumbering?: boolean,
  AuxiliaryChoiceForm?: ОбъектМетаданных: ФормаXML,
  AuxiliaryListForm?: No type found for property ДополнительнаяФормаСписка,
  AuxiliaryObjectForm?: No type found for property ДополнительнаяФормаОбъекта,
  BasedOn?: КоллекцияЗначенийСвойстваОбъектаМетаданныхXML,
  Characteristics?: ОписанияХарактеристикXML,
  CheckUnique?: boolean,
  ChoiceDataGetModeOnInputByString?: SE.ChoiceDataGetModeOnInputByString,
  ChoiceHistoryOnInput?: SE.ChoiceHistoryOnInput,
  Commands?: КоллекцияОбъектовМетаданныхXML,
  Comment?: string,
  CreateOnInput?: SE.CreateOnInput,
  DataHistory?: SE.DataHistoryUse,
  DataLockControlMode?: SE.DefaultDataLockControlMode,
  DataLockFields?: СписокПолейXML,
  DefaultChoiceForm?: НеопределеноXML,
  DefaultListForm?: НеопределеноXML,
  DefaultObjectForm?: НеопределеноXML,
  ExecuteAfterWriteDataHistoryVersionProcessing?: boolean,
  Explanation?: string,
  ExtendedListPresentation?: string,
  ExtendedObjectPresentation?: string,
  Forms?: КоллекцияОбъектовМетаданныхXML,
  FullTextSearch?: SE.UseFullTextSearch,
  FullTextSearchOnInputByString?: SE.FullTextSearchOnInputByString,
  Help?: НеопределеноXML,
  IncludeHelpInContents?: boolean,
  InputByString?: СписокПолейXML,
  ListPresentation?: string,
  ManagerModule?: НеопределеноXML,
  NumberAllowedLength?: SE.AllowedLength,
  NumberLength?: number,
  NumberPeriodicity?: SE.BusinessProcessNumberPeriodicity,
  NumberType?: SE.DocumentNumberType,
  Numerator?: ОбъектМетаданных: НумераторXML,
  ObjectBelonging?: SE.ObjectBelonging,
  ObjectModule?: НеопределеноXML,
  ObjectPresentation?: string,
  Posting?: SE.Posting,
  PrivilegedPostingMode?: boolean,
  PrivilegedUnpostingMode?: boolean,
  RealTimePosting?: SE.RealTimePosting,
  RegisterRecords?: КоллекцияЗначенийСвойстваОбъектаМетаданныхXML,
  RegisterRecordsDeletion?: SE.RegisterRecordsDeletion,
  SearchStringModeOnInputByString?: SE.SearchStringModeOnInputByString,
  SequenceFilling?: SE.SequenceFilling,
  StandardAttributes?: ОписанияСтандартныхРеквизитовXML,
  Synonym?: string,
  TabularSections?: КоллекцияОбъектовМетаданныхXML,
  Templates?: КоллекцияОбъектовМетаданныхXML,
  UpdateDataHistoryImmediatelyAfterWrite?: boolean,
  UserVisible?: UserVisibleXML,
  UseStandardCommands?: boolean,
}

export interface DocumentEnterprise  {
  ЗаписьДвиженийПриПроведении?: SE.RegisterRecordsWritingOnPostEnterprise,
  ДополнительныеИндексы?: ДополнительныеИндексыEnterprise,
  Реквизиты?: КоллекцияОбъектовМетаданныхEnterprise,
  Автонумерация?: boolean,
  ДополнительнаяФормаДляВыбора?: ОбъектМетаданных: ФормаEnterprise,
  ДополнительнаяФормаСписка?: No type found for property ДополнительнаяФормаСписка,
  ДополнительнаяФормаОбъекта?: No type found for property ДополнительнаяФормаОбъекта,
  ВводитсяНаОсновании?: КоллекцияЗначенийСвойстваОбъектаМетаданныхEnterprise,
  Характеристики?: ОписанияХарактеристикEnterprise,
  КонтрольУникальности?: boolean,
  РежимПолученияДанныхВыбораПриВводеПоСтроке?: SE.ChoiceDataGetModeOnInputByStringEnterprise,
  ИсторияВыбораПриВводе?: SE.ChoiceHistoryOnInputEnterprise,
  Команды?: КоллекцияОбъектовМетаданныхEnterprise,
  Комментарий?: string,
  СозданиеПриВводе?: SE.CreateOnInputEnterprise,
  ИсторияДанных?: SE.DataHistoryUseEnterprise,
  РежимУправленияБлокировкойДанных?: SE.DefaultDataLockControlModeEnterprise,
  ПоляБлокировкиДанных?: СписокПолейEnterprise,
  ОсновнаяФормаДляВыбора?: НеопределеноEnterprise,
  ОсновнаяФормаСписка?: НеопределеноEnterprise,
  ОсновнаяФормаОбъекта?: НеопределеноEnterprise,
  ВыполнятьОбработкуПослеЗаписиВерсииИсторииДанных?: boolean,
  Пояснение?: string,
  РасширенноеПредставлениеСписка?: string,
  РасширенноеПредставлениеОбъекта?: string,
  Формы?: КоллекцияОбъектовМетаданныхEnterprise,
  ПолнотекстовыйПоиск?: SE.UseFullTextSearchEnterprise,
  ПолнотекстовыйПоискПриВводеПоСтроке?: SE.FullTextSearchOnInputByStringEnterprise,
  Справка?: НеопределеноEnterprise,
  ВключатьСправкуВСодержание?: boolean,
  ВводПоСтроке?: СписокПолейEnterprise,
  ПредставлениеСписка?: string,
  МодульМенеджера?: НеопределеноEnterprise,
  ДопустимаяДлинаНомера?: SE.AllowedLengthEnterprise,
  ДлинаНомера?: number,
  ПериодичностьНомера?: SE.BusinessProcessNumberPeriodicityEnterprise,
  ТипНомера?: SE.DocumentNumberTypeEnterprise,
  Нумератор?: ОбъектМетаданных: НумераторEnterprise,
  ПринадлежностьОбъекта?: SE.ObjectBelongingEnterprise,
  МодульОбъекта?: НеопределеноEnterprise,
  ПредставлениеОбъекта?: string,
  Проведение?: SE.PostingEnterprise,
  ПривилегированныйРежимПриПроведении?: boolean,
  ПривилегированныйРежимПриОтменеПроведения?: boolean,
  ОперативноеПроведение?: SE.RealTimePostingEnterprise,
  Движения?: КоллекцияЗначенийСвойстваОбъектаМетаданныхEnterprise,
  УдалениеДвижений?: SE.RegisterRecordsDeletionEnterprise,
  СпособПоискаСтрокиПриВводеПоСтроке?: SE.SearchStringModeOnInputByStringEnterprise,
  ЗаполнениеПоследовательностей?: SE.SequenceFillingEnterprise,
  СтандартныеРеквизиты?: ОписанияСтандартныхРеквизитовEnterprise,
  Синоним?: string,
  ТабличныеЧасти?: КоллекцияОбъектовМетаданныхEnterprise,
  Макеты?: КоллекцияОбъектовМетаданныхEnterprise,
  ОбновлятьИсториюДанныхСразуПослеЗаписи?: boolean,
  ПользовательскаяВидимость?: UserVisibleEnterprise,
  ИспользоватьСтандартныеКоманды?: boolean,
}
