import { getParentFromContext } from "~/metadata/context/helpers"
import { ConfigurationContextWithExportToXML } from "~/metadata/context/types"
import { MetadataCommandRules } from "~/metadata/appliedObjects/metadataCommand/rules"
import { V8_MDCLASSES_ROOT } from "~/metadata/orchestration/appliedObject/presets"
import { MetadataItemRule } from "~/metadata/orchestration/property/types"
import {
  externalDataSourceObjectServiceProperties,
} from "../metadataExternalDataSourceField/rules"

const properties = ["Properties"]
const childObjects = ["ChildObjects"]
const root: string[] = []

const MetadataExternalDataSourceTableCommandRules = {
  ...MetadataCommandRules,
  properties: {
    ...MetadataCommandRules.properties,
    commandModule: {
      ...MetadataCommandRules.properties.commandModule,
      xmlPath: ({ name, parentName }: { name: string; parentName?: string }) =>
        parentName === undefined || parentName === ""
          ? `Commands/${name}/Ext/CommandModule.bsl`
          : `Tables/${parentName}/Commands/${name}/Ext/CommandModule.bsl`,
    },
  },
} as const satisfies MetadataItemRule

const tableProperties = {
  xmlRoot: {
    type: "XMLRoot",
    container: "Table",
    rootAttributes: V8_MDCLASSES_ROOT,
    forReferenceOnly: true,
    toYAML: false,
    fromYAML: false,
  },
  internalInfo: {
    type: "InternalInfo",
    xmlParents: root,
    forReferenceOnly: true,
    toYAML: false,
    fromYAML: false,
    getName: (params: { context: ConfigurationContextWithExportToXML; metadata: { name: string } }) => {
      const parent = getParentFromContext(params.context, ["MetadataExternalDataSource"])
      return parent.name ? `${parent.name}.${params.metadata.name}` : params.metadata.name
    },
    items: [
      { name: "ExternalDataSourceTableManager", category: "Manager" },
      { name: "ExternalDataSourceTableObject", category: "Object" },
      { name: "ExternalDataSourceTableRef", category: "Ref" },
      { name: "ExternalDataSourceTableList", category: "List" },
      { name: "ExternalDataSourceTableRecord", category: "Record" },
      { name: "ExternalDataSourceTableRecordSet", category: "RecordSet" },
      { name: "ExternalDataSourceTableRecordKey", category: "RecordKey" },
      { name: "ExternalDataSourceTableRecordManager", category: "RecordManager" },
    ] as { name: string; category: string }[],
  },
  uuid: {
    type: "uuid",
    xml: "_uuid",
    forReferenceOnly: true,
    xmlParents: root,
  },
  name: {
    type: "string",
    xmlParents: properties,
    required: true,
  },
  synonym: {
    yaml: "Синоним",
    type: "I8nText",
    xmlParents: properties,
    defaultValueXMLRaw: "",
  },
  comment: {
    yaml: "Комментарий",
    type: "string",
    xmlParents: properties,
    defaultValueXMLRaw: "",
  },
  tableType: {
    yaml: "ТипТаблицы",
    xml: "TableType",
    type: "SystemEnumeration",
    typeSE: "ExternalDataSourceTableType",
    xmlParents: properties,
    defaultValueXML: "Table",
    implicitValueYAML: "Table",
  },
  nameInDataSource: {
    yaml: "ИмяВИсточникеДанных",
    xml: "NameInDataSource",
    type: "string",
    xmlParents: properties,
    required: true,
  },
  expressionInDataSource: {
    yaml: "ВыражениеВИсточникеДанных",
    xml: "ExpressionInDataSource",
    type: "string",
    xmlParents: properties,
    defaultValueXMLRaw: "",
  },
  tableDataType: {
    yaml: "ТипДанныхТаблицы",
    xml: "TableDataType",
    type: "SystemEnumeration",
    typeSE: "ExternalDataSourceTableDataType",
    xmlParents: properties,
    defaultValueXML: "NonobjectData",
    implicitValueYAML: "NonobjectData",
  },
  keyFields: {
    yaml: "КлючевыеПоля",
    xml: "KeyFields",
    type: "FieldsList",
    fieldsListXMLItem: "xr:Field",
    xmlParents: properties,
    defaultValueXMLRaw: "",
  },
  presentationField: {
    yaml: "ПолеПредставления",
    xml: "PresentationField",
    type: "string",
    xmlParents: properties,
    defaultValueXMLRaw: "",
  },
  parentField: {
    yaml: "ПолеРодителя",
    xml: "ParentField",
    type: "string",
    xmlParents: properties,
    defaultValueXMLRaw: "",
  },
  unfilledParentValue: {
    yaml: "НезаполненноеЗначениеРодителя",
    xml: "UnfilledParentValue",
    type: "MetadataValue",
    xmlParents: properties,
    defaultValueXMLRaw: { "_xsi:nil": true },
  },
  characteristics: {
    yaml: "Характеристики",
    xml: "Characteristics",
    type: "CharacteristicsDescriptions",
    xmlParents: properties,
    defaultValueXMLRaw: "",
  },
  useStandardCommands: {
    yaml: "ИспользоватьСтандартныеКоманды",
    xml: "UseStandardCommands",
    type: "boolean",
    xmlParents: properties,
    defaultValueXML: true,
    implicitValueYAML: true,
  },
  quickChoice: {
    yaml: "БыстрыйВыбор",
    xml: "QuickChoice",
    type: "boolean",
    xmlParents: properties,
    defaultValueXML: false,
    implicitValueYAML: false,
  },
  inputByString: {
    yaml: "ВводПоСтроке",
    xml: "InputByString",
    type: "FieldsList",
    fieldsListXMLItem: "xr:Field",
    xmlParents: properties,
    defaultValueXMLRaw: "",
  },
  createOnInput: {
    yaml: "СозданиеПриВводе",
    xml: "CreateOnInput",
    type: "SystemEnumeration",
    typeSE: "CreateOnInput",
    xmlParents: properties,
    defaultValueXML: "Auto",
    implicitValueYAML: "Auto",
  },
  searchStringModeOnInputByString: {
    yaml: "РежимСтрокиПоискаПриВводеПоСтроке",
    xml: "SearchStringModeOnInputByString",
    type: "SystemEnumeration",
    typeSE: "SearchStringModeOnInputByString",
    xmlParents: properties,
    defaultValueXML: "Begin",
    implicitValueYAML: "Begin",
  },
  choiceDataGetModeOnInputByString: {
    yaml: "РежимПолученияДанныхВыбораПриВводеПоСтроке",
    xml: "ChoiceDataGetModeOnInputByString",
    type: "SystemEnumeration",
    typeSE: "ChoiceDataGetModeOnInputByString",
    xmlParents: properties,
    defaultValueXML: "Directly",
    implicitValueYAML: "Directly",
  },
  choiceHistoryOnInput: {
    yaml: "ИсторияВыбораПриВводе",
    xml: "ChoiceHistoryOnInput",
    type: "SystemEnumeration",
    typeSE: "ChoiceHistoryOnInput",
    xmlParents: properties,
    defaultValueXML: "Auto",
    implicitValueYAML: "Auto",
  },
  defaultObjectForm: {
    yaml: "ОсновнаяФормаОбъекта",
    xml: "DefaultObjectForm",
    type: "string",
    xmlParents: properties,
    metadataTarget: { kind: "member", owner: "this", memberKinds: ["Form"] },
    defaultValueXMLRaw: "",
  },
  defaultRecordForm: {
    yaml: "ОсновнаяФормаЗаписи",
    xml: "DefaultRecordForm",
    type: "string",
    xmlParents: properties,
    metadataTarget: { kind: "member", owner: "this", memberKinds: ["Form"] },
    defaultValueXMLRaw: "",
  },
  defaultListForm: {
    yaml: "ОсновнаяФормаСписка",
    xml: "DefaultListForm",
    type: "string",
    xmlParents: properties,
    metadataTarget: { kind: "member", owner: "this", memberKinds: ["Form"] },
    defaultValueXMLRaw: "",
  },
  defaultChoiceForm: {
    yaml: "ОсновнаяФормаВыбора",
    xml: "DefaultChoiceForm",
    type: "string",
    xmlParents: properties,
    metadataTarget: { kind: "member", owner: "this", memberKinds: ["Form"] },
    defaultValueXMLRaw: "",
  },
  objectPresentation: {
    yaml: "ПредставлениеОбъекта",
    xml: "ObjectPresentation",
    type: "I8nText",
    xmlParents: properties,
    defaultValueXMLRaw: "",
  },
  extendedObjectPresentation: {
    yaml: "РасширенноеПредставлениеОбъекта",
    xml: "ExtendedObjectPresentation",
    type: "I8nText",
    xmlParents: properties,
    defaultValueXMLRaw: "",
  },
  recordPresentation: {
    yaml: "ПредставлениеЗаписи",
    xml: "RecordPresentation",
    type: "I8nText",
    xmlParents: properties,
    defaultValueXMLRaw: "",
  },
  extendedRecordPresentation: {
    yaml: "РасширенноеПредставлениеЗаписи",
    xml: "ExtendedRecordPresentation",
    type: "I8nText",
    xmlParents: properties,
    defaultValueXMLRaw: "",
  },
  listPresentation: {
    yaml: "ПредставлениеСписка",
    xml: "ListPresentation",
    type: "I8nText",
    xmlParents: properties,
    defaultValueXMLRaw: "",
  },
  extendedListPresentation: {
    yaml: "РасширенноеПредставлениеСписка",
    xml: "ExtendedListPresentation",
    type: "I8nText",
    xmlParents: properties,
    defaultValueXMLRaw: "",
  },
  explanation: {
    yaml: "Пояснение",
    xml: "Explanation",
    type: "I8nText",
    xmlParents: properties,
    defaultValueXMLRaw: "",
  },
  includeHelpInContents: {
    yaml: "ВключатьСправкуВСодержание",
    xml: "IncludeHelpInContents",
    type: "boolean",
    xmlParents: properties,
    defaultValueXML: false,
    implicitValueYAML: false,
  },
  readOnly: {
    yaml: "ТолькоЧтение",
    xml: "ReadOnly",
    type: "boolean",
    xmlParents: properties,
    defaultValueXML: false,
  },
  transactionsIsolationLevel: {
    yaml: "УровеньИзоляцииТранзакций",
    xml: "TransactionsIsolationLevel",
    type: "SystemEnumeration",
    typeSE: "TransactionsIsolationLevel",
    xmlParents: properties,
    defaultValueXML: "Auto",
    implicitValueYAML: "Auto",
  },
  dataVersionField: {
    yaml: "ПолеВерсииДанных",
    xml: "DataVersionField",
    type: "string",
    xmlParents: properties,
    defaultValueXMLRaw: "",
  },
  editType: {
    yaml: "СпособРедактирования",
    xml: "EditType",
    type: "SystemEnumeration",
    typeSE: "EditType",
    xmlParents: properties,
    defaultValueXML: "InDialog",
    implicitValueYAML: "InDialog",
  },
  basedOn: {
    yaml: "ВводитсяНаОсновании",
    xml: "BasedOn",
    type: "MetadataItemLinks",
    xmlParents: properties,
    defaultValueXMLRaw: "",
  },
  dataLockFields: {
    yaml: "ПоляБлокировкиДанных",
    xml: "DataLockFields",
    type: "FieldsList",
    fieldsListXMLItem: "xr:Field",
    xmlParents: properties,
    defaultValueXMLRaw: "",
  },
  dataLockControlMode: {
    yaml: "РежимУправленияБлокировкойДанных",
    xml: "DataLockControlMode",
    type: "SystemEnumeration",
    typeSE: "DefaultDataLockControlMode",
    xmlParents: properties,
    defaultValueXML: "Automatic",
    implicitValueYAML: "Automatic",
  },
  fields: {
    yaml: "Поля",
    xml: "Field",
    type: "MetadataExternalDataSourceFields",
    xmlParents: childObjects,
  },
  forms: {
    yaml: "Формы",
    xml: "Form",
    type: "ChildFormNames",
    xmlParents: childObjects,
    folderName: "Формы",
    forReferenceOnly: true,
    toYAML: false,
    fromYAML: false,
  },
  commands: {
    yaml: "Команды",
    xml: "Command",
    type: "MetadataCommands",
    xmlParents: childObjects,
  },
  templates: {
    yaml: "Макеты",
    xml: "Template",
    type: "ChildTemplateNames",
    xmlParents: childObjects,
    folderName: "Макеты",
    forReferenceOnly: true,
    toYAML: false,
    fromYAML: false,
  },
  managerModule: {
    type: "Module",
    nkdkPath: "МодульМенеджера.bsl",
    xmlPath: "Ext/ManagerModule.bsl",
  },
  objectModule: {
    type: "Module",
    nkdkPath: "МодульОбъекта.bsl",
    xmlPath: "Ext/ObjectModule.bsl",
  },
  recordSetModule: {
    type: "Module",
    nkdkPath: "МодульНабораЗаписей.bsl",
    xmlPath: "Ext/RecordSetModule.bsl",
  },
  help: {
    type: "Help",
    filePath: "Ext/Help.xml",
    xmlPath: "Ext/Help.xml",
    nkdkDir: "Справка",
  },
  ...externalDataSourceObjectServiceProperties,
} as const

const { xmlRoot: _xmlRoot, ...tableCollectionProperties } = tableProperties

export const MetadataExternalDataSourceTableRules = {
  itemType: "MetadataExternalDataSourceTable",
  properties: tableProperties,
  childCollections: [{ propertyKey: "commands", itemRule: MetadataExternalDataSourceTableCommandRules }],
} as const satisfies MetadataItemRule

export const MetadataExternalDataSourceTableCollectionRules = {
  itemType: "MetadataExternalDataSourceTable",
  properties: tableCollectionProperties,
  childCollections: [{ propertyKey: "commands", itemRule: MetadataExternalDataSourceTableCommandRules }],
} as const satisfies MetadataItemRule
