import * as SE from "~/lib/metadata/systemEnumerations/types"
import { ZI8nText, ZI8nTextXML } from "~/lib/metadata/commonObjects/i8nText/types"
import { ZColor, ZColorXML } from "~/lib/metadata/commonObjects/color/types"
import { ZTypeDescription, ZTypeDescriptionXML } from "~/lib/metadata/commonObjects/typeDescription/types"
import { ZPicture, ZPictureXML } from "~/lib/metadata/commonObjects/pictures/types"
import { ZFont, ZFontXML } from "~/lib/metadata/commonObjects/font/types"
import { ZBorder, ZBorderXML } from "~/lib/metadata/commonObjects/border/types"
import {  ZBaseElementXML } from "../baseElement/types"
import { ZFormDecoration, ZFormDecorationXML } from "../formDecoration/types"
import { ZTable, ZTableXML } from "../table/types"
import { ZFormField, ZFormFieldXML } from "../formField/types"
import { ZCommandBar, ZCommandBarXML } from "../commandBar/types"
import { ZUserVisible, ZUserVisibleXML } from "~/lib/metadata/commonObjects/userVisible/types"
import { ZEventsXML } from "~/lib/metadata/forms/events/types"
import { ZElementType } from "~/lib/metadata/forms/elements/types"
import { ZodChildItemsType } from "../childItems/typesExt"

export interface PictureField {
  elementType: ElementType
  name: string
  id?: string
  autoCellHeight?: boolean,
  cellHyperlink?: boolean,
  contextMenu?: CommandBar,
  dataPath?: string,
  defaultItem?: boolean,
  displayImportance?: SE.DisplayImportance,
  editMode?: SE.ColumnEditMode,
  enabled?: boolean,
  extendedTooltip?: FormDecoration,
  fixingInTable?: SE.FixingInTable,
  footerBackColor?: Color,
  footerDataPath?: string,
  footerFont?: Font,
  footerHorizontalAlign?: SE.ItemHorizontalLocation,
  footerPicture?: Picture,
  footerText?: I8nText,
  footerTextColor?: Color,
  headerHorizontalAlign?: SE.ItemHorizontalLocation,
  headerPicture?: Picture,
  horizontalAlign?: SE.ItemHorizontalLocation,
  horizontalAlignInGroup?: SE.ItemHorizontalLocation,
  readOnly?: boolean,
  shortcut?: string,
  showInFooter?: boolean,
  showInHeader?: boolean,
  skipOnInput?: boolean,
  table?: Table,
  title?: I8nText,
  titleBackColor?: Color,
  titleFont?: Font,
  titleHeight?: number,
  titleLocation?: SE.FormItemTitleLocation,
  titleTextColor?: Color,
  toolTip?: I8nText,
  toolTipRepresentation?: SE.ToolTipRepresentation,
  type?: SE.FormFieldType,
  typeRestriction?: TypeDescription,
  userVisible?: UserVisible,
  verticalAlign?: SE.ItemVerticalAlign,
  verticalAlignInGroup?: SE.ItemVerticalAlign,
  visible?: boolean,
  warningOnEdit?: I8nText,
  warningOnEditRepresentation?: SE.WarningOnEditRepresentation,
  autoMaxHeight?: boolean,
  autoMaxWidth?: boolean,
  border?: Border,
  borderColor?: Color,
  enableDrag?: boolean,
  enableStartDrag?: boolean,
  fileDragMode?: SE.FileDragMode,
  font?: Font,
  height?: number,
  horizontalStretch?: boolean,
  hyperlink?: boolean,
  maxHeight?: number,
  maxWidth?: number,
  nonselectedPictureText?: string,
  pictureSize?: SE.PictureSize,
  scale?: number,
  textColor?: Color,
  valuesPicture?: Picture,
  verticalStretch?: boolean,
  width?: number,
  zoomable?: boolean,
  events?: {
    onChange?: string,
    click?: string,
    dragStart?: string,
    dragEnd?: string,
    drag?: string,
    dragCheck?: string,
  },
}

export interface PictureFieldXML {
  _name: z.string(),
  _id: z.string(),
  _DisplayImportance: SE.DisplayImportance,
  DataPath: string,
  ShowInHeader: boolean,
  FooterHorizontalAlign: SE.ItemHorizontalLocation,
  Visible: boolean,
  UserVisible: UserVisible,
  Enabled: boolean,
  ReadOnly: boolean,
  SkipOnInput: boolean,
  Title: I8nText,
  TitleTextColor: Color,
  TitleFont: Font,
  TitleLocation: SE.FormItemTitleLocation,
  TitleHeight: number,
  ToolTip: I8nText,
  ToolTipRepresentation: SE.ToolTipRepresentation,
  WarningOnEditRepresentation: SE.WarningOnEditRepresentation,
  WarningOnEdit: I8nText,
  Shortcut: string,
  HorizontalAlign: SE.ItemHorizontalLocation,
  Width: number,
  Height: number,
  Zoomable: boolean,
  Hyperlink: boolean,
  NonselectedPictureText: string,
  EnableStartDrag: boolean,
  EnableDrag: boolean,
  ValuesPicture: Picture,
  Border: Border,
  TextColor: Color,
  Font: Font,
  FileDragMode: SE.FileDragMode,
  ContextMenu: CommandBar,
  ExtendedTooltip: FormDecoration,
  AutoCellHeight: boolean,
  AutoMaxHeight: boolean,
  AutoMaxWidth: boolean,
  BorderColor: Color,
  CellHyperlink: boolean,
  DefaultItem: boolean,
  EditMode: SE.ColumnEditMode,
  FixingInTable: SE.FixingInTable,
  FooterBackColor: Color,
  FooterDataPath: string,
  FooterFont: Font,
  FooterPicture: Picture,
  FooterText: I8nText,
  FooterTextColor: Color,
  HeaderHorizontalAlign: SE.ItemHorizontalLocation,
  HeaderPicture: Picture,
  HorizontalAlignInGroup: SE.ItemHorizontalLocation,
  HorizontalStretch: boolean,
  MaxHeight: number,
  MaxWidth: number,
  PictureSize: SE.PictureSize,
  Scale: number,
  ShowInFooter: boolean,
  Table: Table,
  TitleBackColor: Color,
  Type: SE.FormFieldType,
  TypeRestriction: TypeDescription,
  VerticalAlign: SE.ItemVerticalAlign,
  VerticalAlignInGroup: SE.ItemVerticalAlign,
  VerticalStretch: boolean,
}