import {
  externalDataSourceFieldBaseProperties,
  externalDataSourceObjectServiceProperties,
} from "~/metadata/commonObjects/metadataExternalDataSourceField/rules"
import { MetadataItemRule } from "~/metadata/orchestration/property/types"

const propertiesParents = ["Properties"]
const hasOwnMetadataProperty =
  (propertyKey: string) =>
  (metadataItem: unknown): boolean =>
    metadataItem !== null &&
    metadataItem !== undefined &&
    typeof metadataItem === "object" &&
    Object.prototype.hasOwnProperty.call(metadataItem, propertyKey)

export const MetadataExternalDataSourceCubeDimensionRules = {
  itemType: "MetadataExternalDataSourceCubeDimension",
  properties: {
    ...externalDataSourceFieldBaseProperties,
    choiceFoldersAndItems: {
      yaml: "ВыборГруппИЭлементов",
      xml: "ChoiceFoldersAndItems",
      type: "SystemEnumeration",
      typeSE: "FoldersAndItemsUse",
      xmlParents: propertiesParents,
      defaultValueXML: "Items",
      implicitValueYAML: "Items",
    },
    linkByType: {
      yaml: "СвязьПоТипу",
      xml: "LinkByType",
      type: "TypeLink",
      xmlParents: propertiesParents,
      defaultValueXMLRaw: "",
    },
    documentMap: {
      yaml: "СоответствиеРеквизитамДокументов",
      xml: "DocumentMap",
      type: "MetadataItemLinks",
      xmlParents: propertiesParents,
      defaultValueXMLRaw: "",
      toXML: hasOwnMetadataProperty("documentMap"),
    },
    registerRecordsMap: {
      yaml: "СоответствиеРеквизитамДвижений",
      xml: "RegisterRecordsMap",
      type: "MetadataItemLinks",
      xmlParents: propertiesParents,
      defaultValueXMLRaw: "",
      toXML: hasOwnMetadataProperty("registerRecordsMap"),
    },
    registerDimension: {
      yaml: "ИзмерениеРегистра",
      xml: "RegisterDimension",
      type: "MetadataItemLink",
      typedXML: "xr:MDObjectRef",
      xmlParents: propertiesParents,
      defaultValueXMLRaw: "",
      toXML: hasOwnMetadataProperty("registerDimension"),
    },
    leadingRegisterData: {
      yaml: "ДанныеВедущихРегистров",
      xml: "LeadingRegisterData",
      type: "MetadataItemLinks",
      xmlParents: propertiesParents,
      defaultValueXMLRaw: "",
      toXML: hasOwnMetadataProperty("leadingRegisterData"),
    },
    denyIncompleteValues: {
      yaml: "ЗапретНезавершенныхЗначений",
      xml: "DenyIncompleteValues",
      type: "boolean",
      xmlParents: propertiesParents,
      defaultValueXML: false,
      implicitValueYAML: false,
      toXML: hasOwnMetadataProperty("denyIncompleteValues"),
    },
    baseDimension: {
      yaml: "БазовоеИзмерение",
      xml: "BaseDimension",
      type: "boolean",
      xmlParents: propertiesParents,
      defaultValueXML: false,
      implicitValueYAML: false,
      toXML: hasOwnMetadataProperty("baseDimension"),
    },
    scheduleLink: {
      yaml: "СвязьСГрафиком",
      xml: "ScheduleLink",
      type: "string",
      xmlParents: propertiesParents,
      defaultValueXMLRaw: "",
      toXML: hasOwnMetadataProperty("scheduleLink"),
    },
    useInTotals: {
      yaml: "ИспользоватьВИтогах",
      xml: "UseInTotals",
      type: "boolean",
      xmlParents: propertiesParents,
      defaultValueXML: true,
      implicitValueYAML: true,
      toXML: hasOwnMetadataProperty("useInTotals"),
    },
    master: {
      yaml: "Ведущее",
      xml: "Master",
      type: "boolean",
      xmlParents: propertiesParents,
      defaultValueXML: false,
      implicitValueYAML: false,
      toXML: hasOwnMetadataProperty("master"),
    },
    mainFilter: {
      yaml: "ОсновнойОтбор",
      xml: "MainFilter",
      type: "boolean",
      xmlParents: propertiesParents,
      defaultValueXML: true,
      implicitValueYAML: true,
      toXML: hasOwnMetadataProperty("mainFilter"),
    },
    balance: {
      yaml: "Балансовый",
      xml: "Balance",
      type: "boolean",
      xmlParents: propertiesParents,
      defaultValueXML: true,
      implicitValueYAML: true,
      toXML: hasOwnMetadataProperty("balance"),
    },
    accountingFlag: {
      yaml: "ПризнакУчета",
      xml: "AccountingFlag",
      type: "string",
      xmlParents: propertiesParents,
      defaultValueXMLRaw: "",
      toXML: hasOwnMetadataProperty("accountingFlag"),
    },
    typeReductionMode: {
      yaml: "РежимСокращенияТипа",
      xml: "TypeReductionMode",
      type: "SystemEnumeration",
      typeSE: "TypeReductionMode",
      xmlParents: propertiesParents,
      defaultValueXML: "TransformValues",
      implicitValueYAML: "TransformValues",
      toXML: hasOwnMetadataProperty("typeReductionMode"),
    },
    indexing: {
      yaml: "Индексирование",
      xml: "Indexing",
      type: "SystemEnumeration",
      typeSE: "Indexing",
      xmlParents: propertiesParents,
      defaultValueXML: "DontIndex",
      implicitValueYAML: "DontIndex",
      toXML: hasOwnMetadataProperty("indexing"),
    },
    fullTextSearch: {
      yaml: "ПолнотекстовыйПоиск",
      xml: "FullTextSearch",
      type: "SystemEnumeration",
      typeSE: "UseFullTextSearch",
      xmlParents: propertiesParents,
      defaultValueXML: "Use",
      implicitValueYAML: "Use",
      toXML: hasOwnMetadataProperty("fullTextSearch"),
    },
    dataHistory: {
      yaml: "ИсторияДанных",
      xml: "DataHistory",
      type: "SystemEnumeration",
      typeSE: "DataHistoryUse",
      xmlParents: propertiesParents,
      defaultValueXML: "Use",
      implicitValueYAML: "Use",
      toXML: hasOwnMetadataProperty("dataHistory"),
    },
    ...externalDataSourceObjectServiceProperties,
  },
} as const satisfies MetadataItemRule
