import {
  SpreadSheetDocumentField,
  SpreadSheetDocumentFieldEnterprise,
  SpreadSheetDocumentFieldPartialYAML,
} from "../types"

import {
  fullFormFieldCommonFixture,
  fullFormFieldEnterpriseCommonFixture,
  fullFormFieldPartialYAMLCommonFixture,
} from "../../__fixtures__/formField/rules"
import { RequiredFieldsElement } from "../../../../../tests/types"

export const fullSpreadSheetDocumentField = {
  itemType: "SpreadSheetDocumentField",
  name: "ПолеТабличногоДокумента",
  title: {
    items: { ru: "Поле табличного документа" },
  },
  autoMaxHeight: false,
  autoMaxWidth: false,
  blackAndWhiteView: true,
  borderColor: { type: "WebColor", value: "Black" },
  commandSet: ["Print"],
  drawingSelectionShowMode: "DontShow",
  edit: true,
  height: 200,
  horizontalScrollBar: "DontUse",
  horizontalStretch: false,
  maxHeight: 500,
  maxWidth: 400,
  output: "Enable",
  pointerType: "Regular",
  protection: true,
  showCellNames: true,
  showGrid: true,
  showGroups: false,
  showHeaders: true,
  showRowAndColumnNames: true,
  verticalScrollBar: "DontUse",
  verticalStretch: false,
  viewScalingMode: "Normal",
  width: 300,
  selectionShowMode: "DontShow",
  enableDrag: false,
  enableStartDrag: false,
  events: {
    onChange: "ПроцедураПриИзменении",
    selection: "ПроцедураПриВыборе",
    dragStart: "ПроцедураПриПеретаскивании",
    dragCheck: "ПроцедураПриПроверкеПеретаскивания",
    additionalDetailProcessing: "ПроцедураПриОбработкеДополнительнойРасшифровки",
    uRLProcessing: "ПроцедураПриОбработкеНавигационнойСсылки",
    detailProcessing: "ПроцедураПриОбработкеРасшифровки",
    dragEnd: "ПроцедураПриЗавершенииПеретаскивания",
    beforeWrite: "ПроцедураПриЗаписи",
    beforePrint: "ПроцедураПриПечатке",
    drag: "ПроцедураПриПеретаскивании",
    afterWrite: "ПроцедураПриЗавершенииЗаписи",
    onActivate: "ПроцедураПриАктивизации",
    onChangeAreaContent: "ПолеТабличногоДокументаПриИзмененииСодержимогоОбласти",
  },
  ...fullFormFieldCommonFixture,
} satisfies RequiredFieldsElement<SpreadSheetDocumentField>

export const fullSpreadSheetDocumentFieldEnterprise = {
  ElementType: "FormField",
  Name: "prefix_ПолеТабличногоДокумента",
  Type: {
    Type: "SystemEnumeration",
    Value: "FormFieldType.SpreadsheetDocumentField",
  },
  Title: "Поле табличного документа",
  AutoMaxHeight: false,
  AutoMaxWidth: false,
  BlackAndWhiteView: true,
  BorderColor: {
    Type: "Color",
    Value: "WebColors.Black",
  },
  DrawingSelectionShowMode: {
    Type: "SystemEnumeration",
    Value: "DrawingSelectionShowMode.DontShow",
  },
  Edit: true,
  Height: 200,
  HorizontalStretch: false,
  MaxHeight: 500,
  MaxWidth: 400,
  Output: {
    Type: "SystemEnumeration",
    Value: "UseOutput.Enable",
  },
  PointerType: {
    Type: "SystemEnumeration",
    Value: "SpreadsheetDocumentPointerType.Regular",
  },
  HorizontalScrollBar: {
    Type: "SystemEnumeration",
    Value: "ScrollBarUse.DontUse",
  },
  Protection: true,
  ShowCellNames: true,
  ShowGrid: true,
  ShowGroups: false,
  ShowHeaders: true,
  ShowRowAndColumnNames: true,
  SelectionShowMode: {
    Type: "SystemEnumeration",
    Value: "SelectionShowMode.DontShow",
  },
  VerticalScrollBar: {
    Type: "SystemEnumeration",
    Value: "ScrollBarUse.DontUse",
  },
  VerticalStretch: false,
  ViewScalingMode: {
    Type: "SystemEnumeration",
    Value: "ViewScalingMode.Normal",
  },
  Width: 300,
  EnableDrag: false,
  EnableStartDrag: false,
  ...fullFormFieldEnterpriseCommonFixture,
} satisfies Required<SpreadSheetDocumentFieldEnterprise>

export const fullSpreadSheetDocumentFieldPartialYAML: SpreadSheetDocumentFieldPartialYAML = {
  АвтоМаксимальнаяВысота: "Ложь",
  АвтоМаксимальнаяШирина: "Ложь",
  Высота: 200,
  Вывод: "Разрешить",
  ВертикальнаяПолосаПрокрутки: "НеИспользовать",
  ГоризонтальнаяПолосаПрокрутки: "НеИспользовать",
  Защита: "Истина",
  Команда: ["Print"],
  МаксимальнаяВысота: 500,
  МаксимальнаяШирина: 400,
  ОтображатьГруппировки: "Ложь",
  ОтображатьЗаголовки: "Истина",
  ОтображатьИменаСтрокИКолонок: "Истина",
  ОтображатьИменаЯчеек: "Истина",
  ОтображатьСетку: "Истина",
  РастягиватьПоВертикали: "Ложь",
  РастягиватьПоГоризонтали: "Ложь",
  Редактирование: "Истина",
  РежимМасштабированияПросмотра: "Обычный",
  РежимОтображенияВыделенияРисунков: "НеОтображать",
  РежимОтображенияВыделения: "НеОтображать",
  ТипКурсоров: "Обычные",
  ЦветРамки: "Черный",
  ЧерноБелыйПросмотр: "Истина",
  Заголовок: "Поле табличного документа",
  Ширина: 300,
  События: {
    Выбор: "ПроцедураПриВыборе",
    ОбработкаРасшифровки: "ПроцедураПриОбработкеРасшифровки",
    ПередЗаписью: "ПроцедураПриЗаписи",
    ПередПечатью: "ПроцедураПриПечатке",
    ПослеЗаписи: "ПроцедураПриЗавершенииЗаписи",
    ПриИзменении: "ПроцедураПриИзменении",
    НачалоПеретаскивания: "ПроцедураПриПеретаскивании",
    ПроверкаПеретаскивания: "ПроцедураПриПроверкеПеретаскивания",
    ОбработкаДополнительнойРасшифровки: "ПроцедураПриОбработкеДополнительнойРасшифровки",
    ОбработкаНавигационнойСсылки: "ПроцедураПриОбработкеНавигационнойСсылки",
    ОкончаниеПеретаскивания: "ПроцедураПриЗавершенииПеретаскивания",
    Перетаскивание: "ПроцедураПриПеретаскивании",
    ПриАктивизации: "ПроцедураПриАктивизации",
    ПриИзмененииСодержимогоОбласти: "ПолеТабличногоДокументаПриИзмененииСодержимогоОбласти",
  },
  РазрешитьПеретаскивание: "Ложь",
  РазрешитьНачалоПеретаскивания: "Ложь",
  ...fullFormFieldPartialYAMLCommonFixture,
} satisfies Omit<Required<SpreadSheetDocumentFieldPartialYAML>, "Использование">

export const minimalSpreadSheetDocumentField: SpreadSheetDocumentField = {
  itemType: "SpreadSheetDocumentField",
  name: "ПолеТабличногоДокумента",
}

export const minimalSpreadSheetDocumentFieldPartialYAML: SpreadSheetDocumentFieldPartialYAML = {}
