import { V8_MDCLASSES_ROOT } from "~/metadata/orchestration/appliedObject/presets"
import { MetadataItemRule } from "~/metadata/orchestration/property/types"
import { MetadataCommandRules } from "../metadataCommand/rules"

const properties = ["Properties"]
const childObjects = ["ChildObjects"]

export const MetadataChartOfCharacteristicTypesStandardAttributeNames: Record<string, string> = {
  PredefinedDataName: "ИмяПредопределенныхДанных",
  ValueType: "ТипЗначения",
  Description: "Наименование",
  Code: "Код",
  IsFolder: "ЭтоГруппа",
  Parent: "Родитель",
  Predefined: "Предопределенный",
  DeletionMark: "ПометкаУдаления",
  Ref: "Ссылка",
}

const MetadataChartOfCharacteristicTypesCommandRules = {
  ...MetadataCommandRules,
  properties: {
    ...MetadataCommandRules.properties,
    commandModule: {
      ...MetadataCommandRules.properties.commandModule,
      xmlPath: ({ name }: { name: string }) => `Commands/${name}/Ext/CommandModule.bsl`,
    },
  },
} as const satisfies MetadataItemRule

export const MetadataChartOfCharacteristicTypesRules = {
  itemType: "MetadataChartOfCharacteristicTypes",
  itemTypePrefix: "ПланВидовХарактеристик",
  xmlDir: "ChartsOfCharacteristicTypes",
  uniqueNameScopes: [{ collections: ["attributes", "tabularSections"] }],
  properties: {
    xmlRoot: { type: "XMLRoot", container: "ChartOfCharacteristicTypes", rootAttributes: V8_MDCLASSES_ROOT, forReferenceOnly: true, toYAML: false, fromYAML: false },
    internalInfo: {
      type: "InternalInfo",
      xmlParents: [],
      forReferenceOnly: true,
      items: [
        { name: "ChartOfCharacteristicTypesObject", category: "Object" },
        { name: "ChartOfCharacteristicTypesRef", category: "Ref" },
        { name: "ChartOfCharacteristicTypesSelection", category: "Selection" },
        { name: "ChartOfCharacteristicTypesList", category: "List" },
        { name: "Characteristic", category: "Characteristic" },
        { name: "ChartOfCharacteristicTypesManager", category: "Manager" },
      ],
    },
    uuid: { type: "uuid", xml: "_uuid", forReferenceOnly: true, xmlParents: [] },
    name: { type: "string", xmlParents: properties, required: true, defaultValue: ({ name }: { name?: string }) => name },
    synonym: { yaml: "Синоним", type: "I8nText", xmlParents: properties, defaultValueXMLRaw: "" },
    comment: { yaml: "Комментарий", type: "string", xmlParents: properties, defaultValueXMLRaw: "" },
    useStandardCommands: { yaml: "ИспользоватьСтандартныеКоманды", type: "boolean", defaultValueXML: true, implicitValueYAML: true, xmlParents: properties },
    includeHelpInContents: { yaml: "ВключатьСправкуВСодержание", type: "boolean", defaultValueXML: false, implicitValueYAML: false, xmlParents: properties },
    characteristicExtValues: { yaml: "ДополнительныеЗначенияХарактеристик", type: "string", xmlParents: properties, defaultValueXMLRaw: "" },
    type: { yaml: "ТипЗначения", type: "TypeDescription", xml: "Type", xmlParents: properties },
    hierarchical: { yaml: "Иерархический", type: "boolean", defaultValueXML: false, implicitValueYAML: false, xmlParents: properties },
    foldersOnTop: { yaml: "ГруппыСверху", type: "boolean", defaultValueXML: true, implicitValueYAML: true, xmlParents: properties },
    codeLength: { yaml: "ДлинаКода", type: "number", defaultValueXML: 9, implicitValueYAML: 9, xmlParents: properties },
    codeAllowedLength: { yaml: "ДопустимаяДлинаКода", type: "SystemEnumeration", typeSE: "AllowedLength", defaultValueXML: "Variable", implicitValueYAML: "Variable", xmlParents: properties },
    descriptionLength: { yaml: "ДлинаНаименования", type: "number", defaultValueXML: 25, implicitValueYAML: 25, xmlParents: properties },
    codeSeries: { yaml: "СерииКодов", type: "SystemEnumeration", typeSE: "CharacteristicKindCodesSeries", defaultValueXML: "WholeCharacteristicKind", implicitValueYAML: "WholeCharacteristicKind", xmlParents: properties },
    checkUnique: { yaml: "КонтрольУникальности", type: "boolean", defaultValueXML: true, implicitValueYAML: true, xmlParents: properties },
    autonumbering: { yaml: "Автонумерация", type: "boolean", defaultValueXML: true, implicitValueYAML: true, xmlParents: properties },
    defaultPresentation: { yaml: "ОсновноеПредставление", type: "SystemEnumeration", typeSE: "CharacteristicTypeMainPresentation", defaultValueXML: "AsDescription", implicitValueYAML: "AsDescription", xmlParents: properties },
    standardAttributes: { yaml: "СтандартныеРеквизиты", type: "StandardAttributeDescriptions", standartAttributeNames: MetadataChartOfCharacteristicTypesStandardAttributeNames, xmlParents: properties },
    characteristics: { yaml: "Характеристики", type: "CharacteristicsDescriptions", xmlParents: properties, defaultValueXMLRaw: {} },
    predefinedDataUpdate: { yaml: "ОбновлениеПредопределенныхДанных", type: "SystemEnumeration", typeSE: "PredefinedDataUpdate", defaultValueXML: "Auto", implicitValueYAML: "Auto", xmlParents: properties },
    editType: { yaml: "СпособРедактирования", type: "SystemEnumeration", typeSE: "EditType", defaultValueXML: "InDialog", implicitValueYAML: "InDialog", xmlParents: properties },
    quickChoice: { yaml: "БыстрыйВыбор", type: "boolean", defaultValueXML: false, implicitValueYAML: false, xmlParents: properties },
    choiceMode: { yaml: "РежимВыбора", type: "SystemEnumeration", typeSE: "ChoiceMode", defaultValueXML: "BothWays", implicitValueYAML: "BothWays", xmlParents: properties },
    inputByString: { yaml: "ВводПоСтроке", type: "MetadataFields", xmlParents: properties, defaultValueXMLRaw: {} },
    createOnInput: { yaml: "СозданиеПриВводе", type: "SystemEnumeration", typeSE: "CreateOnInput", defaultValueXML: "DontUse", implicitValueYAML: "DontUse", xmlParents: properties },
    searchStringModeOnInputByString: { yaml: "РежимСтрокиПоискаПриВводеПоСтроке", type: "SystemEnumeration", typeSE: "SearchStringModeOnInputByString", defaultValueXML: "Begin", implicitValueYAML: "Begin", xmlParents: properties },
    choiceDataGetModeOnInputByString: { yaml: "РежимПолученияДанныхВыбораПриВводеПоСтроке", type: "SystemEnumeration", typeSE: "ChoiceDataGetModeOnInputByString", defaultValueXML: "Directly", implicitValueYAML: "Directly", xmlParents: properties },
    fullTextSearchOnInputByString: { yaml: "ПолнотекстовыйПоискПриВводеПоСтроке", type: "SystemEnumeration", typeSE: "FullTextSearchOnInputByString", defaultValueXML: "DontUse", implicitValueYAML: "DontUse", xmlParents: properties },
    choiceHistoryOnInput: { yaml: "ИсторияВыбораПриВводе", type: "SystemEnumeration", typeSE: "ChoiceHistoryOnInput", defaultValueXML: "Auto", implicitValueYAML: "Auto", xmlParents: properties },
    defaultObjectForm: { yaml: "ОсновнаяФормаОбъекта", type: "string", xmlParents: properties, metadataTarget: { kind: "localChild", owner: "this", childKind: "Form" }, defaultValueXMLRaw: "" },
    defaultFolderForm: { yaml: "ОсновнаяФормаГруппы", type: "string", xmlParents: properties, metadataTarget: { kind: "localChild", owner: "this", childKind: "Form" }, defaultValueXMLRaw: "" },
    defaultListForm: { yaml: "ОсновнаяФормаСписка", type: "string", xmlParents: properties, metadataTarget: { kind: "localChild", owner: "this", childKind: "Form" }, defaultValueXMLRaw: "" },
    defaultChoiceForm: { yaml: "ОсновнаяФормаВыбора", type: "string", xmlParents: properties, metadataTarget: { kind: "localChild", owner: "this", childKind: "Form" }, defaultValueXMLRaw: "" },
    defaultFolderChoiceForm: { yaml: "ОсновнаяФормаВыбораГруппы", type: "string", xmlParents: properties, metadataTarget: { kind: "localChild", owner: "this", childKind: "Form" }, defaultValueXMLRaw: "" },
    auxiliaryObjectForm: { yaml: "ДополнительнаяФормаОбъекта", type: "string", xmlParents: properties, metadataTarget: { kind: "localChild", owner: "this", childKind: "Form" }, defaultValueXMLRaw: "" },
    auxiliaryFolderForm: { yaml: "ДополнительнаяФормаГруппы", type: "string", xmlParents: properties, metadataTarget: { kind: "localChild", owner: "this", childKind: "Form" }, defaultValueXMLRaw: "" },
    auxiliaryListForm: { yaml: "ДополнительнаяФормаСписка", type: "string", xmlParents: properties, metadataTarget: { kind: "localChild", owner: "this", childKind: "Form" }, defaultValueXMLRaw: "" },
    auxiliaryChoiceForm: { yaml: "ДополнительнаяФормаВыбора", type: "string", xmlParents: properties, metadataTarget: { kind: "localChild", owner: "this", childKind: "Form" }, defaultValueXMLRaw: "" },
    auxiliaryFolderChoiceForm: { yaml: "ДополнительнаяФормаВыбораГруппы", type: "string", xmlParents: properties, metadataTarget: { kind: "localChild", owner: "this", childKind: "Form" }, defaultValueXMLRaw: "" },
    basedOn: { yaml: "ВводитсяНаОсновании", type: "MetadataItemLinks", xmlParents: properties, defaultValueXMLRaw: {} },
    dataLockFields: { yaml: "ПоляБлокировкиДанных", type: "MetadataFields", xmlParents: properties, defaultValueXMLRaw: {} },
    dataLockControlMode: { yaml: "РежимУправленияБлокировкойДанных", type: "SystemEnumeration", typeSE: "DefaultDataLockControlMode", defaultValueXML: "Managed", implicitValueYAML: "Managed", xmlParents: properties },
    fullTextSearch: { yaml: "ПолнотекстовыйПоиск", type: "SystemEnumeration", typeSE: "UseFullTextSearch", defaultValueXML: "Use", implicitValueYAML: "Use", xmlParents: properties },
    objectPresentation: { yaml: "ПредставлениеОбъекта", type: "I8nText", xmlParents: properties, defaultValueXMLRaw: "" },
    extendedObjectPresentation: { yaml: "РасширенноеПредставлениеОбъекта", type: "I8nText", xmlParents: properties, defaultValueXMLRaw: "" },
    listPresentation: { yaml: "ПредставлениеСписка", type: "I8nText", xmlParents: properties, defaultValueXMLRaw: "" },
    extendedListPresentation: { yaml: "РасширенноеПредставлениеСписка", type: "I8nText", xmlParents: properties, defaultValueXMLRaw: "" },
    explanation: { yaml: "Пояснение", type: "I8nText", xmlParents: properties, defaultValueXMLRaw: "" },
    dataHistory: { yaml: "ИсторияДанных", type: "SystemEnumeration", typeSE: "DataHistoryUse", defaultValueXML: "DontUse", implicitValueYAML: "DontUse", xmlParents: properties },
    updateDataHistoryImmediatelyAfterWrite: { yaml: "ОбновлятьИсториюДанныхСразуПослеЗаписи", type: "boolean", defaultValueXML: false, implicitValueYAML: false, xmlParents: properties },
    executeAfterWriteDataHistoryVersionProcessing: { yaml: "ВыполнятьОбработкуПослеЗаписиВерсииИсторииДанных", type: "boolean", defaultValueXML: false, implicitValueYAML: false, xmlParents: properties },
    objectBelonging: { yaml: "ПринадлежностьОбъекта", type: "SystemEnumeration", typeSE: "ObjectBelonging", xmlParents: properties, toYAML: false, fromYAML: false, implicitValueYAML: "Native" },
    extendedConfigurationObject: { type: "string", runtimeOnly: true },
    attributes: { yaml: "Реквизиты", xml: "Attribute", type: "MetadataAttributes", xmlParents: childObjects },
    tabularSections: { yaml: "ТабличныеЧасти", xml: "TabularSection", type: "MetadataChartOfCharacteristicTypesTabularSections", xmlParents: childObjects },
    forms: { yaml: "Формы", xml: "Form", type: "ChildFormNames", xmlParents: childObjects, folderName: "Формы", forReferenceOnly: true, toYAML: false, fromYAML: false },
    templates: { yaml: "Макеты", xml: "Template", type: "ChildTemplateNames", xmlParents: childObjects, folderName: "Макеты", forReferenceOnly: true, toYAML: false, fromYAML: false },
    commands: { yaml: "Команды", xml: "Command", type: "MetadataCommands", xmlParents: childObjects },
    objectModule: { type: "Module", nkdkPath: "МодульОбъекта.bsl", xmlPath: "Ext/ObjectModule.bsl", toXML: false, fromXML: false },
    managerModule: { type: "Module", nkdkPath: "МодульМенеджера.bsl", xmlPath: "Ext/ManagerModule.bsl", toXML: false, fromXML: false },
    predefined: { yaml: "Предопределенные", type: "Predefined", filePath: "Ext/Predefined.xml" },
    additionalIndexes: { yaml: "ДополнительныеИндексы", type: "AdditionalIndex", filePath: "Ext/AdditionalIndexes.xml" },
    help: { type: "Help", filePath: "Ext/Help.xml", xmlPath: "Ext/Help.xml", nkdkDir: "Справка", toXML: false, fromXML: false },
  },
  childCollections: [{ propertyKey: "commands", itemRule: MetadataChartOfCharacteristicTypesCommandRules }],
} as const satisfies MetadataItemRule
