import * as z from "zod"
import * as SE from "~/lib/metadata/systemEnumerations/types"
import { ZColor, ZColorXML } from "~/lib/metadata/commonObjects/color/types"
import { ZFormField, ZFormFieldXML } from "../formField/types"

export const ZSpreadSheetDocumentField = ZFormField.extend({
  autoMaxHeight: z.boolean().optional(),
  autoMaxWidth: z.boolean().optional(),
  blackAndWhiteView: z.boolean().optional(),
  borderColor: ZColor.optional(),
  drawingSelectionShowMode: SE.ZDrawingSelectionShowMode.optional(),
  edit: z.boolean().optional(),
  enableDrag: z.boolean().optional(),
  enableStartDrag: z.boolean().optional(),
  height: z.number().optional(),
  horizontalScrollBar: SE.ZScrollBarUse.optional(),
  horizontalStretch: z.boolean().optional(),
  maxHeight: z.number().optional(),
  maxWidth: z.number().optional(),
  output: SE.ZUseOutput.optional(),
  pointerType: SE.ZSpreadsheetDocumentPointerType.optional(),
  protection: z.boolean().optional(),
  selectionShowMode: SE.ZSelectionShowMode.optional(),
  showCellNames: z.boolean().optional(),
  showGrid: z.boolean().optional(),
  showGroups: z.boolean().optional(),
  showHeaders: z.boolean().optional(),
  showRowAndColumnNames: z.boolean().optional(),
  statePresentation: SE.ZStatePresentation.optional(),
  usedFileName: z.string().optional(),
  verticalScrollBar: SE.ZScrollBarUse.optional(),
  verticalStretch: z.boolean().optional(),
  viewScalingMode: SE.ZViewScalingMode.optional(),
  width: z.number().optional(),
  events: z.object({
    selection: z.string().optional(),
    dragStart: z.string().optional(),
    additionalDetailProcessing: z.string().optional(),
    uRLProcessing: z.string().optional(),
    detailProcessing: z.string().optional(),
    dragEnd: z.string().optional(),
    beforeWrite: z.string().optional(),
    beforePrint: z.string().optional(),
    drag: z.string().optional(),
    afterWrite: z.string().optional(),
    onActivate: z.string().optional(),
    onChangeAreaContentEvent: z.string().optional(),
    dragCheck: z.string().optional(),
  }).optional(),
})

export const ZSpreadSheetDocumentFieldXML = ZFormFieldXML.extend({
  AutoMaxWidth: z.boolean().optional(),
  MaxWidth: z.number().optional(),
  AutoMaxHeight: z.boolean().optional(),
  HorizontalStretch: z.boolean().optional(),
  VerticalStretch: z.boolean().optional(),
  ShowGrid: z.boolean().optional(),
  ShowHeaders: z.boolean().optional(),
  BlackAndWhiteView: z.boolean().optional(),
  Protection: z.boolean().optional(),
  DrawingSelectionShowMode: SE.ZDrawingSelectionShowMode.optional(),
  PointerType: SE.ZSpreadsheetDocumentPointerType.optional(),
  Output: SE.ZUseOutput.optional(),
  Edit: z.boolean().optional(),
  ShowGroups: z.boolean().optional(),
  EnableStartDrag: z.boolean().optional(),
  EnableDrag: z.boolean().optional(),
  ShowCellNames: z.boolean().optional(),
  ShowRowAndColumnNames: z.boolean().optional(),
  ViewScalingMode: SE.ZViewScalingMode.optional(),
  BorderColor: ZColorXML.optional(),
  Height: z.number().optional(),
  HorizontalScrollBar: SE.ZScrollBarUse.optional(),
  MaxHeight: z.number().optional(),
  SelectionShowMode: SE.ZSelectionShowMode.optional(),
  StatePresentation: SE.ZStatePresentation.optional(),
  UsedFileName: z.string().optional(),
  VerticalScrollBar: SE.ZScrollBarUse.optional(),
  Width: z.number().optional(),
  Events: z.object({
    Selection: z.string().optional(),
    DragStart: z.string().optional(),
    AdditionalDetailProcessing: z.string().optional(),
    URLProcessing: z.string().optional(),
    DetailProcessing: z.string().optional(),
    DragEnd: z.string().optional(),
    BeforeWrite: z.string().optional(),
    BeforePrint: z.string().optional(),
    Drag: z.string().optional(),
    AfterWrite: z.string().optional(),
    OnActivate: z.string().optional(),
    OnChangeAreaContentEvent: z.string().optional(),
    DragCheck: z.string().optional(),
  }).optional(),
})

export type TSpreadSheetDocumentField = z.infer<typeof ZSpreadSheetDocumentField>

export type TSpreadSheetDocumentFieldXML = z.infer<typeof ZSpreadSheetDocumentFieldXML>