import { MetadataItemRule } from "~/metadata/orchestration/property/types"
import { StandartAttributeNameFromYAML } from "./standartAttributeNames"

export const StandardAttributeDescriptionRules = {
  itemType: "StandardAttributeDescription",
  properties: {
    name: {
      xml: "_name",
      type: "string",
      defaultValue: ({ name }: { name?: string }) => (name ? StandartAttributeNameFromYAML(name) : undefined),
    },
    choiceForm: {
      yaml: "ФормаВыбора",
      xml: "xr:ChoiceForm",
      type: "string",
      order: 11,
      defaultValueXMLRaw: "",
    },
    choiceHistoryOnInput: {
      yaml: "ИсторияВыбораПриВводе",
      xml: "xr:ChoiceHistoryOnInput",
      type: "SystemEnumeration",
      typeSE: "ChoiceHistoryOnInput",
      order: 13,
      defaultValueXML: "Auto",
      implicitValueYAML: "Auto",
    },
    choiceParameterLinks: {
      yaml: "СвязиПараметровВыбора",
      xml: "xr:ChoiceParameterLinks",
      type: "ChoiceParameterLinks",
      order: 22,
      defaultValueXMLRaw: "",
    },
    choiceParameters: {
      yaml: "ПараметрыВыбора",
      xml: "xr:ChoiceParameters",
      type: "ChoiceParameters",
      order: 25,
      defaultValueXMLRaw: "",
    },
    comment: {
      yaml: "Комментарий",
      xml: "xr:Comment",
      type: "string",
      order: 20,
      defaultValueXMLRaw: "",
    },
    createOnInput: {
      yaml: "СозданиеПриВводе",
      xml: "xr:CreateOnInput",
      type: "SystemEnumeration",
      typeSE: "CreateOnInput",
      order: 5,
      defaultValueXML: "Auto",
      implicitValueYAML: "Auto",
    },
    dataHistory: {
      yaml: "ИсторияДанных",
      xml: "xr:DataHistory",
      type: "SystemEnumeration",
      typeSE: "DataHistoryUse",
      order: 16,
      defaultValueXML: "Use",
      implicitValueYAML: "Use",
    },
    editFormat: {
      yaml: "ФорматРедактирования",
      xml: "xr:EditFormat",
      type: "I8nText",
      order: 14,
      defaultValueXMLRaw: "",
    },
    extendedEdit: {
      yaml: "РасширенноеРедактирование",
      xml: "xr:ExtendedEdit",
      type: "boolean",
      order: 9,
      defaultValueXML: false,
    },
    fillChecking: {
      yaml: "ПроверкаЗаполнения",
      xml: "xr:FillChecking",
      type: "SystemEnumeration",
      typeSE: "FillChecking",
      order: 2,
      defaultValueXML: "DontCheck",
      implicitValueYAML: "DontCheck",
    },
    fillFromFillingValue: {
      yaml: "ЗаполнятьИзДанныхЗаполнения",
      xml: "xr:FillFromFillingValue",
      type: "boolean",
      order: 4,
      defaultValueXML: false,
    },
    fillValue: {
      yaml: "ЗначениеЗаполнения",
      xml: "xr:FillValue",
      type: "MetadataValue",
      order: 23,
      defaultValueXMLRaw: { "_xsi:nil": true },
    },
    format: {
      yaml: "Формат",
      xml: "xr:Format",
      type: "I8nText",
      order: 10,
      defaultValueXMLRaw: "",
    },
    fullTextSearch: {
      yaml: "ПолнотекстовыйПоиск",
      xml: "xr:FullTextSearch",
      type: "SystemEnumeration",
      typeSE: "UseFullTextSearch",
      order: 21,
      defaultValueXML: "Use",
      implicitValueYAML: "Use",
    },
    linkByType: {
      yaml: "СвязьПоТипу",
      xml: "xr:LinkByType",
      type: "TypeLink",
      order: 1,
      defaultValueXMLRaw: "",
    },
    markNegatives: {
      yaml: "ВыделятьОтрицательные",
      xml: "xr:MarkNegatives",
      type: "boolean",
      order: 17,
      defaultValueXML: false,
    },
    mask: {
      yaml: "Маска",
      xml: "xr:Mask",
      type: "string",
      order: 24,
      defaultValueXMLRaw: "",
    },
    maxValue: {
      yaml: "МаксимальноеЗначение",
      xml: "xr:MaxValue",
      type: "MinMaxValue",
      order: 7,
      defaultValueXMLRaw: { "_xsi:nil": true },
    },
    minValue: {
      yaml: "МинимальноеЗначение",
      xml: "xr:MinValue",
      type: "MinMaxValue",
      order: 18,
      defaultValueXMLRaw: { "_xsi:nil": true },
    },
    multiLine: {
      yaml: "МногострочныйРежим",
      xml: "xr:MultiLine",
      type: "boolean",
      order: 3,
      defaultValueXML: false,
    },
    passwordMode: {
      yaml: "РежимПароля",
      xml: "xr:PasswordMode",
      type: "boolean",
      order: 15,
      defaultValueXML: false,
    },
    quickChoice: {
      yaml: "БыстрыйВыбор",
      xml: "xr:QuickChoice",
      type: "SystemEnumeration",
      typeSE: "UseQuickChoice",
      order: 12,
      defaultValueXML: "Auto",
      implicitValueYAML: "Auto",
    },
    synonym: {
      yaml: "Синоним",
      xml: "xr:Synonym",
      type: "I8nText",
      order: 19,
      defaultValueXMLRaw: "",
    },
    toolTip: {
      yaml: "Подсказка",
      xml: "xr:ToolTip",
      type: "I8nText",
      order: 8,
      defaultValueXMLRaw: "",
    },
    type: {
      yaml: "Тип",
      xml: "xr:Type",
      type: "TypeDescription",
    },
    typeReductionMode: {
      yaml: "РежимСокращенияТипа",
      xml: "xr:TypeReductionMode",
      type: "SystemEnumeration",
      typeSE: "TypeReductionMode",
      order: 6,
      defaultValueXML: "TransformValues",
      implicitValueYAML: "TransformValues",
    },
  },
} as const satisfies MetadataItemRule
