import { booleanRule } from "~/metadata/commonObjects/boolean/types"
import { i8nTextRule } from "~/metadata/commonObjects/i8nText/types"
import { metadataValueRule } from "~/metadata/commonObjects/metadataValue/types"
import { stringRule } from "~/metadata/commonObjects/string/types"
import { systemEnumerationRule } from "~/metadata/systemEnumerations/types"
import { MetadataItemRule } from "~/metadata/orchestration/property/types"
import { StandartAttributeNameFromYAML } from "./standartAttributeNames"
export const StandardAttributeDescriptionRules = {
  itemType: "StandardAttributeDescription",
  properties: {
    name: stringRule({
      xml: "_name",
      defaultValue: ({ name }: { name?: string }) => (name ? StandartAttributeNameFromYAML(name) : undefined),
    }),
    choiceForm: stringRule({
      yaml: "ФормаВыбора",
      xml: "xr:ChoiceForm",
      order: 11,
      defaultValueXMLRaw: "",
    }),
    choiceHistoryOnInput: systemEnumerationRule({
      yaml: "ИсторияВыбораПриВводе",
      xml: "xr:ChoiceHistoryOnInput",
      typeSE: "ChoiceHistoryOnInput",
      order: 13,
      defaultValueXML: "Auto",
      implicitValueYAML: "Auto",
    }),
    choiceParameterLinks: {
      yaml: "СвязиПараметровВыбора",
      xml: "xr:ChoiceParameterLinks",
      type: "ChoiceParameterLinks",
      order: 22,
      defaultValueXMLRaw: "",
    },
    choiceParameters: {
      yaml: "ПараметрыВыбора",
      xml: "xr:ChoiceParameters",
      type: "ChoiceParameters",
      order: 25,
      defaultValueXMLRaw: "",
    },
    comment: stringRule({
      yaml: "Комментарий",
      xml: "xr:Comment",
      order: 20,
      defaultValueXMLRaw: "",
    }),
    createOnInput: systemEnumerationRule({
      yaml: "СозданиеПриВводе",
      xml: "xr:CreateOnInput",
      typeSE: "CreateOnInput",
      order: 5,
      defaultValueXML: "Auto",
      implicitValueYAML: "Auto",
    }),
    dataHistory: systemEnumerationRule({
      yaml: "ИсторияДанных",
      xml: "xr:DataHistory",
      typeSE: "DataHistoryUse",
      order: 16,
      defaultValueXML: "Use",
      implicitValueYAML: "Use",
    }),
    editFormat: i8nTextRule({
      yaml: "ФорматРедактирования",
      xml: "xr:EditFormat",
      order: 14,
      defaultValueXMLRaw: "",
    }),
    extendedEdit: booleanRule({
      yaml: "РасширенноеРедактирование",
      xml: "xr:ExtendedEdit",
      order: 9,
      defaultValueXML: false,
      implicitValueYAML: false,
    }),
    fillChecking: systemEnumerationRule({
      yaml: "ПроверкаЗаполнения",
      xml: "xr:FillChecking",
      typeSE: "FillChecking",
      order: 2,
      defaultValueXML: "DontCheck",
      implicitValueYAML: "DontCheck",
    }),
    fillFromFillingValue: booleanRule({
      yaml: "ЗаполнятьИзДанныхЗаполнения",
      xml: "xr:FillFromFillingValue",
      order: 4,
      defaultValueXML: false,
      implicitValueYAML: false,
    }),
    fillValue: metadataValueRule({
      yaml: "ЗначениеЗаполнения",
      xml: "xr:FillValue",
      order: 23,
      defaultValueXMLRaw: { "_xsi:nil": true },
    }),
    format: i8nTextRule({
      yaml: "Формат",
      xml: "xr:Format",
      order: 10,
      defaultValueXMLRaw: "",
    }),
    fullTextSearch: systemEnumerationRule({
      yaml: "ПолнотекстовыйПоиск",
      xml: "xr:FullTextSearch",
      typeSE: "UseFullTextSearch",
      order: 21,
      defaultValueXML: "Use",
      implicitValueYAML: "Use",
    }),
    linkByType: {
      yaml: "СвязьПоТипу",
      xml: "xr:LinkByType",
      type: "TypeLink",
      order: 1,
      defaultValueXMLRaw: "",
    },
    markNegatives: booleanRule({
      yaml: "ВыделятьОтрицательные",
      xml: "xr:MarkNegatives",
      order: 17,
      defaultValueXML: false,
      implicitValueYAML: false,
    }),
    mask: stringRule({
      yaml: "Маска",
      xml: "xr:Mask",
      order: 24,
      defaultValueXMLRaw: "",
    }),
    maxValue: {
      yaml: "МаксимальноеЗначение",
      xml: "xr:MaxValue",
      type: "MinMaxValue",
      order: 7,
      defaultValueXMLRaw: { "_xsi:nil": true },
    },
    minValue: {
      yaml: "МинимальноеЗначение",
      xml: "xr:MinValue",
      type: "MinMaxValue",
      order: 18,
      defaultValueXMLRaw: { "_xsi:nil": true },
    },
    multiLine: booleanRule({
      yaml: "МногострочныйРежим",
      xml: "xr:MultiLine",
      order: 3,
      defaultValueXML: false,
      implicitValueYAML: false,
    }),
    passwordMode: booleanRule({
      yaml: "РежимПароля",
      xml: "xr:PasswordMode",
      order: 15,
      defaultValueXML: false,
      implicitValueYAML: false,
    }),
    quickChoice: systemEnumerationRule({
      yaml: "БыстрыйВыбор",
      xml: "xr:QuickChoice",
      typeSE: "UseQuickChoice",
      order: 12,
      defaultValueXML: "Auto",
      implicitValueYAML: "Auto",
    }),
    synonym: i8nTextRule({
      yaml: "Синоним",
      xml: "xr:Synonym",
      order: 19,
      defaultValueXMLRaw: "",
    }),
    toolTip: i8nTextRule({
      yaml: "Подсказка",
      xml: "xr:ToolTip",
      order: 8,
      defaultValueXMLRaw: "",
    }),
    type: {
      yaml: "Тип",
      xml: "xr:Type",
      type: "TypeDescription",
    },
    typeReductionMode: systemEnumerationRule({
      yaml: "РежимСокращенияТипа",
      xml: "xr:TypeReductionMode",
      typeSE: "TypeReductionMode",
      order: 6,
      defaultValueXML: "TransformValues",
      implicitValueYAML: "TransformValues",
    }),
  },
} as const satisfies MetadataItemRule
