import { registerImport } from "~/lib/xml/import/importerFactory"
import { FormElementType } from "../types"
import { importUserVisibleFromXML } from "../../commonObjects/userVisible/importFromXML"
import { CatalogXML, Catalog } from "./types"

export const importCatalogFromXML = (xml: CatalogXML | undefined): Catalog | undefined => {
  if (!xml) return undefined

  return {
    elementType: FormElementType.Catalog,

    additionalIndexes: xml.AdditionalIndexes,
    attributes: xml.Attributes,
    autonumbering: xml.Autonumbering,
    auxiliaryChoiceForm: xml.AuxiliaryChoiceForm,
    auxiliaryFolderChoiceForm: xml.AuxiliaryFolderChoiceForm,
    auxiliaryFolderForm: xml.AuxiliaryFolderForm,
    auxiliaryListForm: xml.AuxiliaryListForm,
    auxiliaryObjectForm: xml.AuxiliaryObjectForm,
    basedOn: xml.BasedOn,
    characteristics: xml.Characteristics,
    checkUnique: xml.CheckUnique,
    choiceDataGetModeOnInputByString: xml.ChoiceDataGetModeOnInputByString,
    choiceHistoryOnInput: xml.ChoiceHistoryOnInput,
    choiceMode: xml.ChoiceMode,
    codeAllowedLength: xml.CodeAllowedLength,
    codeLength: xml.CodeLength,
    codeSeries: xml.CodeSeries,
    codeType: xml.CodeType,
    commands: xml.Commands,
    comment: xml.Comment,
    createOnInput: xml.CreateOnInput,
    dataHistory: xml.DataHistory,
    dataLockControlMode: xml.DataLockControlMode,
    dataLockFields: xml.DataLockFields,
    defaultChoiceForm: xml.DefaultChoiceForm,
    defaultFolderChoiceForm: xml.DefaultFolderChoiceForm,
    defaultFolderForm: xml.DefaultFolderForm,
    defaultListForm: xml.DefaultListForm,
    defaultObjectForm: xml.DefaultObjectForm,
    defaultPresentation: xml.DefaultPresentation,
    descriptionLength: xml.DescriptionLength,
    editType: xml.EditType,
    executeAfterWriteDataHistoryVersionProcessing: xml.ExecuteAfterWriteDataHistoryVersionProcessing,
    explanation: xml.Explanation,
    extendedConfigurationObject: xml.ExtendedConfigurationObject,
    extendedListPresentation: xml.ExtendedListPresentation,
    extendedObjectPresentation: xml.ExtendedObjectPresentation,
    foldersOnTop: xml.FoldersOnTop,
    forms: xml.Forms,
    fullTextSearch: xml.FullTextSearch,
    fullTextSearchOnInputByString: xml.FullTextSearchOnInputByString,
    help: xml.Help,
    hierarchical: xml.Hierarchical,
    hierarchyType: xml.HierarchyType,
    includeHelpInContents: xml.IncludeHelpInContents,
    inputByString: xml.InputByString,
    levelCount: xml.LevelCount,
    limitLevelCount: xml.LimitLevelCount,
    listPresentation: xml.ListPresentation,
    managerModule: xml.ManagerModule,
    objectBelonging: xml.ObjectBelonging,
    objectModule: xml.ObjectModule,
    objectPresentation: xml.ObjectPresentation,
    owners: xml.Owners,
    predefined: xml.Predefined,
    predefinedDataUpdate: xml.PredefinedDataUpdate,
    quickChoice: xml.QuickChoice,
    searchStringModeOnInputByString: xml.SearchStringModeOnInputByString,
    standardAttributes: xml.StandardAttributes,
    subordinationUse: xml.SubordinationUse,
    synonym: xml.Synonym,
    tabularSections: xml.TabularSections,
    templates: xml.Templates,
    updateDataHistoryImmediatelyAfterWrite: xml.UpdateDataHistoryImmediatelyAfterWrite,
    userVisible: importUserVisibleFromXML(xml.UserVisible),
    useStandardCommands: xml.UseStandardCommands,
  }
}

registerImport(FormElementType.Catalog, importCatalogFromXML)
