
import { TElementRules } from "~/lib/rulesManager/types"
import { registerElementRules } from "~/lib/rulesManager/rulesManager"
import { ZElementType } from "../types"
import * as SE from "~/lib/metadata/systemEnumerations/types"
import { ZI8nText, ZI8nTextXML } from "~/lib/metadata/commonObjects/i8nText/types"
import { ZUserVisible, ZUserVisibleXML } from "~/lib/metadata/commonObjects/userVisible/types"
import { formatUserVisible } from "~/lib/metadata/commonObjects/userVisible/format"
import { formatI8nText } from "~/lib/metadata/commonObjects/i8nText/format"
import { formatBoolean } from "~/lib/metadata/commonObjects/boolean/format"
import { parseBoolean } from "~/lib/metadata/commonObjects/boolean/parse"
import { parseI8nText } from "~/lib/metadata/commonObjects/i8nText/parse"
import { parseUserVisible } from "~/lib/metadata/commonObjects/userVisible/parse"
import { parseSystemEnumeration } from "~/lib/metadata/systemEnumerations/parse"
import { formatSystemEnumeration } from "~/lib/metadata/systemEnumerations/format"

const rules: TElementRules = {
  "additionalIndexes": {
    get type() { return ZДополнительныеИндексы },
    nameEnterprise: "ДополнительныеИндексы",
    formatProperties: undefined,
    parseProperties: undefined,
    inProperties: ()=> true,
  },
  "attributes": {
    get type() { return ZAttributes },
    nameEnterprise: "Реквизиты",
    formatProperties: undefined,
    parseProperties: undefined,
    inProperties: ()=> true,
  },
  "autonumbering": {
    get type() { return z.boolean() },
    nameEnterprise: "Автонумерация",
    formatProperties: formatBoolean,
    parseProperties: parseBoolean,
    inProperties: ()=> true,
  },
  "auxiliaryChoiceForm": {
    get type() { return z.string() },
    nameEnterprise: "ДополнительнаяФормаДляВыбора",
    formatProperties: undefined,
    parseProperties: undefined,
    inProperties: ()=> true,
  },
  "auxiliaryFolderChoiceForm": {
    get type() { return z.string() },
    nameEnterprise: "ДополнительнаяФормаДляВыбораГруппы",
    formatProperties: undefined,
    parseProperties: undefined,
    inProperties: ()=> true,
  },
  "auxiliaryFolderForm": {
    get type() { return z.string() },
    nameEnterprise: "ДополнительнаяФормаГруппы",
    formatProperties: undefined,
    parseProperties: undefined,
    inProperties: ()=> true,
  },
  "auxiliaryListForm": {
    get type() { return z.string() },
    nameEnterprise: "ДополнительнаяФормаСписка",
    formatProperties: undefined,
    parseProperties: undefined,
    inProperties: ()=> true,
  },
  "auxiliaryObjectForm": {
    get type() { return z.string() },
    nameEnterprise: "ДополнительнаяФормаОбъекта",
    formatProperties: undefined,
    parseProperties: undefined,
    inProperties: ()=> true,
  },
  "basedOn": {
    get type() { return ZКоллекцияЗначенийСвойстваОбъектаМетаданных },
    nameEnterprise: "ВводитсяНаОсновании",
    formatProperties: undefined,
    parseProperties: undefined,
    inProperties: ()=> true,
  },
  "characteristics": {
    get type() { return ZОписанияХарактеристик },
    nameEnterprise: "Характеристики",
    formatProperties: undefined,
    parseProperties: undefined,
    inProperties: ()=> true,
  },
  "checkUnique": {
    get type() { return z.boolean() },
    nameEnterprise: "КонтрольУникальности",
    formatProperties: formatBoolean,
    parseProperties: parseBoolean,
    inProperties: ()=> true,
  },
  "choiceDataGetModeOnInputByString": {
    get type() { return SE.ZChoiceDataGetModeOnInputByString },
    nameEnterprise: "РежимПолученияДанныхВыбораПриВводеПоСтроке",
    formatProperties: formatSystemEnumeration,
    parseProperties: parseSystemEnumeration,
    get typeEnterprise() { return SE.ZChoiceDataGetModeOnInputByStringEnterprise },
    inProperties: ()=> true,
  },
  "choiceHistoryOnInput": {
    get type() { return SE.ZChoiceHistoryOnInput },
    nameEnterprise: "ИсторияВыбораПриВводе",
    formatProperties: formatSystemEnumeration,
    parseProperties: parseSystemEnumeration,
    get typeEnterprise() { return SE.ZChoiceHistoryOnInputEnterprise },
    inProperties: ()=> true,
  },
  "choiceMode": {
    get type() { return SE.ZChoiceMode },
    nameEnterprise: "СпособВыбора",
    formatProperties: formatSystemEnumeration,
    parseProperties: parseSystemEnumeration,
    get typeEnterprise() { return SE.ZChoiceModeEnterprise },
    inProperties: ()=> true,
  },
  "codeAllowedLength": {
    get type() { return SE.ZAllowedLength },
    nameEnterprise: "ДопустимаяДлинаКода",
    formatProperties: formatSystemEnumeration,
    parseProperties: parseSystemEnumeration,
    get typeEnterprise() { return SE.ZAllowedLengthEnterprise },
    inProperties: ()=> true,
  },
  "codeLength": {
    get type() { return z.number() },
    nameEnterprise: "ДлинаКода",
    formatProperties: undefined,
    parseProperties: undefined,
    inProperties: ()=> true,
  },
  "codeSeries": {
    get type() { return SE.ZCharacteristicKindCodesSeries },
    nameEnterprise: "СерииКодов",
    formatProperties: formatSystemEnumeration,
    parseProperties: parseSystemEnumeration,
    get typeEnterprise() { return SE.ZCharacteristicKindCodesSeriesEnterprise },
    inProperties: ()=> true,
  },
  "codeType": {
    get type() { return ZТипКодаСправочника },
    nameEnterprise: "ТипКода",
    formatProperties: undefined,
    parseProperties: undefined,
    inProperties: ()=> true,
  },
  "commands": {
    get type() { return ZCommandList },
    nameEnterprise: "Команды",
    formatProperties: undefined,
    parseProperties: undefined,
    inProperties: ()=> true,
  },
  "comment": {
    get type() { return z.string() },
    nameEnterprise: "Комментарий",
    formatProperties: undefined,
    parseProperties: undefined,
    inProperties: ()=> true,
  },
  "createOnInput": {
    get type() { return SE.ZCreateOnInput },
    nameEnterprise: "СозданиеПриВводе",
    formatProperties: formatSystemEnumeration,
    parseProperties: parseSystemEnumeration,
    get typeEnterprise() { return SE.ZCreateOnInputEnterprise },
    inProperties: ()=> true,
  },
  "dataHistory": {
    get type() { return SE.ZDataHistoryUse },
    nameEnterprise: "ИсторияДанных",
    formatProperties: formatSystemEnumeration,
    parseProperties: parseSystemEnumeration,
    get typeEnterprise() { return SE.ZDataHistoryUseEnterprise },
    inProperties: ()=> true,
  },
  "dataLockControlMode": {
    get type() { return SE.ZDefaultDataLockControlMode },
    nameEnterprise: "РежимУправленияБлокировкойДанных",
    formatProperties: formatSystemEnumeration,
    parseProperties: parseSystemEnumeration,
    get typeEnterprise() { return SE.ZDefaultDataLockControlModeEnterprise },
    inProperties: ()=> true,
  },
  "dataLockFields": {
    get type() { return ZFieldList },
    nameEnterprise: "ПоляБлокировкиДанных",
    formatProperties: undefined,
    parseProperties: undefined,
    inProperties: ()=> true,
  },
  "defaultChoiceForm": {
    get type() { return z.string() },
    nameEnterprise: "ОсновнаяФормаДляВыбора",
    formatProperties: undefined,
    parseProperties: undefined,
    inProperties: ()=> true,
  },
  "defaultFolderChoiceForm": {
    get type() { return z.string() },
    nameEnterprise: "ОсновнаяФормаДляВыбораГруппы",
    formatProperties: undefined,
    parseProperties: undefined,
    inProperties: ()=> true,
  },
  "defaultFolderForm": {
    get type() { return z.string() },
    nameEnterprise: "ОсновнаяФормаГруппы",
    formatProperties: undefined,
    parseProperties: undefined,
    inProperties: ()=> true,
  },
  "defaultListForm": {
    get type() { return z.string() },
    nameEnterprise: "ОсновнаяФормаСписка",
    formatProperties: undefined,
    parseProperties: undefined,
    inProperties: ()=> true,
  },
  "defaultObjectForm": {
    get type() { return z.string() },
    nameEnterprise: "ОсновнаяФормаОбъекта",
    formatProperties: undefined,
    parseProperties: undefined,
    inProperties: ()=> true,
  },
  "defaultPresentation": {
    get type() { return ZОсновноеПредставлениеСправочника },
    nameEnterprise: "ОсновноеПредставление",
    formatProperties: undefined,
    parseProperties: undefined,
    inProperties: ()=> true,
  },
  "descriptionLength": {
    get type() { return z.number() },
    nameEnterprise: "ДлинаНаименования",
    formatProperties: undefined,
    parseProperties: undefined,
    inProperties: ()=> true,
  },
  "editType": {
    get type() { return SE.ZEditType },
    nameEnterprise: "СпособРедактирования",
    formatProperties: formatSystemEnumeration,
    parseProperties: parseSystemEnumeration,
    get typeEnterprise() { return SE.ZEditTypeEnterprise },
    inProperties: ()=> true,
  },
  "executeAfterWriteDataHistoryVersionProcessing": {
    get type() { return z.boolean() },
    nameEnterprise: "ВыполнятьОбработкуПослеЗаписиВерсииИсторииДанных",
    formatProperties: formatBoolean,
    parseProperties: parseBoolean,
    inProperties: ()=> true,
  },
  "explanation": {
    get type() { return z.string() },
    nameEnterprise: "Пояснение",
    formatProperties: undefined,
    parseProperties: undefined,
    inProperties: ()=> true,
  },
  "extendedConfigurationObject": {
    get type() { return ZУникальныйИдентификатор },
    nameEnterprise: "ОбъектРасширяемойКонфигурации",
    formatProperties: undefined,
    parseProperties: undefined,
    inProperties: ()=> true,
  },
  "extendedListPresentation": {
    get type() { return z.string() },
    nameEnterprise: "РасширенноеПредставлениеСписка",
    formatProperties: undefined,
    parseProperties: undefined,
    inProperties: ()=> true,
  },
  "extendedObjectPresentation": {
    get type() { return z.string() },
    nameEnterprise: "РасширенноеПредставлениеОбъекта",
    formatProperties: undefined,
    parseProperties: undefined,
    inProperties: ()=> true,
  },
  "foldersOnTop": {
    get type() { return z.boolean() },
    nameEnterprise: "ГруппыСверху",
    formatProperties: formatBoolean,
    parseProperties: parseBoolean,
    inProperties: ()=> true,
  },
  "forms": {
    get type() { return ZКоллекцияОбъектовМетаданных },
    nameEnterprise: "Формы",
    formatProperties: undefined,
    parseProperties: undefined,
    inProperties: ()=> true,
  },
  "fullTextSearch": {
    get type() { return SE.ZUseFullTextSearch },
    nameEnterprise: "ПолнотекстовыйПоиск",
    formatProperties: formatSystemEnumeration,
    parseProperties: parseSystemEnumeration,
    get typeEnterprise() { return SE.ZUseFullTextSearchEnterprise },
    inProperties: ()=> true,
  },
  "fullTextSearchOnInputByString": {
    get type() { return SE.ZFullTextSearchOnInputByString },
    nameEnterprise: "ПолнотекстовыйПоискПриВводеПоСтроке",
    formatProperties: formatSystemEnumeration,
    parseProperties: parseSystemEnumeration,
    get typeEnterprise() { return SE.ZFullTextSearchOnInputByStringEnterprise },
    inProperties: ()=> true,
  },
  "help": {
    get type() { return ZНеопределено },
    nameEnterprise: "Справка",
    formatProperties: undefined,
    parseProperties: undefined,
    inProperties: ()=> true,
  },
  "hierarchical": {
    get type() { return z.boolean() },
    nameEnterprise: "Иерархический",
    formatProperties: formatBoolean,
    parseProperties: parseBoolean,
    inProperties: ()=> true,
  },
  "hierarchyType": {
    get type() { return SE.ZHierarchyType },
    nameEnterprise: "ВидИерархии",
    formatProperties: formatSystemEnumeration,
    parseProperties: parseSystemEnumeration,
    get typeEnterprise() { return SE.ZHierarchyTypeEnterprise },
    inProperties: ()=> true,
  },
  "includeHelpInContents": {
    get type() { return z.boolean() },
    nameEnterprise: "ВключатьСправкуВСодержание",
    formatProperties: formatBoolean,
    parseProperties: parseBoolean,
    inProperties: ()=> true,
  },
  "inputByString": {
    get type() { return ZFieldList },
    nameEnterprise: "ВводПоСтроке",
    formatProperties: undefined,
    parseProperties: undefined,
    inProperties: ()=> true,
  },
  "levelCount": {
    get type() { return z.number() },
    nameEnterprise: "КоличествоУровней",
    formatProperties: undefined,
    parseProperties: undefined,
    inProperties: ()=> true,
  },
  "limitLevelCount": {
    get type() { return z.boolean() },
    nameEnterprise: "ОграничиватьКоличествоУровней",
    formatProperties: formatBoolean,
    parseProperties: parseBoolean,
    inProperties: ()=> true,
  },
  "listPresentation": {
    get type() { return z.string() },
    nameEnterprise: "ПредставлениеСписка",
    formatProperties: undefined,
    parseProperties: undefined,
    inProperties: ()=> true,
  },
  "managerModule": {
    get type() { return ZНеопределено },
    nameEnterprise: "МодульМенеджера",
    formatProperties: undefined,
    parseProperties: undefined,
    inProperties: ()=> true,
  },
  "objectBelonging": {
    get type() { return SE.ZObjectBelonging },
    nameEnterprise: "ПринадлежностьОбъекта",
    formatProperties: formatSystemEnumeration,
    parseProperties: parseSystemEnumeration,
    get typeEnterprise() { return SE.ZObjectBelongingEnterprise },
    inProperties: ()=> true,
  },
  "objectModule": {
    get type() { return ZНеопределено },
    nameEnterprise: "МодульОбъекта",
    formatProperties: undefined,
    parseProperties: undefined,
    inProperties: ()=> true,
  },
  "objectPresentation": {
    get type() { return ZI8nText },
    nameEnterprise: "ПредставлениеОбъекта",
    formatProperties: formatI8nText,
    parseProperties: parseI8nText,
    inProperties: ()=> true,
  },
  "owners": {
    get type() { return ZКоллекцияЗначенийСвойстваОбъектаМетаданных },
    nameEnterprise: "Владельцы",
    formatProperties: undefined,
    parseProperties: undefined,
    inProperties: ()=> true,
  },
  "predefined": {
    get type() { return ZPredefinedList },
    nameEnterprise: "Предопределенные",
    formatProperties: undefined,
    parseProperties: undefined,
    inProperties: ()=> true,
  },
  "predefinedDataUpdate": {
    get type() { return SE.ZPredefinedDataUpdate },
    nameEnterprise: "ОбновлениеПредопределенныхДанных",
    formatProperties: formatSystemEnumeration,
    parseProperties: parseSystemEnumeration,
    get typeEnterprise() { return SE.ZPredefinedDataUpdateEnterprise },
    inProperties: ()=> true,
  },
  "quickChoice": {
    get type() { return z.boolean() },
    nameEnterprise: "БыстрыйВыбор",
    formatProperties: formatBoolean,
    parseProperties: parseBoolean,
    inProperties: ()=> true,
  },
  "searchStringModeOnInputByString": {
    get type() { return SE.ZSearchStringModeOnInputByString },
    nameEnterprise: "СпособПоискаСтрокиПриВводеПоСтроке",
    formatProperties: formatSystemEnumeration,
    parseProperties: parseSystemEnumeration,
    get typeEnterprise() { return SE.ZSearchStringModeOnInputByStringEnterprise },
    inProperties: ()=> true,
  },
  "standardAttributes": {
    get type() { return ZОписанияСтандартныхРеквизитов },
    nameEnterprise: "СтандартныеРеквизиты",
    formatProperties: undefined,
    parseProperties: undefined,
    inProperties: ()=> true,
  },
  "subordinationUse": {
    get type() { return SE.ZSubordinationUse },
    nameEnterprise: "ИспользованиеПодчинения",
    formatProperties: formatSystemEnumeration,
    parseProperties: parseSystemEnumeration,
    get typeEnterprise() { return SE.ZSubordinationUseEnterprise },
    inProperties: ()=> true,
  },
  "synonym": {
    get type() { return ZI8nText },
    nameEnterprise: "Синоним",
    formatProperties: formatI8nText,
    parseProperties: parseI8nText,
    inProperties: ()=> true,
  },
  "tabularSections": {
    get type() { return ZКоллекцияОбъектовМетаданных },
    nameEnterprise: "ТабличныеЧасти",
    formatProperties: undefined,
    parseProperties: undefined,
    inProperties: ()=> true,
  },
  "templates": {
    get type() { return ZКоллекцияОбъектовМетаданных },
    nameEnterprise: "Макеты",
    formatProperties: undefined,
    parseProperties: undefined,
    inProperties: ()=> true,
  },
  "updateDataHistoryImmediatelyAfterWrite": {
    get type() { return z.boolean() },
    nameEnterprise: "ОбновлятьИсториюДанныхСразуПослеЗаписи",
    formatProperties: formatBoolean,
    parseProperties: parseBoolean,
    inProperties: ()=> true,
  },
  "userVisible": {
    get type() { return ZUserVisible },
    nameEnterprise: "ПользовательскаяВидимость",
    formatProperties: formatUserVisible,
    parseProperties: parseUserVisible,
    inProperties: ()=> true,
  },
  "useStandardCommands": {
    get type() { return z.boolean() },
    nameEnterprise: "ИспользоватьСтандартныеКоманды",
    formatProperties: formatBoolean,
    parseProperties: parseBoolean,
    inProperties: ()=> true,
  },
}

registerElementRules(ZElementType.enum.Catalog, rules)