import { IndentationAwareLexer, IndentationAwareTokenBuilder, inject, type Module } from "langium"
import {
  createDefaultModule,
  createDefaultSharedModule,
  type DefaultSharedModuleContext,
  type LangiumServices,
  type LangiumSharedServices,
  type PartialLangiumServices,
} from "langium/lsp"
import { NkdkGeneratedModule, NkdkGeneratedSharedModule } from "./generated/module"
import { NkdkValidator, registerValidationChecks } from "./nkdk-validator"

/**
 * Declaration of custom services - add your own service classes here.
 */
export type NkdkAddedServices = {
  validation: {
    NkdkValidator: NkdkValidator
  }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type NkdkServices = LangiumServices & NkdkAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const NkdkModule: Module<NkdkServices, PartialLangiumServices & NkdkAddedServices> = {
  validation: {
    NkdkValidator: () => new NkdkValidator(),
  },

  parser: {
    TokenBuilder: () => new IndentationAwareTokenBuilder(),
    Lexer: (services) => new IndentationAwareLexer(services),
  },
}

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createNkdkServices(context: DefaultSharedModuleContext): {
  shared: LangiumSharedServices
  Nkdk: NkdkServices
} {
  const shared = inject(createDefaultSharedModule(context), NkdkGeneratedSharedModule)
  const Nkdk = inject(createDefaultModule({ shared }), NkdkGeneratedModule, NkdkModule)
  shared.ServiceRegistry.register(Nkdk)
  registerValidationChecks(Nkdk)
  if (!context.connection) {
    // We don't run inside a language server
    // Therefore, initialize the configuration provider instantly
    shared.workspace.ConfigurationProvider.initialized({})
  }
  return { shared, Nkdk }
}
