import "./additionalIndex/exportToXML"
import "./characteristicsDescription/exportToXML"
import "./choiceList/exportToXML"
import "./color/exportToXML"
import "./dynamicList/exportToXML"
import "./indexField/exportToXML"
import "./metadataAttribute/exportToXML"
import "./metadataCommandGroup/exportToXML"
// import "./metadataPath/exportToXML"
import "./metadataRef/exportToXML"
import "./picture/exportToXML"
import "./standardAttributeDescription/exportToXML"
import "./typeDescription/exportToXML"
import "./userVisible/exportToXML"
