import "./additionalIndex/importFromXML"
import "./characteristicsDescription/importFromXML"
import "./choiceList/importFromXML"
import "./color/importFromXML"
import "./dynamicList/importFromXML"
import "./indexField/importFromXML"
import "./metadataAttribute/importFromXML"
import "./metadataCommandGroup/importFromXML"
// import "./metadataPath/importFromXML"
import "./border/importFromXML"
import "./metadataRef/importFromXML"
import "./picture/importFromXML"
import "./standardAttributeDescription/importFromXML"
import "./typeDescription/importFromXML"
import "./userVisible/importFromXML"
