import "./additionalIndex/fromXML"
import "./additionalIndex/fromYAML"
import "./additionalIndex/toJSONSchema"
import "./additionalIndex/toXML"
import "./additionalIndex/toYAML"

import "../orchestration/event/propertyTypeRules"

import "./boolean/fromXML"
import "./boolean/toJSONSchema"

import "./border/fromXML"
import "./border/fromYAML"
import "./border/toEnterprise"
import "./border/toJSONSchema"
import "./border/toXML"
import "./border/toYAML"

import "./characteristicsDescription/fromXML"
import "./characteristicsDescription/fromYAML"
import "./characteristicsDescription/toJSONSchema"
import "./characteristicsDescription/toXML"
import "./characteristicsDescription/toYAML"

import "./choiceList/fromXML"
import "./choiceList/fromYAML"
import "./choiceList/toJSONSchema"
import "./choiceList/toXML"
import "./choiceList/toYAML"

import "./сhoiceParameterLinks/fromXML"
import "./сhoiceParameterLinks/fromYAML"
import "./сhoiceParameterLinks/toJSONSchema"
import "./сhoiceParameterLinks/toXML"
import "./сhoiceParameterLinks/toYAML"

import "./сhoiceParameters/fromXML"
import "./сhoiceParameters/fromYAML"
import "./сhoiceParameters/toJSONSchema"
import "./сhoiceParameters/toXML"
import "./сhoiceParameters/toYAML"

import "./color/fromXML"
import "./color/fromYAML"
import "./color/toEnterprise"
import "./color/toJSONSchema"
import "./color/toXML"
import "./color/toYAML"

import "../forms/commonObjects/dynamicList/fromXML"
import "../forms/commonObjects/dynamicList/fromYAML"
import "../forms/commonObjects/dynamicList/toXML"
import "../forms/commonObjects/dynamicList/toYAML"

import "./fieldsList/fromXML"
import "./fieldsList/fromYAML"
import "./fieldsList/toJSONSchema"
import "./fieldsList/toXML"
import "./fieldsList/toYAML"

import "./font/fromXML"
import "./font/fromYAML"
import "./font/toEnterprise"
import "./font/toJSONSchema"
import "./font/toXML"
import "./font/toYAML"

import "./formattedI8nText/fromXML"
import "./formattedI8nText/fromYAML"
import "./formattedI8nText/toEnterprise"
import "./formattedI8nText/toJSONSchema"
import "./formattedI8nText/toXML"
import "./formattedI8nText/toYAML"

import "./functionalOptionsProperty/fromXML"
import "./functionalOptionsProperty/fromYAML"
import "./functionalOptionsProperty/toJSONSchema"
import "./functionalOptionsProperty/toXML"
import "./functionalOptionsProperty/toYAML"

import "./i8nText/fromXML"
import "./i8nText/fromYAML"
import "./i8nText/toEnterprise"
import "./i8nText/toJSONSchema"
import "./i8nText/toXML"
import "./i8nText/toYAML"

import "./indexField/fromXML"
import "./indexField/fromYAML"
import "./indexField/toJSONSchema"
import "./indexField/toXML"
import "./indexField/toYAML"

import "./internalInfo/toXML"

import "./metadataAttribute/fromXML"
import "./metadataAttribute/fromYAML"
import "./metadataAttribute/toJSONSchema"
import "./metadataAttribute/toXML"
import "./metadataAttribute/toYAML"

import "./metadataCommandGroup/fromXML"
import "./metadataCommandGroup/fromYAML"
import "./metadataCommandGroup/toXML"
import "./metadataCommandGroup/toYAML"

import "./metadataField/fromXML"
import "./metadataField/fromYAML"
import "./metadataField/toJSONSchema"
import "./metadataField/toXML"
import "./metadataField/toYAML"

import "./metadataPath/fromYAML"
import "./metadataPath/toJSONSchema"
import "./metadataPath/toYAML"

import "./metadataRef/fromXML"
import "./metadataRef/fromYAML"
import "./metadataRef/toJSONSchema"
import "./metadataRef/toXML"
import "./metadataRef/toYAML"

import "./metadataTabularSection/fromXML"
import "./metadataTabularSection/fromYAML"
import "./metadataTabularSection/toJSONSchema"
import "./metadataTabularSection/toXML"
import "./metadataTabularSection/toYAML"

import "./metadataValue/fromXML"
import "./metadataValue/fromYAML"
import "./metadataValue/toJSONSchema"
import "./metadataValue/toXML"
import "./metadataValue/toYAML"

import "./metadataValueCollection/fromXML"
import "./metadataValueCollection/fromYAML"
import "./metadataValueCollection/toJSONSchema"
import "./metadataValueCollection/toXML"
import "./metadataValueCollection/toYAML"

import "./picture/fromXML"
import "./picture/fromYAML"
import "./picture/toEnterprise"
import "./picture/toJSONSchema"
import "./picture/toXML"
import "./picture/toYAML"

import "./predifined/fromXML"
import "./predifined/fromYAML"
import "./predifined/toJSONSchema"
import "./predifined/toXML"
import "./predifined/toYAML"

import "./standardAttributeDescription/fromXML"
import "./standardAttributeDescription/fromYAML"
import "./standardAttributeDescription/toJSONSchema"
import "./standardAttributeDescription/toXML"
import "./standardAttributeDescription/toYAML"

import "./string/fromXML"
import "./string/toJSONSchema"
import "./string/toYAML"

import "./typeDescription/fromXML"
import "./typeDescription/fromYAML"
import "./typeDescription/toEnterprise"
import "./typeDescription/toJSONSchema"
import "./typeDescription/toXML"
import "./typeDescription/toYAML"

import "./typeLink/fromXML"
import "./typeLink/fromYAML"
import "./typeLink/toJSONSchema"
import "./typeLink/toXML"
import "./typeLink/toYAML"

import "./usePurposes/fromXML"
import "./usePurposes/fromYAML"
import "./usePurposes/toJSONSchema"
import "./usePurposes/toXML"
import "./usePurposes/toYAML"

import "./userVisible/fromXML"
import "./userVisible/fromYAML"
import "./userVisible/toJSONSchema"
import "./userVisible/toXML"
import "./userVisible/toYAML"

import "./metadataRef/fromXML"
import "./metadataRef/fromYAML"
import "./metadataRef/toXML"
import "./metadataRef/toYAML"

import "./characteristicsDescription/fromXML"
import "./characteristicsDescription/fromYAML"
import "./characteristicsDescription/toXML"
import "./characteristicsDescription/toYAML"

import "./characteristicsDescription/fromXML"
import "./characteristicsDescription/fromYAML"
import "./characteristicsDescription/toXML"
import "./characteristicsDescription/toYAML"

import "./number/toJSONSchema"

import "./internalInfo/fromXML"
import "./internalInfo/toXML"
