import "./metadataCommand/register"
import "./metadataCommonCommand"

import "./metadataCatalog/register"

import "./metadataConstant/register"
import "./metadataConstant"
import "./metadataBot"
import "./metadataCommonAttribute/register"
import "./metadataCommonAttribute"
import "./metadataDefinedType/register"
import "./metadataDefinedType"
import "./metadataEventSubscription"
import "./metadataFilterCriterion/register"
import "./metadataFilterCriterion"
import "./metadataFunctionalOptionsParameter"
import "./metadataSettingsStorage/register"
import "./metadataSettingsStorage"

import "./metadataDocument/register"
import "./metadataDocument"
import "./metadataDataProcessor/register"
import "./metadataDataProcessor"
import "./metadataReport/register"
import "./metadataReport"
import "./metadataDocumentJournal/register"
import "./metadataDocumentJournal"
import "./metadataHTTPService"
import "./metadataInformationRegister/register"
import "./metadataInformationRegister"
import "./metadataAccumulationRegister/register"
import "./metadataAccumulationRegister"
import "./metadataExchangePlan/register"
import "./metadataExchangePlan"
import "./metadataDocumentNumerator/register"
import "./metadataDocumentNumerator"

import "./metadataEnumeration/register"
import "./metadataEnumeration"

import "./metadataSequence"
import "./metadataSessionParameter"
import "./metadataStyleItem/register"
import "./metadataWSReference"

import "./metadataFunctionalOption"
import "./metadataRole"
import "./metadataScheduledJob"
import "./metadataLanguage"
import "./metadataCommonTemplate"
import "./metadataCommonModule"
import "./metadataXDTOPackage"
import "./metadataWebSocketClient"
import "./metadataExternalDataSource/register"
import "./metadataCommonPicture/register"
import "./metadataStyle"
import "./metadataCommandGroup"
import "./metadataSubsystem/register"
import "./metadataAccountingRegister/register"
import "./dataPathCommon/register"
import "./metadataAccountingRegister"
import "./metadataBusinessProcess/register"
import "./metadataBusinessProcess"
import "./metadataCalculationRegister/register"
import "./metadataCalculationRegister"
import "./metadataChartOfAccounts/register"
import "./metadataChartOfAccounts"
import "./metadataChartOfCalculationTypes/register"
import "./metadataChartOfCalculationTypes"
import "./metadataChartOfCharacteristicTypes/register"
import "./metadataChartOfCharacteristicTypes"
import "./metadataCommonForm"
import "./metadataIntegrationService"
import "./metadataTask/register"
import "./metadataTask"
import "./metadataWebService"

let appliedObjectsRegistered = false

export function registerAppliedObjects(): void {
  if (appliedObjectsRegistered) return
  appliedObjectsRegistered = true
}
