import { MetadataItemRule } from "~/metadata/orchestration/property/types"

export const CharacteristicsDescriptionRules = {
  itemType: "CharacteristicsDescription",
  properties: {
    characteristicTypes: {
      yaml: "ВидыХарактеристик",
      xml: "_from",
      xmlParents: ["xr:CharacteristicTypes"],
      type: "string",
      order: 1,
    },
    keyField: {
      yaml: "ПолеКлюча",
      xml: "xr:KeyField",
      xmlParents: ["xr:CharacteristicTypes"],
      type: "string",
      defaultValueXML: "-1",
      order: 2,
    },
    typesFilterField: {
      yaml: "ПолеОтбораВидов",
      xml: "xr:TypesFilterField",
      xmlParents: ["xr:CharacteristicTypes"],
      type: "string",
      defaultValueXML: "-1",
      order: 3,
    },
    typesFilterValue: {
      yaml: "ЗначениеОтбораВидов",
      xml: "xr:TypesFilterValue",
      xmlParents: ["xr:CharacteristicTypes"],
      type: "MetadataValue",
      valueType: ["string", "ref", "boolean"],
      exportNilValue: true,
      order: 4,
    },
    dataPathField: {
      yaml: "ПолеПутиКДанным",
      xml: "xr:DataPathField",
      xmlParents: ["xr:CharacteristicTypes"],
      type: "string",
      defaultValueXML: "-1",
      preserveFromReferenceXML: true,
      order: 5,
    },
    multipleValuesUseField: {
      yaml: "ПолеИспользованияМножественныхЗначений",
      xml: "xr:MultipleValuesUseField",
      xmlParents: ["xr:CharacteristicTypes"],
      type: "string",
      defaultValueXML: "-1",
      preserveFromReferenceXML: true,
      order: 6,
    },
    characteristicValues: {
      yaml: "ЗначенияХарактеристик",
      xml: "_from",
      xmlParents: ["xr:CharacteristicValues"],
      type: "string",
      order: 7,
    },
    objectField: {
      yaml: "ПолеОбъекта",
      xml: "xr:ObjectField",
      xmlParents: ["xr:CharacteristicValues"],
      type: "string",
      defaultValueXML: "-1",
      order: 8,
    },
    typeField: {
      yaml: "ПолеВида",
      xml: "xr:TypeField",
      xmlParents: ["xr:CharacteristicValues"],
      type: "string",
      defaultValueXML: "-1",
      order: 9,
    },
    valueField: {
      yaml: "ПолеЗначения",
      xml: "xr:ValueField",
      xmlParents: ["xr:CharacteristicValues"],
      type: "string",
      defaultValueXML: "-1",
      order: 10,
    },
    multipleValuesKeyField: {
      yaml: "ПолеКлючаМножественныхЗначений",
      xml: "xr:MultipleValuesKeyField",
      xmlParents: ["xr:CharacteristicValues"],
      type: "string",
      defaultValueXML: "-1",
      preserveFromReferenceXML: true,
      order: 11,
    },
    multipleValuesOrderField: {
      yaml: "ПолеПорядкаМножественныхЗначений",
      xml: "xr:MultipleValuesOrderField",
      xmlParents: ["xr:CharacteristicValues"],
      type: "string",
      defaultValueXML: "-1",
      preserveFromReferenceXML: true,
      order: 12,
    },
  },
} as const satisfies MetadataItemRule
