import { booleanRule } from "~/metadata/commonObjects/boolean/types"
import { i8nTextRule } from "~/metadata/commonObjects/i8nText/types"
import { moduleRule } from "~/metadata/commonObjects/module/types"
import { numberRule } from "~/metadata/commonObjects/number/types"
import { stringRule } from "~/metadata/commonObjects/string/types"
import { uuidRule } from "~/metadata/commonObjects/uuid/types"
import { xmlRootRule } from "~/metadata/commonObjects/xmlRoot/types"
import { systemEnumerationRule } from "~/metadata/systemEnumerations/types"
import { V8_MDCLASSES_ROOT } from "~/metadata/orchestration/appliedObject/presets"
import { MetadataItemRule } from "~/metadata/orchestration/property/types"
import { commonBasedOnObjectPaths } from "~/metadata/commonObjects/metadataTargets"
import { MetadataCommandRules } from "../metadataCommand/rules"
const properties = ["Properties"]
const childObjects = ["ChildObjects"]
export const MetadataChartOfAccountsStandardAttributeNames: Record<string, string> = {
  PredefinedDataName: "ИмяПредопределенныхДанных",
  Order: "Порядок",
  OffBalance: "Забалансовый",
  Type: "Вид",
  Description: "Наименование",
  Code: "Код",
  Parent: "Родитель",
  Predefined: "Предопределенный",
  DeletionMark: "ПометкаУдаления",
  Ref: "Ссылка",
}
const MetadataChartOfAccountsCommandRules = {
  ...MetadataCommandRules,
  properties: {
    ...MetadataCommandRules.properties,
    commandModule: {
      ...MetadataCommandRules.properties.commandModule,
      xmlPath: ({ name }: { name: string }) => `Commands/${name}/Ext/CommandModule.bsl`,
    },
  },
} as const satisfies MetadataItemRule
export const MetadataChartOfAccountsRules = {
  itemType: "MetadataChartOfAccounts",
  metadataTargetOwner: { kind: "self", root: "ChartOfAccounts" },
  itemTypePrefix: "ПланСчетов",
  xmlDir: "ChartsOfAccounts",
  uniqueNameScopes: [{ collections: ["attributes", "tabularSections"] }],
  properties: {
    xmlRoot: xmlRootRule({
      container: "ChartOfAccounts",
      rootAttributes: V8_MDCLASSES_ROOT,
      forReferenceOnly: true,
      toYAML: false,
      fromYAML: false,
    }),
    internalInfo: {
      type: "InternalInfo",
      xmlParents: [],
      forReferenceOnly: true,
      items: [
        { name: "ChartOfAccountsObject", category: "Object" },
        { name: "ChartOfAccountsRef", category: "Ref" },
        { name: "ChartOfAccountsSelection", category: "Selection" },
        { name: "ChartOfAccountsList", category: "List" },
        { name: "ChartOfAccountsManager", category: "Manager" },
        { name: "ChartOfAccountsExtDimensionTypes", category: "ExtDimensionTypes" },
        { name: "ChartOfAccountsExtDimensionTypesRow", category: "ExtDimensionTypesRow" },
      ],
    },
    uuid: uuidRule({ xml: "_uuid", forReferenceOnly: true, xmlParents: [] }),
    name: stringRule({ xmlParents: properties, required: true, defaultValue: ({ name }: { name?: string }) => name }),
    synonym: i8nTextRule({ yaml: "Синоним", xmlParents: properties, defaultValueXMLRaw: "" }),
    comment: stringRule({ yaml: "Комментарий", xmlParents: properties, defaultValueXMLRaw: "" }),
    useStandardCommands: booleanRule({
      yaml: "ИспользоватьСтандартныеКоманды",
      defaultValueXML: true,
      implicitValueYAML: true,
      xmlParents: properties,
    }),
    includeHelpInContents: booleanRule({
      yaml: "ВключатьСправкуВСодержание",
      defaultValueXML: false,
      implicitValueYAML: false,
      xmlParents: properties,
    }),
    basedOn: {
      yaml: "ВводитсяНаОсновании",
      type: "MetadataItemLinks",
      metadataTarget: { kind: "object", allowedObjectPaths: commonBasedOnObjectPaths },
      xmlParents: properties,
      defaultValueXMLRaw: {},
    },
    extDimensionTypes: stringRule({ yaml: "ВидыСубконто", xmlParents: properties, defaultValueXMLRaw: "" }),
    maxExtDimensionCount: numberRule({
      yaml: "МаксКоличествоСубконто",
      defaultValueXML: 0,
      implicitValueYAML: 0,
      xmlParents: properties,
    }),
    codeMask: stringRule({ yaml: "МаскаКода", xmlParents: properties, defaultValueXMLRaw: "" }),
    codeLength: numberRule({ yaml: "ДлинаКода", defaultValueXML: 9, implicitValueYAML: 9, xmlParents: properties }),
    descriptionLength: numberRule({
      yaml: "ДлинаНаименования",
      defaultValueXML: 25,
      implicitValueYAML: 25,
      xmlParents: properties,
    }),
    codeSeries: systemEnumerationRule({
      yaml: "СерииКодов",
      typeSE: "CharOfAccountCodeSeries",
      defaultValueXML: "WholeChartOfAccounts",
      implicitValueYAML: "WholeChartOfAccounts",
      xmlParents: properties,
    }),
    checkUnique: booleanRule({
      yaml: "КонтрольУникальности",
      defaultValueXML: true,
      implicitValueYAML: true,
      xmlParents: properties,
    }),
    defaultPresentation: systemEnumerationRule({
      yaml: "ОсновноеПредставление",
      typeSE: "AccountMainPresentation",
      defaultValueXML: "AsCode",
      implicitValueYAML: "AsCode",
      xmlParents: properties,
    }),
    standardAttributes: {
      yaml: "СтандартныеРеквизиты",
      type: "StandardAttributeDescriptions",
      standartAttributeNames: MetadataChartOfAccountsStandardAttributeNames,
      xmlParents: properties,
    },
    characteristics: {
      yaml: "Характеристики",
      type: "CharacteristicsDescriptions",
      xmlParents: properties,
      defaultValueXMLRaw: {},
    },
    standardTabularSections: {
      type: "StandardTabularSectionDescriptions",
      xmlParents: properties,
      toYAML: false,
      fromYAML: false,
    },
    predefinedDataUpdate: systemEnumerationRule({
      yaml: "ОбновлениеПредопределенныхДанных",
      typeSE: "PredefinedDataUpdate",
      defaultValueXML: "Auto",
      implicitValueYAML: "Auto",
      xmlParents: properties,
    }),
    editType: systemEnumerationRule({
      yaml: "СпособРедактирования",
      typeSE: "EditType",
      defaultValueXML: "InDialog",
      implicitValueYAML: "InDialog",
      xmlParents: properties,
    }),
    quickChoice: booleanRule({
      yaml: "БыстрыйВыбор",
      defaultValueXML: false,
      implicitValueYAML: false,
      xmlParents: properties,
    }),
    choiceMode: systemEnumerationRule({
      yaml: "РежимВыбора",
      typeSE: "ChoiceMode",
      defaultValueXML: "BothWays",
      implicitValueYAML: "BothWays",
      xmlParents: properties,
    }),
    inputByString: { yaml: "ВводПоСтроке", type: "MetadataFields", xmlParents: properties, defaultValueXMLRaw: {} },
    searchStringModeOnInputByString: systemEnumerationRule({
      yaml: "РежимСтрокиПоискаПриВводеПоСтроке",
      typeSE: "SearchStringModeOnInputByString",
      defaultValueXML: "Begin",
      implicitValueYAML: "Begin",
      xmlParents: properties,
    }),
    fullTextSearchOnInputByString: systemEnumerationRule({
      yaml: "ПолнотекстовыйПоискПриВводеПоСтроке",
      typeSE: "FullTextSearchOnInputByString",
      defaultValueXML: "DontUse",
      implicitValueYAML: "DontUse",
      xmlParents: properties,
    }),
    choiceDataGetModeOnInputByString: systemEnumerationRule({
      yaml: "РежимПолученияДанныхВыбораПриВводеПоСтроке",
      typeSE: "ChoiceDataGetModeOnInputByString",
      defaultValueXML: "Directly",
      implicitValueYAML: "Directly",
      xmlParents: properties,
    }),
    createOnInput: systemEnumerationRule({
      yaml: "СозданиеПриВводе",
      typeSE: "CreateOnInput",
      defaultValueXML: "DontUse",
      implicitValueYAML: "DontUse",
      xmlParents: properties,
    }),
    choiceHistoryOnInput: systemEnumerationRule({
      yaml: "ИсторияВыбораПриВводе",
      typeSE: "ChoiceHistoryOnInput",
      defaultValueXML: "Auto",
      implicitValueYAML: "Auto",
      xmlParents: properties,
    }),
    defaultObjectForm: stringRule({
      yaml: "ОсновнаяФормаОбъекта",
      xmlParents: properties,
      metadataTarget: { kind: "member", owner: "this", memberKinds: ["Form"], objectRoots: ["CommonForm"] },
      defaultValueXMLRaw: "",
    }),
    defaultListForm: stringRule({
      yaml: "ОсновнаяФормаСписка",
      xmlParents: properties,
      metadataTarget: { kind: "member", owner: "this", memberKinds: ["Form"], objectRoots: ["CommonForm"] },
      defaultValueXMLRaw: "",
    }),
    defaultChoiceForm: stringRule({
      yaml: "ОсновнаяФормаВыбора",
      xmlParents: properties,
      metadataTarget: { kind: "member", owner: "this", memberKinds: ["Form"], objectRoots: ["CommonForm"] },
      defaultValueXMLRaw: "",
    }),
    auxiliaryObjectForm: stringRule({
      yaml: "ДополнительнаяФормаОбъекта",
      xmlParents: properties,
      metadataTarget: { kind: "member", owner: "this", memberKinds: ["Form"], objectRoots: ["CommonForm"] },
      defaultValueXMLRaw: "",
    }),
    auxiliaryListForm: stringRule({
      yaml: "ДополнительнаяФормаСписка",
      xmlParents: properties,
      metadataTarget: { kind: "member", owner: "this", memberKinds: ["Form"], objectRoots: ["CommonForm"] },
      defaultValueXMLRaw: "",
    }),
    auxiliaryChoiceForm: stringRule({
      yaml: "ДополнительнаяФормаВыбора",
      xmlParents: properties,
      metadataTarget: { kind: "member", owner: "this", memberKinds: ["Form"], objectRoots: ["CommonForm"] },
      defaultValueXMLRaw: "",
    }),
    autoOrderByCode: booleanRule({
      yaml: "АвтоПорядокПоКоду",
      defaultValueXML: false,
      implicitValueYAML: false,
      xmlParents: properties,
    }),
    orderLength: numberRule({ yaml: "ДлинаПорядка", defaultValueXML: 0, implicitValueYAML: 0, xmlParents: properties }),
    dataLockFields: {
      yaml: "ПоляБлокировкиДанных",
      type: "MetadataFields",
      xmlParents: properties,
      defaultValueXMLRaw: {},
    },
    dataLockControlMode: systemEnumerationRule({
      yaml: "РежимУправленияБлокировкойДанных",
      typeSE: "DefaultDataLockControlMode",
      defaultValueXML: "Managed",
      implicitValueYAML: "Managed",
      xmlParents: properties,
    }),
    fullTextSearch: systemEnumerationRule({
      yaml: "ПолнотекстовыйПоиск",
      typeSE: "UseFullTextSearch",
      defaultValueXML: "Use",
      implicitValueYAML: "Use",
      xmlParents: properties,
    }),
    dataHistory: systemEnumerationRule({
      yaml: "ИсторияДанных",
      typeSE: "DataHistoryUse",
      defaultValueXML: "DontUse",
      implicitValueYAML: "DontUse",
      xmlParents: properties,
    }),
    objectPresentation: i8nTextRule({ yaml: "ПредставлениеОбъекта", xmlParents: properties, defaultValueXMLRaw: "" }),
    extendedObjectPresentation: i8nTextRule({
      yaml: "РасширенноеПредставлениеОбъекта",
      xmlParents: properties,
      defaultValueXMLRaw: "",
    }),
    listPresentation: i8nTextRule({ yaml: "ПредставлениеСписка", xmlParents: properties, defaultValueXMLRaw: "" }),
    extendedListPresentation: i8nTextRule({
      yaml: "РасширенноеПредставлениеСписка",
      xmlParents: properties,
      defaultValueXMLRaw: "",
    }),
    explanation: i8nTextRule({ yaml: "Пояснение", xmlParents: properties, defaultValueXMLRaw: "" }),
    updateDataHistoryImmediatelyAfterWrite: booleanRule({
      yaml: "ОбновлятьИсториюДанныхСразуПослеЗаписи",
      defaultValueXML: false,
      implicitValueYAML: false,
      xmlParents: properties,
    }),
    executeAfterWriteDataHistoryVersionProcessing: booleanRule({
      yaml: "ВыполнятьОбработкуПослеЗаписиВерсииИсторииДанных",
      defaultValueXML: false,
      implicitValueYAML: false,
      xmlParents: properties,
    }),
    objectBelonging: systemEnumerationRule({
      yaml: "ПринадлежностьОбъекта",
      typeSE: "ObjectBelonging",
      xmlParents: properties,
      toYAML: false,
      fromYAML: false,
      implicitValueYAML: "Native",
    }),
    extendedConfigurationObject: stringRule({ runtimeOnly: true }),
    attributes: { yaml: "Реквизиты", xml: "Attribute", type: "MetadataAttributes", xmlParents: childObjects },
    tabularSections: {
      yaml: "ТабличныеЧасти",
      xml: "TabularSection",
      type: "MetadataChartOfAccountsTabularSections",
      xmlParents: childObjects,
    },
    accountingFlags: {
      yaml: "ПризнакиУчета",
      xml: "AccountingFlag",
      type: "AccountingFlags",
      xmlParents: childObjects,
    },
    extDimensionAccountingFlags: {
      yaml: "ПризнакиУчетаСубконто",
      xml: "ExtDimensionAccountingFlag",
      type: "ExtDimensionAccountingFlags",
      xmlParents: childObjects,
    },
    forms: {
      yaml: "Формы",
      xml: "Form",
      type: "ChildFormNames",
      xmlParents: childObjects,
      folderName: "Формы",
      forReferenceOnly: true,
      toYAML: false,
      fromYAML: false,
    },
    templates: {
      yaml: "Макеты",
      xml: "Template",
      type: "ChildTemplateNames",
      xmlParents: childObjects,
      folderName: "Макеты",
      forReferenceOnly: true,
      toYAML: false,
      fromYAML: false,
    },
    commands: { yaml: "Команды", xml: "Command", type: "MetadataCommands", xmlParents: childObjects },
    objectModule: moduleRule({
      externalMetadata: { segment: "ObjectModule", placement: "derivedEntry" },
      nkdkPath: "МодульОбъекта.bsl",
      xmlPath: "Ext/ObjectModule.bsl",
      toXML: false,
      fromXML: false,
    }),
    managerModule: moduleRule({
      externalMetadata: { segment: "ManagerModule", placement: "derivedEntry" },
      nkdkPath: "МодульМенеджера.bsl",
      xmlPath: "Ext/ManagerModule.bsl",
      toXML: false,
      fromXML: false,
    }),
    predefined: { yaml: "Предопределенные", type: "Predefined", filePath: "Ext/Predefined.xml" },
    additionalIndexes: {
      yaml: "ДополнительныеИндексы",
      type: "AdditionalIndex",
      filePath: "Ext/AdditionalIndexes.xml",
    },
    help: {
      type: "Help",
      externalMetadata: { segment: "Help", placement: "derivedEntry" },
      filePath: "Ext/Help.xml",
      xmlPath: "Ext/Help.xml",
      nkdkDir: "Справка",
      toXML: false,
      fromXML: false,
    },
  },
  childCollections: [{ propertyKey: "commands", itemRule: MetadataChartOfAccountsCommandRules }],
} as const satisfies MetadataItemRule
