import { commonRegisterFieldProperties } from "../metadataRegisterField/rules"
import type { MetadataItemRule } from "../../ruleRuntime/property/types"
import {
  metadataRegisterDimensionRuleBase,
  registerDimensionRoleFragment,
  registerDimensionTotalsFragment,
} from "./fragments"

export const MetadataRegisterDimensionRules = {
  ...metadataRegisterDimensionRuleBase,
  xmlOrder: [
    "objectBelonging",
    "name",
    "synonym",
    "comment",
    "type",
    "passwordMode",
    "format",
    "editFormat",
    "toolTip",
    "markNegatives",
    "mask",
    "multiLine",
    "extendedEdit",
    "minValue",
    "maxValue",
    "fillFromFillingValue",
    "fillValue",
    "fillChecking",
    "choiceFoldersAndItems",
    "choiceParameterLinks",
    "choiceParameters",
    "quickChoice",
    "createOnInput",
    "choiceForm",
    "linkByType",
    "choiceHistoryOnInput",
    "master",
    "mainFilter",
    "balance",
    "accountingFlag",
    "denyIncompleteValues",
    "baseDimension",
    "scheduleLink",
    "indexing",
    "fullTextSearch",
    "dataHistory",
    "useInTotals",
    "typeReductionMode",
    "uuid",
  ],
  properties: {
    ...commonRegisterFieldProperties,
    ...registerDimensionRoleFragment.properties,
    ...registerDimensionTotalsFragment.properties,
  },
} as const satisfies MetadataItemRule
