import "./allowedIncomingShareRequestTypes"
import "./mobileApplicationURLs"
import "./usedMobileApplicationFunctionalities"
import "~/metadata/commonObjects/clientApplicationInterface/register"
import "~/metadata/commonObjects/homePageWorkArea/register"
import "~/metadata/commonObjects/rootCommandInterface/register"
import { V8_MDCLASSES_ROOT } from "~/metadata/orchestration/appliedObject/presets"
import type { MetadataItemRule } from "~/metadata/orchestration/property/types"

const configurationProperties = ["Properties"]

export const MetadataConfigurationRules = {
  itemType: "MetadataConfiguration",
  properties: {
    xmlRoot: {
      type: "XMLRoot",
      container: "Configuration",
      rootAttributes: V8_MDCLASSES_ROOT,
      forReferenceOnly: true,
      toYAML: false,
      fromYAML: false,
    },
    uuid: {
      type: "uuid",
      xml: "_uuid",
      forReferenceOnly: true,
      xmlParents: [],
    },
    name: {
      yaml: "Имя",
      type: "string",
      xmlParents: configurationProperties,
      required: true,
    },
    synonym: {
      yaml: "Синоним",
      type: "I8nText",
      xmlParents: configurationProperties,
      defaultValueXML: "",
      defaultValueXMLRaw: "",
    },
    comment: {
      yaml: "Комментарий",
      type: "string",
      xmlParents: configurationProperties,
      defaultValueXML: "",
      defaultValueXMLRaw: "",
    },
    namePrefix: {
      yaml: "ПрефиксИмен",
      type: "string",
      xmlParents: configurationProperties,
      defaultValueXML: "",
      defaultValueXMLRaw: "",
    },
    configurationExtensionCompatibilityMode: {
      yaml: "РежимСовместимостиРасширенияКонфигурации",
      type: "SystemEnumeration",
      typeSE: "CompatibilityMode",
      required: true,
      defaultValueXML: "Version8_3_27",
      preserveExplicitDefaultXML: true,
      implicitValueYAML: undefined,
      xmlParents: configurationProperties,
    },
    defaultRunMode: {
      yaml: "ОсновнойРежимЗапуска",
      type: "SystemEnumeration",
      typeSE: "ClientRunMode",
      defaultValueXML: "ManagedApplication",
      xmlParents: configurationProperties,
    },
    usePurposes: {
      yaml: "НазначенияИспользования",
      xml: "UsePurposes",
      type: "UsePurposes",
      xmlParents: configurationProperties,
    },
    scriptVariant: {
      yaml: "ВариантВстроенногоЯзыка",
      type: "SystemEnumeration",
      typeSE: "ScriptVariant",
      defaultValueXML: "Russian",
      xmlParents: configurationProperties,
    },
    defaultRoles: {
      yaml: "ОсновныеРоли",
      type: "MetadataItemLinks",
      xmlParents: configurationProperties,
      defaultValueXML: "",
      defaultValueXMLRaw: "",
    },
    vendor: {
      yaml: "Поставщик",
      type: "string",
      xmlParents: configurationProperties,
      defaultValueXML: "",
      defaultValueXMLRaw: "",
    },
    version: {
      yaml: "Версия",
      type: "string",
      xmlParents: configurationProperties,
      defaultValueXML: "",
      defaultValueXMLRaw: "",
    },
    updateCatalogAddress: {
      yaml: "АдресКаталогаОбновлений",
      type: "string",
      xmlParents: configurationProperties,
      defaultValueXML: "",
      defaultValueXMLRaw: "",
    },
    includeHelpInContents: {
      yaml: "ВключатьСправкуВСодержание",
      type: "boolean",
      defaultValueXML: false,
      xmlParents: configurationProperties,
    },
    useManagedFormInOrdinaryApplication: {
      yaml: "ИспользоватьУправляемыеФормыВОбычномПриложении",
      type: "boolean",
      defaultValueXML: false,
      xmlParents: configurationProperties,
    },
    useOrdinaryFormInManagedApplication: {
      yaml: "ИспользоватьОбычныеФормыВУправляемомПриложении",
      type: "boolean",
      defaultValueXML: false,
      xmlParents: configurationProperties,
    },
    additionalFullTextSearchDictionaries: {
      yaml: "ДополнительныеСловариПолнотекстовогоПоиска",
      type: "MetadataItemLinks",
      xmlParents: configurationProperties,
      defaultValueXML: "",
      defaultValueXMLRaw: "",
    },
    commonSettingsStorage: {
      yaml: "ХранилищеОбщихНастроек",
      type: "MetadataItemLink",
      xmlParents: configurationProperties,
      defaultValueXML: "",
      defaultValueXMLRaw: "",
    },
    reportsUserSettingsStorage: {
      yaml: "ХранилищеПользовательскихНастроекОтчетов",
      type: "MetadataItemLink",
      xmlParents: configurationProperties,
      defaultValueXML: "",
      defaultValueXMLRaw: "",
    },
    reportsVariantsStorage: {
      yaml: "ХранилищеВариантовОтчетов",
      type: "MetadataItemLink",
      xmlParents: configurationProperties,
      defaultValueXML: "",
      defaultValueXMLRaw: "",
    },
    formDataSettingsStorage: {
      yaml: "ХранилищеНастроекДанныхФорм",
      type: "MetadataItemLink",
      xmlParents: configurationProperties,
      defaultValueXML: "",
      defaultValueXMLRaw: "",
    },
    dynamicListsUserSettingsStorage: {
      yaml: "ХранилищеПользовательскихНастроекДинамическихСписков",
      type: "MetadataItemLink",
      xmlParents: configurationProperties,
      defaultValueXML: "",
      defaultValueXMLRaw: "",
    },
    urlExternalDataStorage: {
      yaml: "ХранилищеВнешнихДанныхНавигационныхСсылок",
      xml: "URLExternalDataStorage",
      type: "MetadataItemLink",
      xmlParents: configurationProperties,
      defaultValueXML: "",
      defaultValueXMLRaw: "",
    },
    content: {
      xml: "Content",
      type: "string",
      defaultValueXML: "",
      defaultValueXMLRaw: "",
      toYAML: false,
      fromYAML: false,
      xmlParents: configurationProperties,
    },
    defaultReportForm: {
      yaml: "ОсновнаяФормаОтчета",
      type: "MetadataItemLink",
      xmlParents: configurationProperties,
      defaultValueXML: "",
      defaultValueXMLRaw: "",
    },
    defaultReportVariantForm: {
      yaml: "ОсновнаяФормаВариантаОтчета",
      type: "MetadataItemLink",
      xmlParents: configurationProperties,
      defaultValueXML: "",
      defaultValueXMLRaw: "",
    },
    defaultReportSettingsForm: {
      yaml: "ОсновнаяФормаНастроекОтчета",
      type: "MetadataItemLink",
      xmlParents: configurationProperties,
      defaultValueXML: "",
      defaultValueXMLRaw: "",
    },
    defaultReportAppearanceTemplate: {
      yaml: "ОсновнойМакетОформленияОтчета",
      type: "string",
      xmlParents: configurationProperties,
      defaultValueXML: "",
      defaultValueXMLRaw: "",
    },
    defaultDynamicListSettingsForm: {
      yaml: "ОсновнаяФормаНастроекДинамическогоСписка",
      type: "MetadataItemLink",
      xmlParents: configurationProperties,
      defaultValueXML: "",
      defaultValueXMLRaw: "",
    },
    defaultSearchForm: {
      yaml: "ОсновнаяФормаПоиска",
      type: "string",
      xmlParents: configurationProperties,
      defaultValueXML: "",
      defaultValueXMLRaw: "",
    },
    defaultDataHistoryChangeHistoryForm: {
      yaml: "ОсновнаяФормаИсторииИзмененийИсторииДанных",
      type: "MetadataItemLink",
      xmlParents: configurationProperties,
      defaultValueXML: "",
      defaultValueXMLRaw: "",
    },
    defaultDataHistoryVersionDataForm: {
      yaml: "ОсновнаяФормаДанныхВерсииИсторииДанных",
      type: "MetadataItemLink",
      xmlParents: configurationProperties,
      defaultValueXML: "",
      defaultValueXMLRaw: "",
    },
    defaultDataHistoryVersionDifferencesForm: {
      yaml: "ОсновнаяФормаРазличийВерсийИсторииДанных",
      type: "MetadataItemLink",
      xmlParents: configurationProperties,
      defaultValueXML: "",
      defaultValueXMLRaw: "",
    },
    defaultCollaborationSystemUsersChoiceForm: {
      yaml: "ОсновнаяФормаВыбораПользователейСистемыВзаимодействия",
      type: "MetadataItemLink",
      xmlParents: configurationProperties,
      defaultValueXML: "",
      defaultValueXMLRaw: "",
    },
    requiredMobileApplicationPermissions: {
      xml: "RequiredMobileApplicationPermissions",
      type: "string",
      defaultValueXML: "",
      defaultValueXMLRaw: "",
      toYAML: false,
      fromYAML: false,
      xmlParents: configurationProperties,
    },
    usedMobileApplicationFunctionalities: {
      yaml: "ИспользуемаяФункциональностьМобильногоПриложения",
      type: "UsedMobileApplicationFunctionalities",
      xmlParents: configurationProperties,
    },
    standaloneConfigurationRestrictionRoles: {
      yaml: "РолиОграниченияАвтономнойКонфигурации",
      type: "MetadataItemLinks",
      xmlParents: configurationProperties,
      defaultValueXML: "",
      defaultValueXMLRaw: "",
    },
    mobileApplicationURLs: {
      yaml: "НавигационныеСсылкиМобильногоПриложения",
      xml: "MobileApplicationURLs",
      type: "MobileApplicationURLs",
      defaultValueXML: "",
      defaultValueXMLRaw: "",
      xmlParents: configurationProperties,
    },
    allowedIncomingShareRequestTypes: {
      yaml: "ДопустимыеТипыВходящихЗапросовПоделиться",
      xml: "AllowedIncomingShareRequestTypes",
      type: "AllowedIncomingShareRequestTypes",
      defaultValueXML: "",
      defaultValueXMLRaw: "",
      xmlParents: configurationProperties,
    },
    mainClientApplicationWindowMode: {
      yaml: "РежимОсновногоОкнаКлиентскогоПриложения",
      type: "SystemEnumeration",
      typeSE: "MainClientApplicationWindowMode",
      defaultValueXML: "Normal",
      xmlParents: configurationProperties,
    },
    defaultInterface: {
      yaml: "ОсновнойИнтерфейс",
      type: "string",
      xmlParents: configurationProperties,
      defaultValueXML: "",
      defaultValueXMLRaw: "",
    },
    defaultStyle: {
      yaml: "ОсновнойСтиль",
      type: "MetadataItemLink",
      xmlParents: configurationProperties,
      defaultValueXML: "",
      defaultValueXMLRaw: "",
    },
    defaultLanguage: {
      yaml: "ОсновнойЯзык",
      type: "MetadataItemLink",
      required: true,
      defaultValueXML: "Language.Русский",
      preserveExplicitDefaultXML: true,
      xmlParents: configurationProperties,
    },
    briefInformation: {
      yaml: "КраткаяИнформация",
      type: "I8nText",
      xmlParents: configurationProperties,
      defaultValueXML: "",
      defaultValueXMLRaw: "",
    },
    detailedInformation: {
      yaml: "ПодробнаяИнформация",
      type: "I8nText",
      xmlParents: configurationProperties,
      defaultValueXML: "",
      defaultValueXMLRaw: "",
    },
    copyright: {
      yaml: "АвторскиеПрава",
      type: "I8nText",
      xmlParents: configurationProperties,
      defaultValueXML: "",
      defaultValueXMLRaw: "",
    },
    vendorInformationAddress: {
      yaml: "АдресИнформацииОПоставщике",
      type: "I8nText",
      xmlParents: configurationProperties,
      defaultValueXML: "",
      defaultValueXMLRaw: "",
    },
    configurationInformationAddress: {
      yaml: "АдресИнформацииОКонфигурации",
      type: "I8nText",
      xmlParents: configurationProperties,
      defaultValueXML: "",
      defaultValueXMLRaw: "",
    },
    dataLockControlMode: {
      yaml: "РежимУправленияБлокировкойДанных",
      type: "SystemEnumeration",
      typeSE: "DataLockControlMode",
      defaultValueXML: "Managed",
      xmlParents: configurationProperties,
    },
    objectAutonumerationMode: {
      yaml: "РежимАвтонумерацииОбъектов",
      type: "SystemEnumeration",
      typeSE: "ObjectAutonumerationMode",
      defaultValueXML: "NotAutoFree",
      xmlParents: configurationProperties,
    },
    modalityUseMode: {
      yaml: "РежимИспользованияМодальности",
      type: "SystemEnumeration",
      typeSE: "ModalityUseMode",
      defaultValueXML: "DontUse",
      xmlParents: configurationProperties,
    },
    synchronousPlatformExtensionAndAddInCallUseMode: {
      yaml: "РежимИспользованияСинхронныхВызововРасширенийПлатформыИВнешнихКомпонент",
      type: "SystemEnumeration",
      typeSE: "SynchronousExtensionAndAddInCallUseMode",
      defaultValueXML: "DontUse",
      xmlParents: configurationProperties,
    },
    interfaceCompatibilityMode: {
      yaml: "РежимСовместимостиИнтерфейса",
      type: "SystemEnumeration",
      typeSE: "InterfaceCompatibilityMode",
      defaultValueXML: "Taxi",
      xmlParents: configurationProperties,
    },
    databaseTablespacesUseMode: {
      yaml: "РежимИспользованияТабличныхПространствБазыДанных",
      type: "SystemEnumeration",
      typeSE: "DatabaseTablespacesUseMode",
      defaultValueXML: "DontUse",
      xmlParents: configurationProperties,
    },
    compatibilityMode: {
      yaml: "РежимСовместимости",
      type: "SystemEnumeration",
      typeSE: "CompatibilityMode",
      required: true,
      defaultValueXML: "Version8_3_27",
      preserveExplicitDefaultXML: true,
      implicitValueYAML: undefined,
      xmlParents: configurationProperties,
    },
    defaultConstantsForm: {
      yaml: "ОсновнаяФормаКонстант",
      type: "string",
      xmlParents: configurationProperties,
      defaultValueXML: "",
      defaultValueXMLRaw: "",
    },
    managedApplicationModule: {
      type: "Module",
      nkdkPath: "МодульПриложения.bsl",
      xmlPath: "Ext/ManagedApplicationModule.bsl",
      syncExternalOnly: true,
    },
    sessionModule: {
      type: "Module",
      nkdkPath: "МодульСеанса.bsl",
      xmlPath: "Ext/SessionModule.bsl",
      syncExternalOnly: true,
    },
    externalConnectionModule: {
      type: "Module",
      nkdkPath: "МодульВнешнегоСоединения.bsl",
      xmlPath: "Ext/ExternalConnectionModule.bsl",
      syncExternalOnly: true,
    },
    ordinaryApplicationModule: {
      type: "Module",
      nkdkPath: "МодульОбычногоПриложения.bsl",
      xmlPath: "Ext/OrdinaryApplicationModule.bsl",
      syncExternalOnly: true,
    },
    commandInterface: {
      yaml: "КомандныйИнтерфейс",
      type: "RootCommandInterface",
      filePath: "Ext/CommandInterface.xml",
    },
    mainSectionCommandInterface: {
      yaml: "КомандныйИнтерфейсОсновногоРаздела",
      type: "RootCommandInterface",
      filePath: "Ext/MainSectionCommandInterface.xml",
    },
    clientApplicationInterface: {
      yaml: "ИнтерфейсКлиентскогоПриложения",
      type: "ClientApplicationInterface",
      filePath: "Ext/ClientApplicationInterface.xml",
    },
    homePageWorkArea: {
      yaml: "РабочаяОбластьНачальнойСтраницы",
      type: "HomePageWorkArea",
      filePath: "Ext/HomePageWorkArea.xml",
    },
    help: {
      type: "Help",
      filePath: "Ext/Help.xml",
      nkdkDir: "Справка",
    },
    mobileClientSignature: {
      type: "ExternalFile",
      nkdkPath: "ПодписьМобильногоКлиента.bin",
      xmlPath: "Ext/MobileClientSignature.bin",
      syncExternalOnly: true,
    },
    mainSectionPicture: {
      type: "ExternalPicture",
      nkdkDir: "КартинкаОсновногоРаздела",
      xmlPath: "Ext/MainSectionPicture.xml",
      payloadXmlDir: "Ext/MainSectionPicture",
      syncExternalOnly: true,
    },
    logo: {
      type: "ExternalPicture",
      nkdkDir: "Логотип",
      xmlPath: "Ext/Logo.xml",
      payloadXmlDir: "Ext/Logo",
      syncExternalOnly: true,
    },
    splash: {
      type: "ExternalPicture",
      nkdkDir: "Заставка",
      xmlPath: "Ext/Splash.xml",
      payloadXmlDir: "Ext/Splash",
      syncExternalOnly: true,
    },
    standaloneConfigurationContent: {
      type: "ExternalFile",
      nkdkPath: "СодержимоеАвтономнойКонфигурации.bin",
      xmlPath: "Ext/StandaloneConfigurationContent.bin",
      syncExternalOnly: true,
    },
  },
} satisfies MetadataItemRule
