import {
  InputField,
  InputFieldEnterprise,
  InputFieldPartialYAML,
  TableInputField,
  TableInputFieldEnterprise,
  TableInputFieldPartialYAML,
  TableInputFieldTypedYAML,
} from "../types"
import { StructureResult } from "../../../../../tests/types"
import { explicitYAMLString } from "../../../../../yaml/explicitString"
import {
  fullFormFieldCommonFixture,
  fullFormFieldEnterpriseCommonFixture,
  fullFormFieldEnterpriseTableRelatedFixture,
  fullFormFieldPartialYAMLCommonFixture,
  fullFormFieldTableRelatedPartialYAMLCommonFixture,
} from "../../__fixtures__/formField/rules"
import { RequiredFieldsElement } from "../../../../../tests/types"

export const fullInputField: RequiredFieldsElement<InputField> = {
  itemType: "InputField",
  name: "ПолеВвода",
  title: {
    items: { ru: "Поле ввода" },
  },
  allowInputEmptyMultipleValues: true,
  allowMultipleValuesDuplicates: true,
  autoCapitalizationOnTextInput: "AllCharacters",
  autoChoiceIncomplete: true,
  autoCorrectionOnTextInput: "Use",
  autoFillHint: "FullName",
  autoMarkIncomplete: true,
  autoMaxHeight: false,
  autoMaxWidth: false,
  autoShowClearButton: "Always",
  autoShowOpenButton: "FilledOnly",
  availableTypes: { type: ["string"] },
  backColor: { type: "WebColor", value: "Blue" },
  borderColor: { type: "WebColor", value: "Green" },
  choiceButton: true,
  choiceButtonPicture: {
    type: "StandardPicture",
    ref: "Print",
    loadTransparent: true,
  },
  choiceButtonRepresentation: "ShowInInputField",
  choiceFoldersAndItems: "FoldersAndItems",
  choiceForm: "Catalog.Справочник.Form.ФормаВыбора",
  choiceHistoryOnInput: "DontUse",
  choiceList: [
    {
      type: "formChoiceListDesTimeValue",
      presentation: { items: { ru: "Значение 1" } },
      value: {
        type: "string",
        value: "Значение1",
      },
    },
  ],
  choiceListButton: true,
  choiceListHeight: 200,
  choiceParameterLinks: [
    {
      name: "РеквизитПодвала",
      dataPath: "РеквизитПодвала",
      valueChange: "Clear",
    },
  ],
  choiceParameters: [
    {
      name: "Отбор.Параметр",
      value: {
        type: "string",
        value: "Значение",
      },
    },
  ],
  chooseType: false,
  clearButton: true,
  createButton: true,
  dropListButton: true,
  dropListWidth: 300,
  editFormat: { items: { ru: "Формат редактирования" } },
  editTextUpdate: "OnValueChange",
  extendedEdit: true,
  font: { kind: "StyleItem", ref: "NormalTextFont" },
  format: { items: { ru: "Формат отображения" } },
  height: 100,
  heightControlVariant: "UseContentHeight",
  horizontalStretch: true,
  incompleteChoiceMode: "OnActivate",
  inputHint: { items: { ru: "Подсказка ввода" } },
  listChoiceMode: true,
  typeDomainEnabled: false,
  markNegatives: true,
  mask: "999",
  maxHeight: 500,
  maxValue: 99,
  maxWidth: 400,
  minValue: 1,
  multiLine: true,
  multipleValuePictureDataPath: "Реквизит.РеквизитТаблицы",
  multipleValuePictureShape: "Circle",
  multipleValuePictureSize: "Large",
  multipleValuePresentationDataPath: "Реквизит.РеквизитТаблицы",
  multipleValuesBackColor: { type: "WebColor", value: "Magenta" },
  multipleValuesExtendedEdit: true,
  multipleValuesFont: { kind: "StyleItem", ref: "NormalTextFont" },
  multipleValuesHyperlink: true,
  multipleValuesPicture: {
    type: "StandardPicture",
    ref: "Print",
    loadTransparent: true,
  },
  multipleValuesTextColor: { type: "WebColor", value: "Red" },
  multipleValueValueDataPath: "Реквизит.РеквизитТаблицы",
  onScreenKeyboardReturnKeyText: "Done",
  openButton: true,
  passwordMode: true,
  quickChoice: true,
  showCheckBoxesInDropListWhenInputMultipleValues: true,
  specialTextInputMode: "Email",
  spellCheckingOnTextInput: "Use",
  spinButton: true,
  textColor: { type: "WebColor", value: "Yellow" },
  textEdit: false,
  typeLink: {
    dataPath: "РеквизитПодвала",
    linkItem: 1,
  },
  verticalStretch: true,
  width: 200,
  wrap: false,
  events: {
    onChange: "ПроцедураПриИзменении",
    autoComplete: "ПроцедураАвтоПодбора",
    multipleValuesAdd: "ПроцедураДобавленияМножественныхЗначений",
    editTextChange: "ПроцедураИзмененияТекстаРедактирования",
    startChoice: "ПроцедураНачалаВыбора",
    startListChoice: "ПроцедураНачалаВыбораИзСписка",
    choiceProcessing: "ПроцедураОбработкиВыбора",
    multipleValueURLProcessing: "ПроцедураОбработкиНавигационнойСсылкиМножественногоЗначения",
    commandGenerateProcessing: "ПроцедураОбработкиФормированияКоманд",
    textEditEnd: "ПроцедураОкончанияВводаТекста",
    opening: "ПроцедураОткрытия",
    multipleValueOpening: "ПроцедураОткрытияМножественногоЗначения",
    clearing: "ПроцедураОчистки",
    tuning: "ПроцедураРегулирования",
    creating: "ПроцедураСоздания",
    multipleValuesDelete: "ПроцедураУдаленияМножественныхЗначений",
  },
  ...fullFormFieldCommonFixture,
} satisfies RequiredFieldsElement<InputField>

export const fullTableInputField: TableInputField = {
  itemType: "TableInputField",
  name: "ПолеВводаВсеСвойства",
  displayImportance: "High",
  dataPath: "Таблица.СписокЗначений",
  table: { type: "string", value: "Таблица" },
  visible: false,
  userVisible: {
    common: true,
    values: [{ name: "Role.Администратор", value: false }],
  },
  defaultItem: true,
  enabled: false,
  readOnly: true,
  skipOnInput: true,
  title: { items: { ru: "Заголовок" } },
  titleTextColor: { type: "WebColor", value: "Black" },
  titleBackColor: { type: "WebColor", value: "Blue" },
  titleFont: { kind: "StyleItem", ref: "NormalTextFont" },
  titleLocation: "Left",
  titleHeight: 20,
  toolTip: { items: { ru: "Подсказка" } },
  toolTipRepresentation: "None",
  warningOnEditRepresentation: "DontShow",
  warningOnEdit: { items: { ru: "Предупреждение" } },
  shortcut: "S",
  horizontalAlign: "Left",
  verticalAlign: "Top",
  horizontalAlignInGroup: "Left",
  verticalAlignInGroup: "Top",
  editMode: "EnterOnInput",
  cellHyperlink: true,
  showInHeader: false,
  headerHorizontalAlign: "Left",
  headerPicture: {
    type: "StandardPicture",
    ref: "Print",
    loadTransparent: true,
  },
  showInFooter: false,
  footerDataPath: "РеквизитПодвала",
  footerText: { items: { ru: "Текст подвала" } },
  footerTextColor: { type: "WebColor", value: "Black" },
  footerBackColor: { type: "WebColor", value: "White" },
  footerFont: { kind: "StyleItem", ref: "NormalTextFont" },
  footerPicture: {
    type: "StandardPicture",
    ref: "Print",
    loadTransparent: true,
  },
  footerHorizontalAlign: "Left",
  onMainServerUnavalableBehavior: "DontChangeBehavior",
  width: 200,
  autoMaxWidth: false,
  maxWidth: 400,
  height: 100,
  autoCellHeight: false,
  autoMaxHeight: false,
  maxHeight: 500,
  horizontalStretch: true,
  verticalStretch: true,
  wrap: false,
  passwordMode: true,
  multiLine: true,
  extendedEdit: true,
  markNegatives: true,
  dropListButton: true,
  choiceButton: true,
  choiceButtonRepresentation: "ShowInInputField",
  clearButton: true,
  spinButton: true,
  openButton: true,
  createButton: true,
  mask: "999",
  listChoiceMode: true,
  multipleValuesFont: { kind: "StyleItem", ref: "NormalTextFont" },
  multipleValuesTextColor: { type: "WebColor", value: "Red" },
  multipleValuesBackColor: { type: "WebColor", value: "Magenta" },
  multipleValuesExtendedEdit: true,
  multipleValuePictureSize: "Large",
  multipleValuePictureShape: "Circle",
  showCheckBoxesInDropListWhenInputMultipleValues: false,
  multipleValuesHyperlink: true,
  autoChoiceIncomplete: true,
  quickChoice: true,
  choiceFoldersAndItems: "FoldersAndItems",
  format: { items: { ru: "ЧЦ=15; ЧДЦ=2" } },
  editFormat: { items: { ru: "ЧЦ=16; ЧДЦ=3" } },
  autoMarkIncomplete: true,
  chooseType: false,
  incompleteChoiceMode: "OnActivate",
  typeDomainEnabled: false,
  textEdit: false,
  editTextUpdate: "OnValueChange",
  minValue: 10,
  maxValue: 90,
  choiceButtonPicture: {
    type: "StandardPicture",
    ref: "Print",
    loadTransparent: true,
  },
  choiceParameters: [
    {
      name: "Отбор.Параметр",
      value: {
        type: "string",
        value: "Значение",
      },
    },
  ],
  availableTypes: { type: ["string"] },
  choiceList: [
    {
      type: "formChoiceListDesTimeValue",
      presentation: { items: { ru: "Значение 1" } },
      value: {
        type: "string",
        value: "Значение1",
      },
    },
  ],
  choiceListButton: true,
  choiceListHeight: 200,
  dropListWidth: 300,
  textColor: { type: "WebColor", value: "Yellow" },
  backColor: { type: "WebColor", value: "Blue" },
  borderColor: { type: "WebColor", value: "Green" },
  font: { kind: "StyleItem", ref: "NormalTextFont" },
  typeLink: {
    dataPath: "РеквизитПодвала",
    linkItem: 1,
  },
  typeRestriction: { type: ["string"] },
  heightControlVariant: "UseContentHeight",
  autoShowClearButton: "Always",
  autoShowOpenButton: "FilledOnly",
  autoCorrectionOnTextInput: "Use",
  spellCheckingOnTextInput: "Use",
  autoCapitalizationOnTextInput: "AllCharacters",
  specialTextInputMode: "Email",
  autoFillHint: "FullName",
  onScreenKeyboardReturnKeyText: "Done",
  inputHint: { items: { ru: "Подсказка ввода" } },
  choiceHistoryOnInput: "DontUse",
  fixingInTable: "None",
  contextMenu: {
    itemType: "ContextMenu",
    autofill: false,
    childItems: [],
  },
  extendedTooltip: {
    itemType: "ExtendedTooltip",
    title: { items: { ru: "Расширенная подсказка" }, formatted: false },
  },
  events: {
    onChange: "ПроцедураПриИзменении",
    editTextChange: "ПроцедураИзмененияТекстаРедактирования",
    autoComplete: "ПроцедураАвтоПодбора",
    startChoice: "ПроцедураНачалаВыбора",
    multipleValueURLProcessing: "ПроцедураОбработкиНавигационнойСсылкиМножественногоЗначения",
    multipleValuesDelete: "ПроцедураУдаленияМножественныхЗначений",
    tuning: "ПроцедураРегулирования",
    multipleValuesAdd: "ПроцедураДобавленияМножественныхЗначений",
    opening: "ПроцедураОткрытия",
    creating: "ПроцедураСоздания",
    startListChoice: "ПроцедураНачалаВыбораИзСписка",
    clearing: "ПроцедураОчистки",
    textEditEnd: "ПроцедураОкончанияВводаТекста",
    multipleValueOpening: "ПроцедураОткрытияМножественногоЗначения",
    choiceProcessing: "ПроцедураОбработкиВыбора",
    commandGenerateProcessing: "ПроцедураОбработкиФормированияКоманд",
  },
} satisfies TableInputField

export const fullInputFieldPartialYAML: InputFieldPartialYAML = {
  АвтоВыборНезаполненного: "Истина",
  АвтоИзменениеРегистраПриВводеТекста: "ВсеСимволы",
  АвтоИсправлениеПриВводеТекста: "Использовать",
  АвтоМаксимальнаяВысота: "Ложь",
  АвтоМаксимальнаяШирина: "Ложь",
  АвтоОтметкаНезаполненного: "Истина",
  АвтоОтображениеКнопкиОткрытия: "ТолькоДляЗаполненного",
  АвтоОтображениеКнопкиОчистки: "Всегда",
  АвтоПереносСтрок: "Ложь",
  БыстрыйВыбор: "Истина",
  ВариантУправленияВысотой: "ПоСодержимому",
  ВыбиратьТип: "Ложь",
  ВыборГруппИЭлементов: "ГруппыИЭлементы",
  ВыделятьОтрицательные: "Истина",
  Высота: 100,
  ВысотаСпискаВыбора: 200,
  ГиперссылкаМножественныхЗначений: "Истина",
  ДоступныеТипы: "Строка",
  ИсторияВыбораПриВводе: "НеИспользовать",
  КартинкаКнопкиВыбора: "Печать",
  КартинкаМножественныхЗначений: "Печать",
  КнопкаВыбора: "Истина",
  КнопкаВыпадающегоСписка: "Истина",
  КнопкаОткрытия: "Истина",
  КнопкаОчистки: "Истина",
  КнопкаРегулирования: "Истина",
  КнопкаСоздания: "Истина",
  КнопкаСпискаВыбора: "Истина",
  МаксимальнаяВысота: 500,
  МаксимальнаяШирина: 400,
  МаксимальноеЗначение: 99,
  Маска: "999",
  МинимальноеЗначение: 1,
  МногострочныйРежим: "Истина",
  ОбновлениеТекстаРедактирования: "ПриИзмененииЗначения",
  ОтображатьФлажкиВВыпадающемСпискеПриВводеМножественныхЗначений: "Истина",
  ОтображениеКнопкиВыбора: "ОтображатьВПолеВвода",
  ПараметрыВыбора: {
    "Отбор.Параметр": explicitYAMLString("Значение"),
  },
  ПодсказкаАвтозаполнения: "ПолноеИмя",
  ПодсказкаВвода: "Подсказка ввода",
  ПроверкаПравописанияПриВводеТекста: "Использовать",
  ПутьКДанным: "Реквизит",
  ПутьКДаннымЗначенияМножественногоЗначения: "Реквизит.РеквизитТаблицы",
  ПутьКДаннымКартинкиМножественногоЗначения: "Реквизит.РеквизитТаблицы",
  ПутьКДаннымПредставленияМножественногоЗначения: "Реквизит.РеквизитТаблицы",
  РазмерКартинкиМножественногоЗначения: "Крупный",
  РазрешитьВводПустыхМножественныхЗначений: "Истина",
  РазрешитьДублированиеМножественныхЗначений: "Истина",
  РастягиватьПоВертикали: "Истина",
  РастягиватьПоГоризонтали: "Истина",
  РасширенноеРедактирование: "Истина",
  РасширенноеРедактированиеМножественныхЗначений: "Истина",
  РедактированиеТекста: "Ложь",
  РежимВыбораИзСписка: "Истина",
  РежимВыбораНезаполненного: "ПриАктивизации",
  РежимПароля: "Истина",
  РазрешитьСоставнойТип: "Ложь",
  СвязиПараметровВыбора: [
    {
      Имя: "РеквизитПодвала",
      ПутьКДанным: "РеквизитПодвала",
    },
  ],
  СвязьПоТипу: "РеквизитПодвала(1)",
  СпециальныйРежимВводаТекста: "Email",
  СписокВыбора: [
    {
      Представление: "Значение 1",
      Значение: explicitYAMLString("Значение1"),
    },
  ],
  ТекстКнопкиВводаЭкраннойКлавиатуры: "Готово",
  ФигураКартинкиМножественногоЗначения: "Круг",
  ФормаВыбора: "Catalog.Справочник.Form.ФормаВыбора",
  Формат: "Формат отображения",
  ФорматРедактирования: "Формат редактирования",
  Заголовок: "Поле ввода",
  ЦветРамки: "Зеленый",
  ЦветТекста: "Желтый",
  ЦветТекстаМножественныхЗначений: "Красный",
  ЦветФона: "Синий",
  ЦветФонаМножественныхЗначений: "Фуксин",
  Ширина: 200,
  ШиринаВыпадающегоСписка: 300,
  Шрифт: { Вид: "ОбычныйШрифтТекста" },
  ШрифтМножественныхЗначений: { Вид: "ОбычныйШрифтТекста" },
  События: {
    ПриИзменении: "ПроцедураПриИзменении",
    АвтоПодбор: "ПроцедураАвтоПодбора",
    ДобавлениеМножественныхЗначений: "ПроцедураДобавленияМножественныхЗначений",
    ИзменениеТекстаРедактирования: "ПроцедураИзмененияТекстаРедактирования",
    НачалоВыбора: "ПроцедураНачалаВыбора",
    НачалоВыбораИзСписка: "ПроцедураНачалаВыбораИзСписка",
    ОбработкаВыбора: "ПроцедураОбработкиВыбора",
    ОбработкаНавигационнойСсылкиМножественногоЗначения: "ПроцедураОбработкиНавигационнойСсылкиМножественногоЗначения",
    ОбработкаФормированияКоманд: "ПроцедураОбработкиФормированияКоманд",
    ОкончаниеВводаТекста: "ПроцедураОкончанияВводаТекста",
    Открытие: "ПроцедураОткрытия",
    ОткрытиеМножественногоЗначения: "ПроцедураОткрытияМножественногоЗначения",
    Очистка: "ПроцедураОчистки",
    Регулирование: "ПроцедураРегулирования",
    Создание: "ПроцедураСоздания",
    УдалениеМножественныхЗначений: "ПроцедураУдаленияМножественныхЗначений",
  },
  ...fullFormFieldPartialYAMLCommonFixture,
} satisfies Omit<Required<InputFieldPartialYAML>, "Использование">

const {
  КартинкаМножественныхЗначений: _tableInputFieldMultipleValuesPicture,
  ПутьКДаннымЗначенияМножественногоЗначения: _tableInputFieldMultipleValueValueDataPath,
  ПутьКДаннымКартинкиМножественногоЗначения: _tableInputFieldMultipleValuePictureDataPath,
  ПутьКДаннымПредставленияМножественногоЗначения: _tableInputFieldMultipleValuePresentationDataPath,
  РазрешитьВводПустыхМножественныхЗначений: _tableInputFieldAllowInputEmptyMultipleValues,
  РазрешитьДублированиеМножественныхЗначений: _tableInputFieldAllowMultipleValuesDuplicates,
  СвязиПараметровВыбора: _tableInputFieldChoiceParameterLinks,
  ФормаВыбора: _tableInputFieldChoiceForm,
  ...fullTableInputFieldPartialYAMLBase
} = fullInputFieldPartialYAML

export const fullTableInputFieldPartialYAML: TableInputFieldPartialYAML = {
  ...fullTableInputFieldPartialYAMLBase,
  Заголовок: "Заголовок",
  МаксимальноеЗначение: 90,
  МинимальноеЗначение: 10,
  ОтображатьФлажкиВВыпадающемСпискеПриВводеМножественныхЗначений: "Ложь",
  ПутьКДанным: "Таблица.СписокЗначений",
  Формат: "ЧЦ=15; ЧДЦ=2",
  ФорматРедактирования: "ЧЦ=16; ЧДЦ=3",
  ...fullFormFieldTableRelatedPartialYAMLCommonFixture,
}

export const fullTableInputFieldTypedYAML: TableInputFieldTypedYAML = {
  ...fullTableInputFieldPartialYAML,
  Тип: "ПолеВвода",
  Заголовок: "Заголовок",
  ПутьКДанным: "Таблица.СписокЗначений",
}

export const minimalInputField: InputField = {
  itemType: "InputField",
  name: "ПолеВвода",
}

export const minMaxStringTypeInputField = {
  itemType: "InputField",
  name: "ПолеВвода",
  dataPath: "Объект.Количество",
  minValue: 1,
  maxValue: 99.99,
} satisfies InputField

export const minimalInputFieldPartialYAML: InputFieldPartialYAML = {}

export const minimalTableInputField: TableInputField = {
  itemType: "TableInputField",
  name: "ПолеВвода",
}

export const minimalTableInputFieldPartialYAML: TableInputFieldPartialYAML = {}

export const minimalTableInputFieldTypedYAML: TableInputFieldTypedYAML = {
  Тип: "ПолеВвода",
}

export interface InputFieldStructureFixture {
  name: string
  element: InputField
  structured: StructureResult
}

export const inputFieldStructureFixturesTable: InputFieldStructureFixture[] = [
  {
    name: "with title",
    element: {
      name: "ИмяПоля",
      itemType: "InputField",
      title: { items: { ru: "Поле" } },
      dataPath: "ИмяПоля",
    },
    structured: {
      strings: ['"Поле": ИмяПоля'],
      toOneLineGroup: true,
    },
  },
  {
    name: "without title",
    element: {
      name: "ИмяПоля",
      itemType: "InputField",
      dataPath: "ИмяПоля",
    },
    structured: {
      strings: ["ИмяПоля: "],
      toOneLineGroup: true,
    },
  },
  {
    name: "with raw platform data path",
    element: {
      name: "ВидЗанятости",
      itemType: "InputField",
      dataPath: "1/0:a917a122-f663-4c45-8de0-fd5104007de3",
    },
    structured: {
      strings: ["ВидЗанятости(1/0:a917a122-f663-4c45-8de0-fd5104007de3): "],
      toOneLineGroup: true,
    },
  },
]

export const fullInputFieldEnterprise = {
  ElementType: "FormField",
  Name: "prefix_ПолеВвода",
  Type: { Type: "SystemEnumeration", Value: "FormFieldType.InputField" },
  Title: "Поле ввода",
  AllowInputEmptyMultipleValues: true,
  AllowMultipleValuesDuplicates: true,
  AutoCapitalizationOnTextInput: {
    Type: "SystemEnumeration",
    Value: "AutoCapitalizationOnTextInput.AllCharacters",
  },
  AutoChoiceIncomplete: true,
  AutoCorrectionOnTextInput: {
    Type: "SystemEnumeration",
    Value: "AutoCorrectionOnTextInput.Use",
  },
  AutoFillHint: {
    Type: "SystemEnumeration",
    Value: "InputFieldAutofillHint.FullName",
  },
  AutoMarkIncomplete: true,
  AutoMaxHeight: false,
  AutoMaxWidth: false,
  AutoShowClearButton: {
    Type: "SystemEnumeration",
    Value: "AutoShowClearButtonMode.Always",
  },
  AutoShowOpenButton: {
    Type: "SystemEnumeration",
    Value: "AutoShowOpenButtonMode.FilledOnly",
  },
  BackColor: { Type: "Color", Value: "WebColors.Blue" },
  BorderColor: { Type: "Color", Value: "WebColors.Green" },
  ChoiceButton: true,
  ChoiceButtonPicture: { Type: "Picture", Value: "PictureLib.Print" },
  ChoiceButtonRepresentation: {
    Type: "SystemEnumeration",
    Value: "ChoiceButtonRepresentation.ShowInInputField",
  },
  ChoiceFoldersAndItems: {
    Type: "SystemEnumeration",
    Value: "FoldersAndItems.FoldersAndItems",
  },
  ChoiceHistoryOnInput: {
    Type: "SystemEnumeration",
    Value: "ChoiceHistoryOnInput.DontUse",
  },
  ChoiceListButton: true,
  ChoiceListHeight: 200,
  ChooseType: false,
  ClearButton: true,
  CreateButton: true,
  DropListButton: true,
  DropListWidth: 300,
  EditFormat: "Формат редактирования",
  EditTextUpdate: {
    Type: "SystemEnumeration",
    Value: "EditTextUpdate.OnValueChange",
  },
  ExtendedEdit: true,
  Font: { Type: "Font", Value: "StyleFonts.NormalTextFont" },
  Format: "Формат отображения",
  Height: 100,
  HeightControlVariant: {
    Type: "SystemEnumeration",
    Value: "ItemHeightControlVariant.UseContentHeight",
  },
  HorizontalStretch: true,
  IncompleteChoiceMode: {
    Type: "SystemEnumeration",
    Value: "IncompleteChoiceMode.OnActivate",
  },
  InputHint: "Подсказка ввода",
  ListChoiceMode: true,
  TypeDomainEnabled: false,
  MarkNegatives: true,
  Mask: "999",
  MaxHeight: 500,
  MaxValue: 99,
  MaxWidth: 400,
  MinValue: 1,
  MultiLine: true,
  MultipleValuePictureDataPath: "prefix_РеквизитРеквизитТаблицы",
  MultipleValuePictureShape: {
    Type: "SystemEnumeration",
    Value: "InputFieldMultipleValuePictureShape.Circle",
  },
  MultipleValuePictureSize: {
    Type: "SystemEnumeration",
    Value: "InputFieldMultipleValuePictureSize.Large",
  },
  MultipleValuePresentationDataPath: "prefix_РеквизитРеквизитТаблицы1",
  MultipleValueValueDataPath: "prefix_РеквизитРеквизитТаблицы",
  MultipleValuesBackColor: { Type: "Color", Value: "WebColors.Magenta" },
  MultipleValuesExtendedEdit: true,
  MultipleValuesFont: { Type: "Font", Value: "StyleFonts.NormalTextFont" },
  MultipleValuesHyperlink: true,
  MultipleValuesPicture: {
    Type: "Picture",
    Value: "PictureLib.Print",
  },
  MultipleValuesTextColor: { Type: "Color", Value: "WebColors.Red" },
  OnScreenKeyboardReturnKeyText: {
    Type: "SystemEnumeration",
    Value: "OnScreenKeyboardReturnKeyText.Done",
  },
  OpenButton: true,
  PasswordMode: true,
  QuickChoice: true,
  ShowCheckBoxesInDropListWhenInputMultipleValues: true,
  SpecialTextInputMode: {
    Type: "SystemEnumeration",
    Value: "SpecialTextInputMode.Email",
  },
  SpellCheckingOnTextInput: {
    Type: "SystemEnumeration",
    Value: "SpellCheckingOnTextInput.Use",
  },
  SpinButton: true,
  TextColor: { Type: "Color", Value: "WebColors.Yellow" },
  TextEdit: false,
  VerticalStretch: true,
  Width: 200,
  Wrap: false,
  ...fullFormFieldEnterpriseCommonFixture,
} satisfies Required<InputFieldEnterprise>

const {
  AllowInputEmptyMultipleValues: _tableInputFieldEnterpriseAllowInputEmptyMultipleValues,
  AllowMultipleValuesDuplicates: _tableInputFieldEnterpriseAllowMultipleValuesDuplicates,
  MultipleValuePictureDataPath: _tableInputFieldEnterpriseMultipleValuePictureDataPath,
  MultipleValuePresentationDataPath: _tableInputFieldEnterpriseMultipleValuePresentationDataPath,
  MultipleValueValueDataPath: _tableInputFieldEnterpriseMultipleValueValueDataPath,
  MultipleValuesPicture: _tableInputFieldEnterpriseMultipleValuesPicture,
  ...fullTableInputFieldEnterpriseBase
} = fullInputFieldEnterprise

export const fullTableInputFieldEnterprise = {
  ...fullTableInputFieldEnterpriseBase,
  Name: "prefix_ПолеВводаВсеСвойства",
  Title: "Заголовок",
  DataPath: "prefix_ТаблицаСписокЗначений",
  EditFormat: "ЧЦ=16; ЧДЦ=3",
  Format: "ЧЦ=15; ЧДЦ=2",
  MaxValue: 90,
  MinValue: 10,
  ShowCheckBoxesInDropListWhenInputMultipleValues: false,
  ...fullFormFieldEnterpriseTableRelatedFixture,
} satisfies TableInputFieldEnterprise

export const minimalInputFieldEnterprise = {
  ElementType: "FormField",
  Name: "prefix_ПолеВвода",
  Type: { Type: "SystemEnumeration", Value: "FormFieldType.InputField" },
} satisfies InputFieldEnterprise
