import { cypherPredicate } from "~/metadata/orchestration/property/cypherPredicate"
import { registerElementRule } from "~/metadata/orchestration/formElement/ruleFactory"
import { PropertyRule } from "~/metadata/orchestration/property/types"
import { ElementRule } from "../../../orchestration/formElement/types"
export type { ElementRule, PropertyRule }

export const dynamicListFormAttributeQuery =
  'MATCH (s {id: $scope})-[:FORM_ATTRIBUTE]->(a:FormAttribute) WHERE "DynamicList" IN a.p_type_type RETURN a.name AS name'

export const TableRules = {
  itemType: "Table",
  enterpriseField: "FormTable",
  enterpriseFieldType: "None",
  properties: {
    name: {
      type: "string",
      xml: "_name",
      required: true,
    },
    autoAddIncomplete: { yaml: "АвтоВводНезаполненного", type: "boolean" },
    autoCommandBar: { yaml: "КоманднаяПанель", type: "TableAutoCommandBar", toEnterprise: false },
    autofill: { yaml: "АвтозаполнениеКолонок", type: "boolean" },
    viewMode: {
      yaml: "РежимОтображения",
      type: "SystemEnumeration",
      typeSE: "DataCompositionSettingsViewMode",
    },
    settingsNamedItemDetailedRepresentation: {
      yaml: "ПодробноеОтображениеИменованныхЭлементовНастройки",
      xml: "SettingsNamedItemDetailedRepresentation",
      type: "boolean",
    },
    autoInsertNewRow: { yaml: "АвтоВводНовойСтроки", type: "boolean" },
    autoMarkIncomplete: { yaml: "АвтоОтметкаНезаполненного", type: "boolean" },
    autoMaxHeight: { yaml: "АвтоМаксимальнаяВысота", type: "boolean" },
    autoMaxHeightInTableRows: {
      yaml: "АвтоМаксимальнаяВысотаВСтрокахТаблицы",
      xml: "AutoMaxRowsCount",
      type: "boolean",
    },
    autoMaxWidth: { yaml: "АвтоМаксимальнаяШирина", type: "boolean" },
    backColor: { yaml: "ЦветФона", type: "Color" },
    behaviorOnHorizontalCompression: {
      yaml: "ПоведениеПриСжатииПоГоризонтали",
      type: "SystemEnumeration",
      typeSE: "TableBehaviorOnHorizontalCompression",
    },
    borderColor: { yaml: "ЦветРамки", type: "Color" },
    changeRowOrder: { yaml: "ИзменятьПорядокСтрок", type: "boolean" },
    changeRowSet: { yaml: "ИзменятьСоставСтрок", type: "boolean" },
    childItems: { type: "TableChildItems", defaultValue: [], fromPartialYAML: true },
    choiceMode: { yaml: "РежимВыбора", type: "boolean" },
    commandBarLocation: {
      yaml: "ПоложениеКоманднойПанели",
      type: "SystemEnumeration",
      typeSE: "FormItemCommandBarLabelLocation",
    },
    commandSet: { yaml: "Команда", type: "CommandSet", toEnterprise: false },
    contextMenu: { yaml: "КонтекстноеМеню", type: "ContextMenu", toEnterprise: false },
    currentRowUse: {
      yaml: "ИспользованиеТекущейСтроки",
      type: "SystemEnumeration",
      typeSE: "TableCurrentRowUse",
    },
    dataPath: { yaml: "ПутьКДанным", type: "DataPath", toYAML: false, fromYAML: false, defaultType: "ValueTable" },
    defaultItem: { yaml: "АктивизироватьПоУмолчанию", type: "boolean" },
    displayImportance: {
      yaml: "ВажностьПриОтображении",
      xml: "_DisplayImportance",
      type: "SystemEnumeration",
      typeSE: "DisplayImportance",
    },
    enabled: { yaml: "Доступность", type: "boolean" },
    enableDrag: { yaml: "РазрешитьПеретаскивание", type: "boolean" },
    enableStartDrag: { yaml: "РазрешитьНачалоПеретаскивания", type: "boolean" },
    extendedTooltip: { yaml: "РасширеннаяПодсказка", type: "ExtendedTooltip", toEnterprise: false },
    fileDragMode: {
      yaml: "СпособПеретаскиванияФайлов",
      type: "SystemEnumeration",
      typeSE: "FileDragMode",
    },
    font: { yaml: "Шрифт", type: "Font" },
    footer: { yaml: "Подвал", type: "boolean" },
    footerHeight: { yaml: "ВысотаПодвала", type: "number" },
    header: { yaml: "Шапка", type: "boolean" },
    headerHeight: { yaml: "ВысотаШапки", type: "number" },
    height: { yaml: "Высота", type: "number" },
    heightControlVariant: {
      yaml: "ВариантУправленияВысотой",
      type: "SystemEnumeration",
      typeSE: "TableHeightControlVariant",
    },
    heightInTableRows: { yaml: "ВысотаВСтрокахТаблицы", type: "number" },
    horizontalAlignInGroup: {
      yaml: "ГоризонтальноеПоложениеВГруппе",
      xml: "GroupHorizontalAlign",
      type: "SystemEnumeration",
      typeSE: "ItemHorizontalLocation",
    },
    horizontalLines: { yaml: "ГоризонтальныеЛинии", type: "boolean" },
    horizontalScrollBar: {
      yaml: "ГоризонтальнаяПолосаПрокрутки",
      type: "SystemEnumeration",
      typeSE: "ScrollBarUse",
      defaultValueYAML: "AutoUse",
    },
    horizontalStretch: { yaml: "РастягиватьПоГоризонтали", type: "boolean" },
    initialListView: {
      yaml: "НачальноеОтображениеСписка",
      type: "SystemEnumeration",
      typeSE: "InitialListView",
    },
    initialTreeView: {
      yaml: "НачальноеОтображениеДерева",
      type: "SystemEnumeration",
      typeSE: "InitialTreeView",
    },
    // markIncomplete: { yaml: "ОтметкаНезаполненного", type: "boolean" },
    maxHeight: { yaml: "МаксимальнаяВысота", type: "number" },
    maxHeightInTableRows: {
      yaml: "МаксимальнаяВысотаВСтрокахТаблицы",
      type: "number",
      xml: "MaxRowsCount",
    },
    maxWidth: { yaml: "МаксимальнаяШирина", type: "number" },
    multipleChoice: { yaml: "МножественныйВыбор", type: "boolean" },
    onMainServerUnavalableBehavior: {
      yaml: "ПоведениеПриНедоступностиОсновногоСервера",
      type: "SystemEnumeration",
      typeSE: "OnMainServerUnavalableBehavior",
    },
    output: {
      yaml: "Вывод",
      type: "SystemEnumeration",
      typeSE: "UseOutput",
    },
    readOnly: { yaml: "ТолькоПросмотр", type: "boolean" },
    refreshRequest: {
      yaml: "ЗапросОбновления",
      type: "SystemEnumeration",
      typeSE: "RefreshRequestMethod",
    },
    representation: {
      yaml: "Отображение",
      type: "SystemEnumeration",
      typeSE: "TableRepresentation",
    },
    rowInputMode: {
      yaml: "РежимВводаСтрок",
      type: "SystemEnumeration",
      typeSE: "TableRowInputMode",
    },
    rowPictureDataPath: { yaml: "ПутьКДаннымКартинкиСтроки", type: "DataPath", defaultType: "Picture" },
    rowSelectionMode: {
      yaml: "РежимВыделенияСтроки",
      type: "SystemEnumeration",
      typeSE: "TableRowSelectionMode",
    },
    rowsPicture: { yaml: "КартинкаСтрок", type: "Picture" },
    searchControl: {
      yaml: "УправлениеПоиском",
      type: "SingleSearchControlAddition",
      xml: "SearchControlAddition",
      toEnterprise: false,
    },
    searchControlLocation: {
      yaml: "ПоложениеУправленияПоиском",
      type: "SystemEnumeration",
      typeSE: "SearchControlLocation",
    },
    searchOnInput: {
      yaml: "ПоискПриВводе",
      type: "SystemEnumeration",
      typeSE: "SearchInTableOnInput",
    },
    searchStringLocation: {
      yaml: "ПоложениеСтрокиПоиска",
      type: "SystemEnumeration",
      typeSE: "SearchStringLocation",
    },
    searchStringRepresentation: {
      yaml: "ОтображениеСтрокиПоиска",
      type: "SingleSearchStringAddition",
      toEnterprise: false,
      xml: "SearchStringAddition",
    },
    selectionMode: {
      yaml: "РежимВыделения",
      type: "SystemEnumeration",
      typeSE: "TableSelectionMode",
    },
    shortcut: { yaml: "СочетаниеКлавиш", type: "string", toEnterprise: false },
    skipOnInput: { yaml: "ПропускатьПриВводе", type: "boolean" },
    textColor: { yaml: "ЦветТекста", type: "Color" },
    title: {
      yaml: "Заголовок",
      type: "I8nText",
      yamlPartialOthers: true,
    },
    titleFont: { yaml: "ШрифтЗаголовка", type: "Font" },
    titleHeight: { yaml: "ВысотаЗаголовка", type: "number" },
    titleLocation: {
      yaml: "ПоложениеЗаголовка",
      type: "SystemEnumeration",
      typeSE: "FormItemTitleLocation",
    },
    titleTextColor: { yaml: "ЦветТекстаЗаголовка", type: "Color" },
    toolTip: { yaml: "Подсказка", type: "I8nText" },
    toolTipRepresentation: {
      yaml: "ОтображениеПодсказки",
      type: "SystemEnumeration",
      typeSE: "ToolTipRepresentation",
    },
    useAlternationRowColor: { yaml: "ЧередованиеЦветовСтрок", type: "boolean" },
    userVisible: {
      yaml: "РазрешитьИспользование",
      yamlDeny: "ЗапретитьИспользование",
      type: "UserVisible",
      toEnterprise: false,
    },
    verticalAlignInGroup: {
      yaml: "ВертикальноеПоложениеВГруппе",
      xml: "GroupVerticalAlign",
      type: "SystemEnumeration",
      typeSE: "ItemVerticalAlign",
      defaultValueYAML: "Auto",
    },
    verticalLines: { yaml: "ВертикальныеЛинии", type: "boolean" },
    verticalScrollBar: {
      yaml: "ВертикальнаяПолосаПрокрутки",
      type: "SystemEnumeration",
      typeSE: "ScrollBarUse",
      defaultValueYAML: "AutoUse",
    },
    verticalStretch: { yaml: "РастягиватьПоВертикали", type: "boolean" },
    viewStatusLocation: {
      yaml: "ПоложениеСостоянияПросмотра",
      type: "SystemEnumeration",
      typeSE: "ViewStatusLocation",
    },
    viewStatusRepresentation: {
      yaml: "ОтображениеСостоянияПросмотра",
      type: "ViewStatusAddition",
      xml: "ViewStatusAddition",
      toEnterprise: false,
    },
    visible: { yaml: "Видимость", type: "boolean" },
    width: { yaml: "Ширина", type: "number" },
    autoRefresh: { yaml: "АвтоОбновление", type: "boolean", defaultValueYAML: false },
    restoreCurrentRow: { yaml: "ВосстанавливатьТекущуюСтроку", type: "boolean" },
    choiceFoldersAndItems: {
      yaml: "ВыборГруппИЭлементов",
      type: "SystemEnumeration",
      typeSE: "FoldersAndItemsUse",
    },
    // additionalCreateParameters: { yaml: "ДополнительныеПараметрыСоздания", type: "boolean" },
    updateOnDataChange: {
      yaml: "ОбновлениеПриИзмененииДанных",
      type: "SystemEnumeration",
      typeSE: "UpdateOnDataChange",
    },
    showRoot: { yaml: "ОтображатьКорень", type: "boolean" },
    autoRefreshPeriod: { yaml: "ПериодАвтоОбновления", type: "number" },
    allowRootChoice: { yaml: "РазрешитьВыборКорня", type: "boolean" },
    allowGettingCurrentRowURL: { yaml: "РазрешитьПолучатьНавигационнуюСсылкуТекущейСтроки", type: "boolean" },
    userSettingsGroup: { yaml: "ГруппаПользовательскихНастроек", type: "string" },
    // Тип boolean: в XML значения всегда фиксированные (1С-дефолты); структуру в модели хранить не нужно.
    // Эмитируются только когда DataPath указывает на FormAttribute с единственным типом "DynamicList".
    period: {
      yaml: "Период",
      type: "boolean",
      fromXML: false,
      toYAML: false,
      fromYAML: false,
      defaultValueXMLRaw: {
        "v8:variant": { "#text": "Custom", "_xsi:type": "v8:StandardPeriodVariant" },
        "v8:startDate": "0001-01-01T00:00:00",
        "v8:endDate": "0001-01-01T00:00:00",
      },
      toXML: cypherPredicate({
        query: dynamicListFormAttributeQuery,
        test: (el: any, rows: Record<string, unknown>[]) =>
          rows.some((r) => r.name === el?.dataPath?.split(".")[0]),
      }),
    },
    topLevelParent: {
      yaml: "РодительВерхнегоУровня",
      type: "boolean",
      fromXML: false,
      toYAML: false,
      fromYAML: false,
      defaultValueXMLRaw: { "_xsi:nil": "true" },
      toXML: cypherPredicate({
        query: dynamicListFormAttributeQuery,
        test: (el: any, rows: Record<string, unknown>[]) =>
          rows.some((r) => r.name === el?.dataPath?.split(".")[0]),
      }),
    },
    events: {
      type: "Events",
      yaml: "События",
      toEnterprise: false,
      items: {
        selection: "Выбор",
        valueChoice: "ВыборЗначения",
        dragStart: "НачалоПеретаскивания",
        choiceProcessing: "ОбработкаВыбора",
        newWriteProcessing: "ОбработкаЗаписиНового",
        refreshRequestProcessing: "ОбработкаЗапросаОбновления",
        dragEnd: "ОкончаниеПеретаскивания",
        beforeLoadUserSettingsAtServer: "ПередЗагрузкойПользовательскихНастроекНаСервере",
        beforeAddRow: "ПередНачаломДобавления",
        beforeRowChange: "ПередНачаломИзменения",
        beforeEditEnd: "ПередОкончаниемРедактирования",
        beforeExpand: "ПередРазворачиванием",
        beforeCollapse: "ПередСворачиванием",
        beforeDeleteRow: "ПередУдалением",
        drag: "Перетаскивание",
        afterDeleteRow: "ПослеУдаления",
        onActivateField: "ПриАктивизацииПоля",
        onActivateRow: "ПриАктивизацииСтроки",
        onActivateCell: "ПриАктивизацииЯчейки",
        onChange: "ПриИзменении",
        onStartEdit: "ПриНачалеРедактирования",
        onEditEnd: "ПриОкончанииРедактирования",
        onCurrentParentChange: "ПриСменеТекущегоРодителя",
        dragCheck: "ПроверкаПеретаскивания",
      },
    },
  } as const,
} as const satisfies ElementRule

registerElementRule("Table", TableRules)
