import { ElementRule, PropertyRule, registerElementRule } from "../../../metadataFactory/elementRulesFactory"
import { Table } from "./types"
export type { ElementRule, PropertyRule }

export const TableRules: ElementRule<Table> = {
  enterpriseField: "FormTable",
  properties: {
    autoAddIncomplete: { yaml: "АвтоВводНезаполненного", type: "boolean" },
    autoCommandBar: { yaml: "КоманднаяПанель", type: "string" },
    autoInsertNewRow: { yaml: "АвтоВводНовойСтроки", type: "boolean" },
    autoMarkIncomplete: { yaml: "АвтоОтметкаНезаполненного", type: "boolean" },
    autoMaxHeight: { yaml: "АвтоМаксимальнаяВысота", type: "boolean" },
    autoMaxHeightInTableRows: {
      yaml: "АвтоМаксимальнаяВысотаВСтрокахТаблицы",
      xml: "AutoMaxRowsCount",
      type: "boolean",
    },
    autoMaxWidth: { yaml: "АвтоМаксимальнаяШирина", type: "boolean" },
    backColor: { yaml: "ЦветФона", type: "Color" },
    behaviorOnHorizontalCompression: {
      yaml: "ПоведениеПриСжатииПоГоризонтали",
      type: "SystemEnumeration",
      typeSE: "TableBehaviorOnHorizontalCompression",
    },
    borderColor: { yaml: "ЦветРамки", type: "Color" },
    changeRowOrder: { yaml: "ИзменятьПорядокСтрок", type: "boolean" },
    changeRowSet: { yaml: "ИзменятьСоставСтрок", type: "boolean" },
    childItems: { yaml: "ПодчиненныеЭлементы", type: "string" },
    choiceMode: { yaml: "РежимВыбора", type: "boolean" },
    commandBarLocation: {
      yaml: "ПоложениеКоманднойПанели",
      type: "SystemEnumeration",
      typeSE: "FormItemCommandBarLabelLocation",
    },
    commandSet: { yaml: "Команда", type: "string" },
    contextMenu: { yaml: "КонтекстноеМеню", type: "ContextMenu" },
    currentRowUse: {
      yaml: "ИспользованиеТекущейСтроки",
      type: "SystemEnumeration",
      typeSE: "TableCurrentRowUse",
    },
    dataPath: { yaml: "ПутьКДанным", type: "string" },
    defaultItem: { yaml: "АктивизироватьПоУмолчанию", type: "boolean" },
    displayImportance: {
      yaml: "ВажностьПриОтображении",
      xml: "_DisplayImportance",
      type: "SystemEnumeration",
      typeSE: "DisplayImportance",
    },
    enabled: { yaml: "Доступность", type: "boolean" },
    enableDrag: { yaml: "РазрешитьПеретаскивание", type: "boolean" },
    enableStartDrag: { yaml: "РазрешитьНачалоПеретаскивания", type: "boolean" },
    extendedTooltip: { yaml: "РасширеннаяПодсказка", type: "ExtendedTooltip" },
    fileDragMode: {
      yaml: "СпособПеретаскиванияФайлов",
      type: "SystemEnumeration",
      typeSE: "FileDragMode",
    },
    font: { yaml: "Шрифт", type: "Font" },
    footer: { yaml: "Подвал", type: "boolean" },
    footerHeight: { yaml: "ВысотаПодвала", type: "number" },
    header: { yaml: "Шапка", type: "boolean" },
    headerHeight: { yaml: "ВысотаШапки", type: "number" },
    height: { yaml: "Высота", type: "number" },
    heightControlVariant: {
      yaml: "ВариантУправленияВысотой",
      type: "SystemEnumeration",
      typeSE: "TableHeightControlVariant",
    },
    heightInTableRows: { yaml: "ВысотаВСтрокахТаблицы", type: "number" },
    horizontalAlignInGroup: {
      yaml: "ГоризонтальноеПоложениеВГруппе",
      xml: "GroupHorizontalAlign",
      type: "SystemEnumeration",
      typeSE: "ItemHorizontalLocation",
    },
    horizontalLines: { yaml: "ГоризонтальныеЛинии", type: "boolean" },
    horizontalScrollBar: {
      yaml: "ГоризонтальнаяПолосаПрокрутки",
      type: "SystemEnumeration",
      typeSE: "ScrollBarUse",
    },
    horizontalStretch: { yaml: "РастягиватьПоГоризонтали", type: "boolean" },
    initialListView: {
      yaml: "НачальноеОтображениеСписка",
      type: "SystemEnumeration",
      typeSE: "InitialListView",
    },
    initialTreeView: {
      yaml: "НачальноеОтображениеДерева",
      type: "SystemEnumeration",
      typeSE: "InitialTreeView",
    },
    // markIncomplete: { yaml: "ОтметкаНезаполненного", type: "boolean" },
    maxHeight: { yaml: "МаксимальнаяВысота", type: "number" },
    maxHeightInTableRows: {
      yaml: "МаксимальнаяВысотаВСтрокахТаблицы",
      type: "number",
      xml: "MaxRowsCount",
    },
    maxWidth: { yaml: "МаксимальнаяШирина", type: "number" },
    multipleChoice: { yaml: "МножественныйВыбор", type: "boolean" },
    onMainServerUnavalableBehavior: {
      yaml: "ПоведениеПриНедоступностиОсновногоСервера",
      type: "SystemEnumeration",
      typeSE: "OnMainServerUnavalableBehavior",
    },
    output: {
      yaml: "Вывод",
      type: "SystemEnumeration",
      typeSE: "UseOutput",
    },
    readOnly: { yaml: "ТолькоПросмотр", type: "boolean" },
    refreshRequest: {
      yaml: "ЗапросОбновления",
      type: "SystemEnumeration",
      typeSE: "RefreshRequestMethod",
    },
    representation: {
      yaml: "Отображение",
      type: "SystemEnumeration",
      typeSE: "TableRepresentation",
    },
    rowInputMode: {
      yaml: "РежимВводаСтрок",
      type: "SystemEnumeration",
      typeSE: "TableRowInputMode",
    },
    rowPictureDataPath: { yaml: "ПутьКДаннымКартинкиСтроки", type: "string" },
    rowSelectionMode: {
      yaml: "РежимВыделенияСтроки",
      type: "SystemEnumeration",
      typeSE: "TableRowSelectionMode",
    },
    rowsPicture: { yaml: "КартинкаСтрок", type: "Picture" },
    searchControl: { yaml: "УправлениеПоиском", type: "string" },
    searchControlLocation: {
      yaml: "ПоложениеУправленияПоиском",
      type: "SystemEnumeration",
      typeSE: "SearchControlLocation",
    },
    searchOnInput: {
      yaml: "ПоискПриВводе",
      type: "SystemEnumeration",
      typeSE: "SearchInTableOnInput",
    },
    searchStringLocation: {
      yaml: "ПоложениеСтрокиПоиска",
      type: "SystemEnumeration",
      typeSE: "SearchStringLocation",
    },
    searchStringAddition: { yaml: "ОтображениеСтрокиПоиска", type: "string" },
    selectionMode: {
      yaml: "РежимВыделения",
      type: "SystemEnumeration",
      typeSE: "TableSelectionMode",
    },
    shortcut: { yaml: "СочетаниеКлавиш", type: "string" },
    skipOnInput: { yaml: "ПропускатьПриВводе", type: "boolean" },
    textColor: { yaml: "ЦветТекста", type: "Color" },
    title: {
      yaml: "Заголовок",
      type: "I8nText",
      yamlPartialOthers: true,
    },
    titleFont: { yaml: "ШрифтЗаголовка", type: "Font" },
    titleHeight: { yaml: "ВысотаЗаголовка", type: "number" },
    titleLocation: {
      yaml: "ПоложениеЗаголовка",
      type: "SystemEnumeration",
      typeSE: "FormItemTitleLocation",
    },
    titleTextColor: { yaml: "ЦветТекстаЗаголовка", type: "Color" },
    toolTip: { yaml: "Подсказка", type: "I8nText" },
    toolTipRepresentation: {
      yaml: "ОтображениеПодсказки",
      type: "SystemEnumeration",
      typeSE: "ToolTipRepresentation",
    },
    useAlternationRowColor: { yaml: "ЧередованиеЦветовСтрок", type: "boolean" },
    userVisible: {
      yaml: "РазрешитьИспользование",
      yamlDeny: "ЗапретитьИспользование",
      type: "UserVisible",
    },
    verticalAlignInGroup: {
      yaml: "ВертикальноеПоложениеВГруппе",
      xml: "GroupVerticalAlign",
      type: "SystemEnumeration",
      typeSE: "ItemVerticalAlign",
    },
    verticalLines: { yaml: "ВертикальныеЛинии", type: "boolean" },
    verticalScrollBar: {
      yaml: "ВертикальнаяПолосаПрокрутки",
      type: "SystemEnumeration",
      typeSE: "ScrollBarUse",
    },
    verticalStretch: { yaml: "РастягиватьПоВертикали", type: "boolean" },
    viewStatusLocation: {
      yaml: "ПоложениеСостоянияПросмотра",
      type: "SystemEnumeration",
      typeSE: "ViewStatusLocation",
    },
    viewStatusAddition: { yaml: "ОтображениеСостоянияПросмотра", type: "string" },
    visible: { yaml: "Видимость", type: "boolean" },
    width: { yaml: "Ширина", type: "number" },
    autoRefresh: { yaml: "АвтоОбновление", type: "boolean" },
    restoreCurrentRow: { yaml: "ВосстанавливатьТекущуюСтроку", type: "boolean" },
    choiceFoldersAndItems: {
      yaml: "ВыборГруппИЭлементов",
      type: "SystemEnumeration",
      typeSE: "FoldersAndItemsUse",
    },
    // additionalCreateParameters: { yaml: "ДополнительныеПараметрыСоздания", type: "boolean" },
    updateOnDataChange: {
      yaml: "ОбновлениеПриИзмененииДанных",
      type: "SystemEnumeration",
      typeSE: "UpdateOnDataChange",
    },
    showRoot: { yaml: "ОтображатьКорень", type: "boolean" },
    autoRefreshPeriod: { yaml: "ПериодАвтоОбновления", type: "number" },
    allowRootChoice: { yaml: "РазрешитьВыборКорня", type: "boolean" },
    allowGettingCurrentRowURL: { yaml: "РазрешитьПолучатьНавигационнуюСсылкуТекущейСтроки", type: "boolean" },
    userSettingsGroup: { yaml: "ГруппаПользовательскихНастроек", type: "string" },
  },
  events: {
    selection: "Выбор",
    valueChoice: "ВыборЗначения",
    dragStart: "НачалоПеретаскивания",
    choiceProcessing: "ОбработкаВыбора",
    newWriteProcessing: "ОбработкаЗаписиНового",
    refreshRequestProcessing: "ОбработкаЗапросаОбновления",
    dragEnd: "ОкончаниеПеретаскивания",
    beforeAddRow: "ПередНачаломДобавления",
    beforeRowChange: "ПередНачаломИзменения",
    beforeEditEnd: "ПередОкончаниемРедактирования",
    beforeExpand: "ПередРазворачиванием",
    beforeCollapse: "ПередСворачиванием",
    beforeDeleteRow: "ПередУдалением",
    drag: "Перетаскивание",
    afterDeleteRow: "ПослеУдаления",
    onActivateField: "ПриАктивизацииПоля",
    onActivateRow: "ПриАктивизацииСтроки",
    onActivateCell: "ПриАктивизацииЯчейки",
    onChange: "ПриИзменении",
    onStartEdit: "ПриНачалеРедактирования",
    onEditEnd: "ПриОкончанииРедактирования",
    onCurrentParentChange: "ПриСменеТекущегоРодителя",
    dragCheck: "ПроверкаПеретаскивания",
  },
}

registerElementRule("Table", TableRules)
