import {
  PlannerField,
  PlannerFieldEnterprise,
  PlannerFieldPartialYAML,
} from "~/metadata/forms/elements/plannerField/types"

import {
  fullFormFieldCommonFixture,
  fullFormFieldEnterpriseCommonFixture,
  fullFormFieldPartialYAMLCommonFixture,
} from "~/tests/fixtures/forms/base/formField/rules"
import { RequiredFieldsElement } from "~/tests/types"

export const fullPlannerField: RequiredFieldsElement<PlannerField> = {
  itemType: "PlannerField",
  name: "ПолеПланировщика",
  title: {
    items: { ru: "Поле планировщика" },
  },
  autoMaxHeight: false,
  autoMaxWidth: false,
  commandSet: ["Begin"],
  dimensionItemHyperlink: true,
  // enableDrag: undefined as never,
  // enableStartDrag: undefined as never,
  height: 200,
  horizontalStretch: false,
  maxHeight: 10,
  maxWidth: 5,
  timeScaleItemHyperlink: true,
  verticalStretch: false,
  width: 300,
  wrappedTimeScaleHeaderHyperlink: true,
  events: {
    onChange: "ПроцедураПриИзменении",
    selection: "ПроцедураВыбора",
    plannerActionClick: "ПроцедураНажатияНаПланировщике",
    uRLClick: "ПроцедураНажатияНаСсылке",
    wrappedTimeScaleHeaderClick: "ПроцедураНажатияНаЗаголовке",
    dimensionItemClick: "ПроцедураНажатияНаЭлементе",
    timeScaleItemClick: "ПроцедураНажатияНаЭлементе",
    dragStart: "ПроцедураНачалаПеретаскивания",
    commandGenerateProcessing: "ПроцедураГенерацииКоманды",
    dragEnd: "ПроцедураЗавершенияПеретаскивания",
    beforeStartQuickEdit: "ПроцедураНачалаБыстрогоРедактирования",
    beforeStartEdit: "ПроцедураНачалаРедактирования",
    beforePrint: "ПроцедураПередПечатью",
    beforeExpandDimensionItem: "ПроцедураРазворачиванияЭлемента",
    beforeCollapseDimensionItem: "ПроцедураСворачиванияЭлемента",
    beforeCreate: "ПроцедураСозданияЭлемента",
    beforeDelete: "ПроцедураУдаленияЭлемента",
    drag: "ПроцедураПеретаскивания",
    onActivate: "ПроцедураАктивации",
    onEditEnd: "ПроцедураЗавершенияРедактирования",
    onCurrentRepresentationPeriodChange: "ПроцедураИзмененияПериода",
    dragCheck: "ПроцедураПроверкиПеретаскивания",
    insideDragCheck: "ПроцедураПроверкиПеретаскиванияВнутри",
  },
  ...fullFormFieldCommonFixture,
}

export const fullPlannerFieldEnterprise = {
  ElementType: "FormField",
  Name: "prefix_ПолеПланировщика",
  Type: {
    Type: "SystemEnumeration",
    Value: "FormFieldType.PlannerField",
  },
  Title: "Поле планировщика",
  AutoMaxHeight: false,
  AutoMaxWidth: false,
  DimensionItemHyperlink: true,
  // EnableDrag: undefined as never,
  // EnableStartDrag: undefined as never,
  Height: 200,
  HorizontalStretch: false,
  MaxHeight: 10,
  MaxWidth: 5,
  TimeScaleItemHyperlink: true,
  VerticalStretch: false,
  Width: 300,
  WrappedTimeScaleHeaderHyperlink: true,
  ...fullFormFieldEnterpriseCommonFixture,
} satisfies Required<PlannerFieldEnterprise>

export const fullPlannerFieldPartialYAML: PlannerFieldPartialYAML = {
  АвтоМаксимальнаяВысота: "Ложь",
  АвтоМаксимальнаяШирина: "Ложь",
  Команда: ["Begin"],
  ГиперссылкаЭлементаИзмерения: "Истина",
  // РазрешитьПеретаскивание: undefined as never,
  // РазрешитьНачалоПеретаскивания: undefined as never,
  Высота: 200,
  МаксимальнаяВысота: 10,
  МаксимальнаяШирина: 5,
  ГиперссылкаЭлементаШкалыВремени: "Истина",
  РастягиватьПоВертикали: "Ложь",
  РастягиватьПоГоризонтали: "Ложь",
  Ширина: 300,
  ГиперссылкаПеренесенногоЗаголовкаШкалыВремени: "Истина",
  События: {
    ПриИзменении: "ПроцедураПриИзменении",
    Выбор: "ПроцедураВыбора",
    НажатиеНаДействиеПланировщика: "ПроцедураНажатияНаПланировщике",
    НажатиеНаНавигационнойСсылке: "ПроцедураНажатияНаСсылке",
    НажатиеНаПеренесенномЗаголовкеШкалыВремени: "ПроцедураНажатияНаЗаголовке",
    НажатиеНаЭлементеИзмерения: "ПроцедураНажатияНаЭлементе",
    НажатиеНаЭлементеШкалыВремени: "ПроцедураНажатияНаЭлементе",
    НачалоПеретаскивания: "ПроцедураНачалаПеретаскивания",
    ОбработкаФормированияКоманд: "ПроцедураГенерацииКоманды",
    ОкончаниеПеретаскивания: "ПроцедураЗавершенияПеретаскивания",
    ПередНачаломБыстрогоРедактирования: "ПроцедураНачалаБыстрогоРедактирования",
    ПередНачаломРедактирования: "ПроцедураНачалаРедактирования",
    ПередПечатью: "ПроцедураПередПечатью",
    ПередРазворачиваниемЭлементаИзмерения: "ПроцедураРазворачиванияЭлемента",
    ПередСворачиваниемЭлементаИзмерения: "ПроцедураСворачиванияЭлемента",
    ПередСозданием: "ПроцедураСозданияЭлемента",
    ПередУдалением: "ПроцедураУдаленияЭлемента",
    Перетаскивание: "ПроцедураПеретаскивания",
    ПриАктивизации: "ПроцедураАктивации",
    ПриОкончанииРедактирования: "ПроцедураЗавершенияРедактирования",
    ПриСменеТекущегоПериодаОтображения: "ПроцедураИзмененияПериода",
    ПроверкаПеретаскивания: "ПроцедураПроверкиПеретаскивания",
    ПроверкаПеретаскиванияВнутри: "ПроцедураПроверкиПеретаскиванияВнутри",
  },
  ...fullFormFieldPartialYAMLCommonFixture,
} satisfies Omit<Required<PlannerFieldPartialYAML>, "ЗапретитьИспользование" | "Заголовок" | "РазрешитьИспользование">

export const minimalPlannerField: PlannerField = {
  itemType: "PlannerField",
  name: "ПолеПланировщика",
}

export const minimalPlannerFieldPartialYAML: PlannerFieldPartialYAML = {}
