import { registerExport } from "~/lib/xml/export/exporterFactory"
import { FormElementType } from "../types"

export const exportMetadataCatalogToXML = (data: MetadataCatalog | undefined): MetadataCatalogXML | undefined => {
  if (!data) return undefined

  return {
    AdditionalIndexes: data.additionalIndexes,
    Attributes: data.attributes,
    Autonumbering: data.autonumbering,
    AuxiliaryChoiceForm: data.auxiliaryChoiceForm,
    AuxiliaryFolderChoiceForm: data.auxiliaryFolderChoiceForm,
    AuxiliaryFolderForm: data.auxiliaryFolderForm,
    AuxiliaryListForm: data.auxiliaryListForm,
    AuxiliaryObjectForm: data.auxiliaryObjectForm,
    BasedOn: data.basedOn,
    Characteristics: data.characteristics,
    CheckUnique: data.checkUnique,
    ChoiceDataGetModeOnInputByString: data.choiceDataGetModeOnInputByString,
    ChoiceHistoryOnInput: data.choiceHistoryOnInput,
    ChoiceMode: data.choiceMode,
    CodeAllowedLength: data.codeAllowedLength,
    CodeLength: data.codeLength,
    CodeSeries: data.codeSeries,
    CodeType: data.codeType,
    Commands: data.commands,
    Comment: data.comment,
    CreateOnInput: data.createOnInput,
    DataHistory: data.dataHistory,
    DataLockControlMode: data.dataLockControlMode,
    DataLockFields: data.dataLockFields,
    DefaultChoiceForm: data.defaultChoiceForm,
    DefaultFolderChoiceForm: data.defaultFolderChoiceForm,
    DefaultFolderForm: data.defaultFolderForm,
    DefaultListForm: data.defaultListForm,
    DefaultObjectForm: data.defaultObjectForm,
    DefaultPresentation: data.defaultPresentation,
    DescriptionLength: data.descriptionLength,
    EditType: data.editType,
    ExecuteAfterWriteDataHistoryVersionProcessing: data.executeAfterWriteDataHistoryVersionProcessing,
    Explanation: data.explanation,
    ExtendedConfigurationObject: data.extendedConfigurationObject,
    ExtendedListPresentation: data.extendedListPresentation,
    ExtendedObjectPresentation: data.extendedObjectPresentation,
    FoldersOnTop: data.foldersOnTop,
    Forms: data.forms,
    FullTextSearch: data.fullTextSearch,
    FullTextSearchOnInputByString: data.fullTextSearchOnInputByString,
    Help: data.help,
    Hierarchical: data.hierarchical,
    HierarchyType: data.hierarchyType,
    IncludeHelpInContents: data.includeHelpInContents,
    InputByString: data.inputByString,
    LevelCount: data.levelCount,
    LimitLevelCount: data.limitLevelCount,
    ListPresentation: data.listPresentation,
    ManagerModule: data.managerModule,
    ObjectBelonging: data.objectBelonging,
    ObjectModule: data.objectModule,
    ObjectPresentation: data.objectPresentation,
    Owners: data.owners,
    Predefined: data.predefined,
    PredefinedDataUpdate: data.predefinedDataUpdate,
    QuickChoice: data.quickChoice,
    SearchStringModeOnInputByString: data.searchStringModeOnInputByString,
    StandardAttributes: data.standardAttributes,
    SubordinationUse: data.subordinationUse,
    Synonym: data.synonym,
    TabularSections: data.tabularSections,
    Templates: data.templates,
    UpdateDataHistoryImmediatelyAfterWrite: data.updateDataHistoryImmediatelyAfterWrite,
    UseStandardCommands: data.useStandardCommands,
  }
}

registerExport(FormElementType.MetadataCatalog, exportMetadataCatalogToXML)
