import { MetadataItemRule } from "~/metadata/orchestration/property/types"

export const formFieldCommonProperties = {
  name: {
    type: "string",
    xml: "_name",
    required: true,
  },
  autoCellHeight: {
    yaml: "АвтоВысотаЯчейки",
    type: "boolean",
    defaultValueYAML: true,
  },
  defaultItem: {
    yaml: "АктивизироватьПоУмолчанию",
    type: "boolean",
    defaultValueYAML: false,
  },
  displayImportance: {
    yaml: "ВажностьПриОтображении",
    xml: "_DisplayImportance",
    type: "SystemEnumeration",
    typeSE: "DisplayImportance",
    defaultValueYAML: "Auto",
  },
  verticalAlign: {
    yaml: "ВертикальноеПоложение",
    type: "SystemEnumeration",
    typeSE: "ItemVerticalAlign",
  },
  verticalAlignInGroup: {
    yaml: "ВертикальноеПоложениеВГруппе",
    xml: "GroupVerticalAlign",
    type: "SystemEnumeration",
    typeSE: "ItemVerticalAlign",
  },
  // type: {
  //   yaml: "Вид",
  //   type: "SystemEnumeration",
  //   typeSE: "FormFieldType",
  // },
  visible: { yaml: "Видимость", type: "boolean", defaultValueYAML: true },
  titleHeight: { yaml: "ВысотаЗаголовка", type: "number" },
  cellHyperlink: { yaml: "ГиперссылкаЯчейки", type: "boolean", defaultValueYAML: false },
  horizontalAlign: {
    yaml: "ГоризонтальноеПоложение",
    type: "SystemEnumeration",
    typeSE: "ItemHorizontalLocation",
  },
  horizontalAlignInGroup: {
    yaml: "ГоризонтальноеПоложениеВГруппе",
    xml: "GroupHorizontalAlign",
    type: "SystemEnumeration",
    typeSE: "ItemHorizontalLocation",
  },
  footerHorizontalAlign: {
    yaml: "ГоризонтальноеПоложениеВПодвале",
    type: "SystemEnumeration",
    typeSE: "ItemHorizontalLocation",
  },
  headerHorizontalAlign: {
    yaml: "ГоризонтальноеПоложениеВШапке",
    type: "SystemEnumeration",
    typeSE: "ItemHorizontalLocation",
  },
  enabled: { yaml: "Доступность", type: "boolean", defaultValueYAML: true },
  title: {
    yaml: "Заголовок",
    type: "I8nText",
    yamlPartialOthers: true,
  },
  footerPicture: { yaml: "КартинкаПодвала", type: "Picture" },
  headerPicture: { yaml: "КартинкаШапки", type: "Picture" },
  contextMenu: { yaml: "КонтекстноеМеню", type: "ContextMenu", toEnterprise: false },
  typeRestriction: { yaml: "ОграничениеТипа", type: "TypeDescription", toEnterprise: false },
  showInFooter: { yaml: "ОтображатьВПодвале", type: "boolean", defaultValueYAML: true },
  showInHeader: { yaml: "ОтображатьВШапке", type: "boolean", defaultValueYAML: true },
  toolTipRepresentation: {
    yaml: "ОтображениеПодсказки",
    type: "SystemEnumeration",
    typeSE: "ToolTipRepresentation",
  },
  warningOnEditRepresentation: {
    yaml: "ОтображениеПредупрежденияПриРедактировании",
    type: "SystemEnumeration",
    typeSE: "WarningOnEditRepresentation",
  },
  onMainServerUnavalableBehavior: {
    yaml: "ПоведениеПриНедоступностиОсновногоСервера",
    type: "SystemEnumeration",
    typeSE: "OnMainServerUnavalableBehavior",
  },
  toolTip: { yaml: "Подсказка", type: "I8nText" },
  titleLocation: {
    yaml: "ПоложениеЗаголовка",
    type: "SystemEnumeration",
    typeSE: "FormItemTitleLocation",
  },
  warningOnEdit: { yaml: "ПредупреждениеПриРедактировании", type: "I8nText" },
  skipOnInput: { yaml: "ПропускатьПриВводе", type: "boolean", defaultValueYAML: false },
  dataPath: {
    yaml: "ПутьКДанным",
    type: "DataPath",
    toYAML: false,
    fromYAML: false,
    defaultType: "dateTime",
  },
  footerDataPath: { yaml: "ПутьКДаннымПодвала", type: "DataPath", defaultType: "string" },
  extendedTooltip: { yaml: "РасширеннаяПодсказка", type: "ExtendedTooltip", toEnterprise: false },
  editMode: {
    yaml: "РежимРедактирования",
    type: "SystemEnumeration",
    typeSE: "ColumnEditMode",
  },
  parent: { yaml: "Родитель", type: "string", toEnterprise: false },
  shortcut: { yaml: "СочетаниеКлавиш", type: "string", toEnterprise: false },
  table: { yaml: "Таблица", xml: "AssociatedTableElementId", type: "AssociatedTable", toEnterprise: false },
  footerText: { yaml: "ТекстПодвала", type: "I8nText" },
  readOnly: { yaml: "ТолькоПросмотр", type: "boolean", defaultValueYAML: false },
  fixingInTable: {
    yaml: "ФиксацияВТаблице",
    type: "SystemEnumeration",
    typeSE: "FixingInTable",
  },
  titleTextColor: { yaml: "ЦветТекстаЗаголовка", type: "Color" },
  footerTextColor: { yaml: "ЦветТекстаПодвала", type: "Color" },
  titleBackColor: { yaml: "ЦветФонаЗаголовка", type: "Color" },
  footerBackColor: { yaml: "ЦветФонаПодвала", type: "Color" },
  titleFont: { yaml: "ШрифтЗаголовка", type: "Font" },
  footerFont: { yaml: "ШрифтПодвала", type: "Font" },
} as const satisfies MetadataItemRule["properties"]
