export const fullFormDecorationCommonFixture = {
  autoMaxHeight: false,
  autoMaxWidth: false,
  contextMenu: {
    itemType: "ContextMenu" as const,
    autofill: false,
    childItems: [],
  },
  displayImportance: "VeryHigh" as const,
  enabled: false,
  extendedTooltip: {
    itemType: "ExtendedTooltip" as const,
    title: { items: { ru: "РасширеннаяПодсказка" }, formatted: false },
  },
  font: { kind: "StyleItem" as const, ref: "LargeTextFont" as const },
  height: 15,
  horizontalAlignInGroup: "Left" as const,
  horizontalStretch: true,
  maxHeight: 25,
  maxWidth: 20,
  onMainServerUnavalableBehavior: "MakeDisable" as const,
  shortcut: "Cmd+S",
  skipOnInput: true,
  textColor: { type: "WebColor" as const, value: "Crimson" },
  toolTip: { items: { ru: "Подсказка" } },
  toolTipRepresentation: "Balloon" as const,
  userVisible: {
    common: true,
    values: [{ name: "Role.Администратор", value: false }],
  },
  verticalAlignInGroup: "Top" as const,
  verticalStretch: false,
  visible: false,
  width: 10,
}

export const fullFormDecorationEnterpriseCommonFixture = {
  AutoMaxHeight: false,
  AutoMaxWidth: false,
  DisplayImportance: { Type: "SystemEnumeration", Value: "DisplayImportance.VeryHigh" },
  Enabled: false,
  Font: { Type: "Font", Value: "StyleFonts.LargeTextFont" },
  Height: 15,
  HorizontalAlignInGroup: { Type: "SystemEnumeration", Value: "ItemHorizontalLocation.Left" },
  HorizontalStretch: true,
  MaxHeight: 25,
  MaxWidth: 20,
  OnMainServerUnavalableBehavior: {
    Type: "SystemEnumeration",
    Value: "OnMainServerUnavalableBehavior.MakeDisable",
  },
  SkipOnInput: true,
  TextColor: { Type: "Color", Value: "WebColors.Crimson" },
  ToolTip: "Подсказка",
  ToolTipRepresentation: { Type: "SystemEnumeration", Value: "ToolTipRepresentation.Balloon" },
  VerticalAlignInGroup: { Type: "SystemEnumeration", Value: "ItemVerticalAlign.Top" },
  VerticalStretch: false,
  Visible: false,
  Width: 10,
} as const

export const fullFormDecorationPartialYAMLCommonFixture = {
  АвтоМаксимальнаяВысота: "Ложь" as any,
  АвтоМаксимальнаяШирина: "Ложь",
  ВажностьПриОтображении: "ОченьВысокая",
  ВертикальноеПоложениеВГруппе: "Верх",
  Видимость: "Ложь",
  Высота: 15,
  ГоризонтальноеПоложениеВГруппе: "Лево",
  Доступность: "Ложь",
  МаксимальнаяВысота: 25,
  МаксимальнаяШирина: 20,
  ОтображениеПодсказки: "Всплывающая",
  Подсказка: "Подсказка",
  ПоведениеПриНедоступностиОсновногоСервера: "ОтключитьДоступность",
  ПропускатьПриВводе: "Истина",
  РазрешитьИспользование: { "Role.Администратор": "Ложь" },
  РастягиватьПоВертикали: "Ложь",
  РастягиватьПоГоризонтали: "Истина",
  СочетаниеКлавиш: "Cmd+S",
  ЦветТекста: "Малиновый",
  Ширина: 10,
  Шрифт: "КрупныйШрифтТекста",
  КонтекстноеМеню: { Автозаполнение: "Ложь" },
  РасширеннаяПодсказка: { Заголовок: "РасширеннаяПодсказка" },
} as const
