import { V8_MDCLASSES_ROOT } from "~/metadata/orchestration/appliedObject/presets"
import { MetadataItemRule } from "~/metadata/orchestration/property/types"
import { commonBasedOnObjectPaths } from "~/metadata/commonObjects/metadataTargets"
import { MetadataCommandRules } from "../metadataCommand/rules"

const properties = ["Properties"]
const childObjects = ["ChildObjects"]

export const MetadataChartOfCalculationTypesStandardAttributeNames: Record<string, string> = {
  PredefinedDataName: "ИмяПредопределенныхДанных",
  Predefined: "Предопределенный",
  Ref: "Ссылка",
  DeletionMark: "ПометкаУдаления",
  ActionPeriodIsBasic: "ПериодДействияБазовый",
  Description: "Наименование",
  Code: "Код",
}

const MetadataChartOfCalculationTypesCommandRules = {
  ...MetadataCommandRules,
  properties: {
    ...MetadataCommandRules.properties,
    commandModule: {
      ...MetadataCommandRules.properties.commandModule,
      xmlPath: ({ name }: { name: string }) => `Commands/${name}/Ext/CommandModule.bsl`,
    },
  },
} as const satisfies MetadataItemRule

export const MetadataChartOfCalculationTypesRules = {
  itemType: "MetadataChartOfCalculationTypes",
  metadataTargetOwner: { kind: "self", root: "ChartOfCalculationTypes" },
  itemTypePrefix: "ПланВидовРасчета",
  xmlDir: "ChartsOfCalculationTypes",
  uniqueNameScopes: [{ collections: ["attributes", "tabularSections"] }],
  properties: {
    xmlRoot: { type: "XMLRoot", container: "ChartOfCalculationTypes", rootAttributes: V8_MDCLASSES_ROOT, forReferenceOnly: true, toYAML: false, fromYAML: false },
    internalInfo: {
      type: "InternalInfo",
      xmlParents: [],
      forReferenceOnly: true,
      items: [
        { name: "ChartOfCalculationTypesObject", category: "Object" },
        { name: "ChartOfCalculationTypesRef", category: "Ref" },
        { name: "ChartOfCalculationTypesSelection", category: "Selection" },
        { name: "ChartOfCalculationTypesList", category: "List" },
        { name: "ChartOfCalculationTypesManager", category: "Manager" },
        { name: "DisplacingCalculationTypes", category: "DisplacingCalculationTypes" },
        { name: "DisplacingCalculationTypesRow", category: "DisplacingCalculationTypesRow" },
        { name: "BaseCalculationTypes", category: "BaseCalculationTypes" },
        { name: "BaseCalculationTypesRow", category: "BaseCalculationTypesRow" },
        { name: "LeadingCalculationTypes", category: "LeadingCalculationTypes" },
        { name: "LeadingCalculationTypesRow", category: "LeadingCalculationTypesRow" },
      ],
    },
    uuid: { type: "uuid", xml: "_uuid", forReferenceOnly: true, xmlParents: [] },
    name: { type: "string", xmlParents: properties, required: true, defaultValue: ({ name }: { name?: string }) => name },
    synonym: { yaml: "Синоним", type: "I8nText", xmlParents: properties, defaultValueXMLRaw: "" },
    comment: { yaml: "Комментарий", type: "string", xmlParents: properties, defaultValueXMLRaw: "" },
    useStandardCommands: { yaml: "ИспользоватьСтандартныеКоманды", type: "boolean", defaultValueXML: true, implicitValueYAML: true, xmlParents: properties },
    codeLength: { yaml: "ДлинаКода", type: "number", defaultValueXML: 9, implicitValueYAML: 9, xmlParents: properties },
    descriptionLength: { yaml: "ДлинаНаименования", type: "number", defaultValueXML: 40, implicitValueYAML: 40, xmlParents: properties },
    codeType: { yaml: "ТипКода", type: "SystemEnumeration", typeSE: "ChartOfCalculationTypesCodeType", defaultValueXML: "String", implicitValueYAML: "String", xmlParents: properties },
    codeAllowedLength: { yaml: "ДопустимаяДлинаКода", type: "SystemEnumeration", typeSE: "AllowedLength", defaultValueXML: "Variable", implicitValueYAML: "Variable", xmlParents: properties },
    defaultPresentation: { yaml: "ОсновноеПредставление", type: "SystemEnumeration", typeSE: "CalculationTypeMainPresentation", defaultValueXML: "AsDescription", implicitValueYAML: "AsDescription", xmlParents: properties },
    editType: { yaml: "СпособРедактирования", type: "SystemEnumeration", typeSE: "EditType", defaultValueXML: "InDialog", implicitValueYAML: "InDialog", xmlParents: properties },
    quickChoice: { yaml: "БыстрыйВыбор", type: "boolean", defaultValueXML: false, implicitValueYAML: false, xmlParents: properties },
    choiceMode: { yaml: "РежимВыбора", type: "SystemEnumeration", typeSE: "ChoiceMode", defaultValueXML: "BothWays", implicitValueYAML: "BothWays", xmlParents: properties },
    inputByString: { yaml: "ВводПоСтроке", type: "MetadataFields", xmlParents: properties, defaultValueXMLRaw: {} },
    searchStringModeOnInputByString: { yaml: "РежимСтрокиПоискаПриВводеПоСтроке", type: "SystemEnumeration", typeSE: "SearchStringModeOnInputByString", defaultValueXML: "Begin", implicitValueYAML: "Begin", xmlParents: properties },
    fullTextSearchOnInputByString: { yaml: "ПолнотекстовыйПоискПриВводеПоСтроке", type: "SystemEnumeration", typeSE: "FullTextSearchOnInputByString", defaultValueXML: "DontUse", implicitValueYAML: "DontUse", xmlParents: properties },
    choiceDataGetModeOnInputByString: { yaml: "РежимПолученияДанныхВыбораПриВводеПоСтроке", type: "SystemEnumeration", typeSE: "ChoiceDataGetModeOnInputByString", defaultValueXML: "Directly", implicitValueYAML: "Directly", xmlParents: properties },
    createOnInput: { yaml: "СозданиеПриВводе", type: "SystemEnumeration", typeSE: "CreateOnInput", defaultValueXML: "DontUse", implicitValueYAML: "DontUse", xmlParents: properties },
    choiceHistoryOnInput: { yaml: "ИсторияВыбораПриВводе", type: "SystemEnumeration", typeSE: "ChoiceHistoryOnInput", defaultValueXML: "Auto", implicitValueYAML: "Auto", xmlParents: properties },
    defaultObjectForm: { yaml: "ОсновнаяФормаОбъекта", type: "string", xmlParents: properties, metadataTarget: { kind: "member", owner: "this", memberKinds: ["Form"], objectRoots: ["CommonForm"] }, defaultValueXMLRaw: "" },
    defaultListForm: { yaml: "ОсновнаяФормаСписка", type: "string", xmlParents: properties, metadataTarget: { kind: "member", owner: "this", memberKinds: ["Form"], objectRoots: ["CommonForm"] }, defaultValueXMLRaw: "" },
    defaultChoiceForm: { yaml: "ОсновнаяФормаВыбора", type: "string", xmlParents: properties, metadataTarget: { kind: "member", owner: "this", memberKinds: ["Form"], objectRoots: ["CommonForm"] }, defaultValueXMLRaw: "" },
    auxiliaryObjectForm: { yaml: "ДополнительнаяФормаОбъекта", type: "string", xmlParents: properties, metadataTarget: { kind: "member", owner: "this", memberKinds: ["Form"], objectRoots: ["CommonForm"] }, defaultValueXMLRaw: "" },
    auxiliaryListForm: { yaml: "ДополнительнаяФормаСписка", type: "string", xmlParents: properties, metadataTarget: { kind: "member", owner: "this", memberKinds: ["Form"], objectRoots: ["CommonForm"] }, defaultValueXMLRaw: "" },
    auxiliaryChoiceForm: { yaml: "ДополнительнаяФормаВыбора", type: "string", xmlParents: properties, metadataTarget: { kind: "member", owner: "this", memberKinds: ["Form"], objectRoots: ["CommonForm"] }, defaultValueXMLRaw: "" },
    basedOn: { yaml: "ВводитсяНаОсновании", type: "MetadataItemLinks", metadataTarget: { kind: "object", allowedObjectPaths: commonBasedOnObjectPaths }, xmlParents: properties, defaultValueXMLRaw: {} },
    dependenceOnCalculationTypes: { yaml: "ЗависимостьОтВидовРасчета", type: "SystemEnumeration", typeSE: "ChartOfCalculationTypesBaseUse", defaultValueXML: "DontUse", implicitValueYAML: "DontUse", xmlParents: properties },
    baseCalculationTypes: { yaml: "БазовыеВидыРасчета", type: "MetadataItemLinks", xmlParents: properties, defaultValueXMLRaw: {} },
    actionPeriodUse: { yaml: "ПериодДействияБазовый", type: "boolean", defaultValueXML: false, implicitValueYAML: false, xmlParents: properties },
    standardAttributes: { yaml: "СтандартныеРеквизиты", type: "StandardAttributeDescriptions", standartAttributeNames: MetadataChartOfCalculationTypesStandardAttributeNames, xmlParents: properties },
    characteristics: { yaml: "Характеристики", type: "CharacteristicsDescriptions", xmlParents: properties, defaultValueXMLRaw: {} },
    standardTabularSections: { type: "StandardTabularSectionDescriptions", xmlParents: properties, toYAML: false, fromYAML: false },
    predefinedDataUpdate: { yaml: "ОбновлениеПредопределенныхДанных", type: "SystemEnumeration", typeSE: "PredefinedDataUpdate", defaultValueXML: "Auto", implicitValueYAML: "Auto", xmlParents: properties },
    includeHelpInContents: { yaml: "ВключатьСправкуВСодержание", type: "boolean", defaultValueXML: false, implicitValueYAML: false, xmlParents: properties },
    dataLockFields: { yaml: "ПоляБлокировкиДанных", type: "MetadataFields", xmlParents: properties, defaultValueXMLRaw: {} },
    dataLockControlMode: { yaml: "РежимУправленияБлокировкойДанных", type: "SystemEnumeration", typeSE: "DefaultDataLockControlMode", defaultValueXML: "Managed", implicitValueYAML: "Managed", xmlParents: properties },
    fullTextSearch: { yaml: "ПолнотекстовыйПоиск", type: "SystemEnumeration", typeSE: "UseFullTextSearch", defaultValueXML: "Use", implicitValueYAML: "Use", xmlParents: properties },
    objectPresentation: { yaml: "ПредставлениеОбъекта", type: "I8nText", xmlParents: properties, defaultValueXMLRaw: "" },
    extendedObjectPresentation: { yaml: "РасширенноеПредставлениеОбъекта", type: "I8nText", xmlParents: properties, defaultValueXMLRaw: "" },
    listPresentation: { yaml: "ПредставлениеСписка", type: "I8nText", xmlParents: properties, defaultValueXMLRaw: "" },
    extendedListPresentation: { yaml: "РасширенноеПредставлениеСписка", type: "I8nText", xmlParents: properties, defaultValueXMLRaw: "" },
    explanation: { yaml: "Пояснение", type: "I8nText", xmlParents: properties, defaultValueXMLRaw: "" },
    dataHistory: { yaml: "ИсторияДанных", type: "SystemEnumeration", typeSE: "DataHistoryUse", defaultValueXML: "DontUse", implicitValueYAML: "DontUse", xmlParents: properties },
    updateDataHistoryImmediatelyAfterWrite: { yaml: "ОбновлятьИсториюДанныхСразуПослеЗаписи", type: "boolean", defaultValueXML: false, implicitValueYAML: false, xmlParents: properties },
    executeAfterWriteDataHistoryVersionProcessing: { yaml: "ВыполнятьОбработкуПослеЗаписиВерсииИсторииДанных", type: "boolean", defaultValueXML: false, implicitValueYAML: false, xmlParents: properties },
    objectBelonging: { yaml: "ПринадлежностьОбъекта", type: "SystemEnumeration", typeSE: "ObjectBelonging", xmlParents: properties, toYAML: false, fromYAML: false, implicitValueYAML: "Native" },
    extendedConfigurationObject: { type: "string", runtimeOnly: true },
    attributes: { yaml: "Реквизиты", xml: "Attribute", type: "MetadataAttributes", xmlParents: childObjects },
    tabularSections: { yaml: "ТабличныеЧасти", xml: "TabularSection", type: "MetadataChartOfCalculationTypesTabularSections", xmlParents: childObjects },
    forms: { yaml: "Формы", xml: "Form", type: "ChildFormNames", xmlParents: childObjects, folderName: "Формы", forReferenceOnly: true, toYAML: false, fromYAML: false },
    templates: { yaml: "Макеты", xml: "Template", type: "ChildTemplateNames", xmlParents: childObjects, folderName: "Макеты", forReferenceOnly: true, toYAML: false, fromYAML: false },
    commands: { yaml: "Команды", xml: "Command", type: "MetadataCommands", xmlParents: childObjects },
    objectModule: { type: "Module", externalMetadata: { segment: "ObjectModule", placement: "derivedEntry" }, nkdkPath: "МодульОбъекта.bsl", xmlPath: "Ext/ObjectModule.bsl", toXML: false, fromXML: false },
    managerModule: { type: "Module", externalMetadata: { segment: "ManagerModule", placement: "derivedEntry" }, nkdkPath: "МодульМенеджера.bsl", xmlPath: "Ext/ManagerModule.bsl", toXML: false, fromXML: false },
    predefined: { yaml: "Предопределенные", type: "Predefined", filePath: "Ext/Predefined.xml" },
    additionalIndexes: { yaml: "ДополнительныеИндексы", type: "AdditionalIndex", filePath: "Ext/AdditionalIndexes.xml" },
    help: { type: "Help", externalMetadata: { segment: "Help", placement: "derivedEntry" }, filePath: "Ext/Help.xml", xmlPath: "Ext/Help.xml", nkdkDir: "Справка", toXML: false, fromXML: false },
  },
  childCollections: [{ propertyKey: "commands", itemRule: MetadataChartOfCalculationTypesCommandRules }],
} as const satisfies MetadataItemRule
