import importColorFromXML from "~/lib/metadata/color/importFromXML"
import importFontFromXML from "~/lib/metadata/font/importFromXML"
import importI8nTextFromXML from "~/lib/metadata/i8nText/importI8nTextFromXML"
import { importBaseElementFromXML } from "../baseElement/importBaseElementFromXML"
import { importFormDecorationFromXML } from "../formDecoration/importFromXML"
import { TFormTableXML, TFormTable } from "./types"


export const importFormTableFromXML = (xml: TFormTableXML | undefined): TFormTable | undefined => {
   if (!xml) return undefined
   return {
    ...importBaseElementFromXML(xml),
     autoAddIncomplete: xml.AutoAddIncomplete,
     autoInsertNewRow: xml.AutoInsertNewRow,
     autoMaxHeight: xml.AutoMaxHeight,
     autoMaxHeightInTableRows: xml.AutoMaxHeightInTableRows,
     autoMaxWidth: xml.AutoMaxWidth,
     autoMarkIncomplete: xml.AutoMarkIncomplete,
     defaultItem: xml.DefaultItem,
     displayImportance: xml.DisplayImportance,
     heightControlVariant: xml.HeightControlVariant,
     verticalScrollBar: xml.VerticalScrollBar,
     verticalAlignInGroup: xml.VerticalAlignInGroup,
     verticalLines: xml.VerticalLines,
     visible: xml.Visible,
     output: xml.Output,
     selectedRows: xml.SelectedRows,
     height: xml.Height,
     heightInTableRows: xml.HeightInTableRows,
     titleHeight: xml.TitleHeight,
     footerHeight: xml.FooterHeight,
     headerHeight: xml.HeaderHeight,
     horizontalScrollBar: xml.HorizontalScrollBar,
     horizontalAlignInGroup: xml.HorizontalAlignInGroup,
     horizontalLines: xml.HorizontalLines,
     enabled: xml.Enabled,
     title: importI8nTextFromXML(xml.Title),
     refreshRequest: xml.RefreshRequest,
     changeRowOrder: xml.ChangeRowOrder,
     changeRowSet: xml.ChangeRowSet,
     currentRowUse: xml.CurrentRowUse,
     rowsPicture: xml.RowsPicture,
     commandBar: xml.CommandBar,
     contextMenu: xml.ContextMenu,
     maxHeight: xml.MaxHeight,
     maxHeightInTableRows: xml.MaxHeightInTableRows,
     maxWidth: xml.MaxWidth,
     multipleChoice: xml.MultipleChoice,
     initialTreeView: xml.InitialTreeView,
     initialListView: xml.InitialListView,
     markIncomplete: xml.MarkIncomplete,
     representation: xml.Representation,
     toolTipRepresentation: xml.ToolTipRepresentation,
     viewStatusRepresentation: xml.ViewStatusRepresentation,
     searchStringRepresentation: xml.SearchStringRepresentation,
     behaviorOnHorizontalCompression: xml.BehaviorOnHorizontalCompression,
     footer: xml.Footer,
     toolTip: importI8nTextFromXML(xml.ToolTip),
     childItems: xml.ChildItems,
     searchOnInput: xml.SearchOnInput,
     titleLocation: xml.TitleLocation,
     commandBarLocation: xml.CommandBarLocation,
     hierarchyPanelLocation: xml.HierarchyPanelLocation,
     viewStatusLocation: xml.ViewStatusLocation,
     searchStringLocation: xml.SearchStringLocation,
     searchControlLocation: xml.SearchControlLocation,
     skipOnInput: xml.SkipOnInput,
     dataPath: xml.DataPath,
     rowPictureDataPath: xml.RowPictureDataPath,
     enableStartDrag: xml.EnableStartDrag,
     enableDrag: xml.EnableDrag,
     verticalStretch: xml.VerticalStretch,
     horizontalStretch: xml.HorizontalStretch,
     extendedTooltip: importFormDecorationFromXML(xml.ExtendedTooltip),
     rowInputMode: xml.RowInputMode,
     choiceMode: xml.ChoiceMode,
     selectionMode: xml.SelectionMode,
     rowSelectionMode: xml.RowSelectionMode,
     shortcut: xml.Shortcut,
     fileDragMode: xml.FileDragMode,
     currentRow: xml.CurrentRow,
     currentData: xml.CurrentData,
     currentParent: xml.CurrentParent,
     currentItem: xml.CurrentItem,
     readOnly: xml.ReadOnly,
     searchControl: xml.SearchControl,
     borderColor: importColorFromXML(xml.BorderColor),
     textColor: importColorFromXML(xml.TextColor),
     titleTextColor: importColorFromXML(xml.TitleTextColor),
     backColor: importColorFromXML(xml.BackColor),
     useAlternationRowColor: xml.UseAlternationRowColor,
     header: xml.Header,
     width: xml.Width,
     font: importFontFromXML(xml.Font),
     titleFont: importFontFromXML(xml.TitleFont),
  }
}