export type BuilderMode = "strict" | "wide"

export type BuilderCatalogEntry = {
  propertyType: string
  builderName: string
  importPath: string
  mode: BuilderMode
}

export type BuilderCatalog = ReadonlyMap<string, BuilderCatalogEntry>

const entries = [
  ["string", "stringRule", "~/metadata/commonObjects/string/types", "strict"],
  ["boolean", "booleanRule", "~/metadata/commonObjects/boolean/types", "strict"],
  ["number", "numberRule", "~/metadata/commonObjects/number/types", "strict"],
  ["uuid", "uuidRule", "~/metadata/commonObjects/uuid/types", "strict"],
  ["XMLRoot", "xmlRootRule", "~/metadata/commonObjects/xmlRoot/types", "strict"],
  ["I8nText", "i8nTextRule", "~/metadata/commonObjects/i8nText/types", "strict"],
  ["SystemEnumeration", "systemEnumerationRule", "~/metadata/systemEnumerations/types", "strict"],
  ["Module", "moduleRule", "~/metadata/commonObjects/module/types", "strict"],
  ["MetadataValue", "metadataValueRule", "~/metadata/commonObjects/metadataValue/types", "wide"],
  ["AccountingFlags", "accountingFlagsRule", "~/metadata/appliedObjects/metadataChartOfAccounts/builders", "wide"],
  [
    "AccumulationRegisterAggregateCollection",
    "accumulationRegisterAggregateCollectionRule",
    "~/metadata/commonObjects/accumulationRegisterAggregates/builders",
    "wide",
  ],
  [
    "AccumulationRegisterAggregateDimensions",
    "accumulationRegisterAggregateDimensionsRule",
    "~/metadata/commonObjects/accumulationRegisterAggregates/builders",
    "wide",
  ],
  [
    "AccumulationRegisterAggregates",
    "accumulationRegisterAggregatesRule",
    "~/metadata/appliedObjects/metadataAccumulationRegister/builders",
    "wide",
  ],
  ["AdditionalIndex", "additionalIndexRule", "~/metadata/appliedObjects/metadataAccountingRegister/builders", "wide"],
  [
    "AdditionalIndexCollection",
    "additionalIndexCollectionRule",
    "~/metadata/commonObjects/additionalIndex/builders",
    "wide",
  ],
  [
    "AllowedIncomingShareRequestTypes",
    "allowedIncomingShareRequestTypesRule",
    "~/metadata/appliedObjects/configuration/builders",
    "wide",
  ],
  [
    "AppearanceFields",
    "appearanceFieldsRule",
    "~/metadata/commonObjects/dataCompositionSystem/appearanceFields/builders",
    "wide",
  ],
  ["AssociatedTable", "associatedTableRule", "~/metadata/commonObjects/metadataValue/types", "wide"],
  ["AutoCommandBar", "autoCommandBarRule", "~/metadata/forms/clientApplicationForm/builders", "wide"],
  [
    "AvailableFields",
    "availableFieldsRule",
    "~/metadata/commonObjects/dataCompositionSystem/availableFields/types",
    "wide",
  ],
  ["Border", "borderRule", "~/metadata/commonObjects/border/types", "wide"],
  [
    "CalculatedFieldOrderExpression",
    "calculatedFieldOrderExpressionRule",
    "~/metadata/commonObjects/dataCompositionSystem/calculatedField/builders",
    "wide",
  ],
  ["CalculatedFields", "calculatedFieldsRule", "~/metadata/forms/commonObjects/dynamicList/builders", "wide"],
  [
    "CalculatedFieldUseRestriction",
    "calculatedFieldUseRestrictionRule",
    "~/metadata/commonObjects/dataCompositionSystem/calculatedField/builders",
    "wide",
  ],
  [
    "CharacteristicsDescriptions",
    "characteristicsDescriptionsRule",
    "~/metadata/commonObjects/characteristicsDescription/types",
    "wide",
  ],
  ["Chart", "chartRule", "~/metadata/forms/commonObjects/formAttribute/builders", "wide"],
  ["ChildFileItemNames", "childFileItemNamesRule", "~/metadata/commonObjects/childFileItemNames/types", "wide"],
  ["ChildFormNames", "childFormNamesRule", "~/metadata/commonObjects/childFormNames/types", "wide"],
  ["ChildSubsystemNames", "childSubsystemNamesRule", "~/metadata/commonObjects/childSubsystemNames/types", "wide"],
  ["ChildTemplateNames", "childTemplateNamesRule", "~/metadata/commonObjects/childTemplateNames/types", "wide"],
  ["ChoiceList", "choiceListRule", "~/metadata/commonObjects/choiceList/types", "wide"],
  ["ChoiceParameterLinks", "choiceParameterLinksRule", "~/metadata/commonObjects/сhoiceParameterLinks/types", "wide"],
  ["ChoiceParameters", "choiceParametersRule", "~/metadata/commonObjects/сhoiceParameters/types", "wide"],
  ["ClientApplicationForm", "clientApplicationFormRule", "~/metadata/forms/clientApplicationForm/builders", "wide"],
  [
    "ClientApplicationInterface",
    "clientApplicationInterfaceRule",
    "~/metadata/appliedObjects/configuration/builders",
    "wide",
  ],
  [
    "ClientApplicationInterfaceItems",
    "clientApplicationInterfaceItemsRule",
    "~/metadata/commonObjects/clientApplicationInterface/builders",
    "wide",
  ],
  [
    "ClientApplicationInterfacePanelDefs",
    "clientApplicationInterfacePanelDefsRule",
    "~/metadata/commonObjects/clientApplicationInterface/builders",
    "wide",
  ],
  ["Color", "colorRule", "~/metadata/commonObjects/color/types", "wide"],
  ["CommandBarChildItems", "commandBarChildItemsRule", "~/metadata/forms/commonObjects/childItems/types", "wide"],
  ["CommandInterface", "commandInterfaceRule", "~/metadata/forms/commonObjects/commandInterface/types", "wide"],
  [
    "CommandInterfaceCommandGroups",
    "commandInterfaceCommandGroupsRule",
    "~/metadata/commonObjects/rootCommandInterface/builders",
    "wide",
  ],
  [
    "CommandInterfaceOrder",
    "commandInterfaceOrderRule",
    "~/metadata/commonObjects/rootCommandInterface/builders",
    "wide",
  ],
  [
    "CommandInterfacePlacementMap",
    "commandInterfacePlacementMapRule",
    "~/metadata/commonObjects/rootCommandInterface/builders",
    "wide",
  ],
  [
    "CommandInterfaceSubsystemsOrder",
    "commandInterfaceSubsystemsOrderRule",
    "~/metadata/commonObjects/rootCommandInterface/builders",
    "wide",
  ],
  [
    "CommandInterfaceSubsystemsVisibilityMap",
    "commandInterfaceSubsystemsVisibilityMapRule",
    "~/metadata/commonObjects/rootCommandInterface/builders",
    "wide",
  ],
  [
    "CommandInterfaceVisibilityMap",
    "commandInterfaceVisibilityMapRule",
    "~/metadata/commonObjects/rootCommandInterface/builders",
    "wide",
  ],
  ["CommandSet", "commandSetRule", "~/metadata/forms/commonObjects/commandSet/types", "wide"],
  [
    "CommonAttributeContent",
    "commonAttributeContentRule",
    "~/metadata/commonObjects/commonAttributeContent/types",
    "wide",
  ],
  ["ConditionalAppearance", "conditionalAppearanceRule", "~/metadata/forms/clientApplicationForm/builders", "wide"],
  [
    "ConditionalAppearanceItems",
    "conditionalAppearanceItemsRule",
    "~/metadata/commonObjects/dataCompositionSystem/conditionalAppearance/builders",
    "wide",
  ],
  ["ContextMenu", "contextMenuRule", "~/metadata/forms/elements/viewStatusAddition/builders", "wide"],
  [
    "DataCompositionSchemaDataSetFieldKind",
    "dataCompositionSchemaDataSetFieldKindRule",
    "~/metadata/commonObjects/dataCompositionSystem/dataCompositionSchemaDataSetField/builders",
    "wide",
  ],
  ["DataPath", "dataPathRule", "~/metadata/commonObjects/metadataPath/types", "wide"],
  ["DataSetFieldFields", "dataSetFieldFieldsRule", "~/metadata/forms/commonObjects/dynamicList/builders", "wide"],
  ["dateTime", "dateTimeRule", "~/metadata/commonObjects/dateTime/types", "wide"],
  [
    "DcsAvailableValues",
    "dcsAvailableValuesRule",
    "~/metadata/commonObjects/dataCompositionSystem/availableValues/types",
    "wide",
  ],
  [
    "DcsLocalStringType",
    "dcsLocalStringTypeRule",
    "~/metadata/commonObjects/dataCompositionSystem/dcsLocalStringType/types",
    "wide",
  ],
  [
    "DcsMetadataTypedValue",
    "dcsMetadataTypedValueRule",
    "~/metadata/commonObjects/dataCompositionSystem/dscMetadataTypedValue/types",
    "wide",
  ],
  ["DCSParameters", "dCSParametersRule", "~/metadata/forms/commonObjects/dynamicList/builders", "wide"],
  ["DynamicList", "dynamicListRule", "~/metadata/forms/commonObjects/formAttribute/builders", "wide"],
  ["DynamicListKeyFields", "dynamicListKeyFieldsRule", "~/metadata/forms/commonObjects/dynamicList/builders", "wide"],
  ["ElementId", "elementIdRule", "~/metadata/forms/commonObjects/elementId/types", "wide"],
  ["Events", "eventsRule", "~/metadata/forms/commonObjects/event/types", "wide"],
  ["ExchangePlanContent", "exchangePlanContentRule", "~/metadata/appliedObjects/metadataExchangePlan/builders", "wide"],
  [
    "ExchangePlanContentItems",
    "exchangePlanContentItemsRule",
    "~/metadata/commonObjects/exchangePlanContent/builders",
    "wide",
  ],
  [
    "ExtDimensionAccountingFlags",
    "extDimensionAccountingFlagsRule",
    "~/metadata/appliedObjects/metadataChartOfAccounts/builders",
    "wide",
  ],
  ["ExtendedTooltip", "extendedTooltipRule", "~/metadata/forms/elements/viewStatusAddition/builders", "wide"],
  ["ExternalFile", "externalFileRule", "~/metadata/commonObjects/externalFile/types", "wide"],
  ["ExternalFormItemFile", "externalFormItemFileRule", "~/metadata/forms/clientApplicationForm/builders", "wide"],
  ["ExternalPicture", "externalPictureRule", "~/metadata/commonObjects/externalPicture/types", "wide"],
  ["FieldsList", "fieldsListRule", "~/metadata/commonObjects/fieldsList/types", "wide"],
  ["Filter", "filterRule", "~/metadata/commonObjects/dataCompositionSystem/conditionalAppearanceItem/builders", "wide"],
  ["FilterItem", "filterItemRule", "~/metadata/commonObjects/dataCompositionSystem/filter/builders", "wide"],
  [
    "FilterItemPresentationValue",
    "filterItemPresentationValueRule",
    "~/metadata/commonObjects/dataCompositionSystem/filterItem/builders",
    "wide",
  ],
  ["FlowchartContext", "flowchartContextRule", "~/metadata/forms/commonObjects/formAttribute/builders", "wide"],
  ["Font", "fontRule", "~/metadata/commonObjects/font/types", "wide"],
  ["FormattedI8nText", "formattedI8nTextRule", "~/metadata/commonObjects/formattedI8nText/types", "wide"],
  [
    "FormAttributeAdditionalColumns",
    "formAttributeAdditionalColumnsRule",
    "~/metadata/forms/commonObjects/formAttribute/builders",
    "wide",
  ],
  ["FormAttributeColumns", "formAttributeColumnsRule", "~/metadata/forms/commonObjects/formAttribute/builders", "wide"],
  ["FormAttributes", "formAttributesRule", "~/metadata/forms/commonObjects/formAttribute/builders", "wide"],
  ["FormCommands", "formCommandsRule", "~/metadata/forms/commonObjects/formCommand/builders", "wide"],
  ["FormParameters", "formParametersRule", "~/metadata/forms/commonObjects/formParameter/types", "wide"],
  [
    "FunctionalOptionsProperty",
    "functionalOptionsPropertyRule",
    "~/metadata/commonObjects/functionalOptionsProperty/types",
    "wide",
  ],
  ["GanttChart", "ganttChartRule", "~/metadata/forms/commonObjects/formAttribute/builders", "wide"],
  [
    "GanttChartFieldTable",
    "ganttChartFieldTableRule",
    "~/metadata/forms/commonObjects/ganttChartFieldTable/types",
    "wide",
  ],
  ["GroupChildItems", "groupChildItemsRule", "~/metadata/forms/commonObjects/childItems/types", "wide"],
  ["Help", "helpRule", "~/metadata/commonObjects/help/types", "wide"],
  ["HomePageWorkArea", "homePageWorkAreaRule", "~/metadata/appliedObjects/configuration/builders", "wide"],
  [
    "HomePageWorkAreaColumnItems",
    "homePageWorkAreaColumnItemsRule",
    "~/metadata/commonObjects/homePageWorkArea/builders",
    "wide",
  ],
  [
    "HomePageWorkAreaCommandInterfaceDisplay",
    "homePageWorkAreaCommandInterfaceDisplayRule",
    "~/metadata/commonObjects/homePageWorkArea/builders",
    "wide",
  ],
  [
    "HomePageWorkAreaTemplate",
    "homePageWorkAreaTemplateRule",
    "~/metadata/commonObjects/homePageWorkArea/builders",
    "wide",
  ],
  ["IndexField", "indexFieldRule", "~/metadata/commonObjects/indexField/types", "wide"],
  ["InternalInfo", "internalInfoRule", "~/metadata/commonObjects/internalInfo/types", "wide"],
  ["MetadataAttributes", "metadataAttributesRule", "~/metadata/appliedObjects/metadataDataProcessor/builders", "wide"],
  [
    "MetadataBusinessProcessTabularSections",
    "metadataBusinessProcessTabularSectionsRule",
    "~/metadata/appliedObjects/metadataBusinessProcess/builders",
    "wide",
  ],
  [
    "MetadataCatalogAttributes",
    "metadataCatalogAttributesRule",
    "~/metadata/appliedObjects/metadataCatalog/builders",
    "wide",
  ],
  [
    "MetadataChartOfAccountsTabularSections",
    "metadataChartOfAccountsTabularSectionsRule",
    "~/metadata/appliedObjects/metadataChartOfAccounts/builders",
    "wide",
  ],
  [
    "MetadataChartOfCalculationTypesTabularSections",
    "metadataChartOfCalculationTypesTabularSectionsRule",
    "~/metadata/appliedObjects/metadataChartOfCalculationTypes/builders",
    "wide",
  ],
  [
    "MetadataChartOfCharacteristicTypesTabularSections",
    "metadataChartOfCharacteristicTypesTabularSectionsRule",
    "~/metadata/appliedObjects/metadataChartOfCharacteristicTypes/builders",
    "wide",
  ],
  ["MetadataCommandGroup", "metadataCommandGroupRule", "~/metadata/commonObjects/metadataCommandGroup/types", "wide"],
  ["MetadataCommands", "metadataCommandsRule", "~/metadata/appliedObjects/metadataAccountingRegister/builders", "wide"],
  [
    "MetadataDataProcessorTabularSections",
    "metadataDataProcessorTabularSectionsRule",
    "~/metadata/appliedObjects/metadataDataProcessor/builders",
    "wide",
  ],
  [
    "MetadataDcsMetadataValue",
    "metadataDcsMetadataValueRule",
    "~/metadata/commonObjects/dataCompositionSystem/dcsMetadataValue/types",
    "wide",
  ],
  [
    "MetadataDocumentAttributes",
    "metadataDocumentAttributesRule",
    "~/metadata/appliedObjects/metadataDocument/types",
    "wide",
  ],
  [
    "MetadataDocumentJournalColumns",
    "metadataDocumentJournalColumnsRule",
    "~/metadata/appliedObjects/metadataDocumentJournal/builders",
    "wide",
  ],
  [
    "MetadataDocumentTabularSections",
    "metadataDocumentTabularSectionsRule",
    "~/metadata/appliedObjects/metadataDocument/types",
    "wide",
  ],
  [
    "MetadataEnumerationValues",
    "metadataEnumerationValuesRule",
    "~/metadata/appliedObjects/metadataEnumeration/builders",
    "wide",
  ],
  [
    "MetadataExchangePlanTabularSections",
    "metadataExchangePlanTabularSectionsRule",
    "~/metadata/appliedObjects/metadataExchangePlan/builders",
    "wide",
  ],
  [
    "MetadataExternalDataSourceFunctions",
    "metadataExternalDataSourceFunctionsRule",
    "~/metadata/appliedObjects/metadataExternalDataSource/builders",
    "wide",
  ],
  ["MetadataFields", "metadataFieldsRule", "~/metadata/commonObjects/metadataField/types", "wide"],
  [
    "MetadataHTTPServiceURLTemplates",
    "metadataHTTPServiceURLTemplatesRule",
    "~/metadata/appliedObjects/metadataHTTPService/builders",
    "wide",
  ],
  [
    "MetadataIntegrationServiceChannels",
    "metadataIntegrationServiceChannelsRule",
    "~/metadata/appliedObjects/metadataIntegrationService/builders",
    "wide",
  ],
  ["MetadataItemLink", "metadataItemLinkRule", "~/metadata/commonObjects/metadataPath/types", "wide"],
  ["MetadataItemLinks", "metadataItemLinksRule", "~/metadata/commonObjects/metadataPath/types", "wide"],
  [
    "MetadataObjectRefCollection",
    "metadataObjectRefCollectionRule",
    "~/metadata/commonObjects/metadataObjectRefCollection/types",
    "wide",
  ],
  [
    "MetadataRegisterAttributes",
    "metadataRegisterAttributesRule",
    "~/metadata/appliedObjects/metadataAccountingRegister/builders",
    "wide",
  ],
  [
    "MetadataRegisterDimensions",
    "metadataRegisterDimensionsRule",
    "~/metadata/appliedObjects/metadataAccountingRegister/builders",
    "wide",
  ],
  [
    "MetadataRegisterResources",
    "metadataRegisterResourcesRule",
    "~/metadata/appliedObjects/metadataAccountingRegister/builders",
    "wide",
  ],
  [
    "MetadataReportAttributes",
    "metadataReportAttributesRule",
    "~/metadata/appliedObjects/metadataReport/builders",
    "wide",
  ],
  [
    "MetadataReportTabularSections",
    "metadataReportTabularSectionsRule",
    "~/metadata/appliedObjects/metadataReport/builders",
    "wide",
  ],
  [
    "MetadataSequenceDimensions",
    "metadataSequenceDimensionsRule",
    "~/metadata/appliedObjects/metadataSequence/builders",
    "wide",
  ],
  [
    "MetadataTabularSections",
    "metadataTabularSectionsRule",
    "~/metadata/appliedObjects/metadataCatalog/builders",
    "wide",
  ],
  [
    "MetadataTaskAddressingAttributes",
    "metadataTaskAddressingAttributesRule",
    "~/metadata/appliedObjects/metadataTask/builders",
    "wide",
  ],
  [
    "MetadataTaskTabularSections",
    "metadataTaskTabularSectionsRule",
    "~/metadata/appliedObjects/metadataTask/builders",
    "wide",
  ],
  [
    "MetadataWebServiceOperations",
    "metadataWebServiceOperationsRule",
    "~/metadata/appliedObjects/metadataWebService/builders",
    "wide",
  ],
  ["MinMaxValue", "minMaxValueRule", "~/metadata/commonObjects/minMaxValue/types", "wide"],
  ["MobileApplicationURLs", "mobileApplicationURLsRule", "~/metadata/appliedObjects/configuration/builders", "wide"],
  [
    "MobileDeviceCommandBarContent",
    "mobileDeviceCommandBarContentRule",
    "~/metadata/commonObjects/mobileDeviceCommandBarContent/types",
    "wide",
  ],
  ["Order", "orderRule", "~/metadata/forms/commonObjects/dynamicList/builders", "wide"],
  ["OrderItemFields", "orderItemFieldsRule", "~/metadata/commonObjects/dataCompositionSystem/order/builders", "wide"],
  ["PagesChildItems", "pagesChildItemsRule", "~/metadata/forms/commonObjects/childItems/types", "wide"],
  ["Picture", "pictureRule", "~/metadata/commonObjects/metadataTargets/types", "wide"],
  ["Planner", "plannerRule", "~/metadata/forms/commonObjects/formAttribute/builders", "wide"],
  ["Predefined", "predefinedRule", "~/metadata/commonObjects/predefined/builders", "wide"],
  ["PredefinedCode", "predefinedCodeRule", "~/metadata/commonObjects/predefinedCode/types", "wide"],
  [
    "PredefinedItemCollection",
    "predefinedItemCollectionRule",
    "~/metadata/commonObjects/predefinedItem/builders",
    "wide",
  ],
  ["Recalculations", "recalculationsRule", "~/metadata/commonObjects/recalculation/builders", "wide"],
  ["RootCommandInterface", "rootCommandInterfaceRule", "~/metadata/appliedObjects/configuration/builders", "wide"],
  ["ScrollBarUseBoolean", "scrollBarUseBooleanRule", "~/metadata/forms/commonObjects/scrollBarUse/types", "wide"],
  [
    "SettingsParameterValue",
    "settingsParameterValueRule",
    "~/metadata/commonObjects/dataCompositionSystem/parameterValue/types",
    "wide",
  ],
  [
    "SettingsParameterValueCollection",
    "settingsParameterValueCollectionRule",
    "~/metadata/commonObjects/dataCompositionSystem/settingsParameterValueCollection/types",
    "wide",
  ],
  [
    "SingleViewStatusAddition",
    "singleViewStatusAdditionRule",
    "~/metadata/forms/elements/pdfDocumentField/builders",
    "wide",
  ],
  ["SpreadsheetDocument", "spreadsheetDocumentRule", "~/metadata/forms/commonObjects/formAttribute/builders", "wide"],
  [
    "StandardAttributeDescriptions",
    "standardAttributeDescriptionsRule",
    "~/metadata/commonObjects/standardAttributeDescription/builders",
    "wide",
  ],
  [
    "StandardTabularSectionAttributeDescriptions",
    "standardTabularSectionAttributeDescriptionsRule",
    "~/metadata/commonObjects/standardTabularSectionDescription/builders",
    "wide",
  ],
  [
    "StandardTabularSectionDescriptions",
    "standardTabularSectionDescriptionsRule",
    "~/metadata/commonObjects/standardTabularSectionDescription/builders",
    "wide",
  ],
  ["StringOrNumber", "stringOrNumberRule", "~/metadata/commonObjects/stringOrNumber/types", "wide"],
  [
    "StructureItemGroup",
    "structureItemGroupRule",
    "~/metadata/commonObjects/dataCompositionSystem/structureItemGroup/builders",
    "wide",
  ],
  [
    "StructureItemGroupCollection",
    "structureItemGroupCollectionRule",
    "~/metadata/commonObjects/dataCompositionSystem/structureItemGroup/collection/types",
    "wide",
  ],
  ["StyleItemValue", "styleItemValueRule", "~/metadata/commonObjects/styleItemValue/types", "wide"],
  [
    "TableAdditionalSource",
    "tableAdditionalSourceRule",
    "~/metadata/forms/commonObjects/tableAdditionalSource/types",
    "wide",
  ],
  ["TableChildItems", "tableChildItemsRule", "~/metadata/forms/commonObjects/childItems/types", "wide"],
  ["Template", "templateRule", "~/metadata/commonObjects/module/types", "wide"],
  ["TypeDescription", "typeDescriptionRule", "~/metadata/commonObjects/typeDescription/types", "wide"],
  ["TypeLink", "typeLinkRule", "~/metadata/commonObjects/typeLink/types", "wide"],
  [
    "UsedMobileApplicationFunctionalities",
    "usedMobileApplicationFunctionalitiesRule",
    "~/metadata/appliedObjects/configuration/builders",
    "wide",
  ],
  ["UsePurposes", "usePurposesRule", "~/metadata/commonObjects/usePurposes/types", "wide"],
  ["UserSettingsID", "userSettingsIDRule", "~/metadata/commonObjects/userSettingsID/types", "wide"],
  ["UserVisible", "userVisibleRule", "~/metadata/commonObjects/userVisible/types", "wide"],
  [
    "WebSocketClientHeaders",
    "webSocketClientHeadersRule",
    "~/metadata/commonObjects/webSocketClientHeaders/types",
    "wide",
  ],
  ["WSDefinitionSchemas", "wSDefinitionSchemasRule", "~/metadata/commonObjects/wsDefinitionSchemas/types", "wide"],
  ["XDTOPackages", "xDTOPackagesRule", "~/metadata/commonObjects/xDTOPackages/types", "wide"],
] as const satisfies readonly (readonly [string, string, string, BuilderMode])[]

export function createBuilderCatalog(): BuilderCatalog {
  return new Map(
    entries.map(([propertyType, builderName, importPath, mode]) => [
      propertyType,
      { propertyType, builderName, importPath, mode },
    ])
  )
}
