export type BuilderMode = "strict" | "wide"

export type BuilderCatalogEntry = {
  propertyType: string
  builderName: string
  importPath: string
  mode: BuilderMode
}

export type BuilderCatalog = ReadonlyMap<string, BuilderCatalogEntry>

const entries = [
  ["string", "stringRule", "../commonObjects/string/types", "strict"],
  ["boolean", "booleanRule", "../commonObjects/boolean/types", "strict"],
  ["number", "numberRule", "../commonObjects/number/types", "strict"],
  ["uuid", "uuidRule", "../commonObjects/uuid/types", "strict"],
  ["XMLRoot", "xmlRootRule", "../commonObjects/xmlRoot/types", "strict"],
  ["I8nText", "i8nTextRule", "../commonObjects/i8nText/types", "strict"],
  ["SystemEnumeration", "systemEnumerationRule", "../systemEnumerations/types", "strict"],
  ["Module", "moduleRule", "../commonObjects/module/types", "strict"],
  ["MetadataValue", "metadataValueRule", "../commonObjects/metadataValue/types", "wide"],
  ["AccountingFlags", "accountingFlagsRule", "../appliedObjects/metadataChartOfAccounts/builders", "wide"],
  [
    "AccumulationRegisterAggregateCollection",
    "accumulationRegisterAggregateCollectionRule",
    "../commonObjects/accumulationRegisterAggregates/builders",
    "wide",
  ],
  [
    "AccumulationRegisterAggregateDimensions",
    "accumulationRegisterAggregateDimensionsRule",
    "../commonObjects/accumulationRegisterAggregates/builders",
    "wide",
  ],
  [
    "AccumulationRegisterAggregates",
    "accumulationRegisterAggregatesRule",
    "../appliedObjects/metadataAccumulationRegister/builders",
    "wide",
  ],
  ["AdditionalIndex", "additionalIndexRule", "../appliedObjects/metadataAccountingRegister/builders", "wide"],
  ["AdditionalIndexCollection", "additionalIndexCollectionRule", "../commonObjects/additionalIndex/builders", "wide"],
  [
    "AllowedIncomingShareRequestTypes",
    "allowedIncomingShareRequestTypesRule",
    "../appliedObjects/configuration/builders",
    "wide",
  ],
  [
    "AppearanceFields",
    "appearanceFieldsRule",
    "../commonObjects/dataCompositionSystem/appearanceFields/builders",
    "wide",
  ],
  ["AssociatedTable", "associatedTableRule", "../commonObjects/metadataValue/types", "wide"],
  ["AutoCommandBar", "autoCommandBarRule", "../forms/clientApplicationForm/builders", "wide"],
  ["AvailableFields", "availableFieldsRule", "../commonObjects/dataCompositionSystem/availableFields/types", "wide"],
  ["Border", "borderRule", "../commonObjects/border/types", "wide"],
  [
    "CalculatedFieldOrderExpression",
    "calculatedFieldOrderExpressionRule",
    "../commonObjects/dataCompositionSystem/calculatedField/builders",
    "wide",
  ],
  ["CalculatedFields", "calculatedFieldsRule", "../forms/commonObjects/dynamicList/builders", "wide"],
  [
    "CalculatedFieldUseRestriction",
    "calculatedFieldUseRestrictionRule",
    "../commonObjects/dataCompositionSystem/calculatedField/builders",
    "wide",
  ],
  [
    "CharacteristicsDescriptions",
    "characteristicsDescriptionsRule",
    "../commonObjects/characteristicsDescription/types",
    "wide",
  ],
  ["Chart", "chartRule", "../forms/commonObjects/formAttribute/builders", "wide"],
  ["ChildFileItemNames", "childFileItemNamesRule", "../commonObjects/childFileItemNames/types", "wide"],
  ["ChildFormNames", "childFormNamesRule", "../commonObjects/childFormNames/types", "wide"],
  ["ChildSubsystemNames", "childSubsystemNamesRule", "../commonObjects/childSubsystemNames/types", "wide"],
  ["ChildTemplateNames", "childTemplateNamesRule", "../commonObjects/childTemplateNames/types", "wide"],
  ["ChoiceList", "choiceListRule", "../commonObjects/choiceList/types", "wide"],
  ["ChoiceParameterLinks", "choiceParameterLinksRule", "../commonObjects/сhoiceParameterLinks/types", "wide"],
  ["ChoiceParameters", "choiceParametersRule", "../commonObjects/сhoiceParameters/types", "wide"],
  ["ClientApplicationForm", "clientApplicationFormRule", "../forms/clientApplicationForm/builders", "wide"],
  ["ClientApplicationInterface", "clientApplicationInterfaceRule", "../appliedObjects/configuration/builders", "wide"],
  [
    "ClientApplicationInterfaceItems",
    "clientApplicationInterfaceItemsRule",
    "../commonObjects/clientApplicationInterface/builders",
    "wide",
  ],
  [
    "ClientApplicationInterfacePanelDefs",
    "clientApplicationInterfacePanelDefsRule",
    "../commonObjects/clientApplicationInterface/builders",
    "wide",
  ],
  ["Color", "colorRule", "../commonObjects/color/types", "wide"],
  ["CommandBarChildItems", "commandBarChildItemsRule", "../forms/commonObjects/childItems/types", "wide"],
  ["CommandInterface", "commandInterfaceRule", "../forms/commonObjects/commandInterface/types", "wide"],
  [
    "CommandInterfaceCommandGroups",
    "commandInterfaceCommandGroupsRule",
    "../commonObjects/rootCommandInterface/builders",
    "wide",
  ],
  ["CommandInterfaceOrder", "commandInterfaceOrderRule", "../commonObjects/rootCommandInterface/builders", "wide"],
  [
    "CommandInterfacePlacementMap",
    "commandInterfacePlacementMapRule",
    "../commonObjects/rootCommandInterface/builders",
    "wide",
  ],
  [
    "CommandInterfaceSubsystemsOrder",
    "commandInterfaceSubsystemsOrderRule",
    "../commonObjects/rootCommandInterface/builders",
    "wide",
  ],
  [
    "CommandInterfaceSubsystemsVisibilityMap",
    "commandInterfaceSubsystemsVisibilityMapRule",
    "../commonObjects/rootCommandInterface/builders",
    "wide",
  ],
  [
    "CommandInterfaceVisibilityMap",
    "commandInterfaceVisibilityMapRule",
    "../commonObjects/rootCommandInterface/builders",
    "wide",
  ],
  ["CommandSet", "commandSetRule", "../forms/commonObjects/commandSet/types", "wide"],
  ["CommonAttributeContent", "commonAttributeContentRule", "../commonObjects/commonAttributeContent/types", "wide"],
  ["ConditionalAppearance", "conditionalAppearanceRule", "../forms/clientApplicationForm/builders", "wide"],
  [
    "ConditionalAppearanceItems",
    "conditionalAppearanceItemsRule",
    "../commonObjects/dataCompositionSystem/conditionalAppearance/builders",
    "wide",
  ],
  ["ContextMenu", "contextMenuRule", "../forms/elements/viewStatusAddition/builders", "wide"],
  [
    "DataCompositionSchemaDataSetFieldKind",
    "dataCompositionSchemaDataSetFieldKindRule",
    "../commonObjects/dataCompositionSystem/dataCompositionSchemaDataSetField/builders",
    "wide",
  ],
  ["DataPath", "dataPathRule", "../commonObjects/metadataPath/types", "wide"],
  ["DataSetFieldFields", "dataSetFieldFieldsRule", "../forms/commonObjects/dynamicList/builders", "wide"],
  ["dateTime", "dateTimeRule", "../commonObjects/dateTime/types", "wide"],
  [
    "DcsAvailableValues",
    "dcsAvailableValuesRule",
    "../commonObjects/dataCompositionSystem/availableValues/types",
    "wide",
  ],
  [
    "DcsLocalStringType",
    "dcsLocalStringTypeRule",
    "../commonObjects/dataCompositionSystem/dcsLocalStringType/types",
    "wide",
  ],
  [
    "DcsMetadataTypedValue",
    "dcsMetadataTypedValueRule",
    "../commonObjects/dataCompositionSystem/dscMetadataTypedValue/types",
    "wide",
  ],
  ["DCSParameters", "dCSParametersRule", "../forms/commonObjects/dynamicList/builders", "wide"],
  ["DynamicList", "dynamicListRule", "../forms/commonObjects/formAttribute/builders", "wide"],
  ["DynamicListKeyFields", "dynamicListKeyFieldsRule", "../forms/commonObjects/dynamicList/builders", "wide"],
  ["ElementId", "elementIdRule", "../forms/commonObjects/elementId/types", "wide"],
  ["Events", "eventsRule", "../forms/commonObjects/event/types", "wide"],
  ["ExchangePlanContent", "exchangePlanContentRule", "../appliedObjects/metadataExchangePlan/builders", "wide"],
  ["ExchangePlanContentItems", "exchangePlanContentItemsRule", "../commonObjects/exchangePlanContent/builders", "wide"],
  [
    "ExtDimensionAccountingFlags",
    "extDimensionAccountingFlagsRule",
    "../appliedObjects/metadataChartOfAccounts/builders",
    "wide",
  ],
  ["ExtendedTooltip", "extendedTooltipRule", "../forms/elements/viewStatusAddition/builders", "wide"],
  ["ExternalFile", "externalFileRule", "../commonObjects/externalFile/types", "wide"],
  ["ExternalFormItemFile", "externalFormItemFileRule", "../forms/clientApplicationForm/builders", "wide"],
  ["ExternalPicture", "externalPictureRule", "../commonObjects/externalPicture/types", "wide"],
  ["FieldsList", "fieldsListRule", "../commonObjects/fieldsList/types", "wide"],
  ["Filter", "filterRule", "../commonObjects/dataCompositionSystem/conditionalAppearanceItem/builders", "wide"],
  ["FilterItem", "filterItemRule", "../commonObjects/dataCompositionSystem/filter/builders", "wide"],
  [
    "FilterItemPresentationValue",
    "filterItemPresentationValueRule",
    "../commonObjects/dataCompositionSystem/filterItem/builders",
    "wide",
  ],
  ["FlowchartContext", "flowchartContextRule", "../forms/commonObjects/formAttribute/builders", "wide"],
  ["Font", "fontRule", "../commonObjects/font/types", "wide"],
  ["FormattedI8nText", "formattedI8nTextRule", "../commonObjects/formattedI8nText/types", "wide"],
  [
    "FormAttributeAdditionalColumns",
    "formAttributeAdditionalColumnsRule",
    "../forms/commonObjects/formAttribute/builders",
    "wide",
  ],
  ["FormAttributeColumns", "formAttributeColumnsRule", "../forms/commonObjects/formAttribute/builders", "wide"],
  ["FormAttributes", "formAttributesRule", "../forms/commonObjects/formAttribute/builders", "wide"],
  ["FormCommands", "formCommandsRule", "../forms/commonObjects/formCommand/builders", "wide"],
  ["FormParameters", "formParametersRule", "../forms/commonObjects/formParameter/types", "wide"],
  [
    "FunctionalOptionsProperty",
    "functionalOptionsPropertyRule",
    "../commonObjects/functionalOptionsProperty/types",
    "wide",
  ],
  ["GanttChart", "ganttChartRule", "../forms/commonObjects/formAttribute/builders", "wide"],
  ["GanttChartFieldTable", "ganttChartFieldTableRule", "../forms/commonObjects/ganttChartFieldTable/types", "wide"],
  ["GroupChildItems", "groupChildItemsRule", "../forms/commonObjects/childItems/types", "wide"],
  ["Help", "helpRule", "../commonObjects/help/types", "wide"],
  ["HomePageWorkArea", "homePageWorkAreaRule", "../appliedObjects/configuration/builders", "wide"],
  [
    "HomePageWorkAreaColumnItems",
    "homePageWorkAreaColumnItemsRule",
    "../commonObjects/homePageWorkArea/builders",
    "wide",
  ],
  [
    "HomePageWorkAreaCommandInterfaceDisplay",
    "homePageWorkAreaCommandInterfaceDisplayRule",
    "../commonObjects/homePageWorkArea/builders",
    "wide",
  ],
  ["HomePageWorkAreaTemplate", "homePageWorkAreaTemplateRule", "../commonObjects/homePageWorkArea/builders", "wide"],
  ["IndexField", "indexFieldRule", "../commonObjects/indexField/types", "wide"],
  ["InternalInfo", "internalInfoRule", "../commonObjects/internalInfo/types", "wide"],
  ["MetadataAttributes", "metadataAttributesRule", "../appliedObjects/metadataDataProcessor/builders", "wide"],
  [
    "MetadataBusinessProcessTabularSections",
    "metadataBusinessProcessTabularSectionsRule",
    "../appliedObjects/metadataBusinessProcess/builders",
    "wide",
  ],
  ["MetadataCatalogAttributes", "metadataCatalogAttributesRule", "../appliedObjects/metadataCatalog/builders", "wide"],
  [
    "MetadataChartOfAccountsTabularSections",
    "metadataChartOfAccountsTabularSectionsRule",
    "../appliedObjects/metadataChartOfAccounts/builders",
    "wide",
  ],
  [
    "MetadataChartOfCalculationTypesTabularSections",
    "metadataChartOfCalculationTypesTabularSectionsRule",
    "../appliedObjects/metadataChartOfCalculationTypes/builders",
    "wide",
  ],
  [
    "MetadataChartOfCharacteristicTypesTabularSections",
    "metadataChartOfCharacteristicTypesTabularSectionsRule",
    "../appliedObjects/metadataChartOfCharacteristicTypes/builders",
    "wide",
  ],
  ["MetadataCommandGroup", "metadataCommandGroupRule", "../commonObjects/metadataCommandGroup/types", "wide"],
  ["MetadataCommands", "metadataCommandsRule", "../appliedObjects/metadataAccountingRegister/builders", "wide"],
  [
    "MetadataDataProcessorTabularSections",
    "metadataDataProcessorTabularSectionsRule",
    "../appliedObjects/metadataDataProcessor/builders",
    "wide",
  ],
  [
    "MetadataDcsMetadataValue",
    "metadataDcsMetadataValueRule",
    "../commonObjects/dataCompositionSystem/dcsMetadataValue/types",
    "wide",
  ],
  ["MetadataDocumentAttributes", "metadataDocumentAttributesRule", "../appliedObjects/metadataDocument/types", "wide"],
  [
    "MetadataDocumentJournalColumns",
    "metadataDocumentJournalColumnsRule",
    "../appliedObjects/metadataDocumentJournal/builders",
    "wide",
  ],
  [
    "MetadataDocumentTabularSections",
    "metadataDocumentTabularSectionsRule",
    "../appliedObjects/metadataDocument/types",
    "wide",
  ],
  [
    "MetadataEnumerationValues",
    "metadataEnumerationValuesRule",
    "../appliedObjects/metadataEnumeration/builders",
    "wide",
  ],
  [
    "MetadataExchangePlanTabularSections",
    "metadataExchangePlanTabularSectionsRule",
    "../appliedObjects/metadataExchangePlan/builders",
    "wide",
  ],
  [
    "MetadataExternalDataSourceFunctions",
    "metadataExternalDataSourceFunctionsRule",
    "../appliedObjects/metadataExternalDataSource/builders",
    "wide",
  ],
  ["MetadataFields", "metadataFieldsRule", "../commonObjects/metadataField/types", "wide"],
  [
    "MetadataHTTPServiceURLTemplates",
    "metadataHTTPServiceURLTemplatesRule",
    "../appliedObjects/metadataHTTPService/builders",
    "wide",
  ],
  [
    "MetadataIntegrationServiceChannels",
    "metadataIntegrationServiceChannelsRule",
    "../appliedObjects/metadataIntegrationService/builders",
    "wide",
  ],
  ["MetadataItemLink", "metadataItemLinkRule", "../commonObjects/metadataPath/types", "wide"],
  ["MetadataItemLinks", "metadataItemLinksRule", "../commonObjects/metadataPath/types", "wide"],
  [
    "MetadataObjectRefCollection",
    "metadataObjectRefCollectionRule",
    "../commonObjects/metadataObjectRefCollection/types",
    "wide",
  ],
  [
    "MetadataRegisterAttributes",
    "metadataRegisterAttributesRule",
    "../appliedObjects/metadataAccountingRegister/builders",
    "wide",
  ],
  [
    "MetadataRegisterDimensions",
    "metadataRegisterDimensionsRule",
    "../appliedObjects/metadataAccountingRegister/builders",
    "wide",
  ],
  [
    "MetadataRegisterResources",
    "metadataRegisterResourcesRule",
    "../appliedObjects/metadataAccountingRegister/builders",
    "wide",
  ],
  ["MetadataReportAttributes", "metadataReportAttributesRule", "../appliedObjects/metadataReport/builders", "wide"],
  [
    "MetadataReportTabularSections",
    "metadataReportTabularSectionsRule",
    "../appliedObjects/metadataReport/builders",
    "wide",
  ],
  [
    "MetadataSequenceDimensions",
    "metadataSequenceDimensionsRule",
    "../appliedObjects/metadataSequence/builders",
    "wide",
  ],
  ["MetadataTabularSections", "metadataTabularSectionsRule", "../appliedObjects/metadataCatalog/builders", "wide"],
  [
    "MetadataTaskAddressingAttributes",
    "metadataTaskAddressingAttributesRule",
    "../appliedObjects/metadataTask/builders",
    "wide",
  ],
  ["MetadataTaskTabularSections", "metadataTaskTabularSectionsRule", "../appliedObjects/metadataTask/builders", "wide"],
  [
    "MetadataWebServiceOperations",
    "metadataWebServiceOperationsRule",
    "../appliedObjects/metadataWebService/builders",
    "wide",
  ],
  ["MinMaxValue", "minMaxValueRule", "../commonObjects/minMaxValue/types", "wide"],
  ["MobileApplicationURLs", "mobileApplicationURLsRule", "../appliedObjects/configuration/builders", "wide"],
  [
    "MobileDeviceCommandBarContent",
    "mobileDeviceCommandBarContentRule",
    "../commonObjects/mobileDeviceCommandBarContent/types",
    "wide",
  ],
  ["Order", "orderRule", "../forms/commonObjects/dynamicList/builders", "wide"],
  ["OrderItemFields", "orderItemFieldsRule", "../commonObjects/dataCompositionSystem/order/builders", "wide"],
  ["PagesChildItems", "pagesChildItemsRule", "../forms/commonObjects/childItems/types", "wide"],
  ["Picture", "pictureRule", "../commonObjects/metadataTargets/types", "wide"],
  ["Planner", "plannerRule", "../forms/commonObjects/formAttribute/builders", "wide"],
  ["Predefined", "predefinedRule", "../commonObjects/predefined/builders", "wide"],
  ["PredefinedCode", "predefinedCodeRule", "../commonObjects/predefinedCode/types", "wide"],
  ["PredefinedItemCollection", "predefinedItemCollectionRule", "../commonObjects/predefinedItem/builders", "wide"],
  ["Recalculations", "recalculationsRule", "../commonObjects/recalculation/builders", "wide"],
  ["RootCommandInterface", "rootCommandInterfaceRule", "../appliedObjects/configuration/builders", "wide"],
  ["ScrollBarUseBoolean", "scrollBarUseBooleanRule", "../forms/commonObjects/scrollBarUse/types", "wide"],
  [
    "SettingsParameterValue",
    "settingsParameterValueRule",
    "../commonObjects/dataCompositionSystem/parameterValue/types",
    "wide",
  ],
  [
    "SettingsParameterValueCollection",
    "settingsParameterValueCollectionRule",
    "../commonObjects/dataCompositionSystem/settingsParameterValueCollection/types",
    "wide",
  ],
  ["SingleViewStatusAddition", "singleViewStatusAdditionRule", "../forms/elements/pdfDocumentField/builders", "wide"],
  ["SpreadsheetDocument", "spreadsheetDocumentRule", "../forms/commonObjects/formAttribute/builders", "wide"],
  [
    "StandardAttributeDescriptions",
    "standardAttributeDescriptionsRule",
    "../commonObjects/standardAttributeDescription/builders",
    "wide",
  ],
  [
    "StandardTabularSectionAttributeDescriptions",
    "standardTabularSectionAttributeDescriptionsRule",
    "../commonObjects/standardTabularSectionDescription/builders",
    "wide",
  ],
  [
    "StandardTabularSectionDescriptions",
    "standardTabularSectionDescriptionsRule",
    "../commonObjects/standardTabularSectionDescription/builders",
    "wide",
  ],
  ["StringOrNumber", "stringOrNumberRule", "../commonObjects/stringOrNumber/types", "wide"],
  [
    "StructureItemGroup",
    "structureItemGroupRule",
    "../commonObjects/dataCompositionSystem/structureItemGroup/builders",
    "wide",
  ],
  [
    "StructureItemGroupCollection",
    "structureItemGroupCollectionRule",
    "../commonObjects/dataCompositionSystem/structureItemGroup/collection/types",
    "wide",
  ],
  ["StyleItemValue", "styleItemValueRule", "../commonObjects/styleItemValue/types", "wide"],
  ["TableAdditionalSource", "tableAdditionalSourceRule", "../forms/commonObjects/tableAdditionalSource/types", "wide"],
  ["TableChildItems", "tableChildItemsRule", "../forms/commonObjects/childItems/types", "wide"],
  ["Template", "templateRule", "../commonObjects/module/types", "wide"],
  ["TypeDescription", "typeDescriptionRule", "../commonObjects/typeDescription/types", "wide"],
  ["TypeLink", "typeLinkRule", "../commonObjects/typeLink/types", "wide"],
  [
    "UsedMobileApplicationFunctionalities",
    "usedMobileApplicationFunctionalitiesRule",
    "../appliedObjects/configuration/builders",
    "wide",
  ],
  ["UsePurposes", "usePurposesRule", "../commonObjects/usePurposes/types", "wide"],
  ["UserSettingsID", "userSettingsIDRule", "../commonObjects/userSettingsID/types", "wide"],
  ["UserVisible", "userVisibleRule", "../commonObjects/userVisible/types", "wide"],
  ["WebSocketClientHeaders", "webSocketClientHeadersRule", "../commonObjects/webSocketClientHeaders/types", "wide"],
  ["WSDefinitionSchemas", "wSDefinitionSchemasRule", "../commonObjects/wsDefinitionSchemas/types", "wide"],
  ["XDTOPackages", "xDTOPackagesRule", "../commonObjects/xDTOPackages/types", "wide"],
] as const satisfies readonly (readonly [string, string, string, BuilderMode])[]

export function createBuilderCatalog(): BuilderCatalog {
  return new Map(
    entries.map(([propertyType, builderName, importPath, mode]) => [
      propertyType,
      { propertyType, builderName, importPath, mode },
    ])
  )
}
